### ISSUE TITLE
What about https://medium.com/realmodelabs/sd-pwn-part-2-citrix-sd-wan-center-another-network-takeover-a9c950a1a27c

### ISSUE THREAD

**Issue by estebancano-dev** [cakephp/cakephp#15178] opened 2020-11-19 12:57 UTC
Sorry, may be nothing, but need to know
CakePHP 2.x
https://medium.com/realmodelabs/sd-pwn-part-2-citrix-sd-wan-center-another-network-takeover-a9c950a1a27c

**Comment by garas** [comment] 2020-11-19 13:01
Duplicate of https://github.com/cakephp/cakephp/issues/15163

**Closed by garas** 2020-11-19 13:01 UTC
