### ISSUE TITLE
Datetime fails validation when field type or options are changed

### ISSUE THREAD

**Issue by dreamtechnicsgithub** [cakephp/cakephp#8563] opened 2016-03-29 16:27 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: CakePHP v3.2.5
* PHP Version => 5.5.30-1+deb.sury.org~precise+1
System => Linux novics 3.13.0-83-generic #127-Ubuntu SMP Fri Mar 11 00:26:47 UTC 2016 i686

### What you did
I had my default CRUD generated, I was editing the input field, which in the database was set as datetime. 
I tried   echo $this->Form->input('prodtime', ['disabled' => true ]); ,
(When it didnt work, I also tried echo $this->Form->hidden('prodtime');)
I saved the ctp view file, then tried to submit the form that was in that view.
The part of the form:

```php
  <?= $this->Form->create($product) ?>
    <fieldset>
        <legend><?= __('Add Product') ?></legend>
        <?php
            echo $this->Form->select('type', $material);
            echo $this->Form->input('weight');
            echo $this->Form->input('prodtime', ['disabled' => true ]); <- changes were attempted here
            echo $this->Form->select('supervisor', $supervisors);
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
```

### Expected Behavior
I expected the form data to be saved without errors. The date data was supposed to be successfuly casted into proper format and saved in the database irregardless of the options on the field (hidden, disabled, whatever)

### Actual Behavior
I got cakephp error message "the product could not be saved" whenever I set the input field to hidden or field being input, but the disabled option  on.

### Hack
I hacked it like this to make it work, although it isnt a good solution:
            echo $this->Form->hidden('prodtime[year]', ['value' => date( 'Y', time() ) ]);
            echo $this->Form->hidden('prodtime[month]', ['value' => date( 'm', time() ) ]);
            echo $this->Form->hidden('prodtime[day]', ['value' => date( 'd', time() ) ]);
            echo $this->Form->hidden('prodtime[hour]', ['value' => date( 'H', time() ) ]);
            echo $this->Form->hidden('prodtime[minute]', ['value' => date( 'i', time() ) ]);
            echo $this->Form->hidden('prodtime[second]', ['value' => date( 's', time() ) ]);

**Comment by markstory** [comment] 2016-03-29 21:13
Disabled fields are not submitted in the POST data. So there is no way that could work. If your datetime field is _required_ the validation error is correct. What do your validation rules look like?

**Comment by markstory** [comment] 2016-04-11 23:42
Closing due to lack of followup or a clear way to reproduce this issue.

**Closed by markstory** 2016-04-11 23:42 UTC
Labels: On hold, ORM
