### ISSUE TITLE
AuthComponent->login throwing Fatal error when request is empty (PHP 7.1, nginx, fpm)

### ISSUE THREAD

**Issue by nebojsac** [cakephp/cakephp#10065] opened 2017-01-19 23:18 UTC
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 2.8.9.
* Platform and Target: php-fpm, PHP 7.1, nginx, MySQL 5.6

### What you did
Getting Fatal errors in the log after upgrading PHP from 5.6 to 7.1

### What happened
Fatal Error in error log (see test).

### What you expected to happen
I would expect the login to fail, and the AuthComponent->login() to return false instead of a FatalError. I'm going to copy a failing test for AuthComponentTest here:

```
	public function testLoginWithNoRequestData()
	{
		$this->Auth->request = null;
		$this->Auth->response = null;
		$result = $this->Auth->login();
		$this->assertFalse($result, 'If no request data, login fails.');
	}
```

Honestly, I'm not sure what can be triggering login attempts without request data. Looks like it's hitting a 404 error page, as far as the URL goes. Here is the full Stack trace:

```
2017/01/19 21:43:19 [error] 2636#0: *11569502 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to AuthComponent::identify() must be an instance of CakeRequest, null given, called in /var/www/domains/ourdomain.com/lib/Cake/Controller/Component/AuthComponent.php on line 611 and defined in /var/www/domains/ourdomain.com/lib/Cake/Controller/Component/AuthComponent.php:765
Stack trace:
#0 /var/www/domains/ourdomain.com/lib/Cake/Controller/Component/AuthComponent.php(611): AuthComponent->identify(NULL, NULL)
#1 /var/www/domains/ourdomain.com/app/Controller/AppController.php(243): AuthComponent->login()
#2 /var/www/domains/ourdomain.com/lib/Cake/Event/CakeEventManager.php(243): AppController->beforeFilter(Object(CakeEvent))
#3 /var/www/domains/ourdomain.com/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#4 /var/www/domains/ourdomain.com/lib/Cake/Error/ExceptionRenderer.php(158): Controller->startupProcess()
#5 /var/www/domains/ourdomain.com/lib/Cake/Error/ExceptionRenderer.php(95): ExceptionRenderer->_getControlle" while reading response header from upstream, client: 216.80.11.2, server: ourdomain.com, request: "GET /apple-touch-icon-precomposed.
```

The beforeFilter line references the `login()` call after reading login details from a Cookie. Should `login()` be checking for the existance of `CakeRequest` data and returning false if it's not there?

**Comment by markstory** [comment] 2017-01-20 03:06
You're getting a fatal error as PHP7 raises `TypeError` when typehints are violated vs. PHP5 which just emits an error that can be easily ignored.

AuthComponent and the other core components require their properties to be filled out properly before they can function properly. I can't see your application code but how is AuthComponent being created on the ErrorController? It would seem like AuthComponent is not having its `initialize()` method invoked.

**Comment by nebojsac** [comment] 2017-01-20 07:40
Thanks for the clarification there.

The AuthComponent is loaded in the AppController->beforeFilter, as it's set up in the `$components` property. I think that means that it's initialized everywhere. Also, I'm not able to consistently reproduce this, it shows up in the logs from time to time.

The code right before the `login()` call sets request data from the cookie:

```
if (!$this->Auth->loggedIn()) {
		$this->Auth->authError = false;
		$cookie = $this->Cookie->read('Auth.User');
		if ($cookie AND isset($cookie['username']) AND isset($cookie['password'])) {
			$this->request->data['User']['username'] = $cookie['username'];
			$this->request->data['User']['password'] = $cookie['password'];
			// Session expired, login from cookie
			if ($this->Auth->login()) { // Fatal Error
```

Not sure how it can even get to `login()` without CakeRequest being set up.

If it's not an issue with the core, which means there isn't a check needed in `login()`, then I'll check for CakeRequest in userland code.

**Comment by josegonzalez** [comment] 2017-01-20 07:49
Could be a byproduct of requesting a file/controller that doesn't exist somehow?

```
#5 /var/www/domains/ourdomain.com/lib/Cake/Error/ExceptionRenderer.php(95): ExceptionRenderer->_getControlle" while reading response header from upstream, client: 216.80.11.2, server: ourdomain.com, request: "GET /apple-touch-icon-precomposed.
```

That triggers the entire error - also why is it `_getControlle` without the `r`? Can you gist your AppController?

**Comment by nebojsac** [comment] 2017-01-20 07:56
It definitely is due to a missing file. It's hitting a missing .png file, so Cake looks for a Controller.
`_getControlle` doesn't exist in the codebase, so I assume it was `_getController` but got cutoff in the logged stack trace.

I really can't gist the entire AppController, but apart from a few more `loggedIn` checks, I don't think there's anything useful. Also it's pretty big. But this may help somewhat, it's the `$components` property:

```
class AppController extends Controller {
	var $components = array(
		'Auth' => array(
			'authenticate' => array(
				'Form' => array(
					'userModel' => 'User'
				)
			),
			'authorize' => 'Controller',
			'loginRedirect' => '/',
			'autoRedirect' => false,
			'authError' => 'You are not authorized.',
			'userScope' => array('active' => true),
			'loginError' => 'Login Error'
		),
		'Session',
		'Cookie',
		'RequestHandler',
	);
```

**Comment by nebojsac** [comment] 2017-01-20 07:59
I think the bottomline is: "Is this Test case valid? Should this return false, instead of throwing an Exception?" for the test I sent in.

I don't want to waste anyone elses time in debugging our legacy code, just thought that this is a check that belongs in the core - which of course I might be completely wrong about. I do appreciate all the pointers so far though.

**Comment by nebojsac** [comment] 2017-01-23 10:47
Ok, an update to this.

This is how I was able to repeat the issue: 

1. Delete the CakePHP session from my browser via Inspect element, but leave the Cookie.
2. Navigate to an invalid URL that triggers a 404 error.
3. This triggers the Fatal error, BUT it does actually create the session and login the user, so upon refreshing the page it's a regular 404 page.

Because it's a Fatal error, and I can't catch it I had to add checks in the core. The full Auth->login() method is now:

```php
	public function login($user = null) {
		$this->_setDefaults();

		if (empty($user)) {
			if ($this->request && $this->response) { // Only this was added
				$user = $this->identify($this->request, $this->response);
			}
		}
		if ($user) {
			if (static::$sessionKey) {
				$this->Session->renew();
				$this->Session->write(static::$sessionKey, $user);
			} else {
				static::$_user = $user;
			}
			$event = new CakeEvent('Auth.afterIdentify', $this, array('user' => $user));
			$this->_Collection->getController()->getEventManager()->dispatch($event);
		}
		return (bool)$this->user();
	}
```

So this is the only change:

```php
			if ($this->request && $this->response) { // Only this was added
				$user = $this->identify($this->request, $this->response);
			}
```

I'm not checking for the correct object instance for the sake of speed, just assuming that it's fine as long as it's not null.

I backtracked a bit to see why we did it this way, and it's because the login Cookie only holds user/pass data, and didn't want to pass that into the `login()` call, as we would be missing the rest of the session data compared to calling the `login()` method without params.

Let me know if the above is ok, or if something should be changed. Or maybe it's not a Cake core issue and it's a matter of misusing the `login()` method.

**Comment by markstory** [comment] 2017-01-23 14:54
>  Delete the CakePHP session from my browser via Inspect element, but leave the Cookie.

Which cookie are you leaving in? If you're removing the session cookie, how does the user automatically get logged in again?

**Comment by nebojsac** [comment] 2017-01-23 15:14
Because we have a "remember me" Cookie that we manually generate upon login.
So, the above issue happens if the Session cookie expires,  but the "remember me" Cookie is still valid.

**Comment by markstory** [comment] 2017-01-23 16:13
Ok. Its a bit strange that you get an AuthComponent that is missing the request/response. Is the `initialize()` event not being triggered for your 404 page?

**Comment by nebojsac** [comment] 2017-01-24 10:54
That would be odd, because the `login()` is being called from within `AppController->beforeFilter()`.

I found the 404 page code, we use custom exception rendering in AppExceptionRenderer.php:

```
<?php
App::uses('ExceptionRenderer', 'Error');

class AppExceptionRenderer extends ExceptionRenderer {

    public function notFound($error) {
        $this->controller->response->statusCode(404);
        $this->controller->render('/Errors/error404');
        $this->controller->response->send();
    }
// other exceptions ...
}
```

I believe this is code that survived the migration from CakePHP 1.3 to 2.x at one point.

**Comment by markstory** [comment] 2017-01-24 20:26
Is the `Controller.initialize` event being stopped anywhere?

**Comment by nebojsac** [comment] 2017-01-25 15:47
Honestly, don't know how to check for that. Any pointers?

**Comment by ADmad** [comment] 2017-01-25 15:59
>  because the login() is being called from within AppController->beforeFilter().

You mean you are calling `Auth->login()` from `AppController->beforeFilter()`?

**Comment by nebojsac** [comment] 2017-01-25 16:02
> You mean you are calling Auth->login() from AppController->beforeFilter()?

Yes. This was set up so that, even if the session expires when they come back to the site we can still use the Cookie to log them back in and resume their session, no matter the URL they are at. (this is Legacy stuff, there might be a better place for this code)

**Comment by ADmad** [comment] 2017-01-25 16:06
Well that's a misuse of `Auth->login()` and most likely source of your problems. Cookie based authenticators should implement the `getUser()` method which is automatically called by auth component without need for calling `AuthComponent::login()`.

You should check cookie based authenticators developed by the community and fix your legacy code. Closing as the issue due to developer error and not a bug in core.

**Closed by ADmad** 2017-01-25 16:06 UTC
Labels: Defect, On hold

**Comment by nebojsac** [comment] 2017-01-25 16:12
Fair enough, thanks for confirming!

**Comment by DinhQuocNhat** [comment] 2022-11-23 07:25
if ($this->request && $this->response) { // Only this was added
				$user = $this->identify($this->request, $this->response);
			}
it's done! thanks
