### ISSUE TITLE
Saving associated data with TranslateBehavior fails (in 3.3)

### ISSUE THREAD

**Issue by jorisvaesen** [cakephp/cakephp#9273] opened 2016-08-15 18:04 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.0
* Platform and Target: Ubuntu 14.04.1 / Apache 2.4.7 / PHP 5.5.9 / MySQL 5.5.5

### What you did
I have a table `products` in which we want to add a new record. I have a `product_options` table which contains a foreign key `product_id` and a foreign key `product_option_list_id`. the last one is chosen from a select box and passed though the form submit.

You can find the code here:
https://gist.github.com/jorisvaesen/3d062933768c21f94ce86d4f90806be5

### Expected Behavior
Save the associated data to the ProductOptions table

### Actual Behavior
The save succeeds and the product is saved, but no associated data (product_options) are saved.
The associated data is not parsed into entities and looks like this:
```
object(App\Model\Entity\Product) {
	'_translations' => [
		'nl' => object(App\Model\Entity\Product) {
			'name' => 'qsdfsqd',
			'description' => '',
			'[new]' => true,
			'[accessible]' => [
				'_translations' => true,
				'product_options' => true,
				'*' => true
			],
			'[dirty]' => [
				'name' => true,
				'description' => true
			],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[invalid]' => [],
			'[repository]' => 'Products'
		
		},
		'en' => object(App\Model\Entity\Product) {
			'name' => '',
			'description' => '',
			'[new]' => true,
			'[accessible]' => [
				'_translations' => true,
				'product_options' => true,
				'*' => true
			],
			'[dirty]' => [
				'name' => true,
				'description' => true
			],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[invalid]' => [],
			'[repository]' => 'Products'
		
		},
		'fr' => object(App\Model\Entity\Product) {
			'name' => '',
			'description' => '',
			'[new]' => true,
			'[accessible]' => [
				'_translations' => true,
				'product_options' => true,
				'*' => true
			],
			'[dirty]' => [
				'name' => true,
				'description' => true
			],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[invalid]' => [],
			'[repository]' => 'Products'
		
		}
	],
	'product_number' => '',
	'price' => '123',
	'product_options' => [
		(int) 0 => [
			'product_option_list_id' => '1',
			'checked' => '1'
		],
		(int) 1 => [
			'product_option_list_id' => '2',
			'checked' => '1'
		]
	],
	'[new]' => true,
	'[accessible]' => [
		'_translations' => true,
		'product_options' => true,
		'*' => true
	],
	'[dirty]' => [
		'_translations' => true,
		'product_number' => true,
		'price' => true,
		'product_options' => true
	],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => [],
	'[invalid]' => [],
	'[repository]' => 'Products'
}
```
When I comment the TranslateBehavior in the ProductsTable, everything gets saved as expected and the associated data gets parsed into entities:
```
object(App\Model\Entity\Product) {
	'_translations' => [
		'nl' => [
			'name' => 'qsdfsqd',
			'description' => ''
		],
		'en' => [
			'name' => '',
			'description' => ''
		],
		'fr' => [
			'name' => '',
			'description' => ''
		]
	],
	'product_number' => '',
	'price' => (float) 123,
	'product_options' => [
		(int) 0 => object(App\Model\Entity\ProductOption) {

			'product_option_list_id' => (int) 1,
			'checked' => '1',
			'[new]' => true,
			'[accessible]' => [
				'*' => true
			],
			'[dirty]' => [
				'product_option_list_id' => true,
				'checked' => true
			],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[invalid]' => [],
			'[repository]' => 'ProductOptions'
		
		},
		(int) 1 => object(App\Model\Entity\ProductOption) {

			'product_option_list_id' => (int) 2,
			'checked' => '1',
			'[new]' => true,
			'[accessible]' => [
				'*' => true
			],
			'[dirty]' => [
				'product_option_list_id' => true,
				'checked' => true
			],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[invalid]' => [],
			'[repository]' => 'ProductOptions'
		
		}
	],
	'[new]' => true,
	'[accessible]' => [
		'_translations' => true,
		'product_options' => true,
		'*' => true
	],
	'[dirty]' => [
		'_translations' => true,
		'product_number' => true,
		'price' => true,
		'product_options' => true
	],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => [],
	'[invalid]' => [],
	'[repository]' => 'Products'
}
```

**Comment by lorenzo** [comment] 2016-08-15 18:49
Duplicate of https://github.com/cakephp/cakephp/issues/9267

**Closed by lorenzo** 2016-08-15 18:49 UTC

**Comment by jorisvaesen** [comment] 2016-08-15 18:54
Saving associated data succeeds, only not when TranslateBehavior is active.
In #9267 it always fails?

**Comment by lorenzo** [comment] 2016-08-15 21:57
@jorisvaesen Let's track it in the other ticket. I'm feeling very confident this is the same issue.

**Comment by markstory** [comment] 2016-08-15 23:02
I will add tests for marshalling and saving
