### ISSUE TITLE
A fixture configured to use a "test_xxx" connection will actually connect to "xxx" instead.

### ISSUE THREAD

**Issue by davehensley** [cakephp/cakephp#8319] opened 2016-02-23 04:11 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 1162121f1e8b8d0f1df0fb65ddf8ace5af8693d0 (3.1.5)
* Platform and Target: phpunit 3.7.28, Ubuntu Linux 14.04.3 LTS, phpunit 5.5.9-1ubuntu4.14 (cli)

### What you did
Hello, I've got 4 database connections defined in config/app.php: default, stats, test, and test_stats. Some fixtures don't have a connection set (so they use test by default). Other fixtures have their connection set to use test_stats.

### Expected Behavior
A fixture that is set to use test_stats as its connection will connect to the test_stats database.

### Actual Behavior
The fixtures that are set to use test_stats actually connect to stats. But the fixtures whose connections are not defined do work correctly (they connect to test like they're supposed to).

This worked fine up until 3.1.5, and it appears that the above commit is what caused the unexpected behavior. Reverting the commit resolves the issue.

Many thanks for your prompt attention to this.

**Comment by lorenzo** [comment] 2016-02-23 09:45
@ADmad do you remember the reason for this change?

**Comment by ADmad** [comment] 2016-02-23 11:03
The previous code was also generating errors for someone. I'll try and find the reference.

**Comment by ADmad** [comment] 2016-02-23 11:38
@lorenzo Refs #7693 and friendsofcake/crud#341  You yourself have confirmed on the crud's tracker that previous issue was a bug :)

**Comment by markstory** [comment] 2016-03-06 18:15
Closing as a pull request is open now.

**Closed by markstory** 2016-03-06 18:15 UTC
Labels: Defect, fixtures, testing
