### ISSUE TITLE
Cake bake all generated controller has lowercase second word in name of Table property of multi word tables

### ISSUE THREAD

**Issue by haddins** [cakephp/cakephp#16578] opened 2022-06-20 04:31 UTC
### Description

I am very new to developing web apps and PHP coding (and everything), so forgive me if this isn't an issue or has already been done but I noticed this:

I auto generated all classes for a CakePHP MVC framework project on a MySQL table named "recipe_categories".
The generated controller "RecipeCategoriesController" refers to its own property "RecipeCategories" (a RecipeCategoriesTable) when generating the view for adding or editing a recipe category. When I ran the script an error was returned. When I investigated further I found that cake bake had defined the name of the Table property as "Recipecategories" only capitalizing the first word. I.e. if I modified the RecipesCategoriesController code to refer to "Recipecategories" (instead of the auto generated "RecipeCategories") then it worked! I was using CakePHP version 4.(something) but I am not sure of the sub versions. (please let me know if you want more information)

### CakePHP Version

4

### PHP Version

8

**Comment by markstory** [comment] 2022-06-20 14:23
How could we reproduce the problem you're having? Is there a command we could run that will result in the incorrectly generated controller?

**Comment by haddins** [comment] 2022-06-20 23:37
OFFICIAL

Hi Mark,

This weekend I can reproduce the problem for real and document it as I go. For now (from memory) it was like this...

I have created a MySQL Table named "recipe_categories"

I used composer to create a CakePHP project in Windows C:\CakePHP\ShoppingListMaker\

At the command prompt I type:

```
C:\>cd "C:\CakePHP\ShoppingListMaker"
C:\CakePHP\ShoppingListMaker> bin\cake bake all recipe_categories
                Now Start the Server
C:\CakePHP\ShoppingListMaker> bin\cake server
```

Next in the browser navigate to:
Localhost:8765/RecipeCategories

If you have display messages installed you will see warnings

Next click on a link next to one of the displayed Recipe Categories e.g. ("View")

Now you should see the error.

As mentioned, I will re-create the error for real on the weekend if you like and document it properly.

Kind regards

Stephen

**Comment by ADmad** [comment] 2022-06-21 01:35
> Next in the browser navigate to:
Localhost:8765/RecipeCategories

This is the cause of your error. By default the app skeleton is configured to use [dashed routes](https://github.com/cakephp/app/blob/1c440d36e31efd86d754fab855ee36d58b6bca69/config/routes.php#L45), so you need to use URL `/recipe-categories`.

Normally you should get a router exception for invalid URL but since you are on Windows which has a case insensitive it loads your controller even with mismatched case.

**Comment by haddins** [comment] 2022-06-21 01:48
UNOFFICIAL

Thankyou,

I will investigate that further.

**Comment by othercorey** [comment] 2022-07-08 07:05
@haddins Do you have anything else before we close this?

**Comment by haddins** [comment] 2022-07-10 13:58
No I don't have anything else. Your suggestion was correct. If I use dashed names in the url it works fine. Please close this.

**Closed as completed** 2022-07-10 15:26 UTC
Labels: invalid
