### ISSUE TITLE
Model#saveMany breaks if entity contains boolean fields with 'false' value, ver 2.7.0

### ISSUE THREAD

**Issue by jpsaltship** [cakephp/cakephp#7069] opened 2015-07-20 13:38 UTC
I use Model#saveMany to update many entities with boolean field like this:
```
$this->ModelExample->saveMany(array(
	0 => array(
		'ModelExample' => array(
			'id' => '1',
			'some_boolean_field' => true
		)
	),
	1 => array(
		'ModelExample' => array(
			'id' => '2',
			'some_boolean_field' => false
		)
	),
));
```
Saving breaks after record with 'false' value assigned to boolean field.

I think problem is with checking result of storing single entity, please take a look:
https://github.com/cakephp/cakephp/blob/2.7/lib/Cake/Model/Model.php#L2342.
```
!in_array(false, Hash::flatten($saved), true)
```
the condition checks fields values instead of result.

**Comment by markstory** [comment] 2015-07-20 16:35
I think the return of save() and saveAssociated() needs to be bool cast for this to work as intended.

**Comment by ezoterik** [comment] 2015-07-21 21:13
The same problem in version 2.6.9

**Comment by markstory** [comment] 2015-07-22 04:10
This sounds like it was caused by #6947

**Comment by markstory** [comment] 2015-07-22 11:54
Closing as a pull request is open now.

**Closed by markstory** 2015-07-22 11:54 UTC
Labels: Defect

**Comment by markstory** [comment] 2015-07-23 02:14
@ezoterik 2.6.10 has been tagged today.
