### ISSUE TITLE
CakePHP 3.4.* composer dependency issue (Your requirements could not be resolved to an installable set of packages.)

### ISSUE THREAD

**Issue by muni2explore** [cakephp/cakephp#10391] opened 2017-03-10 02:45 UTC
I am facing issue dependency issue while installing CakePHP 3.4.* using Composer ... 

Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for cakephp/cakephp 3.4.2 -> satisfiable by cakephp/cakephp[3.4.2].
    - cakephp/cakephp 3.4.2 requires lib-icu >=4.8 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.
  Problem 2
    - cakephp/cakephp 3.4.2 requires lib-icu >=4.8 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - cakephp/debug_kit 3.9.2 requires cakephp/cakephp >=3.1.0 <4.0 -> satisfiable by cakephp/cakephp[3.4.2].
    - Installation request for cakephp/debug_kit 3.9.2 -> satisfiable by cakephp/debug_kit[3.9.2].

Changing folder permission
smarttut@smarttutorials.net [~/public_html/demo_tut/projects/oauth]# composer create-project --prefer-dist cakephp/app cquiz
Installing cakephp/app (3.4.1)
  - Installing cakephp/app (3.4.1)
    Downloading: 100%

Created project in cquiz
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - cakephp/cakephp 3.4.2 requires lib-icu >=4.8 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - cakephp/cakephp 3.4.1 requires lib-icu >=4.8 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - cakephp/cakephp 3.4.0 requires lib-icu >=4.8 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - Installation request for cakephp/cakephp 3.4.* -> satisfiable by cakephp/cakephp[3.4.0, 3.4.1, 3.4.2].
![composer issue](https://cloud.githubusercontent.com/assets/2236409/23779958/aca27796-0569-11e7-92f0-42da964cb952.png)

**Comment by chrisShick** [comment] 2017-03-10 03:24
@muni2explore You need to follow the bug creation format. We need to know what system you are running this one. 

The error is obvious. You have not installed or enabled the intl extension for php.

**Comment by markstory** [comment] 2017-03-10 03:40
Duplicate of #10310. This is fixed on master and will be in the next release.

**Closed by markstory** 2017-03-10 03:40 UTC
