### ISSUE TITLE
UseMuffin & Flash Plugins Broken by 4.1.2

### ISSUE THREAD

**Issue by JacobAGTyler** [cakephp/cakephp#14900] opened 2020-08-13 18:16 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.2
* Platform and Target: MacOS 11, Postgresql 11.

### What you did
On updating from 4.1.1 to 4.1.2, a number of plugins which were previously loading have become unusable.
The repo is: https://github.com/LBDistrictScouts/DistrictLeaders

### What happened
The plugins from UseMuffin (Muffin/Trash & Muffin/Footprint) as well as Flash.Flash became unloadable. I have resolved Flash.Flash, by resolving references to it back to cake core flash.

### What you expected to happen
I need a way to update without breaking my plugins. Is there an alias or something I can use? It appears to be the slash in the plugin name that is breaking the tests, but I can't locate the file or line in the 4.1.1 --> 4.1.2 diff that is causing it.

**Comment by dereuromark** [comment] 2020-08-13 18:17
Can you explain a bit more in detail what is broken.
What errors, what stacktrace etc?

**Comment by JacobAGTyler** [comment] 2020-08-13 18:25
Every integration test is outputting a Missing Plugin Exception

`Cake\Core\Exception\MissingPluginException : Plugin Muffin/Footprint could not be found.
 /Users/jacob/Development/DistrictLeaders/vendor/cakephp/cakephp/src/Core/PluginCollection.php:138
 /Users/jacob/Development/DistrictLeaders/vendor/cakephp/cakephp/src/Core/PluginCollection.php:243
 /Users/jacob/Development/DistrictLeaders/vendor/cakephp/cakephp/src/Http/BaseApplication.php:117
 /Users/jacob/Development/DistrictLeaders/src/Application.php:79`

If I remove that plugin, then Muffin/Trash breaks. I've reverted back to 4.1.1 and it works again.

I have 12 plugins installed and all plugins all of which are latest versions. None of the broken plugins updated at the time of the CakePHP upgrade.

As far as I can see the ones failing have slashes in them.

`
        $this->addPlugin('Expose');

        $this->addPlugin('Muffin/Webservice');

        $this->addPlugin('CakeDto', ['bootstrap' => true]);

        $this->addPlugin('Tools', ['bootstrap' => true]);

        $this->addPlugin('Search');

        $this->addPlugin('Queue', ['routes' => true, 'bootstrap' => true]);

        $this->addPlugin('Ajax', ['bootstrap' => true]);

        $this->addPlugin('Muffin/Footprint');

        $this->addPlugin('DatabaseLog', ['bootstrap' => true]);

        $this->addPlugin('Authorization');

        $this->addPlugin('Authentication');

        $this->addPlugin('Muffin/Trash');

        $this->addPlugin('BootstrapUI');

        $this->addPlugin('WyriHaximus/TwigView');

        // Call parent to load bootstrap from files.
        parent::bootstrap();

        if (PHP_SAPI === 'cli') {
            try {
                $this->addPlugin('Bake');
                $this->addPlugin('IdeHelper');
            } catch (MissingPluginException $e) {
                // Do not halt if the plugin is missing
            }

            $this->addPlugin('Migrations');
        }

        /*
         * Only try to load DebugKit in development mode
         * Debug Kit should not be installed on a production system
         */
        if (Configure::read('debug')) {
            $this->addPlugin('DebugKit', ['bootstrap' => true, 'routes' => true]);
        }
    }`

**Comment by JacobAGTyler** [comment] 2020-08-13 18:30
<img width="596" alt="Screenshot 2020-08-13 at 19 28 16" src="https://user-images.githubusercontent.com/3827053/90172606-2e057380-dd9b-11ea-9aae-1b81f2fa99fa.png">

If I comment out these two the tests all pass. I'm unsure why the ` $this->addPlugin('Muffin/Webservice'); ` is still working, although it isn't used anywhere yet so may be a red herring.

**Comment by othercorey** [comment] 2020-08-13 18:32
Is this part of unit tests? If so, that change was reverted in https://github.com/cakephp/cakephp/pull/14891.

**Comment by dereuromark** [comment] 2020-08-13 18:37
Try latest dev-master.

**Comment by markstory** [comment] 2020-08-13 18:39
I'll get a 4.1.3 release packaged up this weekend.

**Comment by ADmad** [comment] 2020-08-13 18:42
Duplicate of #14889. Fixed in  #14891.

**Closed by ADmad** 2020-08-13 18:42 UTC

**Comment by JacobAGTyler** [comment] 2020-08-13 18:46
> Try latest dev-master.

Just trying DevMaster now, but yes looks like a duplicate of #14889

**Comment by JacobAGTyler** [comment] 2020-08-13 18:49
Awesome, all fixed. Sorry I didn't find #14889 before, it wasn't in my search terms. Thanks for all the help though! 👍

**Comment by othercorey** [comment] 2020-08-16 01:08
Released in 4.1.3
