### ISSUE TITLE
Error Alias Model/Table-Name not working

### ISSUE THREAD

**Issue by mdlouhy** [cakephp/cakephp#5882] opened 2015-02-13 13:58 UTC
```
$this->belongsTo('CompanyAddresses', ['className' => 'Addresses']);
```

It works again if I change Line 272 of src/ORM/Association.php from
```
if (strpos($this->_className, '\\') === false) {
```
to
```
if (false && strpos($this->_className, '\\') === false) {
```

It seems like that the association name is taken from the class name not the alias.
Addresses association name is taken instead of CompanyAddresses
and the foreign key is address_id instead of the correct company_address_id because Addresses model is taken instead of CompanyAddresses

https://github.com/cakephp/cakephp/pull/5836/files
src/ORM/Association.php
Alias is not created anymore for existing Models - since 13, February.

**Comment by LeFuret17** [comment] 2015-02-15 09:39
I confirm the problem.
With for exemple a users table with a colum modified_by.
the relation is :
```	
	$this->belongsTo('Modified', [
			'className' => 'Users',
			'foreignKey' => 'modified_by',
			'propertyName' => 'modified_by'
		]);
```
and the request is :
``` 
		$user = $this->Users->find()
				     ->contain(['Modified'])
				     ->where(['Users.id' => $id])
				     ->first();

```
I've this error :
```
SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'Users' 
```
With the modification mdlouly it's Ok.

**Comment by AD7six** [comment] 2015-02-15 10:10
Applying that change would break [this test](https://github.com/cakephp/cakephp/blob/3.0/tests/TestCase/ORM/TableTest.php#L505-L510) - it was added to account for a specific scenario (using plugin models).

Needs a different fix, to take the table alias from the association definition and not the table object I think.

**Comment by wadeos** [comment] 2015-02-16 01:06
I'm having the same problem as @LeFuret17. MySQL is throwing a `SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'Pages'` It is caused being by a belongsTo relationship to its self. Should we just apply the fix that @mdlouhy was talking about ?

**Comment by mdlouhy** [comment] 2015-02-16 01:09
what I did wasn't a fix - It was just an illustration.

**Comment by wadeos** [comment] 2015-02-16 01:25
Sorry, I was never trying to claim it was a fix. Just wanting a workout until a fix can be published.

**Comment by mdlouhy** [comment] 2015-02-16 01:29
I am confident they will provide a real fix on Monday or Tuesday. I use my "fix" in the meantime.

**Comment by markstory** [comment] 2015-02-16 02:30
One can also use the tagged release (3.0.0-RC2) until this issue is fixed as well :smile:

**Comment by AD7six** [comment] 2015-02-16 16:49
I've added a test for self-joined associations to #5911 - closing as the root cause of the ticket, is the same as #5898.

**Closed by AD7six** 2015-02-16 16:49 UTC
Labels: Defect
