### ISSUE TITLE
Undefined index in entity properties for new entity

### ISSUE THREAD

**Issue by BenoKop** [cakephp/cakephp#12115] opened 2018-05-22 07:57 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.4.
* Platform and Target: Apache / MySQL.

### What you did
I wrote the following reusable Trait for Users:
```php
namespace App\Model\Traits;
trait UsersPropertiesTrait
{

    /**
     * Return fullName of contact.
     *
     * @return string
     */
    protected function _getFullName()
    {
        return $this->_properties['first_name'] . '  ' . $this->_properties['last_name'];
    }

    /**
     * Return fullName + email.
     *
     * @return string
     */
    protected function _getFullLabel()
    {
        return $this->_getFullName() . '  (' . $this->_properties['email'] . ')';
    }
}
```
Entity code for Users, based on CakeDC Users Class:
```php
namespace App\Model\Entity;

use App\Model\Traits\UsersPropertiesTrait;
use CakeDC\Users\Model\Entity\User;

class MyUser extends User
{
    use UsersPropertiesTrait;

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false
    ];

    /**
     * Fields that are excluded from JSON versions of the entity.
     *
     * @var array
     */
    protected $_hidden = [
        'password',
        'token'
    ];

    protected $_virtual = ['full_label', 'full_name'];
}
```
The virtual properties are working if the data already exists. But since my upgrade to 3.6.4, it doesn't work with a new entity.

### What happened
**Undefined index: first_name in [/var/www/html/charlie/src/Model/Traits/UsersPropertiesTrait.php, line 14]**

The new entity hasn't the expected keys.

### What you expected to happen
What can i do to make this work again ?

**Comment by ADmad** [comment] 2018-05-22 08:32
New entities never have properties auto populated. Only entities generated as a result of `Table::find()` do.

**Comment by BenoKop** [comment] 2018-05-22 08:55
Sure, but before newEntity() wasn't bothered about it.

**Comment by dereuromark** [comment] 2018-05-22 08:58
So this happened between patch versions? Do you know between which ones exactly? Then this might be a small regression.

**Comment by BenoKop** [comment] 2018-05-22 09:01
I updated an old project, I Jumped directly from 3.4.6 to 3.6.4.

**Comment by dereuromark** [comment] 2018-05-22 09:03
Check https://book.cakephp.org/3.0/en/appendices/3-5-migration-guide.html#behavior-changes as this might explain the changes.

**Comment by saeideng** [comment] 2018-05-22 09:04
this works for me
I dont have `first_name`  and `last_name` fields on DB :)
```php
//entity
    protected function _getFullName()
{
    return $this->_properties['first_name'] . '  ' . $this->_properties['last_name'];
}
//controller 
    $entity = $this->Users->newEntity();
    $entity->first_name='first';
    $entity->last_name='last';
    debug($entity->fullName);
```

**Comment by BenoKop** [comment] 2018-05-22 09:12
I have the fields on DB but you solution seems to work again in my case.

// controller
$myUser = $this->MyUsers->newEntity();
$myUser->first_name = '';
$myUser->last_name = '';
$myUser->email = '';

I find that evolution a bit weird, but why not if it works...

**Comment by hdogan** [comment] 2018-11-03 12:38
I'm using
```php
if ($this->isNew()) {
    return '';
}
```
condition in virtual property definition to get rid of those notice errors.

**Comment by dereuromark** [comment] 2018-11-03 12:43
It looks like this behavior is something we might have to revisit for 3.7 then.
People do expect those to at least return null instead of throwing notices.

**Comment by ADmad** [comment] 2018-11-03 14:07
Instead of using `$this->_properties`, use `$this->get('prop_name')` and it will return `null` non-existent properties.

**Comment by dereuromark** [comment] 2018-11-03 14:09
Do we have to document that a bit better maybe in docs?

**Comment by dereuromark** [comment] 2018-12-12 00:14
As long as we dont have a proper API here for getting as in e.g. [Dto](https://github.com/dereuromark/cakephp-dto) we shouldnt force the developer to know what fields are virtuel, or nonvirtuel or whatever. So I am for fixing this to not emit a warning here in 3.7.

**Comment by markusramsak** [comment] 2018-12-12 08:53
> Do we have to document that a bit better maybe in docs?

I think it is already very clear what you can do with entities and what not. I never use `$this->_properties` always use `$this->get()` which always returns the value or null if it doesn't exist which is my cases the only thing I need to know.

I have a similar method where I do the following:
```
protected function _getSalutation() {
        $salutation = __('Anonymous');
        if (!empty($this->lastname)) {
            $salutation = $this->lastname;
            if (!empty($this->firstname)) {
                $salutation = $this->firstname . ' ' . $salutation;
            }
        }

       $gender = $this->gender_salutation;
       if (!empty($gender)) {
            $salutation = $gender . ' ' . $salutation;
        }

        return $salutation;
}
```

**Comment by ADmad** [comment] 2018-12-12 10:45
Closing as there's nothing to be done here. Use the get() method or magic properties instead of $_properties and the error is avoided.

I don't think any extra documentation is required either. It's basic PHP knowledge that trying to access an nonexistent array index will result in error.

**Closed by ADmad** 2018-12-12 10:45 UTC
Labels: Defect

**Comment by saeideng** [comment] 2018-12-12 19:31
@ADmad  maybe docs need to update from `_properties['...']` to get() method or magic properties
