### ISSUE TITLE
$query->count() is not giving the count of result when used with formatResults

### ISSUE THREAD

**Issue by mcube27** [cakephp/cakephp#14955] opened 2020-09-02 15:14 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.13.
* Platform and Target: Apache 2.4.3, MySql 5.7.21, PHP 7.4.3
### What you did
A query with a formatResults to filter values received from the query :
```
$eventOverlapping = $this
                ->find()
                ->contain('Bookings')
                ->where(
                    [
                        'Events.workplace_id' => $event->workplace_id,
                        'Events.start <' => $event->end,
                        'Events.end >' => $event->start,
                    ]
                )
                ->formatResults(
                    function (CollectionInterface $findEvents) use ($event) {
                        // A modifier quand les events auront leur status.
                        $eventsFilteredForBookingStatus = $findEvents->filter(function ($findEvent) use ($event) {
                            if (isset($findEvent->booking_id) && !empty($findEvent->booking)) {
                                if ($findEvent->booking_id != $event->booking_id ?? -1) {
                                    if (
                                        !in_array(
                                            $findEvent->booking->status,
                                            [Booking::STATUS_NO_SHOW, Booking::STATUS_CANCELED]
                                        )
                                    ) {
                                        return true;
                                    } else {
                                        return false;
                                    }
                                } else {
                                    return false;
                                }
                            } elseif (!isset($findEvent->booking_id)) {
                                return true;
                            } else {
                                return false;
                            }
                        });

                        return $eventsFilteredForBookingStatus;
                    }
                );
            return $eventOverlapping->count() === 0;
```

### What happened
On the last line, `$eventOverlapping->count()` returns 1 instead of 0, while `$eventOverlapping->all()` returns 
```
object(Cake\Datasource\ResultSetDecorator) {
	'count' => (int) 0
}
``` 
and `$eventOverlapping->toArray()` returns an empty array.

### What you expected to happen
I was expecting to get the actual count ie. 0.

**Comment by ndm2** [comment] 2020-09-02 15:38
That is the expected behavior, `count()` is a concrete query builder method that will return the actual number of records that will be queried, while after invoking `all()`, you're operating on a resultset/collection, which's `count()` method will operate on the possibly filtered collection.

You're usually best of trying to filter on SQL level. For situations where that's _really_ not possible, you'll have to work with result sets if you need to know the filtered count.

If there are situations where you need to pass a query object which's `count()` method must return the filtered count result, you could for example implement a custom count query via `Query::counter()`, but it might require some creative fiddling to get this working in a performant manner.

**https://book.cakephp.org/4/en/orm/query-builder.html#returning-the-total-count-of-records**

**Comment by othercorey** [comment] 2020-09-02 15:57
This can be confusing since most count functions don't change the "collection" definition. Maybe we can make this more obvious somehow.

**Comment by mcube27** [comment] 2020-09-02 16:00
I understand, however the returned object `$eventOverlapping` is a Query object. It is confusing to say that it's the expected behavior since count works on Query objects.

**Comment by othercorey** [comment] 2020-09-02 16:09
As the comment here explains, it re-runs the query with `COUNT(*)`:
https://github.com/cakephp/cakephp/blob/a03b363939c135e2446c31ed82017971ac2b1fff/src/ORM/Query.php#L888

We could explain this better in the QueryInterface docblock.

**Comment by ADmad** [comment] 2021-08-11 06:49
Closing as the issue is due to confusion between `Query::count()` and `CollectionInterface::count()`.

**Closed by ADmad** 2021-08-11 06:49 UTC
