### ISSUE TITLE
A date array can't be converted as a date type column in _joinData 

### ISSUE THREAD

**Issue by hodakamio** [cakephp/cakephp#12485] opened 2018-08-20 02:34 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.2
* Platform and Target: MAMP apache2.2.32 , Mysql5.6.35, PHP7.1.8

### What you did
I have many-to-many relation tables.
Users table, calendars table, and calendars_users table.
Users can subscribe any events of calendars, and subscription date stored in calendars_users table.
view is:
```
foreach($event_data as $id=>$data){
    <?= $this->Form->select("calendars.{$id}.id", $events, [
        'empty' => '---',
        'value' => ...
    ]) ?>
    <?= $this->Form->input("calendars.{$id}._joinData.subscribed", [
        'type' => 'date',
        'dateFormat' => 'YMD',
        'empty' => '---',
        'value' => ...
    ]) ?>
}
```

### What happened
`Cake\Controller\Component\SecurityComponent->_validatePostCORE/src/Controller/Component/SecurityComponent.php, line 124`
says:
`Missing field ‘calendars.1._joinData.subscribed’ in POST data`

Request data as follows:
```
calendars (array)
    1 (array)
        id 1
        _joinData (array)
            subscribed (array)
                year 2018
                month 08
                day 01
```

### What you expected to happen
A date array of _joinData could be also converted to a date type data in marshalling.  Why not _joinData?

This might be not a bug and my misunderstanding, how can I work it?

Thanks in advance.

**Comment by markstory** [comment] 2018-08-20 21:05
How are you marshalling data into your entities?

**Comment by hodakamio** [comment] 2018-08-21 00:43
just converted a date array to date type string, and unset the array.
This does not work.
```
class CalendarsUsersTable extends Table
{
    ....
    public function beforeMarshal(Event $event, ArrayObject $data, ArrayObject $options)
	{
		if (isset($data['subscribed']) && is_array($data['subscribed'])) {
			$ymd = $data['subscribed']['year'].'-'.$data['subscribed']['month'].'-'.$data['subscribed']['day'];
			unset($data['subscribed']['year']);
			unset($data['subscribed']['month']);
			unset($data['subscribed']['day']);
			$data['subscribed'] = $ymd;
		}
        }
    ....
}
```

**Comment by markstory** [comment] 2018-08-21 01:28
I meant how are you calling newEntity()/patchEntity()? These methods can convert `_joinData` records if used correctly and the `_joinData` model has been linked up.

**Comment by hodakamio** [comment] 2018-08-21 02:12
Model:
```
class UsersTable extends Table
{
    public function initialize(array $config)
    {
        .....
        $this->belongsToMany('Calendars', [
	    'joinTable' => 'calendars_users',
	    'foreignKey' => 'user_id',
	    'targetForeignKey' => 'calendar_id',
	    'through' => 'CalendarsUsers',
	]);
        ....
    }
}
class CalendarsTable extends Table
{
    public function initialize(array $config)
    {
        ....
        $this->belongsToMany('Users', [
            'joinTable' => 'calendars_users',
            'foreignKey' => 'calendar_id',
            'targetForeignKey' => 'user_id',
            'through' => 'CalendarsUsers',
        ]);
        ....
    }
}
class CalendarsUsersTable extends Table
{
    public function initialize(array $config)
    {
        ....
        $this->belongsTo('Calendars', [
	    'foreignKey' => 'calendar_id',
	    'joinType' => 'INNER'
	]);
	$this->belongsTo('Users', [
	    'foreignKey' => 'user_id',
	    'joinType' => 'INNER'
	]);
    }
}
```

In add/edit action of the Users controller:
as the book page:
https://book.cakephp.org/3.0/ja/orm/saving-data.html#id19
```
if ($this->request->is(['patch', 'post', 'put'])) {
    $user = $this->Users->patchEntity($user, $this->request->getData(), ['associated' => ['Calendars._joinData']]);
    $user->setDirty('calendars', true);
    if ($this->Users->save($user)) {
	$this->Flash->success(__('success message'));
        return $this->redirect(['action' => 'index']);
    }
    $this->Flash->error(__('failed message'));
}
```
That's all i did.
Thanks.

**Comment by markstory** [comment] 2018-08-21 02:40
Ok. Is the problem that the request data is not being converted into a `Time` object or that `SecurityComponent` is causing the request to fail?

**Comment by hodakamio** [comment] 2018-08-21 02:45
Yes, that' the problem.
Sorry for my poor English.

**Comment by markstory** [comment] 2018-08-21 03:06
No need to apologize. I wanted to make sure I understood the problem. I'll try to reproduce the issue you're having with marshalling data in the joinData record.

**Comment by markstory** [comment] 2018-11-27 14:15
Closing as I was unable to reproduce. If more information becomes available please reopen this issue.

**Closed by markstory** 2018-11-27 14:15 UTC
Labels: Need more information, ORM, On hold
