### ISSUE TITLE
3.3.3 Regression: original entity data lost on save

### ISSUE THREAD

**Issue by jeremyharris** [cakephp/cakephp#9411] opened 2016-09-05 16:44 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.3

### What you did

Continuing my upgrade to 3.3, I found a possible regression caused by https://github.com/cakephp/cakephp/pull/9354 caught by our tests. We were relying on original entity data to trigger events based on the entity's changes.

Here's a simple test case:

```php
    public function testOriginalsPersist()
    {
        $UsersTable = TableRegistry::get('Users');
        $user = $UsersTable->get(1);
        $this->assertSame('mariano', $user->username);

        $user = $UsersTable->patchEntity($user, ['username' => 'new_username']);
        $this->assertSame('mariano', $user->getOriginal('username'));

        $UsersTable->save($user);

        $this->assertSame('mariano', $user->getOriginal('username'));
    }
```

This test passes in 3.3.2 and fails in 3.3.3 due to the above mentioned patch.

### Expected Behavior

Expected the original data to persist the save.

### Actual Behavior

Original data is lost.

**Comment by ADmad** [comment] 2016-09-05 17:03
Expecting original values to be available after an entity is persisted and save operation is complete is unwise IMHO. The original values should still be available in afterSave if you need to do so operations based on that.

**Comment by lorenzo** [comment] 2016-09-05 17:03
A similar bug was reported, but with a different view point: original data should not persist once you call `clean()`, which `save()` does.

Personally, I don't think it is a great idea to persist original after saving.

**Comment by jeremyharris** [comment] 2016-09-05 17:06
So does this mean the original functionality in <3.3.2 was a bug that we were relying on? What are the disadvantages of keeping the original data after saving (I'm curious)?

**Comment by lorenzo** [comment] 2016-09-05 17:10
The problem starts when you modify the saved entity again, asking for original will give you the previous one, instead of the current state. A side effect is useless memory consumption.

before settling on whether or not the change should be reverted, may I suggest using something like AuditStash? It already has the logic for tracking modified properties after a commit.

**Comment by markstory** [comment] 2016-09-05 18:51
It does look like this was caused by #9354. We either get to keep that bug, or this one. Philosophically I'm for keeping the current behavior, as it makes `save()` return a similar entity to what you would get if the entity was reloaded with `find()`.

**Comment by jeremyharris** [comment] 2016-09-05 19:09
I understand the reasoning behind this, so I'm fine with closing. I'll implement something to match what we need in our app code.

Would it be worth mentioning this change in the migration guide or release notes (too late?) as it breaks applications that relied on the past behavior. I feel it's sort of a fuzzy area as the previous behavior is now considered a bug.

**Comment by lorenzo** [comment] 2016-09-05 19:14
I think it is worth mentioning it in the guide

**Comment by markstory** [comment] 2016-09-05 19:34
@jeremyharris I'm a dork and forgot to publish the release notes for 3.3.3. When done building they will contain

> * ``EntityTrait::clean()`` now resets the original value states.

Is there anything you think I should add to that?

**Comment by jeremyharris** [comment] 2016-09-05 19:39
@markstory I opened a PR against the docs to mention it. Perhaps the release notes (are they published in other places than just Github?) can contain a little mention that "applications relying on this bug will no longer have access to original values after a successful save" or something to that effect.

**Comment by markstory** [comment] 2016-09-05 20:59
@jeremyharris I'll update the bakery to that effect.

**Comment by markstory** [comment] 2016-09-05 21:02
Closing as the docs and release notes have been updated.

**Closed by markstory** 2016-09-05 21:02 UTC
Labels: documentation
