### ISSUE TITLE
Incompatible types according to phpstan

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#13874] opened 2019-11-12 08:40 UTC
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.5.
* Platform and Target: Linux, Apache, MySQL.

### What you did
In the model:
```
$entities = $this->MyModel->newEntities($data);
$this->MyModel->saveMany($entities);
```
Then I run phpstan on level 5.

### What happened
The error was reported:
```
Parameter #1 $entities of method Cake\ORM\Table::saveMany() expects      
Cake\Datasource\ResultSetInterface&iterable<Cake\Datasource\EntityInter  
face>, array<Cake\Datasource\EntityInterface> given.
```

### What you expected to happen
I would expect no error.

**Comment by ADmad** [comment] 2019-11-12 11:38
The docblock has a union type `\Cake\Datasource\EntityInterface[]|\Cake\Datasource\ResultSetInterface` for the `$entities` argument. No idea why phpstan thinks it's an intersection `Cake\Datasource\ResultSetInterface&iterable<Cake\Datasource\EntityInter  
face>`

**Comment by othercorey** [comment] 2019-11-12 12:24
What version of phpstan are you using?

**Comment by bancer** [comment] 2019-11-12 12:34
```
Vendor/bin/phpstan --version
PHPStan - PHP Static Analysis Tool 0.11.16
```

**Comment by othercorey** [comment] 2019-11-12 13:00
I couldn't reproduce this with the phpstan sandbox.

https://phpstan.org/r/a7c8d2fa-9b03-458d-b672-70eb8270052a

**Comment by ADmad** [comment] 2019-11-12 13:00
> PHPStan - PHP Static Analysis Tool 0.11.16

Latest phpstan version is `0.11.19`.

**Comment by bancer** [comment] 2019-11-12 13:51
Updating phpstan to version 0.11.19 did not fix the problem.

**Comment by ADmad** [comment] 2019-11-12 13:57
@othercorey I wouldn't rely 100% on phpstan's playground result. It runs on phpstan's development branch and can have different behaviour than the `0.11` releases, see https://github.com/phpstan/phpstan/issues/2536.

@bancer I don't see what we can do here if phpstan infers incorrect type. Either submit an issue with phpstan or ignore the error in your config file.

**Comment by bancer** [comment] 2019-11-12 14:04
Hmmm... 
Changing `@param \Cake\Datasource\EntityInterface[]|\Cake\Datasource\ResultSetInterface` 
to  `@param []\Cake\Datasource\EntityInterface|\Cake\Datasource\ResultSetInterface` 
in `saveMany()` fixes the problem.

**Comment by ADmad** [comment] 2019-11-12 14:06
I haven't seen `[]\Cake\Datasource\EntityInterface` format document anywhere, if you have please provide a reference.

Also try `(\Cake\Datasource\EntityInterface[])|\Cake\Datasource\ResultSetInterface`.

**Comment by bancer** [comment] 2019-11-12 14:08
`(\Cake\Datasource\EntityInterface[])|\Cake\Datasource\ResultSet` still gives the error.

**Comment by bancer** [comment] 2019-11-12 14:11
Hmmm... Weird. `\Cake\Datasource\EntityInterface[]||\Cake\Datasource\ResultSetInterface` also fixes the problem.

**Comment by othercorey** [comment] 2019-11-14 21:48
This sounds like a phpstan issue.  We can't control how they parse the types, right?

**Comment by dereuromark** [comment] 2019-11-18 09:57
I agree, consider opening a bug report on their repo instead. Closing then for now as we can't do much at this point.

**Closed by dereuromark** 2019-11-18 09:57 UTC
