### ISSUE TITLE
Translatebehaviour fails saving multiple Translations

### ISSUE THREAD

**Issue by 3811015** [cakephp/cakephp#9524] opened 2016-09-26 14:50 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.
Still there: https://github.com/cakephp/cakephp/commit/5803eefc3670993e0c819de10b734321a0a86ee5
* Platform and Target: 

### What you did
I followed this instructions. literally.
http://book.cakephp.org/3.0/en/orm/behaviors/translate.html#saving-multiple-translations

### Expected Behavior
Translations beeing saved. Period.

### Actual Behavior
```Error: Call to a member function dirty() on array ```

### Where I think the fault happens:

```$translations``` is an array: 
```
$translations = (array)$entity->get('_translations');
```

But following is performed on it:
```
 foreach ($translations as $lang => $translation) {
            foreach ($fields as $field) {
                if (!$translation->dirty($field)) {
```

### What i think would fix it:

Using an entity. Not an array.
```
if (!$entity->dirty($field)) {
```

**Comment by 3811015** [comment] 2016-09-26 15:09
3.3.

**Comment by markstory** [comment] 2016-09-26 20:47
I'll see if I can reproduce this.

**Comment by markstory** [comment] 2016-09-29 03:27
I'm not able to reproduce the issue you're having. Can you:

* Make sure that `_translations` is in the `$_accessible` property in your entity.
* Make sure that `['translations' => true]` is being passed as an option to newEntity().
* Make sure you're using at least CakePHP 3.3.3

**Comment by markstory** [comment] 2016-10-02 23:00
Closing as I couldn't reproduce the issue. If you continue to experience the issue please reply back and I'd be happy to help further.

**Closed by markstory** 2016-10-02 23:00 UTC
Labels: behaviors, Defect, i18n, On hold
