### ISSUE TITLE
Collection `skip(x)` throw exception when collection size is `x`

### ISSUE THREAD

**Issue by gaetansnl** [cakephp/cakephp#11165] opened 2017-09-07 09:33 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.0

### What you did
```php
        $collection = new Collection([1]);
        $allExceptFirst = $collection->skip(1)->toList();
```
### What happened
OutOfBounds exception

### What you expected to happen
return empty collection

**Comment by lorenzo** [comment] 2017-09-07 10:33
That makes sense, no?

**Comment by pulse14** [comment] 2017-09-07 10:40
I don't understand in what way it makes sense ?

IMO If I skip 2 items in a collection containing one item, i'm OutOfBounds because I try to skip an item that does not exists. But in my example I skip one item, in a collection of one, so I do nothing wrong. I should have 0 items in my collection. And I can use ::isEmpty.

**Comment by dereuromark** [comment] 2017-09-07 10:49
I agree with @pulse14 , you reach the end of the array, but you are not yet out of bounds.

**Comment by lorenzo** [comment] 2017-09-07 11:17
Would you say it makes sense if you `skip(2)`?

**Comment by dereuromark** [comment] 2017-09-08 09:21
@lorenzo No, skip(2) only makes sense for 2+ of count. In his example it is truly out of bounds as he mentioned.
It looks like a bug in PHP and the LimitIterator implementation.

To display, for array of count 2:

[a, b]
- skip(0) => [a, b] (makes sense^^)
- skip(1) => [b]
- skip(2) => Is Exception, BUT should be []
- skip(3) => Always is exception

IMO skip() should behave similar to array_pop() and array_shift() operations on an array implementations. If you take the last one out, it is an empty array(). If you then do it again it should fail.

**Comment by dereuromark** [comment] 2017-09-08 09:36
My reasoning here comes from looking at the 0 count behavior:
```
// Count of 0 going in:
$collection = new Collection([]);
$allExceptFirst = $collection->skip(0)->toList();
// Results in [] and not OutOfBoundsExeption!
```

This must be in sync with the behavior moving up for count===skip:

```
// Count of 1 going in:
$collection = new Collection([a]);
$allExceptFirst = $collection->skip(1)->toList();
// Now OutOfBoundsExeption :(
```
and
```
// Count of 2 going in:
$collection = new Collection([a, b]);
$allExceptFirst = $collection->skip(2)->toList();
// Now OutOfBoundsExeption :(
```

**Comment by markstory** [comment] 2017-10-26 13:16
Is it reasonable to fix the `0` case to match the other scenarios (raise OutOfBoundsException)?  Making skip(x) return an empty collection would require re-implementing `LimitIterator` which I'm not keen on doing.

**Comment by markstory** [comment] 2019-07-14 02:26
Closing as I wasn't able to reproduce this in our test suite.

**Closed by markstory** 2019-07-14 02:26 UTC
Labels: collection, defect
