### ISSUE TITLE
SqlserverSchema return colum length double the actual size

### ISSUE THREAD

**Issue by dmromanov** [cakephp/cakephp#11295] opened 2017-10-07 19:18 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.3.
* Platform and Target: Windows, MS SQL Server 2012.

### What you did
I've created a fixture with a string field having a limit of 50 characters. 
```php
// extra columns were truncated
class BakeArticlesFixture extends TestFixture
{
    public $fields = [
        'title' => ['type' => 'string', 'length' => 50, 'null' => false],
    ];
}
```

### What happened
During unit-testing, the table's object reported, that the "title" field has a length of 100 characters.
```php
$schema = $table->getSchema();
```

### What you expected to happen
The length of the field to be reported as 50 characters.

[AppVeyor's build log](https://ci.appveyor.com/project/cakephp/bake/build/1.0.594#L285)
Affects cakephp/bake/pull/335

**Comment by markstory** [comment] 2017-10-07 20:49
This is likely caused by SQLServer telling us that the field is double the length it actually is because SQLServer uses ucs2/utf16 internally. There might not be a way around this.

**Comment by dmromanov** [comment] 2017-10-07 21:24
Can't we just divide the value by 2?

**Comment by markstory** [comment] 2017-10-08 01:11
> Can't we just divide the value by 2?

We could. We'd have to make sure the columns where `NVARCHAR` / `NCHAR` and not the standard `VARCHAR`/`CHAR` columns as only types with the `N` prefix have the double length issue.

**Comment by markstory** [comment] 2017-10-08 14:12
Closing as there is a pull request open now.

**Closed by markstory** 2017-10-08 14:12 UTC
Labels: database, Defect, On hold, ORM, sqlserver
