### ISSUE TITLE
Contain usage of custom finder not working

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#10223] opened 2017-02-14 19:48 UTC
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.0
* Platform and Target: Apache 2, PHP 7.1.1, MySQL 5.7

### What you did

```
        $jobs = $this->Jobs->find('active')
            ->contain(['JobLogs' => [
                'strategy' => 'select',
                'finder' => ['orphan' => ['node_id' => $nc->node_id()]]
            ]]);
```

Jobs is returned with all JobLogs records.

### What happened

Confirmed that finder is not called.

```
    public function findOrphan(Query $query, array $options = [])
    {
        dd('findOrphan');
    }
```

### What you expected to happen

Finder for contain should be used instead of find "All".

**Comment by ADmad** [comment] 2017-02-14 20:15
I never knew such an usage was possible. Is it documented or are there test cases for it?

**Comment by thinkingmedia** [comment] 2017-02-14 20:22
@ADmad I'm digging in the code now. There's no support for this in the eagerLoader for 3.4, and that's okay. I'll see if I can figure out why I did it this way in 3.3.

**Comment by thinkingmedia** [comment] 2017-02-14 20:29
@ADmad I think I followed this SO answer

http://stackoverflow.com/questions/26926945/custom-finder-with-matching-in-association-definition

**Comment by thinkingmedia** [comment] 2017-02-14 20:37
This was not a defect. It was just an side effect of how 3.3 loaded associations.

To move forward:

1. Do we add support for this?
2. Do we throw an argument exception saying "finder" is not support.
3. Do we do nothing.

**Comment by robertpustulka** [comment] 2017-02-14 22:05
```php
'finder' => ['orphan' => ['node_id' => $nc->node_id()]]
```

I like that. This way we could configure several finders.

**Comment by markstory** [comment] 2017-02-14 22:27
> Do we throw an argument exception saying "finder" is not support.

We don't throw exceptions in other places when unexpected keys are provided in options arrays. I don't know why this would be different.

Adding support for `finder` sounds interesting. Resolving all the joins might get hairy as custom finders can modify the query with more 'contain' and 'matching' calls.

**Comment by thinkingmedia** [comment] 2017-02-15 02:18
@markstory we already support custom finders for associations, and in contain using the query builder. This is just a matter of syntax for using a finder.

Add the `finder` key to the $options array would be consistent with how Table::get() works with custom finders. That is the only other place that I could find that uses the key `finder` in options.

**Comment by robertpustulka** [comment] 2017-02-15 08:25
@thinkingmedia @lorenzo 

Is there anywhere support for multiple finders? Somethink like:
```php
'finder' => ['foo' ,'bar']
//or
'finder' => [
    'foo' => [
        'id' => 1
    ],
    'bar'
]

**Comment by lorenzo** [comment] 2017-02-15 09:03
The `finder` option for arrays in contain is called `queryBuilder` as explained in the API docs https://api.cakephp.org/3.4/class-Cake.ORM.Query.html#_contain

**Comment by lorenzo** [comment] 2017-02-15 09:05
I'm closing because I think there are already enough options for contain, no need to make it more complex than it already is. Just pass any callable to `queryBuilder`!

**Comment by lorenzo** [comment] 2017-02-15 09:13
Digging further In the code I can see the docs for `finder` where added by the author of that stackoverflow response, and that there is one shy test in the code to support it's usage. Given that I don't remember adding that, and it was probably me who did, I think I'll just deprecate it.

The excess of alternative syntax makes it difficult to not break things when refactoring

**Comment by thinkingmedia** [comment] 2017-02-15 13:32
@lorenzo thank you for showing restraint on this.

Sorry I opened it :)

**Comment by lorenzo** [comment] 2017-02-15 20:18
Nothing to be sorry about @thinkinmedia

This showed a poorly documented and poorly tested part of the code, so it was valuable :)

**Comment by ADmad** [comment] 2017-06-20 08:26
@lorenzo I too stumbled upon this yesterday. One of the plugin's I maintained has such [usage](https://github.com/UseMuffin/Trash/blob/master/tests/TestCase/Model/Behavior/TrashBehaviorTest.php#L297) which worked prior to 3.4 and [fails](https://travis-ci.org/UseMuffin/Trash/builds/244647048) now on 3.4.

The docblock for `Query::contain()` does show examples of using `finder` option and also there [tests](https://github.com/cakephp/cakephp/blob/master/tests/TestCase/ORM/QueryTest.php#L2790-L2817) for it. So if it doesn't work currently it's a regression.

@thinkingmedia Do you still have problem with the example you have provided? Similar usage in the test case I linked also fails.

**Comment by cleptric** [comment] 2017-06-21 21:00
Closing again as we have an open PR to fix this.

**Closed by cleptric** 2017-06-21 21:00 UTC
Labels: Defect, ORM
