### ISSUE TITLE
Fails to save entities in find() loop with MSSQL

### ISSUE THREAD

**Issue by celsowm** [cakephp/cakephp#11271] opened 2017-10-04 15:06 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4
* Platform and Target: Windows Server 2012 R2, PHP 7.0.10, SQL SERVER 2008 R2

### What you did

```
$servidor_table = \Cake\ORM\TableRegistry::get('Servidor');
$acervo_ldap_table = \Cake\ORM\TableRegistry::get('AcervoLdap');

$servidores = $servidor_table->find();

foreach ($servidores as $servidor) {

    $acervo_ldap_objeto = $acervo_ldap_table->newEntity([
                    'ldap' => 'xpto',
                    'servidor_id' => $servidor->COD_SERVIDOR
                ]);

   $acervo_ldap_table->save($acervo_ldap_objeto);

}
```

### What happened
`Error: SQLSTATE[HY010]: [Microsoft][ODBC Driver 11 for SQL Server]Function sequence error`

### What you expected to happen
Just Save

### Workaround
Using the ->toArray();
`$servidores = $servidor_table->find()->toArray();`

PS.: It's not the first time and we are not the only with the same problem:
https://stackoverflow.com/questions/39614060/cakephp-fails-to-save-entities-in-loop-with-mssql

**Comment by markstory** [comment] 2017-10-04 20:33
How is this an issue with CakePHP? It seems like you're getting a sequence error from SQLServer.

**Comment by celsowm** [comment] 2017-10-05 12:02
Hi Mark,
Well.... for this situation, the cakephp only works with the **->toArray()** approach. Could even be a sqlsrv bug but as we can see on stackoverflow it's not the first time this problems occurs with cake and the comment about lazy approach was the hint for me to try the toArray() thing.

If you want I could create a small foobar project to test this.

**Comment by chinpei215** [comment] 2017-10-05 22:44
@celsowm I could reproduce this issue. Do you have any ideas to fix this problem?

**Comment by markstory** [comment] 2017-10-06 00:39
This sounds like multiple cursors which is something that SQLServer does not like at all.

**Comment by celsowm** [comment] 2017-10-06 14:23
Hi @chinpei215, if you could would be nice too ! 
This is our db configuration: 

```
USE [master]
GO

/****** Object:  Database [mybd]    Script Date: 06/10/2017 11:08:44 ******/
CREATE DATABASE [mybd] ON  PRIMARY 
( NAME = N'mybd_Data', FILENAME = N'D:\BASES\DATA\mybd_290317.mdf' , SIZE = 13465216KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'mybd_Log', FILENAME = N'D:\BASES\LOG\mybd_LOG_290317.ldf' , SIZE = 5000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 25600KB )
GO

ALTER DATABASE [mybd] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [mybd].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [mybd] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [mybd] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [mybd] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [mybd] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [mybd] SET ARITHABORT OFF 
GO
ALTER DATABASE [mybd] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [mybd] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [mybd] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [mybd] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [mybd] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [mybd] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [mybd] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [mybd] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [mybd] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [mybd] SET  DISABLE_BROKER 
GO
ALTER DATABASE [mybd] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [mybd] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [mybd] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [mybd] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [mybd] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [mybd] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [mybd] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [mybd] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [mybd] SET  MULTI_USER 
GO
ALTER DATABASE [mybd] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO
ALTER DATABASE [mybd] SET DB_CHAINING OFF 
GO
ALTER DATABASE [mybd] SET  READ_WRITE 
GO


```

**Table acervo_ldap:**

```
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[acervo_ldap](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[servidor_id] [varchar](4) NULL,
	[ldap] [varchar](50) NULL,
 CONSTRAINT [PK_acervo_ldap] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

```

**Table SERVIDOR: (civil servant in portuguese)**

```
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Servidor](
	[COD_SERVIDOR] [varchar](4) NOT NULL,
	[MAT] [char](16) NULL,
	[SERVIDOR] [varchar](60) NOT NULL,
	[COD_UNIDADE] [varchar](8) NOT NULL,
	[E_MAIL] [varchar](50) NULL,
	[ATIVO] [bit] NOT NULL,
	[CHEFIA] [bit] NOT NULL,
	[DIST_TEMP] [bit] NOT NULL,
	[DATA_INC1] [smalldatetime] NOT NULL,
	[USUARIO1] [varchar](15) NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Servidor] ADD  CONSTRAINT [DF_Servidor_COD_UNIDADE]  DEFAULT (0) FOR [COD_UNIDADE]
GO
ALTER TABLE [dbo].[Servidor] ADD  CONSTRAINT [DF_Servidor_ATIVO]  DEFAULT (1) FOR [ATIVO]
GO
ALTER TABLE [dbo].[Servidor] ADD  CONSTRAINT [DF_Servidor_CHEFIA]  DEFAULT (0) FOR [CHEFIA]
GO
ALTER TABLE [dbo].[Servidor] ADD  CONSTRAINT [DF_Servidor_TEMP]  DEFAULT (0) FOR [DIST_TEMP]
GO
ALTER TABLE [dbo].[Servidor] ADD  CONSTRAINT [DF_Servidor_DATA_INC]  DEFAULT (getdate()) FOR [DATA_INC1]
GO
ALTER TABLE [dbo].[Servidor] ADD  CONSTRAINT [DF_Servidor_USUARIO]  DEFAULT (suser_sname()) FOR [USUARIO1]
GO
```

As @markstory said, I suppose the problem is something related with infamous sql server cursors
Very Soon I will be able to migrate this database to SQL SERVER 2014 and test if this problem will persist

**Comment by chinpei215** [comment] 2017-10-06 14:25
The following could be a small snippet to reproduce this issue without Cake.

```php
$pdo = new PDO('sqlsrv:Server=(localdb)\.\DeptSharedLocalDB;Database=cakephp;MultipleActiveResultSets=false', 'cakephp', 'cakephp', [
	PDO::ATTR_EMULATE_PREPARES => true,
	PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
]);

$select = $pdo->prepare('SELECT * FROM articles', [PDO::ATTR_CURSOR => PDO::CURSOR_SCROLL]);
$select->execute();

while ($row = $select->fetch(PDO::FETCH_OBJ)) {
	$pdo->beginTransaction();
	$update = $pdo->prepare('UPDATE articles SET title = :title WHERE id = :id', [PDO::ATTR_CURSOR => PDO::CURSOR_SCROLL]);
	$update->execute([
		'id' => $row->id,
		'title' => date('Y-m-d H:i:s'),
	]);
	$pdo->commit();
}

// Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY010]: [Microsoft][ODBC Driver 11 for SQL Server]Function sequence error'
```

What is incorrect with this?

**Comment by markstory** [comment] 2017-11-02 01:11
Closing as this seems to be an issue with SQLServer cursors and can be reproduced with basic PDO driver usage.

**Closed by markstory** 2017-11-02 01:11 UTC
Labels: Defect, sqlserver
