### ISSUE TITLE
Query caching not working as documented.

### ISSUE THREAD

**Issue by ndm2** [cakephp/cakephp#9768] opened 2016-11-17 17:29 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.8

---

### Model.beforeFind is being triggered after the cache check

I stumbled over **http://stackoverflow.com/q/40653462/1392379** and noticed that unlike [**documented**](http://book.cakephp.org/3.0/en/orm/query-builder.html#caching-loaded-results), `Model.beforeFind` is being triggered _after_ the cache is being checked, hence making query cache configuration changes via that event impossible, and of course also causing any query changes that might affect the caching key to be excluded when using the query clauses to build the key as show in the examples.

[**The original behavior**](https://github.com/cakephp/cakephp/issues/2562) seems to have been changed with **https://github.com/cakephp/cakephp/pull/5181**, not intentionally I'd think.

```php
public function testBeforeFindQueryCacheConfig()
{
	$table = TableRegistry::get('Articles');
	$query = new Query($this->connection, $table);

	$cacher = $this->getMockBuilder('Cake\Cache\CacheEngine')->getMock();
	$cacher
		->expects($this->once())
		->method('read')
		->with('my_key');

	$table->eventManager()->on('Model.beforeFind', function ($event, $query) use ($cacher) {
		$query->cache('my_key', $cacher);
	});

	$query
		->select(['id', 'title'])
		->where(['id' => 1])
		->all();
}

public function testBeforeFindChangesAffectingCachingKeyBuiltFromSelectClause()
{
	$table = TableRegistry::get('Articles');
	$query = new Query($this->connection, $table);

	$cacher = $this->getMockBuilder('Cake\Cache\CacheEngine')->getMock();
	$cacher
		->expects($this->once())
		->method('read')
		->with('51cfd5d91114aee17fcd65ffb9be4ced');
	$cacher
		->expects($this->once())
		->method('write')
		->with(
			'51cfd5d91114aee17fcd65ffb9be4ced',
			$this->isInstanceOf('Cake\Datasource\ResultSetInterface')
		);

	$table->eventManager()->on('Model.beforeFind', function ($event, $query) use ($cacher) {
		$query->select(['body']);
	});

	$query
		->select(['id', 'title'])
		->where(['id' => 1])
		->cache(
			function ($query) {
				return md5(serialize($query->clause('select')));
			},
			$cacher
		)
		->all();
}
```

### Using the `select` clause to build the key from may not work

Also when using the `select` clause as shown in the examples, the automatic aliasing will cause the caching key to change inbetween reading and writing to the cache:

```php
public function testFieldAliasingAffectingCachingKeyBuiltFromSelectClause()
{
	$table = TableRegistry::get('Articles');
	$query = new Query($this->connection, $table);

	$cacher = $this->getMockBuilder('Cake\Cache\CacheEngine')->getMock();
	$cacher
		->expects($this->once())
		->method('read')
		->with('b02de94289c454531e9dc73b78c52085');
	$cacher
		->expects($this->once())
		->method('write')
		->with(
			'b02de94289c454531e9dc73b78c52085',
			$this->isInstanceOf('Cake\Datasource\ResultSetInterface')
		);

	$query
		->select(['id', 'title'])
		->where(['id' => 1])
		->cache(
			function ($query) {
				return md5(serialize($query->clause('select')));
			},
			$cacher
		)
		->all();
}
```

For the `read` action the clause will contain

```
[
	(int) 0 => 'id',
	(int) 1 => 'title'
]
```

but after the query is being transformed this will change to

```
[
	'Articles__id' => 'Articles.id',
	'Articles__title' => 'Articles.title'
]
```

causing the key for writing to be different.

**Comment by markstory** [comment] 2016-11-17 21:12
Because of query transformations and expression objects, I'm not sure it is ever a good idea to simply hash the selected columns to generate a cache key.

**Comment by ayman-alkom** [comment] 2016-11-18 07:41
I am not expert in this enough, but just as an idea I wonder if adding a new event like `beforeFindExecute`  that triggers exactly before getting the result.

**Comment by lorenzo** [comment] 2016-11-18 09:07
Caching in a generic way is difficult. This is the primary reason why I only use query caching with a fixed human readable key that is not depending on the arguments. I would argue that calling beforeFind on a cached query makes little sense, so it should indeed be called before the cache check.

I'm saying this lightly right now though, since I have not thought of the consequences of making the change.

**Comment by markstory** [comment] 2018-01-09 04:01
Closing as it has been quite some time without any activity, or additional reports of this problem. I agree with @lorenzo that basing cache keys on selected columns is not a solution we should encourage by making it 'easy'.

**Closed by markstory** 2018-01-09 04:01 UTC
Labels: Defect, ORM, On hold

**Comment by Aerue** [comment] 2018-10-11 12:32
May we reopen this issue ?

Still present in cake 3.6.12

**Comment by markstory** [comment] 2018-10-12 00:55
Maybe. Do you have a potential solution? Bouncing this issue around for another 2 years isn't going to help anyone.

**Comment by inoas** [comment] 2018-10-12 08:28
What was bad about the `beforeExecute()` callback suggestion? That would also be BC?

**Comment by Aerue** [comment] 2018-10-12 11:30
beforeCache() / afterCache() sound better to me

**Comment by ravage84** [comment] 2018-10-18 11:40
We shouldn't re-onen this. @Aerue please open a new issue with a reference to this issue, a short summary what the problem is and how you would solve it. This will lead to a far better collaboration. Thanks.
