### ISSUE TITLE
__x() with context is not working / cakephp 3.6.1

### ISSUE THREAD

**Issue by xsyfrost** [cakephp/cakephp#12013] opened 2018-04-27 07:28 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.1
* Platform and Target: MAMP / chrome

### What you did
I used the __x() function. 
I used that fonction with context in order to make 2 different translation

In french "i am" and "i have" could be translated that way with "Je suis"
Hereunder the functions

```php
__x("Being - I'm from a special country",'{0,plural,=0{Je suis}=1{Je suis}=2{Nous sommes} other{Nous sommes}}', [1])
__x("Ethnicity - I've european oringins",'{0,plural,=0{Je suis}=1{Je suis}=2{Nous sommes} other{Nous sommes}}', [1])
```

### What happened
Unfortunatly it gaves me every time the same (first) transl
![context](https://user-images.githubusercontent.com/9862529/39350046-51f26304-49fd-11e8-8d1e-a7912bc9b99f.jpg)
ation despite of the context that have been set

### What you expected to happen
It should output "I'm" for the first occurence and "i've" for the second

Best regards

**Comment by markstory** [comment] 2018-04-27 14:37
What do your `po` files look like?

**Comment by xsyfrost** [comment] 2018-04-27 14:58
In fact they look pretty good. 
![capture d ecran 2018-04-27 a 16 57 06](https://user-images.githubusercontent.com/9862529/39369286-22c5070a-4a3c-11e8-8db3-02a38f89ebfd.png)

**Comment by xsyfrost** [comment] 2018-04-27 14:59
#: Template/......ctp:58
#, fuzzy
msgctxt "Je suis actuellement en ligne"
msgid "{0,plural,=0{Je suis}=1{Je suis}=2{Nous sommes} other{Nous sommes}}"
msgstr "{0,plural,=0{I'm}=1{I'm}=2{We are} other{We are}}"

#: View/Helper/......php:66
#, fuzzy
msgctxt "Ethnicity - I've european oringins"
msgid "{0,plural,=0{Je suis}=1{Je suis}=2{Nous sommes} other{Nous sommes}}"
msgstr "{0,plural,=0{I've}=1{I've}=2{We are} other{We are}}"

**Comment by markstory** [comment] 2018-04-27 17:52
Thanks! I'll see if I can reproduce the problem you're having.

**Comment by markstory** [comment] 2018-04-27 18:39
In my local environment I was not able to reproduce this issue. I've opened a pull request to see if this issue can be reproduced in our CI system.

**Comment by xsyfrost** [comment] 2018-04-28 07:40
In fact, it is not a trouble of creating the po file. This file is correct, but when I output the content i didn't get the right content.
I think the trouble came from the translate() function in I18n/Translator.php : 
if (isset($message['_context'])) { # should be: if (isset($tokensValues['_context'])) { 
But even so, it does not work

best regards

**Comment by markstory** [comment] 2018-04-28 13:01
Ok, I don't know how to reproduce the issue you are having based on the information here. In #12017 I added tests covering what I understand to be your situation, but the tests pass and return the values you described.

Is there something missing from my test case?

**Comment by markstory** [comment] 2018-05-07 20:11
Closing as I've not been able to reproduce this issue and there hasn't been any follow up.

**Closed by markstory** 2018-05-07 20:11 UTC
Labels: Defect, Need more information, i18n
