### ISSUE TITLE
matching with belongsToMany conditions

### ISSUE THREAD

**Issue by aiphee** [cakephp/cakephp#7813] opened 2015-12-08 13:57 UTC
I'm assigning `belongsToMany` in my behavior `initalize`:
```PHP
$this->_table->belongsToMany('Tags', [
				'through'    => 'TagsContents',
				'foreignKey' => 'foreign_table_id',
				'conditions' => ['foreign_table_name' => $this->_table->table()],
			]);
```
but when i try to
```PHP
$query = $this->ContentPages->find()->contain('Tags')->matching('Tags', function ($q) {
				return $q->where(['Tags.name' => 'test']);
			})->toArray();
```
it reports: `Unknown column 'foreign_table_name' in 'on clause'`.
It works without conditions.

CakePHP 3.1

**Comment by lorenzo** [comment] 2015-12-08 20:27
Duplicate of https://github.com/cakephp/cakephp/issues/7707

**Comment by lorenzo** [comment] 2015-12-08 20:28
Please use latest commits in master or wait for `3.1.6` :)

**Closed by lorenzo** 2015-12-08 20:27 UTC

**Comment by aiphee** [comment] 2016-01-07 08:16
Ok, i have updated to `3.1.6` and it is still not working. And now, it won`t even save data from _joinData
`Field 'foreign_table_name' doesn't have a default value`

SQL from error on find:
```SQL
SELECT
  ContentPages.id                 AS `ContentPages__id`,
  ContentPages.layout_id          AS `ContentPages__layout_id`,
  ContentPages.name               AS `ContentPages__name`,
  ContentPages.title              AS `ContentPages__title`,
  ContentPages.perex              AS `ContentPages__perex`,
  ContentPages.text               AS `ContentPages__text`,
  ContentPages.custom_class       AS `ContentPages__custom_class`,
  ContentPages.active             AS `ContentPages__active`,
  ContentPages.protected          AS `ContentPages__protected`,
  ContentPages.show_social_plugin AS `ContentPages__show_social_plugin`,
  ContentPages.show_page_title    AS `ContentPages__show_page_title`,
  ContentPages.show_page_perex    AS `ContentPages__show_page_perex`,
  ContentPages.latitude           AS `ContentPages__latitude`,
  ContentPages.longitude          AS `ContentPages__longitude`,
  ContentPages.created            AS `ContentPages__created`,
  ContentPages.modified           AS `ContentPages__modified`,
  Tags.id                         AS `Tags__id`,
  Tags.name                       AS `Tags__name`,
  Tags.title                      AS `Tags__title`,
  Tags.description                AS `Tags__description`,
  Tags.active                     AS `Tags__active`,
  Tags.protected                  AS `Tags__protected`,
  Tags.special_tag                AS `Tags__special_tag`,
  Tags.created                    AS `Tags__created`,
  Tags.modified                   AS `Tags__modified`,
  TagsContents.id                 AS `TagsContents__id`,
  TagsContents.foreign_table_name AS `TagsContents__foreign_table_name`,
  TagsContents.foreign_table_id   AS `TagsContents__foreign_table_id`,
  TagsContents.tag_id             AS `TagsContents__tag_id`,
  TagsContents.created            AS `TagsContents__created`,
  TagsContents.modified           AS `TagsContents__modified`
FROM content_pages ContentPages INNER JOIN tags Tags ON (TagsContents.foreign_table_name = :c0 AND Tags.name = :c1)
  INNER JOIN tags_contents TagsContents
    ON (ContentPages.id = (TagsContents.foreign_table_id) AND Tags.id = (TagsContents.tag_id))
```

No matter if conditions are `['TagsContents.foreign_table_name' => $this->_table->table()]` or `['foreign_table_name' => $this->_table->table()]`

Tags table:
```
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| id          | int(11)      | NO   | PRI | NULL    | auto_increment |
| name        | varchar(255) | NO   |     | NULL    |                |
| title       | varchar(255) | YES  |     | NULL    |                |
| description | text         | YES  |     | NULL    |                |
| active      | tinyint(1)   | NO   |     | 1       |                |
| protected   | tinyint(1)   | NO   |     | 0       |                |
| special_tag | tinyint(1)   | NO   |     | 0       |                |
| created     | datetime     | NO   |     | NULL    |                |
| modified    | datetime     | NO   |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+
```
TagsContents table:
```
+--------------------+--------------+------+-----+---------+----------------+
| Field              | Type         | Null | Key | Default | Extra          |
+--------------------+--------------+------+-----+---------+----------------+
| id                 | int(11)      | NO   | PRI | NULL    | auto_increment |
| foreign_table_name | varchar(255) | NO   |     | NULL    |                |
| foreign_table_id   | int(11)      | NO   |     | NULL    |                |
| tag_id             | int(11)      | NO   | MUL | NULL    |                |
| created            | datetime     | NO   |     | NULL    |                |
| modified           | datetime     | NO   |     | NULL    |                |
+--------------------+--------------+------+-----+---------+----------------+
```

Any ideas? Thank you.

**Comment by lorenzo** [comment] 2016-01-07 13:35
Are you certain that you upgraded to 3.1.6?

**Comment by aiphee** [comment] 2016-01-07 13:57
I am, i used composer and debugbar shows so.

**Comment by lorenzo** [comment] 2016-01-07 22:06
Save what?

**Comment by aiphee** [comment] 2016-01-08 08:04
As written before, when im saving ContentPage with tags it reports
`Field 'foreign_table_name' doesn't have a default value`
It worked in 3.1.5

Field `foreign_table_name` is in _joinData.

Conent of `$data['tags']` after i fill it in `beforeMarshal`
```PHP
0 => [
					'id'        => 1000,
					'_joinData' => ['foreign_table_name' => 'content_pages']
				],
				1 => [
					'id' => 1002,
					'_joinData' => ['foreign_table_name' => 'content_pages']
				]
```

**Comment by lorenzo** [comment] 2016-01-08 09:21
Please open a new ticket for that problem, make sure you add the code you are using, the queries that are generated and the end result. Thanks

**Comment by aiphee** [comment] 2016-01-08 13:33
Ok, i have created a new issue. Please let me know if it need some more info.
#7994
