### ISSUE TITLE
DateTimeType should convert toPHP based on timezone

### ISSUE THREAD

**Issue by doshu** [cakephp/cakephp#13846] opened 2019-11-06 08:16 UTC
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.*
the setTimezone method of the DateTimeType add the possibility to convert datetime field to a specific timezone before saving on db.
if for example i have the main app timezone to Europe/Rome and i would like to save on db in UTC, this method is very helpful.
Unfortunately when data i retrived from db, the datetime field are converted from an UTC string date to a datetime object using a pre-constructed datetime object using the modify method.

the pre-constructed datetime object, because of the main timezone, has the timezone setted to Europe/Rome, but it will be modified with an UTC string.
The result is that i have a wrong localized datetime.

In my opinion the toPHP method shoud be aware of the different timezone and convert the value based on the two different timezones.

**Comment by markstory** [comment] 2019-11-06 11:23
I think the behavior you're describing was implemented as part of 4.0.

**Comment by ADmad** [comment] 2019-11-06 12:06
Yes it's done in 4.0.

**Comment by dereuromark** [comment] 2019-11-06 12:10
Are we able to backport this in a way? E.g. in shim context?

**Comment by othercorey** [comment] 2019-11-06 13:23
The partial implementation in 3.x was probably a mistake in hindsight.  It leaves the user with partial conversion support.

The alternative is to set php's default timezone to the same timezone you'd use for `toTimezone()`.

**Comment by dereuromark** [comment] 2019-11-06 13:24
There are quite a few 3.x topics/bugs around timezone open: https://github.com/cakephp/cakephp/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+timezone

**Comment by othercorey** [comment] 2019-11-06 13:26
I put together a detailed issue on this when I was trying to back-port something to 3.x.

https://github.com/cakephp/cakephp/issues/13729

**Comment by dereuromark** [comment] 2019-11-06 13:29
Then we can probably close this as dup and continue discussing in the linked one.

I personally dropped timezone in my apps long time ago because of that and use local time, but of course that only works for me as I dont have timezone handling needs, no different users across countries, all german only.
I really  hope we can find a working solution here also for 3.x apps.

**Comment by othercorey** [comment] 2019-11-06 13:34
For postgres users, I am adding `timestamp with timezone` support to 4.x that could theoretically back-port to 3.x.  However, that's a pretty limited solution for users.

We could add a duplicate API just for 3.x that does the exact same thing as `toTimezone()` but is ONLY for `toPHP()`.

**Comment by dereuromark** [comment] 2019-11-06 13:35
Sure, you can also investigate if those go into 3.9 or in https://github.com/dereuromark/cakephp-shim as opt-in replacement.

**Comment by ADmad** [comment] 2019-11-06 13:44
Duplicate of #13729

**Closed by ADmad** 2019-11-06 13:44 UTC
Labels: enhancement
