### ISSUE TITLE
Error/Debugger.php Gets stuck in endless loop

### ISSUE THREAD

**Issue by half2me** [cakephp/cakephp#7933] opened 2015-12-31 13:00 UTC
I've run into a problem, when using debug($query) Cake will go into and endless loop, and processor utilization will go up to 100% Until it times out.

Here is the bit of code that causes this error:
``` php
$products = $this->Websites->Products->find()
                    ->select(['Products.id'])
                    ->where(['Products.id IN' => $allowedIds])
                    ->contain(['Websites', 'ProductInfo']);
                debug($products); // <-- Calling debug() here gets Deugger.php into an endless loop
```

Now this code is inside a transaction, but calling debug in or outside the anonymous function gives the same result. When using var_dump() instead, everything works fine.
Transaction:
``` php
$this->Websites->Products->connection()->transactional(function () {
  // Code is here...
}
```

I've made a gist of the entire code incase these snippets are not enough. Its inside a controller action:
https://gist.github.com/half2me/31b3f5f1767c6808d060

Here is the error I get (timeout):
![60sec](https://cloud.githubusercontent.com/assets/6759894/12064573/88f01712-afc6-11e5-9587-8a3b8e7cd88c.png)

**Comment by lorenzo** [comment] 2015-12-31 14:20
I think the problem is that you have an association called Websites inside the Websites table

**Comment by half2me** [comment] 2015-12-31 14:24
@lorenzo Ohshhh... :) In this case, could I get an error message instead of an endless loop?

**Comment by markstory** [comment] 2015-12-31 17:31
Do your tables have any beforeFind, or resultFormatters that execute additional queries?

**Comment by half2me** [comment] 2015-12-31 18:06
@markstory none

**Comment by markstory** [comment] 2015-12-31 18:39
Is `$allowedIds` a subquery?

**Comment by half2me** [comment] 2015-12-31 18:50
@markstory yes, (see the gist)

**Comment by markstory** [comment] 2015-12-31 19:16
Ok, I'll see if I can come up with a more compact way to reproduce the issue.

**Comment by markstory** [comment] 2016-01-04 03:22
I wasn't able to reproduce this. I tried the following code:

```php
        $users = \Cake\ORM\TableRegistry::get('Users');
        $e = function () use ($users) {
            $query = $users->Bookmarks->find()
                ->select(['Bookmarks.id'])
                ->where(['Bookmarks.id IN' => [1, 2, 3]])
                ->contain(['Users', 'Tags']);
            debug($query);
        };
        $e();
```
The associations here are:

* Users HasMany Bookmarks
* Bookmarks BelongsToMany Tags
* Bookmarks BelongsTo Users

I ran that in both a controller action and a shell task, and no infinite loop was hit. I also tried putting the anonymous function inside a call to `connection()->transactional()` as well.

Are you able to enable xdebug? Often that gives useful stacktraces when there are fatal errors.

**Comment by dereuromark** [comment] 2016-01-04 10:09
@half2me Whats your PHP version? PHP5.6 is recommended to leverage the __debugInfo feature etc. This often prevents those things from my experience.

**Comment by half2me** [comment] 2016-01-04 15:35
@dereuromark PHP 5.6.11-1ubuntu3.1

**Comment by half2me** [comment] 2016-01-04 15:35
@markstory I will try to reproduce this problem with less code

**Comment by dereuromark** [comment] 2016-01-04 15:38
@half2me What is the value of $allowedIds? Is it empty array in your case maybe?

**Comment by half2me** [comment] 2016-01-04 15:39
@half2me there were cases when it was an empty array. I only added code to check if it is empty or not later on.

**Comment by dereuromark** [comment] 2016-01-04 15:44
Is there a reason you are using &$website and &$request?
Should be without & afaik. But that is most likely not related to your issue.

**Comment by half2me** [comment] 2016-01-04 15:45
@dereuromark I was modifying some of those values from within the anonymous function.

**Comment by markstory** [comment] 2016-01-04 17:47
I'll try using innerJoinWith() and see if I can reproduce the issue.

**Comment by markstory** [comment] 2016-02-06 20:01
I've still not had any luck in reproducing this. I tried an innerJoinWith() last night.

**Comment by markstory** [comment] 2016-02-15 22:08
Closing as without a way to reproduce this I don't think we can fix it.

**Closed by markstory** 2016-02-15 22:08 UTC
Labels: Defect, On hold, ORM
