### ISSUE TITLE
SQL cast using query builder

### ISSUE THREAD

**Issue by gustavokataoka** [cakephp/cakephp#12018] opened 2018-04-27 18:47 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x.
* Platform and Target: Apache Postgres.

Using Cake3 and trying to do a cast using the query builder.
SQL that i need:

`CAST ( EXTRACT (MONTH FROM FIELD_DATE) AS NUMERIC)`

I figured out that the following code does the job:

```
$exp = $this->query()
  ->newExpr()->setConjunction('AS')
  ->add([
    $query->func()->extract('MONTH','FIELD_DATE'), 'NUMERIC',
  ]);
$cast = $query->func()->CAST([$exp]);
```

But the generated looks like this:

`CAST((EXTRACT(YEAR FROM FIELD_DATA) AS NUMERIC))`

As you can see, there's a additional parentheses that makes DB error.
How can i remove the parentheses.
Looked up in documentation but found anything.

**Comment by raul338** [comment] 2018-04-27 19:36
This looks similar to #11410 
What cakephp version are you using?

**Comment by gustavokataoka** [comment] 2018-04-27 19:41
3.5.14

**Comment by raul338** [comment] 2018-04-27 19:52
Does it work if you change the last line to
```php
$cast = $query->func()->CAST($exp);
```

**Comment by gustavokataoka** [comment] 2018-04-27 20:04
It seems not. It masses the param construction and this happens:

`CAST(:param1, :param2, :param3)`

And i did not inform only one of this.

**Comment by lorenzo** [comment] 2018-04-28 10:36
Anything that needs to be a sting literal needs to be explicitly marked as a string literal

```php
$exp = $this->query()
  ->newExpr()->setConjunction('AS')
  ->add([
    $query->func()->extract('MONTH','FIELD_DATE'),
   'NUMERIC' => 'literal',
  ]);
$cast = $query->func()->CAST([$exp]);
```

**Closed by lorenzo** 2018-04-28 10:36 UTC
Labels: Defect, ORM, database

**Comment by ndm2** [comment] 2018-04-28 11:45
@lorenzo I think you've mixed up adding parts/conditions with adding arguments ;)

The root of the problem is that expressions always nest themselves in parentheses when they contain more than one part, which probably is required in some cases to avoid creating invalid SQL in the first place, but has the unfortunate side effect that it will create invalid SQL in cases like this.

https://github.com/cakephp/cakephp/blob/9739f275edd4f97c2a50dc028d870ce51e7aa058/src/Database/Expression/QueryExpression.php#L542-L553

Not sure if this can be "fixed" properly so that it works in all situations... maybe the outer compiler could decide whether the inner expression needs to be nested in parentheses, similar to how it's done with the query in the above method? Surely there would be potential that it would just cause another can of worms to be opened.

I'm usually resorting to custom expression classes where I can dictate the compiling process, sometimes this also requires implementing additional transpilers in case one needs to provide cross dialect support...

**Comment by markstory** [comment] 2018-04-28 12:56
Given that your cast expression doesn't need any placeholders have you considered using a single string for the entire expression.

```php
$exp = $query->newExpr()->add('...');
```

**Comment by lorenzo** [comment] 2018-04-28 13:30
@ndm2 I usually resort to custom expression objects when thugs get difficult with the builders alone.

I couldn’t find a reliable way of determining when something may need parentheses as I was building the ORM. There seemed to be way too many special cases and exceptions, so the code ended up reflecting that reality.

If you have any smart ideas in mind I’d love to hear them!

**Comment by ndm2** [comment] 2018-04-30 12:27
@lorenzo I guess things could always be made configurable (like `$expression->setWrappingMode(...)`) to make it a little more straightforward for people that like to build expressions via the builder rather than implementing custom compilation logic, but other than that... no, I don't really have any ideas how to handle this in an automated manner, let alone any smart ones. I can see how this can easily go very wrong, and I really don't want to be the one responsible for breaking all the apps ;)

**Comment by lorenzo** [comment] 2018-04-30 14:47
Yeah, having a flag may actually work. @ndm2 Would you like to help collecting examples where the sql compiler is adding parentheses which cause errors? That could come handy when figuring out a solution for it
