### ISSUE TITLE
pagination in cells

### ISSUE THREAD

**Issue by arilia** [cakephp/cakephp#7276] opened 2015-08-21 09:27 UTC
being "small mini-controllers" I expected I could use components in Cells. 

I understand that components are attached to actual controllers and cells are not controllers. But It would be very useful to have at least pagination. Is it possible? Are there technical problems to solve or it is a deliberate choice?

**Comment by dereuromark** [comment] 2015-08-21 09:38
Refs https://github.com/cakephp/cakephp/issues/3660
If the PaginatorComponent logic was extracted into a more common lib class it might very well possible to also make it available for cells and other use cases.

**Comment by lorenzo** [comment] 2015-08-21 09:41
@arilia How would pagination work in a cell? It requires reading variables from the query string, wouldn't it clash with the same variables used in the pagination for the main view?

**Comment by ionas** [comment] 2015-08-21 10:00
Paginator should take some (optional) parameters to encapsulate one pagination from another (arrayish params). I have done that for 2.x and imho it should come out of the box for bake already.

**Comment by arilia** [comment] 2015-08-21 10:48
@lorenzo the optimal would be being able to paginate more than one controller at a time as described by ionas. But I think it's up to me avoid conflicts.

Even now it's possible to call paginate() many time in the same action

**Comment by lorenzo** [comment] 2015-12-06 11:17
Closing as duplicate of https://github.com/cakephp/cakephp/issues/1731

**Closed by lorenzo** 2015-12-06 11:17 UTC
Labels: RFC
