### ISSUE TITLE
Cell $this->template not working any more

### ISSUE THREAD

**Issue by Kepro** [cakephp/cakephp#8202] opened 2016-02-08 08:20 UTC
Hi cakephp team, 
in older version like 3.0.x i have class

````php
<?php
namespace App\View\Cell;

use Cake\View\Cell;

/**
 * Static cell
 */
class StaticCell extends Cell
{

    protected $_validCellOptions = [];

    public function load($params)
    {
        $this->template = 'custom_template';
    }
}
````

but in 3.2.x is not working any more they still want to load Load.ctp

**Comment by ADmad** [comment] 2016-02-08 08:29
Duplicate of #8163 fixed in #8182. Wait for next 3.2 release.

**Comment by ADmad** [comment] 2016-02-08 08:30
Also use `$this->viewBuilder()->template()` instead of `$this->template`.

**Closed by ADmad** 2016-02-08 08:29 UTC

**Comment by Kepro** [comment] 2016-02-08 08:32
@ADmad thanks!
