### ISSUE TITLE
patchEntity() causes errors where newEntity() doesn't

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#11187] opened 2017-09-14 10:15 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.13
* Platform and Target: Windows 10, Nginx

### What you did
```php
   $entity = $this->Votes->newEntity((array)$this->request->getData());
debug($entity->getErrors());
   $this->Votes->patchEntity($entity, [
    'voting_year' => BuildingOfTheYear::getVotingYear(),
    'domain_id' => $this->domainData('id')
   ], [
    'guard' => false
   ]);
debug($entity->getErrors());
```

Entity class:

```php
<?php
declare(strict_types = 1);

namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * BuildingOfTheYearVote Entity
 */
class BuildingOfTheYearVote extends Entity {

	/**
	 * Fields that can be mass assigned using newEntity() or patchEntity().
	 * Note that when '*' is set to true, this allows all unspecified fields to
	 * be mass assigned. For security purposes, it is advised to set '*' to false
	 * (or remove it), and explicitly make individual fields accessible as needed.
	 *
	 * @var array
	 */
	protected $_accessible = [
		'*' => true,
		'id' => false,
		'domain_id' => false
	];

}
```

Validation rules:

```php
	public function validationDefault(Validator $validator) {
		$validator
			->add('id', 'valid', ['rule' => 'numeric'])
			->allowEmpty('id', 'create');

		$validator
			->add('voting_year', 'valid', ['rule' => 'numeric'])
			->numeric('voting_year')
			->requirePresence('voting_year')
			->notEmpty('voting_year');

		$validator
			->requirePresence('first_name', 'create')
			->notEmpty('first_name');

		$validator
			->requirePresence('last_name', 'create')
			->notEmpty('last_name');

		$validator
			->requirePresence('email', 'create')
			->notEmpty('email')
			->email('email');

		return $validator;
	}
```

### What happened
```sh
\src\Controller\BuildingOfTheYearController.php (line 60)
[
 'voting_year' => [
  '_required' => 'This field is required'
 ]
]
\src\Controller\BuildingOfTheYearController.php (line 75)
[
 'first_name' => [
  '_required' => 'This field is required'
 ],
 'last_name' => [
  '_required' => 'This field is required'
 ],
 'email' => [
  '_required' => 'This field is required'
 ]
]
```

### What you expected to happen

I didn't expect to end up with _required errors for fields that we're already present when newEntity() was called. Interestingly the `voting_year` is not there which failed before in newEntity(). 

I think the cause is that the errors get overwritten instead of properly merged or something like that.

**Comment by dereuromark** [comment] 2017-09-14 10:23
I think this is somewhat expected behavior.
The required part here is for the validation, not the entity.
So all fields must be required for "all" patching processes, either on newEntity() or patchEntity()

They do not check the entity so far for the existence of those fields.
From from I understand the require definition is necessary to make sure the validation process can rely on the data being present it needs.
Maybe we are missing a dynamic required concept here that takes the entity data into account, as well.

**Comment by burzum** [comment] 2017-09-14 10:24
> Maybe we are missing a dynamic required concept here that takes the entity data into account, as well.

I think we do so, because at least for me the current way it works feels counter-intuitive and wrong.

**Comment by markstory** [comment] 2017-09-14 15:34
Validation is applied to *request data*. You are marking fields as *required* and they are not in your 'request data', therefore validation fails.

**Comment by robertpustulka** [comment] 2017-09-15 06:53
Does error still occur if you save the entity in between?

```php
$entity = $this->Votes->newEntity((array)$this->request->getData());
debug($entity->getErrors());
$this->Votes->save($entity); // save with no errors
   $this->Votes->patchEntity($entity, [
    'voting_year' => BuildingOfTheYear::getVotingYear(),
    'domain_id' => $this->domainData('id')
   ], [
    'guard' => false
   ]);
debug($entity->getErrors());
```

**Comment by ADmad** [comment] 2017-09-15 07:10
@robertpustulka It will still occur. As @markstory pointed out validation is done on request data so if any field marked as "required present" is not set in the 2nd argument there will always be an error regardless of entity state.

**Comment by ADmad** [comment] 2017-09-15 07:13
My apologies, I see now that presence check is enabled only for "create", so yes error won't occur after the entity is persisted to db.

**Comment by robertpustulka** [comment] 2017-09-15 07:14
OK so this works as intended IMO.

**Comment by ADmad** [comment] 2017-09-15 07:14
Yes it does. I don't think there's nothing to do here and the issue can be closed.

**Comment by robertpustulka** [comment] 2017-09-15 07:15
A workaround:

```php
$data = [
    'voting_year' => BuildingOfTheYear::getVotingYear(),
    'domain_id' => $this->domainData('id')
] + (array)$this->request->getData();

$entity = $this->Votes->newEntity($data);
$this->Votes->save($entity);
```

**Closed** 2017-09-15 08:55 UTC
Labels: ORM, RFC

**Comment by burzum** [comment] 2017-09-15 08:57
> Validation is applied to request data. You are marking fields as required and they are not in your 'request data', therefore validation fails.

While this might work as intended, I haven't been aware of this until now and surprisingly this was never a problem before for some reason and I'm using Cake3 since it's alpha. There is no clear indicator that this should (it should be, right?) used with request data. If that is the intention then `patchEntityWithRequest()` would make a lot more sense to me.

**Comment by robertpustulka** [comment] 2017-09-15 08:58
`patchEntity()` works with any kind of data. What's specific about request data?

**Comment by burzum** [comment] 2017-09-15 08:59
@robertpustulka well, @markstory made it sound like it is.

**Comment by dereuromark** [comment] 2017-09-15 09:00
He just meant the data passed it, doesnt matter where they come from :)
Bottom line: It is about data going into validation, not about whats already in the target entity.

**Comment by robertpustulka** [comment] 2017-09-15 09:00
Because it is used to create entities out of user provided data, hence *request* data I suppose.

If you are sure you are providing a correct data in your code, you ca set the properties directly.

**Comment by markstory** [comment] 2017-09-15 14:00
The data passed into `patchEntity()` **is** 'request' data as far as the ORM is concerned.
