### ISSUE TITLE
Plugin shell should use bootstrap_cli.php

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#11775] opened 2018-03-01 22:17 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.11
* Platform and Target: WAMP

### What you did
I build plugin (inside `/plugins`) included shell script. I also prepare `bootstrap_cli.php` file for configuration for command line.

### What happened
Shell script cannot run `bootstrap_cli.php` file from plugin `/config`.

### What you expected to happen
Shell script should run main `bootstrap_cli.php` and secondly `bootstrap_cli.php` from plugin.

**Comment by dereuromark** [comment] 2018-03-01 22:19
Why do you think that?
The only bootstrap_cli is run for config, because there the bootstrap has such an include command.
If you want that for your plugin you need to do the same in the plugin bootstrap there.
This is not a bug, but optional plugin addition.

**Comment by dereuromark** [comment] 2018-03-01 22:20
Refs https://github.com/cakephp/cakephp/issues/11687

**Comment by kicaj** [comment] 2018-03-01 22:28
@dereuromark Did You mean I should copy this code (https://github.com/cakephp/app/blob/master/config/bootstrap.php#L111-L123) to my plugin `bootstrap.php` file?

**Comment by dereuromark** [comment] 2018-03-01 22:31
That would be one way, another would be to look at the open issue linked at its PR(s) and see if this would be valuable to include in a more generic way.
But for now, this is a pure user based addon as copy-and-paste, exactly.

**Comment by markstory** [comment] 2018-03-02 01:25
Going to close this as the new plugin classes will let individual plugin authors include cli specific logic as needed.

**Closed by markstory** 2018-03-02 01:25 UTC
Labels: Enhancement
