### ISSUE TITLE
index.php incorrectly included in path

### ISSUE THREAD

**Issue by stujn** [cakephp/cakephp#11154] opened 2017-09-05 13:24 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: cakephp 3.4.11, Linux, Apache

### What you did

When viewing in a web browser, added "/index.php/test" to the end of the request, e.g.: https://www.example.com/index.php/test

### What happened

"index.php" is incorrectly treated as a subdirectory, which means paths to static files are broken, e.g.:

/index.php/favicon.ico

instead of:

/favicon.ico

Note - this does not happen if the site is actually running in a subdirectory, e.g. this doesn't cause a problem:

https://www.example.com/somerealdir/index.php/test

### What you expected to happen

It's not a huge problem, but it would be nice if this situation was handled without paths to files breaking.

**Comment by stujn** [comment] 2017-09-05 13:26
currently cakephp 3.4.11 (haven't upgraded to latest 3.4.x yet)

**Comment by markstory** [comment] 2017-09-05 15:19
Are you using rewrite rules?

**Comment by stujn** [comment] 2017-09-05 16:10
Yes, I am using the standard cakephp rewrite rules as in point 3 here:

https://book.cakephp.org/3.0/en/installation.html#apache

**Comment by saeideng** [comment] 2017-09-05 17:40
@markstory
`/index.php/controllers/action` works

**Comment by markstory** [comment] 2017-09-06 01:06
@saeideng That's on purpose, as it populates `$_SERVER['PATH_INFO']` which we then use to access the 'application' URL.

**Comment by markstory** [comment] 2017-09-06 01:07
If you are using the rewrite rules @stujn, how/why are you using the `index.php` paths?

**Comment by markstory** [comment] 2017-09-07 04:17
@stujn If you want to put together a pull request to fix this that doesn't add significant complexity, I'd be happy to merge it.

**Comment by stujn** [comment] 2017-09-13 09:05
@markstory - Sounds good. I will put it on the TO DO list and put in a pull request when I get a chance. I'm thinking maybe if we had an option to turn off the index.php paths, then that will help people who definitely don't want them without meaning too many changes to the existing code.

**Comment by Benfarhat** [comment] 2017-09-15 21:57
@stujn, @markstory if you change [.htaccess](https://github.com/cakephp/app/blob/master/.htaccess) file by adding another rule (the second line in the following code) will it resolves this issue?

```
    RewriteRule    ^$    webroot/    [L] 
    RewriteRule ^index.php/(.*) webroot/$1 [L]
    RewriteRule    (.*) webroot/$1    [L]
```
with these rules
https://www.example.com/favicon.ico and https://www.example.com/index.php/favicon.ico show my favicon (no more 400 error), but I'm not sure that using index.php in your path is a good idea, the magic with rewrite mod/rule is to hide this ugly index.php

**Comment by JustAMurph** [comment] 2017-09-17 11:29
I think the problem is less about, "should" somebody use "index.php" in the path, and more about, you CAN access CakePHP by using "index.php/abc/def" and in this case, it should render properly. 

This issue does not appear if a user has a "baseURL" defined in their config.

I found some inconsistency in how PHP has handled $_SERVER['PHP_SELF']. 

If you access a URL like: "/index.php/pages/abc/def"

```
$_SERVER['PHP_SELF'] = '/index.php/pages/abc/def'
```

If you access any URL without "index.php". Like: "/rewrite.php/pages/abc/def" The following happens:

```
$_SERVER['PHP_SELF'] = '/index.php'
```

I think this could be resolved in ServerRequestFactory::getBase(). Would that be the correct place to work on a fix for this? 

@Benfarhat The problem lies at generating the asset URLs themselves. While your fix does help a person accessing an asset through "index.php". The URLs would still be generated incorrectly if you were to visit "index.php/page/about/non-existent" while not having a "baseUrl" defined.

**Comment by dereuromark** [comment] 2018-02-22 23:38
@stujn ping

**Comment by ADmad** [comment] 2018-04-20 19:09
Closing as the issue has gone stale.

**Closed by ADmad** 2018-04-20 19:09 UTC
Labels: Enhancement, optimization, routing
