### ISSUE TITLE
Malformed SQL still Generated in Pagination with complex Matching() added

### ISSUE THREAD

**Issue by eaxexe** [cakephp/cakephp#10697] opened 2017-05-26 13:23 UTC
This is a:

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.7
* Platform and Target: Apache2, PHP v. 5.6.2, MySQL v. 5.5.38 

This issue was reported before #10633, but still exists after #10657 was merged.

I have set up a repository that reproduces this error: [https://github.com/eaxexe/matching_test](https://github.com/eaxexe/matching_test)

It contains both a test `tests/TestCase/Model/Table/ArticlesTableTest.php` and the error can be seen by visiting matching_test/articles in the browser.

### What I did

I set up a beforeFind on my ArticlesTable that adds a few matching() queries to the find Query, with one having a matching() as a sub-query.

**Relevant code from ArticlesController.php:**
```
public function index()
    {
        $articles = $this->paginate($this->Articles);

        $this->set(compact('articles'));
        $this->set('_serialize', ['articles']);
    }
```

**ArticlesTable.php**
```
...
class ArticlesTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('articles');
        $this->setDisplayField('title');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsToMany('Icons', [
            'foreignKey' => 'article_id',
            'targetForeignKey' => 'icon_id',
            'joinTable' => 'articles_icons'
        ]);
        $this->belongsToMany('Tags', [
            'foreignKey' => 'article_id',
            'targetForeignKey' => 'tag_id',
            'joinTable' => 'articles_tags'
        ]);
    }

    public function validationDefault(Validator $validator)
    {
        $validator
            ->uuid('id')
            ->allowEmpty('id', 'create');

        $validator
            ->requirePresence('title', 'create')
            ->notEmpty('title');

        $validator
            ->requirePresence('content', 'create')
            ->notEmpty('content');

        return $validator;
    }

    public function beforeFind(Event $event, Query $query) {
		$query->matching(
			'Tags', function(Query $q) {
				return $q
					->where(['Tags.name' => 'Good'])
					->matching('TagOptions', function(Query $i) {
						return $i->where(['TagOptions.name' => 'display_tag']);
					});
				})
				->matching('Icons', function(Query $q) {
					return $q->where(['Icons.icon' => 'sad']);
				});

		return $event;
	}
}
```

**TagsTable.php**
```
...
class TagsTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('tags');
        $this->setDisplayField('name');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsToMany('Articles', [
            'foreignKey' => 'tag_id',
            'targetForeignKey' => 'article_id',
            'joinTable' => 'articles_tags'
        ]);
        $this->belongsToMany('TagOptions', [
            'foreignKey' => 'tag_id',
            'targetForeignKey' => 'tag_option_id',
            'joinTable' => 'tags_tag_options'
        ]);
    }

    public function validationDefault(Validator $validator)
    {
        $validator
            ->uuid('id')
            ->allowEmpty('id', 'create');

        $validator
            ->requirePresence('name', 'create')
            ->notEmpty('name');

        return $validator;
    }
}
```

**TagOptionsTable.php**
```
...
class TagOptionsTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('tag_options');
        $this->setDisplayField('name');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsToMany('Tags', [
            'foreignKey' => 'tag_option_id',
            'targetForeignKey' => 'tag_id',
            'joinTable' => 'tags_tag_options'
        ]);
    }

    public function validationDefault(Validator $validator)
    {
        $validator
            ->uuid('id')
            ->allowEmpty('id', 'create');

        $validator
            ->requirePresence('name', 'create')
            ->notEmpty('name');

        return $validator;
    }
}
```

### What happened
I get the following SQL error:
`Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'TagOptions.name' in 'on clause'`

And the following SQL is generated, pay special attention to the COUNT(*) call(s):
```
SELECT 
  Articles.id AS `Articles__id`, 
  Articles.title AS `Articles__title`, 
  Articles.content AS `Articles__content`, 
  Articles.created AS `Articles__created`, 
  Articles.modified AS `Articles__modified`, 
  ArticlesTags.id AS `ArticlesTags__id`, 
  ArticlesTags.article_id AS `ArticlesTags__article_id`, 
  ArticlesTags.tag_id AS `ArticlesTags__tag_id`, 
  ArticlesTags.created AS `ArticlesTags__created`, 
  ArticlesTags.modified AS `ArticlesTags__modified`, 
  Tags.id AS `Tags__id`, 
  Tags.name AS `Tags__name`, 
  Tags.created AS `Tags__created`, 
  Tags.modified AS `Tags__modified`, 
  ArticlesIcons.id AS `ArticlesIcons__id`, 
  ArticlesIcons.article_id AS `ArticlesIcons__article_id`, 
  ArticlesIcons.icon_id AS `ArticlesIcons__icon_id`, 
  ArticlesIcons.created AS `ArticlesIcons__created`, 
  ArticlesIcons.modified AS `ArticlesIcons__modified`, 
  Icons.id AS `Icons__id`, 
  Icons.name AS `Icons__name`, 
  Icons.icon AS `Icons__icon`, 
  Icons.created AS `Icons__created`, 
  Icons.modified AS `Icons__modified`, 
  TagsTagOptions.id AS `TagsTagOptions__id`, 
  TagsTagOptions.tag_id AS `TagsTagOptions__tag_id`, 
  TagsTagOptions.tag_option_id AS `TagsTagOptions__tag_option_id`, 
  TagsTagOptions.created AS `TagsTagOptions__created`, 
  TagsTagOptions.modified AS `TagsTagOptions__modified`, 
  TagOptions.id AS `TagOptions__id`, 
  TagOptions.name AS `TagOptions__name`, 
  TagOptions.created AS `TagOptions__created`, 
  TagOptions.modified AS `TagOptions__modified` 
FROM 
  articles Articles 
  INNER JOIN articles_tags ArticlesTags ON Articles.id = (ArticlesTags.article_id) 
  INNER JOIN tags Tags ON (
    Tags.name = 'Good' 
    AND Tags.id = (ArticlesTags.tag_id)
  ) 
  INNER JOIN articles_icons ArticlesIcons ON Articles.id = (ArticlesIcons.article_id) 
  INNER JOIN icons Icons ON (
    Icons.icon = 'sad' 
    AND Icons.id = (ArticlesIcons.icon_id)
  ) 
  INNER JOIN tags_tag_options TagsTagOptions ON Tags.id = (TagsTagOptions.tag_id) 
  INNER JOIN tag_options TagOptions ON (
    TagOptions.name = 'display_tag' 
    AND TagOptions.id = (TagsTagOptions.tag_option_id)
  ) 
LIMIT 
  20 OFFSET 0

SELECT 
  (
    COUNT(*)
  ) AS `count` 
FROM 
  articles Articles 
  INNER JOIN articles_tags ArticlesTags ON Articles.id = (ArticlesTags.article_id) 
  INNER JOIN tags Tags ON (
    Tags.name = 'Good' 
    AND TagOptions.name = 'display_tag' 
    AND Tags.id = (ArticlesTags.tag_id)
  ) 
  INNER JOIN articles_icons ArticlesIcons ON Articles.id = (ArticlesIcons.article_id) 
  INNER JOIN icons Icons ON (
    Icons.icon = 'sad' 
    AND Icons.id = (ArticlesIcons.icon_id)
  ) 
  INNER JOIN tags_tag_options TagsTagOptions ON Tags.id = (TagsTagOptions.tag_id) 
  INNER JOIN tag_options TagOptions ON (
    TagOptions.name = 'display_tag' 
    AND TagOptions.id = (TagsTagOptions.tag_option_id)
  )

SELECT 
  (
    COUNT(*)
  ) AS `count` 
FROM 
  articles Articles 
  INNER JOIN articles_tags ArticlesTags ON Articles.id = (ArticlesTags.article_id) 
  INNER JOIN tags Tags ON (
    Tags.name = 'Good' 
    AND TagOptions.name = 'display_tag' 
    AND TagOptions.name = 'display_tag' 
    AND TagOptions.name = 'display_tag' 
    AND Tags.id = (ArticlesTags.tag_id)
  ) 
  INNER JOIN articles_icons ArticlesIcons ON Articles.id = (ArticlesIcons.article_id) 
  INNER JOIN icons Icons ON (
    Icons.icon = 'sad' 
    AND Icons.id = (ArticlesIcons.icon_id)
  ) 
  INNER JOIN tags_tag_options TagsTagOptions ON Tags.id = (TagsTagOptions.tag_id) 
  INNER JOIN tag_options TagOptions ON (
    TagOptions.name = 'display_tag' 
    AND TagOptions.name = 'display_tag' 
    AND TagOptions.name = 'display_tag' 
    AND TagOptions.id = (TagsTagOptions.tag_option_id)
  )
```

As you can see, the SQL generated for the COUNT(*) seems malformed.

### What I expected to happen
I expected pagination to work, with the added matching() queries.

**Comment by markstory** [comment] 2017-05-26 18:06
I'll try and reproduce again. I was able to reproduce & fix what must have a been a similar issue then. Attaching eager loaded associations in a beforeFind() like this is dangerous, as the beforeFind() will be called twice for the count() query.

You might want to consider using a named finder instead of a beforeFind().

**Comment by markstory** [comment] 2017-05-27 03:54
I'm not sure this issue can be fixed. In my previous fix, I had the order of count()/all() flipped. This exposed a different issue that shares a root cause with this one. 

When a query is executed multiple times, state in the `EagerLoader` is shared between executions. The `count()`, `all()` ordering was simpler to fix as when a copy is made for the count operation, I was able to deep clone the EagerLoader breaking the state being linked.

In this scenario, `all()` is called first, and the `EagerLoader` is modified as part of the `all()` execution, then when `count()` is called, it re-uses the already populated`EagerLoader`, reapplying the `matching()` operations. This re-application combined with how multiple calls to `matching()` with the same key 'merge' the loader functions causes the issue. On the second run, the `Tags` loader is defined, and is decorated as the key matches an existing loader. The redefinition of a loader results in the `TagOptions` conditions being applied to the `Tags` dummy query that was defined in the `all()` execution.

I'll try and see if PaginatorComponent can clone the queries before executing them, but in the mean time you should avoid nested matching() calls and prefer to use the dot paths for deep associations:

```php
$query->matching('Tags.TagOptions', function(Query $q) {
	return $q->where(['TagOptions.name' => 'display_tag']);
})
->matching('Icons', function(Query $q) {
	return $q->where(['Icons.icon' => 'sad']);
});
```

The above should generate the results you're looking for without the SQL errors.

**Comment by markstory** [comment] 2017-05-29 01:10
Closing as I have a temporary fix posted for Pagination, but calling `all()` and then `count()` will still break in other use cases, so #10702 has been opened to track the underlying issues in `EagerLoader`

**Closed** 2017-05-29 07:57 UTC
Labels: Defect, ORM
