### ISSUE TITLE
Floats are truncated to 6th decimal position in toDatabase

### ISSUE THREAD

**Issue by KMPolakowski** [cakephp/cakephp#13080] opened 2019-04-02 06:37 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.14
* Platform and Target: DOESN'T MATTER.

### What you did
Save a float (of type float not string) with 8 decimal positions.

### What happened
CakePHP will truncate to the 6th decimal position when the type is float because sprintf is used to cast the float to string and: 

`sprintf("%F", 0.0000001)` => returns 0.000000

### What you expected to happen
CakePHP should save all decimal positions when the type is float as it does it correctly when the type is string.

The problem is here:

https://github.com/cakephp/cakephp/blob/a594deab6e393d031b74a1d1353a6ff2e51afac1/src/Database/Type/DecimalType.php#L93

This does the truncating the the 6th position maybe you want to use `strval($value)` which would solve the problem quickly.

**Comment by ADmad** [comment] 2019-04-02 06:49
Duplicate of #10233.

**Closed by ADmad** 2019-04-02 06:49 UTC
