### ISSUE TITLE
DatabaseSession triggers warning when session is restarted

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/cakephp#9227] opened 2016-08-07 23:24 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.12
* Platform and Target: Apache 2.4, MySQL, PHP 7

### What you did

I get a 100% reproducible warning when restarting sessions that use the database for storage.

```
Warning (2): session_regenerate_id() [function.session-regenerate-id]: Session object destruction failed.  ID: user (path: ) [CORE\src\Network\Session.php, line 578]
```

## Steps to reproduce

1. Configure database sessions.
2. Start a user session in the browser.
3. Wait for the session to timeout.
4. Make a web request to CakePHP
5. Session is restarted and triggers warning.

Here is my `app.php` configuration.

```
    'Session' => [
        'cookie' => 'ahtag',
        'defaults' => 'database',
        'timeout' => 30,
        'handler' => [
            'model' => 'UserSessions'
        ]
    ],
```

The problem here is that the session ID is used to restore the previous session, but that ID has been deleted from the database.

That happens in `Session.php, line 330` here:

```
        if ($this->_timedOut()) {
            $this->destroy();
            return $this->start();
        }
```

The destroy calls the database storage which does a table delete query on that ID. Later the `Session::renew()` is called and `session_id()` returns that same ID but PHP can not continue the session since the storage is now gone.

> Note: It has taken me a while to gather the reasons behind this bug, because it requires a user's session to expire first and that makes it difficult to debug and trace.

### Expected Behavior

Should continue the session with out a warning, or it should just start a new session successfully.

### Actual Behavior

It's a mix between code in CakePHP and the PHP session APIs. The `Session.php` is clearly deleting the previous session and then trying to start another one, but the code also tries to continue the previous one.

I don't know what the current solution is?

1. Should `Session::renew` be calling `session_regenerate_id`?
2. Should `Session::start()` be destroying the old session?
3. Should the `DatabaseSession` be deleting session records (i.e. should session records be allowed to stay around for X number of days)

**Comment by markstory** [comment] 2016-08-08 01:55
> The destroy calls the database storage which does a table delete query on that ID. Later the Session::renew()

Where is renew() getting called from? 

> Should Session::renew be calling session_regenerate_id?

It does, if the session has no id. Perhaps `destroy()` should be wiping the session id to ensure renew() generates a new session.

**Comment by thinkingmedia** [comment] 2016-08-08 02:05
The business logic appears to be identical between `DatabaseSession` and `CacheSession`. Yet, using `CacheSession` does not raise the warning.

> Where is renew() getting called from?

I'll have to reproduce it again, but I suspect it is from `SessionStorage::write(array $user)` when the user is stored during authorization, because this only happens for logged in users.

**Comment by thinkingmedia** [comment] 2016-08-08 02:11
@markstory I might be wrong about what is happening here. Taking another look at `Session::start` and it does not call `DatabaseSession::destroy` directly.

It's confusing because there are storage objects and then there is the `Session` class. The work session is used so often that I'm getting lost.

**Comment by markstory** [comment] 2016-08-08 02:46
The complexity is inherited from PHP sadly. `Cake\Network\Session` is supposed to be an abstraction around PHP's native `session_` functions, while the storage objects, are supposed to be an abstraction around the storage drivers that get attached to the session.

**Comment by thinkingmedia** [comment] 2016-08-08 03:16
@markstory The storage objects are being partly called directly by the PHP `session_` APIs, right?

I think that's what might be happening as I can't find all the locations that are calling the storage object methods.

**Comment by Perzonallica** [comment] 2016-08-08 10:23
I have similar issue but only with PHP7. I get this when user logs in or out. With PHP5.6 everything is OK.

> Warning (4096): session_regenerate_id(): Failed to create(read) session ID: memcache (path: /apachetmp/sessions) [CORE/src/Network/Session.php, line 579]

**Comment by markstory** [comment] 2016-08-08 13:21
@thinkingmedia That is correct.

**Comment by thinkingmedia** [comment] 2016-08-08 14:11
It looks like PHP reads the previous session using the expired ID, and then the `Session` does a destroy. After that a `renew` is called and `session_id()` is going to return a value, but when `renew` calls regenerate the DB record is now gone.

I think `DatabaseSession::destroy()` needs to call PHP's API `session_destroy()`.

**Comment by thinkingmedia** [comment] 2016-08-08 14:15
> I think DatabaseSession::destroy() needs to call PHP's API session_destroy().

Nope, don't do that. Very bad recursive calls lol

**Comment by markstory** [comment] 2016-08-08 21:24
You might be able to clear the session id with `session_id('')` or `session_regenerate_id()`.

**Comment by markstory** [comment] 2016-08-09 02:20
I'm not sure what I'm doing wrong, but I can't seem to reproduce this. In `config/app.php` I have:

```php
    'Session' => [
        'defaults' => 'database',
        'timeout' => 1,
        'ini' => [
            'session.cookie_lifetime' => 60,
        ]
    ],
```

And in a controller I have:

```php
$this->request->session()->write('test', 'test val');
```

I load a page, wait 3 minutes, and then reload the page, but I don't see any warnings logged or in the HTML response.

**Comment by thinkingmedia** [comment] 2016-08-09 23:53
@markstory okay, I'll open a repo that contains an app that reproduces it. I'll get back to you on it.

**Comment by markstory** [comment] 2016-08-10 01:32
ok.

**Comment by ryantxr** [comment] 2016-08-17 05:09
I ran into this issue and fixed it myself.
For custom sessions, the read function has to return a string, not false.

	public function read($id) {
		$row = $this->_model->find('first', array(
			'conditions' => array($this->_model->primaryKey => $id)
		));

		if (empty($row[$this->_model->alias]['data'])) {
			return ''; // <----- this
		}
		return $row[$this->_model->alias]['data'];
	}

See here: https://bugs.php.net/bug.php?id=71187

**Comment by ADmad** [comment] 2016-08-17 06:04
@ryantxr The bug you have linked has been closed so PHP 7.0.1+  shouldn't have any problem.

**Comment by Perzonallica** [comment] 2016-08-17 06:12
@ADmad As I wrote in my previous post, on PHP7 the session_regenerate_id() problem still exists. I have to refresh twice the page if I want to login. On PHP5.6 its OK. 

> Warning (4096): session_regenerate_id(): Failed to create(read) session ID: memcache (path: /apachetmp/sessions) [CORE/src/Network/Session.php, line 579]

I don't know what that memcache is doing there, I don't use it anywhere in my app. But I think this won't be a Cake problem, because on my Ubuntu localhost, where I'm using PHP7 too, I don't experience this problem. I think this is a PHP bug with memcache.

**Comment by markstory** [comment] 2016-09-17 14:48
Closing as it sounds like this is an issue with PHP7 + memcache not CakePHP.

**Comment by thinkingmedia** [comment] 2016-09-18 19:53
I don't have memcache and I consistently get the error.

**Comment by markstory** [comment] 2016-09-18 23:20
@thinkingmedia If you know how to reproduce it, that would be really helpful.

**Comment by thinkingmedia** [comment] 2016-09-19 02:20
I'm sure I can create a sample app that does it. I'm getting this on my
production server each time a session is restored.

So I have to get it fixed but I do think it's specific to PHP 7. I upgraded
to 7.0.10 but it still continues.

I'll add a new repo on github to demo it. I'll do that first thing in the
morning.

I'd make a PR of I knew how to fix it but I don't know.

**Comment by thinkingmedia** [comment] 2016-09-19 15:29
That was **painful** to reproduce. Took 4 hours this morning to narrow down the setup to a minimal app skeleton, but I can not quickly reproduce it 100% of the time.

![image](https://cloud.githubusercontent.com/assets/551022/18637960/392fcfa0-7e5c-11e6-8c8c-ce3e53034e57.png)

**Comment by lorenzo** [comment] 2016-09-19 15:42
Can you upload a zip file with the app?

**Comment by lorenzo** [comment] 2016-09-20 08:35
Thanks @thinkingmedia I'll take a look at that

**Closed** 2016-09-20 17:28 UTC
Labels: Defect, network, On hold
