### ISSUE TITLE
RoutesBuilder custom prefix path

### ISSUE THREAD

**Issue by jorisvaesen** [cakephp/cakephp#9844] opened 2016-12-05 16:37 UTC
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3

### What you did
```
Router::prefix('DatabaseBackups', ['path' => '/database-backups'], function ($routes) {
    $routes->connect('/:controller');
});
```
### What happened
Error (as expected)

### What you expected to happen
Like `Router::plugin` it would be awesome if you could customize the path of the prefix.
At this point `Inflector::underscore` is used, which is quite ugly if you use `DashedRoute` for the rest
of the url.

**Comment by markstory** [comment] 2016-12-05 20:48
Sounds like a good idea to me. :+1:

**Comment by dereuromark** [comment] 2016-12-05 20:51
Sounds like a duplicate of https://github.com/cakephp/cakephp/issues/8150 - but yeah, I would also like to see this happening.

**Comment by markstory** [comment] 2017-01-14 16:50
Closing as a pull request is open now.

**Closed** 2017-01-15 10:07 UTC
Labels: Enhancement, routing
