### ISSUE TITLE
3.0.6 - Paginator prefix doesn't work when sorting on a computed field

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#6778] opened 2015-06-10 15:07 UTC
Hi guys. I just ran into this one. Say I do this in a finder for a Table named `Table`..

```
$query->select([
    'Table__searchScore' => '(MATCH(Table.name) AGAINST('test') * 10) + (MATCH(Table.description) AGAINST('test') * 4)'
]);
```

Then in a controller when doing a search..
```
$this->paginate = [
	'Table' => [
	 	'limit' => 20,
	 	'order' => ['Table__searchScore' => 'desc'],
	 	'sortWhitelist' => ['Table__searchScore', 'Table.id']
	 ]
];
```
When paginating, it tries to prepend the `Table` alias to `Table__searchScore`, which is invalid. Produces..
```
SELECT (MATCH(Table.name) AGAINST('test') * 10) + (MATCH(Table.description) AGAINST('test') * 4) AS `Table`.`Table__searchScore` ...
```

This is because `PaginatorComponent::_prefix` does that regardless if it should or not. In the case when a query has added an arbitrary select, I don't think it should. This was working as expected in 3.0.5.

Thanks

**Comment by markstory** [comment] 2015-06-10 17:03
Duplicate of #6725, will be fixed by #6740

**Closed by markstory** 2015-06-10 17:03 UTC

**Comment by patrickconroy** [comment] 2015-06-10 17:07
Thanks, @markstory , master works now.

**Comment by markstory** [comment] 2015-06-10 17:08
Huzzah, 3.0.7 will be out soon.

**Comment by patrickconroy** [comment] 2015-06-10 17:12
:+1:
