### ISSUE TITLE
It is not possible to create custom error pages for the prefixes

### ISSUE THREAD

**Issue by allanmcarvalho** [cakephp/cakephp#12260] opened 2018-06-18 13:32 UTC
* [x] enhancement

* CakePHP Version: 3.6.5

I believe the current version does not do the correct routing for error pages when using prefix. For example, if I have the prefix "Admin", it should only use the default "ErrorController", layout "error.ctp" and views "error400.ctp" and "error500.ctp", if there was no version of the prefix folders. This prevents me from being able to create a custom error page for the prefix "Admin"

**Comment by markstory** [comment] 2018-06-18 16:20
Duplicate of #8861

**Closed by markstory** 2018-06-18 16:20 UTC
Labels: Enhancement, errorhandler
