### ISSUE TITLE
Server.buildMiddleware event not dispatched for tests

### ISSUE THREAD

**Issue by sdustinh** [cakephp/cakephp#9763] opened 2016-11-15 20:18 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

```
sdustinh@sdustinh:~/github/app$ composer show cakephp/*
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
cakephp/bake                1.2.8              Bake plugin for CakePHP 3.0
cakephp/cakephp             3.3.8              The CakePHP framework
cakephp/cakephp-codesniffer dev-master 631680d CakePHP CodeSniffer Standards
cakephp/chronos             1.0.0              A simple API extension for DateTime.
cakephp/debug_kit           3.3.7              CakePHP Debug Kit
cakephp/migrations          1.6.3              Database Migration plugin for CakePHP 3.0 based on Phinx
cakephp/plugin-installer    0.0.15             A composer installer for CakePHP 3.0+ plugins.
sdustinh@sdustinh:~/github/app$ php --version
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```

### What you did
In my application I have a plugin that adds to the middleware queue from its bootstrap.

```php
use Cake\Event\EventManager;
use Plugin\Middleware\PluginMiddleware;

$eventManager = EventManager::instance();
$eventManager->on(
    'Server.buildMiddleware',
    function ($event, $middleware) {
        $middleware->add(new PluginMiddleware());
    }
);
```

This event is never dispatched. If I add a `debug('yay'); die()` in there it doesn't die when I run tests but when I view it in a browser it does work. I didn't have time to track this down or test on a fresh clone so I'm sorry if this has already been taken care of or not a bug.

**Comment by sdustinh** [comment] 2016-11-15 23:26
It looks like the reason the event is missing is because of this: https://github.com/cakephp/cakephp/blob/master/src/TestSuite/TestCase.php#L108

I can see both sides of the argument for this so I guess I'm curious what you guys think before I just close this issue and write my own work around.

It seems like if I'm doing an integration test I would expect to be testing the full application as it would be from a real request. The book recommends adding event listeners in your bootstrap so if this event stack is cleared on the setup of each test it seems like that would be a problem.

The problem was introduced here: https://github.com/cakephp/cakephp/pull/5268

**Comment by kevinquinnyo** [comment] 2016-11-16 01:30
Would it make sense to add something like (couldn't think of a good variable name):

```php
public function setUp($clearEvents = true)
{
  // ...
  if ($clearEvents !== false) {
    EventManager::instance(new EventManager());
  }
}
```

That would be backwards compatible (as far as I can tell?), and allow tests to maintain the event stack if they so choose.

**Comment by markstory** [comment] 2016-11-16 02:03
Wiping the dispatcher is both useful and a problem. It solves globally attached listeners being fired N times as multiple tests bind duplicate listeners, but the problem is global state is lost. Perhaps we can add methods to re-run an application's bootstrap process on each test? That would let people who have safe/idempotent bootstrap processes to re-attach their listeners.

@kevinquinnyo I don't know if that would work as any test can reset the global listeners.

**Comment by kevinquinnyo** [comment] 2016-11-16 02:25
> Perhaps we can add methods to re-run an application's bootstrap process on each test? That would let people who have safe/idempotent bootstrap processes to re-attach their listeners.

I think something like that sounds like it would solve the problem.  How do you envision implementing that?  A method that each Integration test's method would have to call, like `$this->runBootstrap()` or a configuration option of some kind?  My knowledge of cakephp's internals is pretty much at it's limit at this point, so forgive me if I'm way off.

**Comment by markstory** [comment] 2016-11-16 02:42
Something like `$this->runBootstrap()` or `$this->bootstrapApp()` sound like good options to me.

**Comment by sdustinh** [comment] 2016-11-16 17:15
I don't know if it's in the scope of this or not but it would be really awesome if registering event listeners was a more rigid process instead of just cramming it all into a boostrap file. The process could be something like:

```php
Plugin::load('Users', ['bootstrap' => true, 'events' => true, 'routes' => true]);
```

Then throughout the application and in testing it would be much easier to control events while not getting in the way of letting them register to listen. Maybe something design of `src/Controller/Events/*Event.php`, `plugins/Users/Events/*Event.php`, etc. Would make it much easier to track and even test event listeners. Right now it's a little bit of an art to make an event-driven application that is also tested well.

**Comment by markstory** [comment] 2016-11-16 20:30
@sdustinh There is the option of using `Application::bootstrap()` post 3.3.

**Comment by sdustinh** [comment] 2016-11-17 00:41
@markstory derp

**Comment by markstory** [comment] 2016-11-17 03:14
@sdustinh I think using the `Application::bootstrap()` hook will let you do what you wanted around re-attaching global event listeners in a reproducible way. I don't think that hook method is well documented or well supported by plugins though.

**Comment by markstory** [comment] 2016-12-11 22:05
@sdustinh Does it seem reasonable for me to update the documentation mentioning that events and plugins can be bootstraped in `Application::boostrap()` and close this issue?

**Comment by sdustinh** [comment] 2016-12-12 02:43
@markstory Definitely sounds good to me. For now I have just been adding them manually. If I come up with a better solution I'll just reference this issue.

**Comment by markstory** [comment] 2016-12-27 05:22
Docs updated now.

**Closed by markstory** 2016-12-27 05:22 UTC
Labels: documentation
