### ISSUE TITLE
3.1 - Bug - Themed Flash Elements

### ISSUE THREAD

**Issue by andtxr** [cakephp/cakephp#7012] opened 2015-07-13 22:28 UTC
Seems that #5920 stopped to work after the merges of #6161

Going to check it later

**Comment by markstory** [comment] 2015-07-14 03:08
Knowing how to reproduce the issue would be helpful. The test added in #5936 is still passing.

**Comment by andtxr** [comment] 2015-07-14 13:47
Going to do isolated tests right now.

**Comment by andtxr** [comment] 2015-07-14 18:31
It is actually working on 3.0.8.

But did not worked with cakephp/app [3.1] and cakephp/cakephp [3.1]
Even this branches are still unstable I preferred report.

You can check it from a fresh install and then:

* `bin/cake bake plugin Theme`
* Copy `src/Template/Element/Flash` to `plugins/Theme/src/Template`
* Add `public $theme = 'Theme';` to AppController class.
* Make some changes in the theme flash elements and test it with some action.

**Comment by markstory** [comment] 2015-07-14 21:13
Thanks @andtxr I'll try reproducing tonight.

**Comment by HavokInspiration** [comment] 2015-07-15 11:50
I was able to take a look at this.
It may be wrong but it seems that the ``$theme`` property of the ``AppController`` is not propagated to the ``View``.
If I set the ``$theme`` property in ``AppView`` it works as expected. 
This explains the fact that tests are passing.

**Comment by ADmad** [comment] 2015-07-15 12:01
@HavokInspiration Yes, view related properties have removed from controller in 3.1. Instead of declaring `public $theme = 'Theme';` one should set `$this->getView()->theme = 'Theme'` in `beforeRender()`.

**Comment by HavokInspiration** [comment] 2015-07-15 12:14
@ADmad OK. We need to update the 3.1 doc around Themes then.

**Comment by ADmad** [comment] 2015-07-15 12:26
I'll check again and ensure the 3.1 docs are updated.

**Comment by markstory** [comment] 2015-07-15 12:27
@ADmad Shouldn't we be handling the theme property in the same way as view/layout?

**Comment by ADmad** [comment] 2015-07-15 12:29
@markstory Usage like `$this->theme` is handled through the magic getter/setter. The problem is the magic getter/setter don't work when you declare those properties as `public $theme = 'Foo';`.

**Comment by lorenzo** [comment] 2015-07-15 12:51
@ADmad I think we need to unset($this->theme) in the constructor and remember its initial value somewhere so it can be applied if it was not changed

**Comment by ADmad** [comment] 2015-07-15 12:52
@lorenzo Or maybe we can do a `property_exists()` check and if the property is set pass it on to View class when it is constructed and then unset it. I'll look into it this weekend, unless someone has wants to handle it earlier :)

**Comment by markstory** [comment] 2015-07-15 21:51
Closing as there is a pull request open now to address this.

**Closed by markstory** 2015-07-15 21:51 UTC
Labels: Defect, On hold
