### ISSUE TITLE
two habtm baked correctly generate error in ADD and EDIT methods

### ISSUE THREAD

**Issue by eajuria** [cakephp/cakephp#6787] opened 2015-06-11 16:31 UTC
IMG of DB structure
![habtm multiple](http://i57.tinypic.com/k4wkyh.jpg)

model baked

```php
App::uses('AppModel', 'Model');

class Solicitude extends AppModel {


	public $displayField = 'radicado';


	public $hasAndBelongsToMany = array(
		'Citante' => array(
			'className' => 'Cliente',
			'joinTable' => 'citantes',
			'foreignKey' => 'solicitude_id',
			'associationForeignKey' => 'cliente_id',
			'unique' => 'keepExisting',
			'conditions' => '',
			'fields' => '',
			'order' => '',
			'limit' => '',
			'offset' => '',
			'finderQuery' => '',
		),
		'Citado' => array(
			'className' => 'Cliente',
			'joinTable' => 'citados',
			'foreignKey' => 'solicitude_id',
			'associationForeignKey' => 'cliente_id',
			'unique' => 'keepExisting',
			'conditions' => '',
			'fields' => '',
			'order' => '',
			'limit' => '',
			'offset' => '',
			'finderQuery' => '',
		)
	);

}
```

controller mothods baked

```php
	public function add() {
		if ($this->request->is('post')) {
			$this->Solicitude->create();var_dump($this->request->data);exit;
			if ($this->Solicitude->save($this->request->data)) {
				$this->Session->setFlash(__('The solicitude has been saved.'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The solicitude could not be saved. Please, try again.'));
			}
		}
		$citantes = $this->Solicitude->Citante->find('list');
		$citados = $this->Solicitude->Citado->find('list');
		$this->set(compact('citantes', 'citados'));
	}


	public function edit($id = null) {
		if (!$this->Solicitude->exists($id)) {
			throw new NotFoundException(__('Invalid solicitude'));
		}
		if ($this->request->is(array('post', 'put'))) {
			if ($this->Solicitude->save($this->request->data)) {
				$this->Session->setFlash(__('The solicitude has been saved.'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The solicitude could not be saved. Please, try again.'));
			}
		} else {
			$options = array('conditions' => array('Solicitude.' . $this->Solicitude->primaryKey => $id));
			$this->request->data = $this->Solicitude->find('first', $options);
		}
		$citantes = $this->Solicitude->Citante->find('list');
		$citados = $this->Solicitude->Citado->find('list');
		$this->set(compact('citantes', 'citados'));
	}
```

**Comment by lorenzo** [comment] 2015-06-11 16:32
what is the error?

**Comment by eajuria** [comment] 2015-06-11 16:39
Buen dia
Gracias por tu pronta respuesta

error en el metodo ADD

Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Citante.cliente_id' in 'field list'
SQL Query: SELECT `Citante`.`cliente_id` FROM `conciliacion`.`clientes` AS `Citante` WHERE `Citante`.`solicitude_id` = '12'

al parecer reconoce mal las relaciones y crea mal las consultas

**Comment by eajuria** [comment] 2015-06-11 16:41
Español
Buen diaGracias por tu pronta respuesta
error en el metodo ADD
 Error:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Citante.cliente_id' in 'field list'  SQL Query:  SELECT `Citante`.`cliente_id` FROM `conciliacion`.`clientes` AS `Citante` WHERE `Citante`.`solicitude_id` = '12' 

al parecer reconoce mal las relaciones y crea mal las consultas




      De: José Lorenzo Rodríguez <notifications@github.com>
 Para: cakephp/cakephp <cakephp@noreply.github.com> 
CC: eajuria <erickajuria@yahoo.es> 
 Enviado: Jueves 11 de junio de 2015 11:32
 Asunto: Re: [cakephp] two habtm baked correctly generate error in ADD and EDIT methods (#6787)
   
what is the error?—

**Comment by markstory** [comment] 2015-06-11 16:58
Does the problem go away if you only have one of the belongsToMany associations?

**Comment by eajuria** [comment] 2015-06-11 16:59
Yes it is.

**Comment by lorenzo** [comment] 2015-06-11 17:10
I don't think you can have Cliente to be using two different tables at the same time. I would suggest you use a different class and modify the useTable property

**Comment by eajuria** [comment] 2015-06-11 17:19
Please, try to build by console thats relationships between **Solicitudes** and **Clientes**,
and you'll have the error

**Comment by lorenzo** [comment] 2015-06-11 17:46
Sorry, I thought it was a hasOne...

**Comment by eajuria** [comment] 2015-06-12 02:46
Any help about how bake thats two relationships ?? :(

**Comment by eajuria** [comment] 2015-06-12 15:46
Well, after many hours trying.
I managed to make it work manually, here I leave the final code.

**Comment by eajuria** [comment] 2015-06-12 16:01
model relationships code

    public $hasAndBelongsToMany = array(
		'Cte' => array(
			'className' => 'Cliente',
			'joinTable' => 'citantes',
			'foreignKey' => 'solicitude_id',
			'associationForeignKey' => 'cliente_id',
			'unique' => 'keepExisting',
			'conditions' => '',
			'fields' => '',
			'order' => '',
			'limit' => '',
			'offset' => '',
			'finderQuery' => '',
		),
		'Cdo' => array(
			'className' => 'Cliente',
			'joinTable' => 'citados',
			'foreignKey' => 'solicitude_id',
			'associationForeignKey' => 'cliente_id',
			'unique' => 'keepExisting',
			'conditions' => '',
			'fields' => '',
			'order' => '',
			'limit' => '',
			'offset' => '',
			'finderQuery' => '',
		)
    );

Controller ADD and EDIT methods

	public function add() {
		if ($this->request->is('post')) {
			$this->Solicitude->create();
			if ($this->Solicitude->save($this->request->data)) {
				$this->Session->setFlash(__('The solicitude has been saved.'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The solicitude could not be saved. Please, try again.'));
			}
		}
		$Cte = $this->Solicitude->Cte->find('list');
		$Cdo = $this->Solicitude->Cdo->find('list');
		$this->set(compact('Cte', 'Cdo'));
		
	}


	public function edit($id = null) {
		if (!$this->Solicitude->exists($id)) {
			throw new NotFoundException(__('Invalid solicitude'));
		}
		if ($this->request->is(array('post', 'put'))) {
			if ($this->Solicitude->save($this->request->data)) {
				$this->Session->setFlash(__('The solicitude has been saved.'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The solicitude could not be saved. Please, try again.'));
			}
		} else {
			$options = array('conditions' => array('Solicitude.' . $this->Solicitude->primaryKey => $id));
			$this->request->data = $this->Solicitude->find('first', $options);
		}
		$Cte = $this->Solicitude->Cte->find('list');
		$Cdo = $this->Solicitude->Cdo->find('list');
		$this->set(compact('Cte', 'Cdo'));
	}

ADD View

    echo $this->Form->create('Solicitude'); 	
		 echo __('Add Solicitude'); 	
		echo $this->Form->input('radicado');
		echo $this->Form->input('fecha');
		echo $this->Form->input('ccsede_id');
		echo $this->Form->input('ccusuario_id');
		echo $this->Form->input('consulta_id');
		echo $this->Form->input('peticiones');
		echo $this->Form->input('area_id');
		echo $this->Form->input('tipo_clase_id');
		echo $this->Form->input('Cte',array('options'=>array($Cte)));
		echo $this->Form->input('Cdo',array('options'=>array($Cdo)));
    echo $this->Form->end(__('Submit')); 

EDIT View

    echo $this->Form->create('Solicitude'); 
	echo __('Edit Solicitude'); 	
		echo $this->Form->input('id');
		echo $this->Form->input('radicado');
		echo $this->Form->input('fecha');
		echo $this->Form->input('ccsede_id');
		echo $this->Form->input('ccusuario_id');
		echo $this->Form->input('consulta_id');
		echo $this->Form->input('peticiones');
		echo $this->Form->input('area_id');
		echo $this->Form->input('tipo_clase_id');
		echo $this->Form->input('Cte',array('options'=>array($Cte)));
		echo $this->Form->input('Cdo',array('options'=>array($Cdo)));
    echo $this->Form->end(__('Submit')); 

I hope you find it useful
EAF

**Comment by markstory** [comment] 2015-06-12 18:50
Is the only thing that has changed the alias names? The model associations look the same to me.

**Comment by eajuria** [comment] 2015-06-13 01:40
The Select's  options I put them manually, if left automatic does not work

**Comment by markstory** [comment] 2015-06-13 03:36
@eajuria Ok that's good to know. I hope to look at this issue over the weekend.

**Comment by markstory** [comment] 2015-06-16 02:42
I wasn't able to get bake to generate the hasAndBelongsToMany associations you have. Did you add in the hasAndBelongsToMany associations afterwards, or define them as part of the interactive process?

**Comment by eajuria** [comment] 2015-06-16 03:38
as part of the interactive process...
if you want add me in skype, and i can share my screen in process
user skype: guess231

**Comment by markstory** [comment] 2015-06-16 11:15
I will give it another shot tonight.

**Comment by markstory** [comment] 2015-06-18 01:52
After taking a look at this it looks like the issue here is being caused by your join tables sharing a name/alias that resolves to an existing alias. 

In your case the `Citante` alias points to the `Cliente` model. Because the join table in your association is also `citantes` the model alias is also `Citante` which points to the `Cliente` via alias re-use. The same issue exists for the Citado alias. This issue of alias re-use is also why modifying the aliases to Cdo and Cte resolves the issue. Alternatively you can set the `with` key in your associations to unique aliases.

Because this issue is caused by ClassRegistry 'poisoning' I'm going to close it. Registry issues are a persistent issue in 2.x which is why we removed this behavior in 3.x.

**Closed by markstory** 2015-06-18 01:52 UTC
Labels: console, Defect, On hold
