### ISSUE TITLE
Flash messages not accessible to test runner (CakePHP 2.10.6, PHPUnit 3.7.38)

### ISSUE THREAD

**Issue by kierenpitts** [cakephp/cakephp#11588] opened 2017-12-30 13:51 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.6
* Platform and Target: Ubuntu 16.04, MySQL, PHPUnit 3.7.38

### What you did
Part of my test suite checks that a Flash message is rendered when a user makes a change via a form. Trying this through the browser shows the correct Flash message but the test runner output does not contain the Flash message (this was working fine in 2.10.5 with PHPUnit 3.7.38 but not with 2.10.6 and PHPUnit 3.7.38) even though the action is performed correctly. I have multiple tests that perform actions and all those that check for the presence of a Flash message are failing due to the missing message.

I set the message with this in the controller:
`$this->Flash->set('Item saved!');`

I have this in the View:
`<?php echo $this->Flash->render() ?>`

and test for it like this:
`$page_contents = $this->contents;`
`$this->assertContains('Item saved!', $page_contents);`

### What happened
Flash messages are not shown in the output received by the test runner. The test runner failure message shows the HTML for the page and this is all correct (i.e. the action is performed correctly and the HTML reflects this) apart from the presence of the Flash message.

### What you expected to happen
Flash messages should be consistent between the test runner and the browser. This was working in 2.10.5 so I assume this is perhaps caused by a problem with session handling in the test runner?

**Comment by markstory** [comment] 2017-12-30 15:54
I don't know which session handling changes you're referring to as [the diff between 2.10.5 and 2.10.6](https://github.com/cakephp/cakephp/compare/2.10.5...2.10.6) doesn't change code related to the cli test runner or session handling.

I can try and reproduce missing flash messages in a test app.

**Comment by kierenpitts** [comment] 2017-12-30 20:17
Sorry, I should've been more explicit. I was wondering if it was an issue caused by:

"CakeSession now supports a timeout mode that is forwards compatible with CakePHP 3.x. This will help improve session compatibility for applications that are straddling both versions."

I'm guessing it's either that or a reversion caused by adding support to later versions of PHPUnit.

**Comment by markstory** [comment] 2017-12-30 21:13
The issue could be caused by the changes to the webrunner. It is the only likely cause. Do your tests pass in the cli runner?

**Comment by kierenpitts** [comment] 2017-12-30 21:52
No, I'm afraid not. I get the same failures from the CLI.

The commit that seems to cause the issue is:-
https://github.com/cakephp/cakephp/commit/a2cc9843e43a98bde3e53ffedaf6e48164aa8479

If I comment out: `ob_end_flush();` then the flash messages appear in the output used by the test runners and the tests pass again.

**Comment by markstory** [comment] 2017-12-31 00:17
Thanks for investigating further. This sounds related to #11448 and #11450.

**Comment by markstory** [comment] 2017-12-31 03:44
I was able to reproduce this issue in the web runner, and was able to confirm that this is related to the changes made in #11450.

I am considering changing the HTML Reporter to buffer all of its content into a string and output the entire page as part of `paintFooter()`. This could result in memory exhaustion more frequently, but I can't think of another way around both this issue and #11448.

**Comment by markstory** [comment] 2017-12-31 04:52
@kierenpitts Any chance you could test the changes in #11590 and see if they work for you? I checked locally with a very basic controller, but you likely have more comprehensive tests.

**Comment by kierenpitts** [comment] 2017-12-31 10:02
Hi
I've tried the changes in #11590  and all my tests pass. In case it's useful (as I noticed your message about memory usage) the usage for the biggest test case in my app is given below (as reported in the output). I also ran the tests with the CakeHtmlReporter.php from 2.10.6 but with `ob_end_flush();` commented out. Memory usage wasn't that different in my case for this test case or any of the others in my app but ymmv ;-)

2.10.6 with `ob_end_flush();` commented out:
`24/24 test methods complete: 24 passes, 0 fails, 234 assertions and 0 exceptions.`
`Time: 1.6970884799957 seconds`
`Peak memory: 14,971,096 bytes`
(nb. the actual time to run this was around 1m 9s)

#11590 version:
`24/24 test methods complete: 24 passes, 0 fails, 234 assertions and 0 exceptions.`
`Time: 2.0537884235382 seconds`
`Peak memory: 14,987,848 bytes`
(nb. actual time was around 1m 7s)

Many thanks for looking at this, hope the above is useful.

**Comment by markstory** [comment] 2017-12-31 14:22
Thanks for testing the changes out. That is a very minor change in memory use that doesn't look very concerning.

**Comment by markstory** [comment] 2017-12-31 14:36
Closing as the open pull request solves this issue.

**Closed by markstory** 2017-12-31 14:36 UTC
Labels: Defect, http, On hold, testing
