### ISSUE TITLE
Translate contain Cakephp

### ISSUE THREAD

**Issue by konowar** [cakephp/cakephp#8465] opened 2016-03-14 21:18 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.4

### What you did

I want to know how I can translate content associated with I18n

**Post Controller**

`I18n::locale('es');
$post = $this->Posts->get($id,['contain'=>['Categories']]);
          $this->set('post', $post);
`

**Categories Table**
`$this->addBehavior('Translate', ['fields' => ['name', 'description', 'slug']]);`

**Posts Table**
`$this->addBehavior('Translate', ['fields' => ['name', 'description', 'specification', 'slug', 'excerpt' ]]);`

with this script I currently translates all data from the POSTS table but I do not translate anything Categories

### Actual Behavior

When entering reading a file associated get an error on the next line

> $this->loadModel('Posts');
> 		$this->Posts->locale('es');
> 		$this->Posts->Categories->locale('es');
> 
> 		$data = $this->Posts->find('all', ['contain' => ['Categories']]);

_Cake\ORM\Association->__call_
Unknown method "locale" IN **$this->Posts->Categories->locale('es');**

_if I make the query directly to the table this category if you run the translation correctly_

**Comment by lorenzo** [comment] 2016-03-14 21:57
If the method does not exist, it means that the association does not have the Translate behavior enabled.

**Comment by konowar** [comment] 2016-03-14 22:08
How to enable the translation association?

**Posts Table**

`$this->belongsToMany('Categories',['joinTable' => 'categories_posts']);`


**Categories Table**

` $this->belongsToMany('Posts', ['joinTable' => 'categories_posts', 'conditions' => ['Posts.status' => 'active']]);`

**Comment by lorenzo** [comment] 2016-03-14 22:10
You need to add the `Translate` behavior in the the CategoriesTable class. If you get an error about a missing method, then the problem is that the behavior is not there.

**Comment by konowar** [comment] 2016-03-14 22:25
but translate behavior is in the file table categories

**Categories Table**
`$this->addBehavior('Translate', ['fields' => ['name', 'description', 'slug']]);`

If I translate content directly works. If I make a find Categories brings me to the translation but if I performed by a Contain brings me no translation.

**Comment by konowar** [comment] 2016-03-15 01:52
investigating a little further documentation also reports on the method of `translations`. It happens the same mistake does not work.

`$results = $this->Posts->find('translations', ['conditions'=>['Posts.id'=>122], 'contain'=>['Categories'=>['finder'=>['translations']]]]);`

**Error**
> ⟩ Cake\ORM\Association\BelongsToMany->find
CORE\src\ORM\Association\SelectableAssociationTrait.php, line 86

> ⟩ Cake\ORM\Table->find
CORE\src\ORM\Association\BelongsToMany.php, line 882

> Unknown finder method "translations"

**Comment by markstory** [comment] 2016-03-15 01:58
This error and the `locale` one both imply that your `CategoriesTable` class is not being loaded correctly. If you run `debug(\Cake\ORM\TableRegistry::get('Categories'));` and get `Cake\ORM\Table` your sub-class is not being used.

**Comment by konowar** [comment] 2016-03-15 11:24
look.

**Result debug for Categories**

`\plugins\Administrator\src\Controller\PostsController.php (line 215)
object(Cake\ORM\Table) {

	'registryAlias' => 'Categories',
	'table' => 'categories',
	'alias' => 'Categories',
	'entityClass' => '\Cake\ORM\Entity',
	'associations' => [
		(int) 0 => 'categoriesposts',
		(int) 1 => 'posts'
	],
	'behaviors' => [],
	'defaultConnection' => 'default',
	'connectionName' => 'default'

}`


**Result debug for Posts**

`\plugins\Administrator\src\Controller\PostsController.php (line 215)
object(Cake\ORM\Table) {

	'registryAlias' => 'Posts',
	'table' => 'posts',
	'alias' => 'Posts',
	'entityClass' => '\Cake\ORM\Entity',
	'associations' => [],
	'behaviors' => [],
	'defaultConnection' => 'default',
	'connectionName' => 'default'

}`


CategoriesTables

`namespace Administrator\Model\Table;

use Cake\ORM\Table;
use Cake\Validation\Validator;

$validator = new Validator();
class CategoriesTable extends Table
{

    public function initialize(array $config)
        {
          $this->addBehavior('Timestamp');
          $this->addBehavior('Translate', ['fields' => ['name', 'description', 'slug']]);
		      $this->addBehavior('Tree');

            $this->belongsToMany('Fields', ['joinTable' => 'fields_categories']);
            $this->belongsToMany('Posts', ['joinTable' => 'categories_posts', 'conditions' => ['Posts.status' => 'active']]);
            $this->belongsTo('Archives'); 
            $this->addBehavior('Translate', ['fields' => ['name', 'description', 'slug']]);
        }

}
?>`



PostsTables

`namespace Administrator\Model\Table;

use Cake\ORM\Table;
use Cake\Validation\Validator;


$validator = new Validator();

class PostsTable extends Table
{

    public function initialize(array $config) {
            
        $this->addBehavior('Timestamp');
            $this->addBehavior('Translate', ['fields' => ['name', 'description', 'specification', 'slug', 'excerpt' ]]);
            
            $this->belongsTo('Users');
            $this->belongsTo('Gadget');
            $this->HasMany('ArchivesPosts');
            $this->HasMany('FieldsPosts');

            $this->belongsToMany('Fields', ['joinTable' => 'fields_posts']);
            $this->belongsToMany('Archives',['joinTable' => 'archives_posts']);
            $this->belongsToMany('Categories',['joinTable' => 'categories_posts']);
           
        }

}`

The error `locale `is in line `$this->Posts->Categories->locale('es'); `

**Comment by markstory** [comment] 2016-03-15 16:32
Both your tables are Generic instances of `Cake\ORM\Table`. You might need to use `Administrator.Categories` in your associations to ensure that the correct models are used, as your models are in plugins.

**Comment by konowar** [comment] 2016-03-15 20:55
Great. It is a matter of placing the name of the plugin.

`$this->belongsToMany('Administrator.Categories',['joinTable' => 'categories_posts']);`

But now is not how to get the translation of a _joinData within Contain.


```
'fields' => [
		(int) 0 => object(Cake\ORM\Entity) {

			'id' => (int) 8,
			'option_key' => 'Fuel',
			'group_type' => 'Data',
			'created' => object(Cake\I18n\Time) {

				'time' => '2016-02-11T01:55:15+00:00',
				'timezone' => 'UTC',
				'fixedNowTime' => false
			
			},
			'modified' => object(Cake\I18n\Time) {

				'time' => '2016-03-15T19:08:52+00:00',
				'timezone' => 'UTC',
				'fixedNowTime' => false
			
			},
			'_locale' => 'es',
			'_joinData' => object(Cake\ORM\Entity) {

				'field_id' => (int) 8,
				'id' => (int) 11695,
				'post_id' => (int) 53,
		
```		'value' => '',
				'created' => object(Cake\I18n\Time) {

					'time' => '2016-03-15T14:08:52+00:00',
					'timezone' => 'UTC',
					'fixedNowTime' => false
				
				},
				'modified' => object(Cake\I18n\Time) {

					'time' => '2016-03-15T14:08:52+00:00',
					'timezone' => 'UTC',
					'fixedNowTime' => false
				
				},
				'[new]' => false,
				'[accessible]' => [
					'*' => true
				],
				'[dirty]' => [],
				'[original]' => [],
				'[virtual]' => [],
				'[errors]' => [],
				'[invalid]' => [],
				'[repository]' => 'FieldsPosts'
			
			},
			'[new]' => false,
			'[accessible]' => [
				'*' => true
			],
			'[dirty]' => [],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[invalid]' => [],
			'[repository]' => 'Administrator.Fields'
		
		},
]
```

**Comment by markstory** [comment] 2016-03-16 01:10
Closing this issue as the problem was how you were setting up your associations.

**Closed by markstory** 2016-03-16 01:10 UTC
Labels: i18n, On hold

**Comment by konowar** [comment] 2016-03-16 01:14
cakephp translate a joindata of an association?

**Comment by markstory** [comment] 2016-03-16 01:16
@konowar Not unless you declare your `through` relationships and attach TranslateBehavior.

**Comment by konowar** [comment] 2016-03-16 12:01
Sorry, I can not translate the contents of association when it is a belongsToMany

Posts Table
`  $this->belongsToMany('Administrator.Fields', [
                'through' => 'Administrator.FieldsPosts',
                ]);`

Fields Table
` $this->belongsToMany('Administrator.Posts', [
            	'through' => 'Administrator.FieldsPosts']);`

FieldsPosts Table

` $this->addBehavior('Translate', ['fields' => ['value']]);
$this->belongsTo('Administrator.Posts');
	        $this->belongsTo('Administrator.Fields');`

BD FieldsPosts
`ID - field_id - post_id - value - created - modified`

Error:
Fields is not associated with .FieldsPosts_value_translation

**Comment by edouard-claude** [comment] 2016-09-10 06:35
Hello @awilchesl you found a solution to your problem? I'm in the same situation as you.

**Comment by awilchesl** [comment] 2016-09-23 15:30
@edouard-claude Hi, you can fix it as follows:

Bootstrap.php
`    ini_set('intl.default_locale', 'en');`

if you change the locale language is changed. ('fr', 'es', 'en') ETC....

likewise it is changed also in the initialize the appcontroller.php

`I18n::locale('en');`

This will automatically bring the Cake default language according to i18n. only to find that translation will be handled without the need to be consulting translate.

which is the partnership that has to 'METAS'?
