### ISSUE TITLE
3.0 ORM Multiple matching and contain

### ISSUE THREAD

**Issue by Laykou** [cakephp/cakephp#5721] opened 2015-01-23 00:24 UTC
## Observation
I have really weird issue:

```
// Articles BelongsTo Categories
// Articles BelongsTo Colors
$this->Articles
->contain(['Categories', 'Colors'])
->matching('Categories', ...)
->matching('Colors', ...)
```

This will hydrate only the `$article->color` property and the `$article->category` will remain as an array. I've really investigated the Core code. The behavior is that if there is matching/contain on the same alias, the last alias in the `contain` is hydrated. If I would swhich `contain(['Colors', 'Categories'])`, only the `$article->category` would be hydrated.

## Investigation
I'm still not sure how the ORM really works, but this is what I found out:

The `_fetchResult` method should get all the columns of the query and those `matching columns` should already be hydrated: https://github.com/cakephp/cakephp/blob/3.0/src/ORM/ResultSet.php#L325

The hydrated property is passed to the `$row` only if exists in the `$resultMap`:
https://github.com/cakephp/cakephp/blob/3.0/src/ORM/Association/SelectableAssociationTrait.php#L286

As I understand it the `$resultMap` is an array of hydrated `matchings` indexed by their ID. So you basically look up the matching row with the ID that is required by the `contain`. The problem is here  - the `$resultMap` **does not contain such an ID**. Why?

Because here the `$keys` which are used to find associated rows are the same for both contains.
https://github.com/cakephp/cakephp/blob/3.0/src/ORM/EagerLoader.php#L505 as the `$collected` array is indexed by an `$alias` instead of  `$meta->aliasPath()`.
But therefore the unit tests may pass, because in test database both `category` and `color` may have ID=1, so this works.

This also explains why only the last `contain` is hydrated. Because in this `foreach` https://github.com/cakephp/cakephp/blob/3.0/src/ORM/EagerLoader.php#L617 only the last keys are saved to the `$collectKeys`, because they are indexed by `$alias`, which remains the same.

## Solution
Hopefully I understand it right. It took me a while to investigate this, but I might make a mistake. I leave the fixing on you. I'm not that skilled to make a pull request for this.

**Comment by lorenzo** [comment] 2015-02-02 22:54
Closing as there is a PR open

**Closed by lorenzo** 2015-02-02 22:54 UTC
Labels: Defect, ORM

**Comment by hagen00** [comment] 2017-07-26 09:30
@lorenzo I have the same issue as above (or similar), described here as well: https://stackoverflow.com/questions/27288957/cakephp-3-0-multiple-matching-conditions

Essentially I need more than one matching condition. 

```
		$query->matching('Foo', function ($q) use ($search) {
			return $q->where(['Foo.title LIKE' => '%'.$search.'%']);
		});
		
		$query->matching('Bar', function ($q) use ($search) {
			return $q->where(['Bar.title LIKE' => '%'.$search.'%']);
		});
```
(Maybe its relevant, but Foo and Bar both point at the SAME table. i.e. the table in question has two FK's both pointing at the same table, in other words, Foo and Bar have the same className in the Model)

This isn't working.

**Comment by lorenzo** [comment] 2017-07-26 20:19
@hagen00 please open another issue and explain exactly what the problem is.
