### ISSUE TITLE
For time and date only columns, only the respective time/date parts should be displayed

### ISSUE THREAD

**Issue by ndm2** [cakephp/cakephp#6937] opened 2015-07-03 11:43 UTC
When dealing with time and date only columns, one would most probably want to display only the time and date parts, ie when you have `10:30` in a time column, the view should show only `10:30`, and that ideally out of the box, at least I think that would be nice. 

Now since all time related columns are using the `Cake\I18n\Time` class, the values will have a date/time part added, depending on what's missing, and thus one ends up with full date-time strings in the views.

I'm not sure how this would be best solved, otherwise I would have come up with a PR. Maybe with a mixture of bake and core, by adding code to the views like

	$entity->time_only_column->i18nFormat(
		Time::getToTimeStringFormat()
	)

and the appropriate getters/setters in the `Time` class, or maybe in the core only, by introducing additional options for the `Time` class, or even extended classes, so that it would be possible to control the default format of the string representation per instance or per type...

**Comment by lorenzo** [comment] 2015-07-03 11:56
Duplicate of https://github.com/cakephp/cakephp/issues/5939

**Closed by lorenzo** 2015-07-03 11:56 UTC
