### ISSUE TITLE
Email: Mailer not load config from app.php - CakePHP 3.8 -> 4.0.1

### ISSUE THREAD

**Issue by michalfordonski** [cakephp/cakephp#14152] opened 2020-01-10 11:31 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

### What you did
Update CakePHP 3.8 to 4.0.1

### What happened
stream_socket_client(): unable to connect to **tcp://localhost:25** (Connection refused)

### What you expected to happen
Config is ok (3.8 sends an email):
app.php:

'EmailTransport' => [
        'default' => [
            'className' => 'Smtp',
            'host' => '**mail.exampleforissue.pl**',
            'port' => **587**,
            'timeout' => 30,
            'username' => 'mail@exampleforissue.pl',
            'password' => 'secretPassword',
            'client' => null,
            'tls' => null,
        ],
    ],

    'Email' => [
        'default' => [
            'transport' => 'default',
            'from' => 'mail@exampleforissue.pl',
            'charset' => 'utf-8',
            'headerCharset' => 'utf-8',
        ],
    ],

Error if is:
$email = new Email(['from' => 'mail@exampleforissue.pl', 'transport' => 'default']);
and error if is:
$email = new Mailer(['from' => 'mail@exampleforissue.pl', 'transport' => 'default']);

//set to, body, etc.
$email->send();

The configuration just before calling is the same as in the configuration file. Any suggestions?

**Comment by markstory** [comment] 2020-01-10 17:36
Does your application bootstrap read configuration from `EmailTransport` and set it into the TransportFactory? You should have something [like this](https://github.com/cakephp/app/blob/62ed4e3a0a5ceb35d4c770e52b850c96fde19e62/config/bootstrap.php#L161) in your application.

If so, have you tried seeing what comes from `debug(TransportFactory::get('default'))` does? Is the SmtpTransport configured correctly?

**Comment by michalfordonski** [comment] 2020-01-10 23:41
bootstrap.app (Line 161):
TransportFactory::setConfig(Configure::consume('EmailTransport'));

debug(TransportFactory::get('default')): 

object(DebugKit\Mailer\Transport\DebugKitTransport) {
	[protected] originalTransport => object(Cake\Mailer\Transport\SmtpTransport) {
		[protected] _defaultConfig => [
			**'host' => 'localhost',
			'port' => (int) 25,**
			'timeout' => (int) 30,
			'username' => null,
			'password' => null,
			'client' => null,
			'tls' => false,
			'keepAlive' => false
		]
		[protected] _socket => null
		[protected] _content => []
		[protected] _lastResponse => []
		[protected] _config => [
			'host' => 'localhost',
			'port' => (int) 25,
			'timeout' => (int) 30,
			'username' => null,
			'password' => null,
			'client' => null,
			'tls' => null,
			'keepAlive' => false,
			'className' => 'DebugKit.DebugKit',
			'url' => null
		]
		[protected] _configInitialized => true
	}
	[protected] emailLog => object(ArrayObject) {
		
	}
	[protected] _defaultConfig => []
	[protected] _config => []
	[protected] _configInitialized => false
}

**Comment by markstory** [comment] 2020-01-11 02:32
Are you confident your configuration file is being loaded?

**Comment by michalfordonski** [comment] 2020-01-11 22:48
Yes, directly before new Email ():
`dump(Configure::read('Email.'.env('EMAIL_CONFIGURATION', 'default')));`
The values are correct

**Comment by markstory** [comment] 2020-01-12 02:46
If you don't load/disable DebugKit do you still have problems? Otherwise I'm at a loss of how configuration data could be getting lost.

**Comment by markstory** [comment] 2020-01-12 02:52
I tried to reproduce this problem locally and was not able to. My mailer transport had the configuration applied correctly.

**Comment by michalfordonski** [comment] 2020-01-13 07:22
If i don't load/disable DebugKit, i still have problems.

Thanks to your suggestion I found a solution.
The problem is that I created the folder `/src/Repositories`, and in it the `EmailRepo.php` file, which is between my application and the CakePHP framework - in case of changes in CakePHP I only change this file. The problem is that in 3.8: `TransportFactory::getConfig('default')` returned null, and in 4.0.1 it returns the default configuration, and if I want to overwrite, I get the error "Cannot reconfigure existing key default" after commenting on line 91 in the vendor file `/cakephp/cakephp/src/Core/StaticConfigTrait.php` its work. How can I do this without commenting on this line? Is there any method to check the configuration is loaded or to overwrite the configuration?

**Comment by michalfordonski** [comment] 2020-01-13 07:42
OK, i have solution - in my EmailRepo.php:
```
TransportFactory::drop('default');
TransportFactory::setConfig(Configure::consume('EmailTransport'));
```

**Comment by markstory** [comment] 2020-01-13 14:23
Closing as you seem to have figured out your problem.

**Closed by markstory** 2020-01-13 14:23 UTC
Labels: defect, email

**Comment by xavier83ar** [comment] 2020-01-14 17:41
I had the same issue working with cakephp 4, I was changing default `EmailTransport` settings, but those changes were ignored by the framework, then I found what was the problem. 

It is not a bug as such, but in this version you have added by default an `app_local.php` config file, and it has `EmailTransport` settings, so, if someone doesn't notice it and it change `EmailTransport` in `app.php` as we use to, it will get ingnored and the default of app_local will be applied instead. I guess that this should be documented.

**Comment by jimbo2150** [comment] 2020-01-14 17:57
That also explains why I kept getting weird errors about it not being able to connect to the default database.

Should probably either remove the file, empty it with a comment letting devs know what it's for, or add a notice to the Mailer docs.

**Comment by markstory** [comment] 2020-01-14 18:28
The `app_local.php` file is mentioned in the documentation. Is there somewhere else you think it should be called out?

**Comment by xavier83ar** [comment] 2020-01-14 18:35
[Here](https://book.cakephp.org/4/en/core-libraries/email.html#configuration) only mention `app.php` and `app.default.php`, and there is no mention to `app_local.php`.

**Comment by markstory** [comment] 2020-01-14 18:38
Ok. I'll get that cleaned up. There is no need to restate how configuration files work in the Mailer sections.

**Comment by asecondwill** [comment] 2020-07-29 14:10
I'm getting the same problem,  mail is sent, but not using the settings I have set up in app.php.  I don't have an app_local or an app.default (because I upgraded from 3.x ).  If I try to debug with 

````debug(TransportFactory::get('default'))````
I get the expected values.  

Is there anything else I should be checking?

**Comment by asecondwill** [comment] 2020-07-29 15:39
Ok, found I had this line:

````
'EmailTransport' => [
       'default' => [
           'className' => MailTransport::class,
````

which needed to be 
````
'EmailTransport' => [
       'default' => [
           'className' => 'Smtp',
````
