### ISSUE TITLE
input hidden field should convert value 'false' to '0'

### ISSUE THREAD

**Issue by markusramsak** [cakephp/cakephp#5639] opened 2015-01-12 01:44 UTC
```
echo $this->Form->hidden('field', ['value' => false]);
```

should equal

```
echo $this->Form->hidden('field', ['value' => 0]);
```

**Comment by markstory** [comment] 2015-01-12 02:47
Why? False is '' in string form.

**Comment by mdlouhy** [comment] 2015-01-12 11:14
I have a boolean database column which stores the value in a hidden field. when the value is true then 'value="1"' but when value is false then nothing will be added as attribute.

**Comment by markstory** [comment] 2015-01-12 11:22
I would expect inputs with no value attribute to still submit '' though.

**Comment by mdlouhy** [comment] 2015-01-12 11:33
But if input[type="radio"] then false will  be converted to '0'
```
echo $this->Form->input('field', ['type' => 'radio', 'options' => ['1' => 'Yes', '0' => 'No']]);
```
later I just wanna store the value in a hidden field.
```
echo $this->Form->hidden('field'); // value is '' or '1' but expected '0' or '1'
```

**Comment by markstory** [comment] 2015-01-12 16:05
@mdlouhy Ok, but radio options are finite lists that we have to do type coercion to match against, so its a little different from hidden() which works more like text/textarea. My concern with changing hidden, is that it creates an inconsistency with text/textarea.

**Comment by mdlouhy** [comment] 2015-01-12 21:49
Like I mentioned above, it's soooo easy to do this, so everyone can do this for himself if he wants to.
It seems like the current behavior is desired therefore this is not an issue, so I suggest we close this.

**Comment by pcworld** [comment] 2018-06-01 04:28
When a hidden field is created using `$this->Form->hidden('myfield');` and myfield was set to `false`, saving back to the database using `save()` fails, as it seems empty string is not automatically converted back to a boolean. I did not find documentation about this particular behavior and hence would consider it a bug.

**Comment by ttm-tt** [comment] 2020-05-05 09:08
I like to come back to this issue, because a change in 4.x now causes me troubles.

In my database I have a "boolean" column define as TINYINT(1) DEFAULT 0 NOT NULL.
When I store the value false as a hidden field in my form the value is an empty string.
Reading back the value is now converted to NULL. But I can't store NULL in that column.

So, how can I store false in the form?

**Comment by dereuromark** [comment] 2020-05-05 09:14
On such a boolean column CakePHP should always convert empty string to false IMO.
But especially if the column is NOT NULL.
https://github.com/cakephp/cakephp/blob/master/tests/TestCase/Database/Type/BoolTypeTest.php#L163
So this seems to be a regression.

**Comment by ttm-tt** [comment] 2020-05-05 10:14
Maybe, a value of "false", if it exists, should be written as such in the form?

**Comment by ttm-tt** [comment] 2020-05-05 10:18
Why thumbs down? We have true, false, and "not a value". We could write true and false as such (or as 0 and 1) in the form, and a missing value would correspond to "not a value", which translates to NULL in marshal.

**Comment by ttm-tt** [comment] 2020-05-05 10:20
It's similar with strings: an empty string ("") is different from "not a value" (null)

**Comment by ADmad** [comment] 2020-05-05 11:14
> When I store the value false as a hidden field in my form the value is an empty string.

Why are you doing that? Use "0", that's what the input generated by FormHelper has. Empty string in POST data will be marshalled to `null`.

**Closed by ADmad** 2020-05-05 11:14 UTC
Labels: need-more-info

**Comment by ttm-tt** [comment] 2020-05-05 11:28
Nope, the FormHelper generates nothing (not even an empty string) as the value, or I wouldn't have had that problem.

What I do in my form is 
echo $this->Form->control(<table>.<column>, array('type' => 'hidden'));
which produces
<input type="hidden" name="table[column]" id="table-column">
Note: no value specified

**Comment by ADmad** [comment] 2020-05-05 11:32
Okay, please open a new issue. Continuing discussion on half a decade old issue for an older minor isn't nice :)

**Comment by ttm-tt** [comment] 2020-05-05 11:46
Will do.

**Comment by ttm-tt** [comment] 2020-05-05 11:48
And sorry for reusing that bug: it was a good fit for my problem and I wanted to keep the context.
