### ISSUE TITLE
[2.x] CookieComponent problems

### ISSUE THREAD

**Issue by chinpei215** [cakephp/cakephp#11280] opened 2017-10-06 00:57 UTC
This is a bug.

* CakePHP Version: 2.10.3
* Platform and Target: Non-related

This ticket contains multiple problems of 2.x CookieComponent. I am planning to send multiple pull requests to fix them step by step.

### Problems

* [x] Problem 1 - The write() method throws fatal error when replacing scalar with array
* [ ] Problem 2 - The read() method restores original values if cookies have been completely deleted
* [x] Problem 3 - Deleting deep entry doesn't work (As of 2.4.3)
* [ ] Problem 4 - Writing cookie with expiration time for specific entry doesn't work (As of 2.4.3)

### TestsController

```php
class TestsController extends AppController
{
	public $autoRender = false;

	public function read() {
		debug( $this->Cookie->read() );
	}

	public function write() {
		$this->Cookie->write('foo.bar', 'value');
	}

	public function deleteDeepEntry() {
		$this->Cookie->delete('foo.bar');
	}

	public function replaceScalarWithArray() {
		$this->Cookie->write('foo', 1);
		$this->Cookie->write('foo.bar', 2);
	}

	public function readAfterDelete() {
		$this->Cookie->delete('foo');
		debug( $this->Cookie->read() );
	}

	public function writeWithExpirationTime() {
		$this->Cookie->write('foo.baz', 'value', true, '5 second');
	}
}
```

----

### Problem 1

The write() method throws fatal error when replacing scalar with array.

#### Test

1. Access /tests/replaceScalarWithArray

#### Expected

Works.

#### Actual

```
Argument 1 passed to Hash::insert() must be of the type array, integer given, called in ...
```

----

### Problem 2

The read() method restores original values if cookies have been completely deleted.

#### Test

1. Access /tests/write
2. Access /tests/readAfterDelete

#### Expected

```
array()
```

#### Actual

```
array(
	'foo' => array(
		'bar' => 'value'
	)
)
```

----

### Problem 3

Deleting deep entry doesn't work (As of 2.4.3).

#### Test

1. Access /tests/write
2. Access /tests/deleteDeepEntry
3. Access /tests/read

#### Expected

```
array()
```

#### Actual

```
array(
	'foo' => array(
		'bar' => 'value'
	)
)
```

----

### Problem 4

Writing cookie with expiration time for specific entry doesn't work (As of 2.4.3).

#### Test

1. Access /tests/write
2. Access /tests/writeWithExpirationTime
3. Access /tests/read (3 seconds later)
3. Access /tests/read (5 seconds later)

#### Expected

(3 seconds later)
```
array(
	'foo' => array(
		'bar' => 'value',
		'baz' => 'value'
	)
)
```

(5 seconds later)
```
array(
	'foo' => array(
		'bar' => 'value',
	)
)
```

#### Actual

(3 seconds later)
```
array(
	'foo' => array(
		'bar' => 'value',
		'baz' => 'value'
	)
)
```

(5 seconds later)
```
array()
```

----

### Related tickets

#10341

**Comment by ADmad** [comment] 2018-02-17 13:45
@chinpei215 Can this issue be closed?

**Comment by chinpei215** [comment] 2018-02-18 14:27
No.

**Comment by dereuromark** [comment] 2018-03-14 16:08
@chinpei215 We need to find a plan of attack on this one, or we should close this as not reproducable.
Do you have a recommendation what to do?

**Comment by chinpei215** [comment] 2018-03-14 21:25
I am plannning to fix the above problems when I have time. Since we supports 2.x with bug fixes for 12 months after the release of 4.0.0, I think we don't need to close this isseu until the time has come.

**Comment by dereuromark** [comment] 2019-02-15 13:46
> Since we supports 2.x with bug fixes for 12 months after the release of 4.0.0

Not quite true. We mainly support critical bugfixes and security patching.
All minor tweaks are usually out of scope for maintenance mode and should be handled as plugin or project solution instead.

**Comment by chinpei215** [comment] 2019-02-17 16:03
The sentence was almost quoted from the bakery:
https://bakery.cakephp.org/2017/06/23/upcoming-cakephp-roadmap.html#long-term-support-for-2-x
If it was not quite true, then it would mean than our announce was not quite true.

**Comment by dereuromark** [comment] 2019-02-17 16:20
Well, it mainly also means that merging existing PRs would be sth to consider.
But since this is stale for 1.5 years and there seems no big interest in providing a PR, this can also be closed as works-for-me - since no active development is done on 2.x for quite some time now.

**Comment by dereuromark** [comment] 2019-08-21 16:50
Closing then until a PR is provided for further discussion of such a non-critical change.

**Closed by dereuromark** 2019-08-21 16:50 UTC
Labels: component, defect
