### ISSUE TITLE
Method updateAll() with UUID treats id as INT, instead of string

### ISSUE THREAD

**Issue by dickvanlieshout** [cakephp/cakephp#13508] opened 2019-08-13 12:13 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.10
* Platform and Target: MAMP With PHP 7.2.14

### What you did
I want to update multiple rows. Set `$account_id` where `$company_id`.
I used the method `updateAll()`

```php
$account_id = '5d4968d8-8138-4c71-8582-ba21c244f941';
$company_id = 40;
$this->Slip->updateAll(
    ['Slip.account_id' => $account_id],
    ['Slip.company_id' => $company_id]
);            
```

### What happened
The update failed. MySQL returned an error: 
```mysql
Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column '5d4968d8' in 'field list'
```
MySQL Query:
```mysql
UPDATE `slips` AS `Slip`
SET `Slip`.`account_id` = 5d4968d8-8138-4c71-8582-ba21c244f941
WHERE `Slip`.`company_id` = 40
```

### What you expected to happen
The correct query should be:
MySQL Query:
```mysql
UPDATE `slips` AS `Slip`
SET `Slip`.`account_id` = '5d4968d8-8138-4c71-8582-ba21c244f941'
WHERE `Slip`.`company_id` = 40
```

Added single quotes (') to the account_id.

**Comment by dereuromark** [comment] 2019-08-13 12:25
Afaik this is a known issue with strings for the atomic wrappers like updateAll().

**Comment by ADmad** [comment] 2019-08-13 14:30
Duplicate of #2388.

**Closed by ADmad** 2019-08-13 14:30 UTC
