### ISSUE TITLE
AuthComponent thowing RuntimeException when some data is already stored in the session

### ISSUE THREAD

**Issue by okatsuralau** [cakephp/cakephp#10636] opened 2017-05-09 21:02 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: v3.2.14 and v3.4.6
* Platform and Target: Apache web-server, PHP 5.6 and 7.1, Chrome 57

### What you did
I used a component that read the session looking for some key and when I try to use some of the **AuthComponent** methods, an Exception is thrown.

This issue can be replicated easy with the following code:

```php
class UsersController extends AppController
{
        public function login()
        {
            // loaded in some component
            $key = $this->request->session()->read('Auth.User.some_key');

            // ...

            // loaded in the app
            $this->Auth->setUser([
                'id' => 'userId',
                'username' => 'user name'
            ]);

            exit('INDEX');
        }
}
```

I tried to recreate this issue in a unit test for the AuthComponent but it did not work in a CLI environment.

The AuthComponent is configured through the UsersAuthComponent from the **[CakeDC/users](https://github.com/CakeDC/users)** plugin, so my custom component that read the session is always loaded before the AuthComponent.

### What happened
this throws a RuntimeException with the message "Session was already started"

The stack trace shows that the \Cake\Network\Session::renew() method is called when is writing the session data but do not detect the previously started session.

### What you expected to happen
The session storage should be able detect if the session was already started and don't try to create another.

**Comment by markstory** [comment] 2017-05-10 00:11
Are you able to check if the session objects are the same in both places? If the session object gets replaced mid requests this kind of error is possible.

**Comment by okatsuralau** [comment] 2017-05-10 19:05
@markstory, I found no indication that the session object was modified.

However, I was able to resolve the problem by calling the session object in the `startup()` callback of the component instead of calling in the `__contructor()` or the `initialize()` method.

I re-created this experiment (reading some value of the session from a component) in a new CakePHP project and both  `__contructor()` or the `initialize()` methods throw the exception.

**Comment by nocaremc** [comment] 2017-05-29 04:03
I suddenly encountered this after 0 code changes. $SESSION was not empty, and I didn't think to destroy it manually.

I located where my local install saves sessions via the php.ini setting: "session.save_path = 'path'".
I turned off server services and then deleted all of those files and it started working again.

I had a blackout and I suppose it corrupted session files in some weird way.
Hopefully that helps others with this ghost of an issue.

I have php 5.6.25 and cake 3.3.16 if it matters.

**Comment by markstory** [comment] 2017-05-29 17:13
The first few lines of `start()` check if the session had been started though. Are you able to reproduce this issue by calling `session->renew()` in your controllers?

**Comment by nocaremc** [comment] 2017-05-29 19:51
Session->_started is null in start() when Session->started() reports true
So it won't return early, just throw an exception. start() is in fact running twice (verified with error_log()) but I haven't located why.

I haven't been able to get anything running yet without my above patch to renew() or having start() checked started() instead of _started.

**Comment by markstory** [comment] 2017-05-30 01:09
Are you using requestAction or something else that would replace the request or the session object?

I am not against calling started() from start() I just would like to understand how to reproduce this issue.

**Comment by nocaremc** [comment] 2017-05-30 14:25
I don't do much with Session. I have just a handful of read/writes. A few in controller actions. One in a helper function and one in a component's beforeFilter.
I call session->destroy() in my user logout function as well.

These have all existed for a while though. Most recent was the component's and I found removing it didn't matter. I did delete and create a component of the same name about a week ago.

I'll step through with a debugger when I have the extra time.

**Comment by nocaremc** [comment] 2017-05-31 08:16
So @markstory , here is what I have learned.
In components, beforeFilter fires during(after? for?) Controller.initialize event. This didn't matter haha.

In my login function I use AuthComponent::identify() followed with AuthComponent::setUser.
This triggers SessionStorage::Write > Session::renew > Session::write.
I removed that line from my login function as identify served the same purpose.

My AppController::getUser() function calls AuthComponent::identify() to get the user too.
This calls jsoftb\Auth0\Auth\Auth0Authenticate::authenticate()
Then jsoftb\Auth0\Auth\Auth0Authenticate::getUser().
That calls Auth0\SDK\Auth0::getUser(). 
A bunch of hooplah later, Auth0\SDK\Store\SessionStore::set() is called.

SessionStore is instantiated when Auth0\SDK\Auth0 is by Auth0Authenticate::__construct().

Auth0Authtenticate is instantiated in AuthComponent::constructAuthenticate():837 via the AuthComponent::identify() path.

What I found is that the error is caused by calling AppController::request::session::destroy().
$this->Auth->logout() flat out never functioned in my implementation.

I believe that killing the session that way, followed by AuthComponent::Identify() at some point in the page redirection/loading process creates an opportunity for Auth0\SDK\Store\SessionStore to create a session, causing cake to freak out. I wasn't able to trace the exact reason before discovering my new fix, but hopefully it is enough to reproduce and look deeper.

Commenting out AuthComponent::setUser() in my login() and AuthComponent::identify() in getUser() functions fixed my issue.

My experience with xdebug (and ancient parsers) made it pretty useless so I manually traced. How fun.

I'd really like to know if this is an issue to be fixed in the Auth0 SDK, jsoftb\Auth0 or cake itself if possible.

**Comment by ADmad** [comment] 2017-05-31 11:49
> SessionStore is instantiated when Auth0\SDK\Auth0 is by Auth0Authenticate::__construct().

This might be the cause of your problems. Ensure the session storage is configured and started by CakePHP and not an external lib.

**Comment by nocaremc** [comment] 2017-05-31 22:05
That was the Auth0\SDK\Store\SessionStore. I do think it had the opportunity to call session_start after destroying session via my Controller::logout() however. I had these libraries functioning fine for months so it was just bizarre all around.

I have to just move past this for now as I lost a lot of time.

**Comment by markstory** [comment] 2017-07-05 01:38
Closing as a solution was found and multiple libraries vying for control of the session generally ends poorly.

**Closed by markstory** 2017-07-05 01:38 UTC
Labels: auth, Defect, On hold
