### ISSUE TITLE
Cant update associated hasMany data in CakePHP 3, with a dynamically created form fields

### ISSUE THREAD

**Issue by salines** [cakephp/cakephp#9283] opened 2016-08-16 17:23 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3
### What you did
If I create form fields like this:

```
    <?= $this->Form->hidden('questions.0.id'); ?>
    <?= $this->Form->input('questions.0.question'); ?>
    <?= $this->Form->hidden('questions.1.id'); ?>
    <?= $this->Form->input('questions.1.question'); ?>
```

**associated data will be saved (updated).**

**EDIT:**
only 3 associated records can be updated!

But, we have an **unknown number of associated fields**, and we create them in this way:

    <?php
    foreach($job->questions as  $key => $value) { ?>
        <?= $this->Form->hidden(sprintf('questions.%s.id', $key)); ?>
        <?= $this->Form->input(sprintf('questions.%s.question', $key)); ?>
        
    <?php } ?>

In both examples html fields are identical. for some reason we can not save changes if the field is created with a loop.

What to do?

Here is all controller. model code: 

http://discourse.cakephp.org/t/cant-update-associated-hasmany-data-in-cakephp3/705/3?u=salines

**Comment by markstory** [comment] 2016-08-16 18:01
Seems like a duplicate of #9267. We'll be doing a patch release later this week to fix this issue.

**Closed by markstory** 2016-08-16 18:01 UTC
