### ISSUE TITLE
Long column name can break Cake?

### ISSUE THREAD

**Issue by Skillaro** [cakephp/cakephp#8964] opened 2016-06-09 14:30 UTC
This is a (multiple allowed):
* [x] bug

* CakePHP Version: 3.2.5
* Platform and Target: Apache, PostgreSQL

### What you did
I try to use ORM on table with long name having columns with long names. x_x

### Expected Behavior
Idk?. Results?

### Actual Behavior

Error occured
```
Undefined index: 
LongClassNameBlaBla__even_longer_field_name_bla_bla_bla_id 
[CORE\src\Database\FieldTypeConverter.php, line 80]

```

**Comment by jhli** [comment] 2016-06-09 15:33
!xy
Please supply the exact table and fieldname.

**Comment by Skillaro** [comment] 2016-06-09 16:49
e.g. `ProEnvironmentSpecialComments__pro_environment_special_comment_type_id`

Its like when string length is more than 64 characters after Cake make an alias it break every time.

**Comment by ndm2** [comment] 2016-06-09 17:30
Sounds like you're exceeding `NAMEDATALEN`. If you inspect the value of `$row` in `FieldTypeConverter::__invoke()`, you'll probably see truncated names like `ProEnvironmentSpecialComments__pro_environment_special_comment_`

https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

**Comment by Skillaro** [comment] 2016-06-09 17:36
But Cake is returning some data but wrong, Cake takes created and modified fields one level up.
` pro_environment_special_comment_type_id =  created`
and modified is empty.

**Comment by jhli** [comment] 2016-06-09 18:17
Could we throw exceptions per adaper?

**Comment by markstory** [comment] 2016-06-09 22:08
Duplicate of #6631

**Closed by markstory** 2016-06-09 22:08 UTC
