### ISSUE TITLE
Prepared statements combined with subqueries results in wrong params

### ISSUE THREAD

**Issue by boindil** [cakephp/cakephp#8425] opened 2016-03-08 15:46 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.4
* Platform and Target: apache 2.4 / nginx / mariadb 5.5

### What you did
I have 2 nice subqueries build with standard `$table->find()` and a main query built with `$table->find()`.

I have multiple conditions in subqueries 1 and 2 (each one has two arguments). I have three conditions in my main query.

The subqueries are used in `$maintable->select()`.

### Expected Behavior
Query created like this:
```
SELECT ... subquery1 (with :c0, :c1) ... subquery2 (with :c2, :c3) ... WHERE _mainconditions_ (with :c4, :c5, :c6)
```

### Actual Behavior
Query created like this:
```
SELECT ... subquery1 (with :c0, :c1) ... subquery2 (with :c0, :c1) ... WHERE _mainconditions_ (with :c0, :c1, :c2)
```
c0, c1 and c2 are filled with the main conditions, while the subquery conditions are ignored

**Comment by lorenzo** [comment] 2016-03-08 23:25
What are you using bind() for anyway? :)

**Comment by markstory** [comment] 2016-03-09 01:36
How can someone reproduce this issue?  Is there a small bit of code that reproduces the issue?

**Comment by boindil** [comment] 2016-03-09 01:47
> What are you using bind() for anyway? :)
Well I didn't plan on using bind() in the first place. bind() is only the workaround for this problem.

@markstory I'll add some code tomorrow, gotta get some sleep now :)

**Comment by boindil** [comment] 2016-03-09 13:05
Hi,
here's my example

```
$subquery1 = $this->MyTables->find()
	->contain(['OtherTable'])
	->select([
		'date'
	])
	->where([
		'OtherTable.column1' => 'condition1',
		'MyTables.column2' => 'condition2',
		'MyTables.primaryKey = MyTablesNeatAlias.primaryKey'
	]);

$subquery2 = $this->MyTables->find()
	->contain(['OtherTable'])
	->select([
		'date'
	])
	->where([
		'OtherTable.column1' => 'condition3',
		'MyTables.column2' => 'condition4',
		'MyTables.primaryKey = MyTablesNeatAlias.primaryKey'
	]);

$mainquery = $this->MyTablesNeatAlias->find()
	->select([
		'MyTablesNeatAlias.column',
		'duration' => 'ROUND(ABS(UNIX_TIMESTAMP(IFNULL((' . $subquery1 . '), DATE_FORMAT(NOW(), "%Y-%m-%d"))) - UNIX_TIMESTAMP((' . $subquery2 . '))))'
	])
	->distinct()
	->where([
		'MyTablesNeatAlias.column3' => 'condition5',
		'MyTablesNeatAlias.column4 NOT LIKE' => 'condition6',
		'MyTablesNeatAlias.column5' => 'condition7'
	])
	->having([
		'NOT' => [
			'duration IS' => NULL
		]
	])->all();
```

I'm migrating a plain SQL query to cake style. Yes I know the possibility to execute plain SQL exists, but I would like not to to that.

While rewriting I needed the subqueries with their conditions, but they were ignored when combining everything.
@lorenzo I ended up using `bind()` as you noticed from my other opened issue to solve this problem, but of course its not the nice/right way to do this.

**Comment by ionas** [comment] 2016-03-09 13:20
Two suggestions:
* You want to setup multiple associations, those should setup aliases correctly. AFAIK you can even setup associations on the fly.
* You can use `->from('aliasname' => 'tablename')` explicitly in your sub-query building to circumvent alias collisions.
Hit me if I am wrong on any of those. Also you are welcome to join IRC for discussing implementation questions on Freenode IRC.

**Comment by boindil** [comment] 2016-03-09 21:46
> You can use `->from('aliasname' => 'tablename')` explicitly in your sub-query building to circumvent alias collisions.

You're right on that, but I'm not sure how this helps on the params. This would fit more on #8427 I think - or am I missing something right now?

**Comment by markstory** [comment] 2016-03-09 22:55
This will likely never work, as the string cast of query object will never be able to know that it is being added to another query. If you wanted to use the query builder, you'd need to make that subtraction expression out of objects. That would have a better chance of working as the value binders might share state.

**Comment by lorenzo** [comment] 2016-03-09 23:14
I'm closing this ticket since the code you posted will never work. Please join us in the IRC channel so we can guide you.

**Closed by lorenzo** 2016-03-09 23:14 UTC
Labels: On hold, ORM

**Comment by jhli** [comment] 2016-03-09 23:28
@ boindil - yes i mixed it up, it is an answer to your other ticket!
