### ISSUE TITLE
FileEngine compression option

### ISSUE THREAD

**Issue by Erwane** [cakephp/cakephp#12264] opened 2018-06-19 09:38 UTC
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

Issue for FileEngine compression.
I will attach PullRequest

### What you did
add new compression options for Cache FileEngine based on gzcompress

### What happened
Cache files are smaller ;)

**Comment by markstory** [comment] 2018-06-19 14:17
Closing as a duplicate of #11563

**Closed by markstory** 2018-06-19 14:17 UTC
Labels: Enhancement, cache
