### ISSUE TITLE
Entity data passed through an event returns notice when accessed but data is present

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#14482] opened 2020-04-21 07:49 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.x
* Platform and Target: Win 10, php 7.4

### What you did

Created a test (put the code below in EventTest.php) to to show the problem we came accross in our app:

The issue is that when passing an entity to the event it gets converted to an array, so far so good. But when you try to access it as an array, you get a undefined index notice.

![image](https://user-images.githubusercontent.com/162789/79839971-8dd3ab00-83b5-11ea-84b7-86e64eeb1029.png)

Remove the dd() to get to this point. If you run the code as shown below, you'll see it checks if the author is emtpy and if it is, it will do the dd() - OK now check the output...

![image](https://user-images.githubusercontent.com/162789/79839599-07b76480-83b5-11ea-9dc1-218ac630dfc1.png)

I think this is actually not an issue of the event but the convenient but prone to failure "magic" of the internals of the entity object. Maybe it is also a php bug because $data is a real array and author still an object implementing array access.

```php
    public function testPassingEntityThroughEventBehavior()
    {
        $manager = EventManager::instance();
        $articles = TableRegistry::getTableLocator()->get('Articles');
        $articles->belongsTo('Authors');
        $article = $articles->find()
            ->contain([
                'Authors'
            ])
            ->first();

        $manager->on('TestEntity', function ($event) {
            $data = $event->getData();

            if (empty($data['author'])) {
                dd($data);
            }

            echo $data['author']['name'];
        });

        $manager->dispatch(new Event('TestEntity', null, $article));
    }
```

### What happened
Getting a notice for an undefined array index but the data is clearly there.

### What you expected to happen
No notice.

**Comment by othercorey** [comment] 2020-04-21 09:57
If the event data implements `ArrayAccess`, we could skip the conversion to array in the constructor and `getData()` method.

**Comment by dereuromark** [comment] 2020-04-21 10:30
This looks like a PHP issue of not being able to traverse through a mix of array and ArrayAccess.
So @othercorey s solution sounds like a good idea to me if that solves it.

**Comment by ADmad** [comment] 2020-04-21 11:15
I can't reproduce this issue with plain PHP https://3v4l.org/obeOH.

**Comment by dereuromark** [comment] 2020-04-21 11:21
@ADmad That is because you are not using mixed array and ArrayAccess. The bug only exists for this specific case, and because the event is casting to array, but only the root element is effected, not recursive.

**Comment by ADmad** [comment] 2020-04-21 11:27
The output @burzum has shown for `dd($data`) looks like an entity. How's that possible when `Event` type casts the data to array?

**Comment by dereuromark** [comment] 2020-04-21 11:28
See https://github.com/cakephp/cakephp/pull/14486/files#diff-42cb97d525e4ec9ac5220bb2bcdec113R88

**Comment by ADmad** [comment] 2020-04-21 11:35
The ArrayAccess / array mangling is a bit different between 4.x and 3.x.

Anyway the issue occurs due to typecasting of `Entity` instance to array. That's what gives the weird array with keys like `*_properties` etc.

**Comment by ndm2** [comment] 2020-04-21 11:50
FYI, an array cast on an object will use its property names as array indices, where public property names are used as is, protected properties are being prefixed with a `*`, and private properties are being prefixed with the fully qualified class name. Also the prefixes are surrounded by null bytes 😄 

https://3v4l.org/k0igK

**Comment by othercorey** [comment] 2020-04-22 03:09
@burzum Event data is required to be an array. You'll have to wrap the entity in an array like `['entity' => $entity]`

**Comment by othercorey** [comment] 2020-04-22 06:33
Added to 5.0 roadmap

**Comment by othercorey** [comment] 2020-04-27 17:05
Closing with above work-around. It's not something we can change in the interface at the moment.

**Closed by othercorey** 2020-04-27 17:05 UTC
Labels: events
