### ISSUE TITLE
Get multiple welcome message on console with sub command

### ISSUE THREAD

**Issue by Zehir** [cakephp/cakephp#8649] opened 2016-04-14 14:18 UTC
This is a (multiple allowed):
* [x] bug (a little one)
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.7
* Platform and Target: 
  * Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-85-generic x86_64)
  * PHP: 7.0.5-2+deb.sury.org~trusty+1

### What you did
The example: http://book.cakephp.org/3.0/en/console-and-shells.html
The part on sub command (sound)

Source for `src/Shell/HelloShell.php`
```php
namespace App\Shell;

use Cake\Console\Shell;

class HelloShell extends Shell
{
    public $tasks = ['World'];

    public function main()
    {
        $this->out('Hello world from shell.');
    }

    public function getOptionParser()
    {
        $parser = parent::getOptionParser();
        $parser->addSubcommand('world', [
            'help' => 'Execute The Hello Task.'
        ]);
        return $parser;
    }
}
```
Source for `src/Shell/Task/WorldTask.php`
```php
namespace App\Shell\Task;

use Cake\Console\Shell;

class WorldTask extends Shell
{
    public function main()
    {
        $this->out('Hello from world task');
    }
}
```
### Expected Behavior
With the command: `/path/to/cakephp/bin/cake hello world`
```bash
Welcome to CakePHP v3.2.7 Console
---------------------------------------------------------------
App : src
Path: /path/to/cakephp/src/
PHP : 7.0.5-2+deb.sury.org~trusty+1
---------------------------------------------------------------
Hello from world task
```
### Actual Behavior
```bash

Welcome to CakePHP v3.2.7 Console
---------------------------------------------------------------
App : src
Path: /path/to/cakephp/src/
PHP : 7.0.5-2+deb.sury.org~trusty+1
---------------------------------------------------------------

Welcome to CakePHP v3.2.7 Console
---------------------------------------------------------------
App : src
Path: /path/to/cakephp/src/
PHP : 7.0.5-2+deb.sury.org~trusty+1
---------------------------------------------------------------
Hello from world task

```
So, I get 2 times the welcome message when running a sub command and a extra blank line before each welcome message.
I think that the problem is in file `vendor/cakephp/cakephp/src/Console/Shell.php` line 440-450

```php
if ($isMethod && isset($subcommands[$command])) {
    $this->startup();
    return call_user_func_array([$this, $method], $this->args);
}

if ($this->hasTask($command) && isset($subcommands[$command])) {
    $this->startup();
    array_shift($argv);
    return $this->{$method}->runCommand($argv, false);
}
```
When I remove the second `$this->startup();` just before array_shift I get only one welcome message.
The first extra line is added line 238 in function _welcome so maby this is expected to happend. Maybe you can remplace the empty line by `$this->hr();` to get dash line instead of blank line

Thank for your work

**Comment by markstory** [comment] 2016-04-14 16:08
Duplicate of #8600. Fixed in #8609

**Closed by markstory** 2016-04-14 16:08 UTC
