### ISSUE TITLE
PaginatorHelper removes param "page" in links to the first page

### ISSUE THREAD

**Issue by berarma** [cakephp/cakephp#17163] opened 2023-06-21 09:48 UTC
### Description

I need links to the first page to always have the parameter "page" but PaginatorHelper removes it whenever page=1. So links to the first page never have the page parameter.

The behavior I'm after is that when there's no page parameter, the last page visited is rendered. But there's no way to do it without overriding the PaginatorHelper.

I think PaginatorHelper should be a bit more flexible and allow us to choose to remove "page=1" in the links it creates or not.

I don't foresee a problem if the default were to never remove the parameter "page=1" for links to the first page.

Thanks

### CakePHP Version

4.4.11

**Comment by markstory** [comment] 2023-06-21 18:22
> The behavior I'm after is that when there's no page parameter, the last page visited is rendered. But there's no way to do it without overriding the PaginatorHelper.

Yep, you'll need to make a custom PaginatorHelper for this.

> I don't foresee a problem if the default were to never remove the parameter "page=1" for links to the first page.

The issue is that CakePHP will be generating two different URLs for the same 'page' and in the past that would create SEO penalties.

**Comment by berarma** [comment] 2023-06-21 18:43
> > I don't foresee a problem if the default were to never remove the parameter "page=1" for links to the first page.
> 
> The issue is that CakePHP will be generating two different URLs for the same 'page' and in the past that would create SEO penalties.

The way modern web indexers work, wouldn't they just find both URLs even when not linking them? I'm not sure if that would cause a SEO problem though.

Any solution that provided some flexibility would be enough.

**Comment by markstory** [comment] 2023-06-22 15:35
> The way modern web indexers work, wouldn't they just find both URLs even when not linking them? I'm not sure if that would cause a SEO problem though.

I'm not sure, I'm not well versed in how these systems work, but I'm not interested in taking a risk and having to deal with additional issues about a change in behavior in the future.

> Any solution that provided some flexibility would be enough.

You can subclass the Paginator helper.

**Comment by dereuromark** [comment] 2023-12-05 20:45
No, web indexers only find one (without) because thats the only one linked to (from the framework generated URLs).
If you manually link to the other version(s), thats on you.
However, even if you did, you can easily use canonical URL setup in your head as meta tags to always tell the indexers which is the primary one.

Closing then as this is a non-core issue.

**Closed as completed by dereuromark** 2023-12-05 20:45 UTC
Labels: enhancement
