### ISSUE TITLE
Remove "Welcome to Cake..." banner for cake console commands.

### ISSUE THREAD

**Issue by notoriousturtle** [cakephp/cakephp#10870] opened 2017-07-06 06:32 UTC
* [x] enhancement

* CakePHP Version: 3.3.7
* Platform and Target: 7.0.18-0ubuntu0.16.04.1

### What you did
Ran `bin/cake`

### What happened

Output:
```
Welcome to CakePHP v3.3.7 Console
---------------------------------------------------------------
App : src
Path: /var/www/vhosts/xxxxx/htdocs/src/
PHP : 7.0.18-0ubuntu0.16.04.1
---------------------------------------------------------------
```

This banner makes working with the console a bit dirty, as it is output with each command.

### What you expected to happen
Can we save this output for `bin/cake version` output? Or for a special `info` command option?

**Comment by slince** [comment] 2017-07-06 06:58
I agree with this. The description should be removed.

**Comment by slince** [comment] 2017-07-06 07:07
The shell library of cake is too tasteless. I think the it should be re-implemented, see  [symfony/console](https://github.com/symfony/console);

**Comment by josegonzalez** [comment] 2017-07-06 07:18
@notoriousturtle seems reasonable to me, though I think you can currently override a method to remove this from your own shells.

> The shell library of cake is too tasteless. I think the it should be re-implemented, see symfony/console;

@slince This sort of feedback isn't very useful as there isn't a list of changes/enhancements that we can act upon. Do you have specific feedback that we can work with?

**Comment by robertpustulka** [comment] 2017-07-06 07:20
@slince see #10716

**Comment by slince** [comment] 2017-07-06 07:45
@josegonzalez 

- Support for custom route for the command.
The command like  './cake foo_bar_baz foo_bar' lacks beauty.

- Increase flexibility
The library helped the developer do too much
```
$this->createFile('bower.json', $stuff);
```
I cannot replace the default  prompt if the target file exists. Perhaps this right should be given to the developer

- Remove the prefix "_" 
```
$this->_io->out('foo');
```


- If I execute a nonexistent command, the output will make me wonder.

```bash
>cake user_binding non_exists

Welcome to CakePHP v3.4.9 Console
---------------------------------------------------------------
App : src
Path: C:\www\slshop\src\
PHP : 5.6.19
---------------------------------------------------------------
Usage:
cake user_binding [-h] [-q] [-v]

Options:

--help, -h     Display this help.
--quiet, -q    Enable quiet output.
--verbose, -v  Enable verbose output.
```
You know, I need an accurate tip. like git.
```
>git commmit
git: 'commmit' is not a git command. See 'git --help'.

Did you mean this?
        commit
```

**Comment by dakota** [comment] 2017-07-06 07:46
Please don't remove the default welcome message. It's a good indicator to beginners that their shell is working, and gives important environment information. Perhaps the better solution is to include how to remove it in the documentation?

**Comment by dakota** [comment] 2017-07-06 07:50
@slince 

> Support for custom route for the command
Already exists, just not documented in the book (https://api.cakephp.org/3.4/class-Cake.Console.ShellDispatcher.html#_alias)

> Increase flexibility
CakePHP doesn't force you to use any thing, you can create your own custom prompt if you want

> Remove the prefix "_"
The prefix is part of the CakePHP coding standards for protected properties.

> If I execute a nonexistent command, the output will make me wonder.
You need to create the correct options/help using https://book.cakephp.org/3.0/en/console-and-shells.html#configuring-options-and-generating-help
CakePHP can't guess what you mean :)

> You know, I need an accurate tip. like git.
Open a Pull Request :)

**Comment by notoriousturtle** [comment] 2017-07-06 08:16
> Please don't remove the default welcome message. It's a good indicator to beginners that their shell is working, and gives important environment information. Perhaps the better solution is to include how to remove it in the documentation?

@dakota include it in `bin/cake version`. Outputting this banner on each command makes reviewing output difficult, and just plain dirty. Most products do not output a banner like this on each command.

**Comment by dereuromark** [comment] 2017-07-06 08:20
With the version shell thing now available everywhere that verbose block could indeed be a bit overkill now.
We could keep it for the default `bin/cake` (which is what people use to check if console works) as long as no shell or shell action is invoked yet for example :)

**Comment by slince** [comment] 2017-07-06 08:26
@dakota 

> Already exists, just not documented in the book

Any basic usage? I cannot find it in the cookbook.

>CakePHP doesn't force you to use any thing, you can create your own custom prompt if you want

How to change default prompt of the method `$this->createFile` ?

>  The prefix is part of the CakePHP coding standards for protected properties.

The coding standard should be advancing with the times. You know psr does not encourage this

> You need to create the correct options/help using...

Sorry i cannot write any help message for an non-exists command. I think shell dispatcher should throw exception or display a friendly message.

**Comment by dereuromark** [comment] 2017-07-06 08:28
@slince Please do not hijack tickets again for your own agenda and topics completely unrelated to the issue mentioned here.
This is disrespectul towards that person and the community as it shifts the focus completely away, making the actual discussion disappearing between your off-topic discussion :/

**Comment by dakota** [comment] 2017-07-06 08:44
@slince - Last comment on this to stop the hijack, but I need to respond to you.

1. Like I said, it's not documented in the book. Follow what the API says. When you've figured it out, I hope we'll see a PR from your to document it.
2. You can't change the default prompt of `createFile()`, but you can write you own. Again, please open a PR if you'd like to see this.
3. The coding standard does advance with the times. Unfortunately, you can't just got and rename all properties and methods and expect to keep BC.
4. Like I said, open a PR

**Comment by dakota** [comment] 2017-07-06 08:45
Back to topic.

@notoriousturtle It's very simple to replace the banner with your own one if you want to :)

**Comment by robertpustulka** [comment] 2017-07-06 08:47
I'm with @dereuromark on this. The banner  could be displayed on `bin/cake` only or `help` command only.

**Comment by notoriousturtle** [comment] 2017-07-06 08:48
> It's very simple to replace the banner with your own one if you want to :)

@dakota yeah, I understand that, but in all I honestly think this is going to be better for the end user if its moved to `bin/cake`, `version`, or say an `info` parameter. Cleaner to use :)

**Comment by notoriousturtle** [comment] 2017-07-06 08:54
> Please don't remove the default welcome message.
@dakota ah, its worth mentioning, I may have interpreted this wrong. Either you meant leave it in every `cake` command output, or just in `cake` somewhere (e.g. no parameters as suggested by @dereuromark). The latter of which I agree with.

**Comment by slince** [comment] 2017-07-06 09:06
@dereuromark  @dakota 


Sorry,  the issue is about the shell.  so i did not create a new issue.

Just my personal opinion。。。

**Comment by ionas** [comment] 2017-07-06 10:37
As for the original PR I think a `--no-welcome` would do?

**Comment by dereuromark** [comment] 2017-07-06 10:40
@ionas Dont add any more non functional arguments :) We already discussed a viable solution above IMO.

**Comment by ionas** [comment] 2017-07-06 10:41
That's what you say but I am with dakota that it shows version and path. However I can live with both easily (V) :)

**Comment by notoriousturtle** [comment] 2017-07-06 10:42
@ionas look at the proposed solution. `bin/cake` to output this. You do not need it in every command.

**Comment by dereuromark** [comment] 2017-07-06 10:46
@notoriousturtle Are you able to make PR with the suggestion change? That might solve this the quickest way :)

**Comment by markstory** [comment] 2017-07-06 15:31
I'm ok with removing the default welcome message from all userland/core shells and only leaving it on the default `bin/cake --help` which is what (`bin/cake` resolves to).

**Comment by saeideng** [comment] 2017-07-06 20:04
extra label/message **must** remove from userland code
but for core shells that can be remove when `config.debug is false`  and remain when `config.debug is true`

**Comment by dereuromark** [comment] 2017-07-06 21:16
@saeideng Why the different behavior here? Just doing what @markstory just confirmed should be enough.

**Comment by saeideng** [comment] 2017-07-06 21:25
> Please don't remove the default welcome message. It's a good indicator to beginners that their shell is working, and gives important environment information.

**Comment by saeideng** [comment] 2017-07-06 21:29
we using core shells just during  develop , not for product time

**Comment by markstory** [comment] 2017-07-06 23:50
@saeideng I think it will be simpler if the welcome message is removed from all shells other than help. This will make the behaviour consistent and predictable. Is anyone able to put together a pull request for this?

**Comment by notoriousturtle** [comment] 2017-07-07 12:24
@markstory @dereuromark I'll look into in the next couple days.

**Comment by dereuromark** [comment] 2017-07-10 11:50
Resolved with https://github.com/cakephp/cakephp/pull/10879
Thanks for all the contribution and feedback!

**Closed by dereuromark** 2017-07-10 11:50 UTC
Labels: console, Enhancement
