### ISSUE TITLE
Use cake 3.x ORM on Cake 2.x project

### ISSUE THREAD

**Issue by backstageel** [cakephp/cakephp#7072] opened 2015-07-20 15:56 UTC
I have a huge Cakephp project with almost 200 tables using cake 2.x. I want to do gradual upgrade to cake 3.x, so i want that some models use cake 3 ORM while others still use cake2.x models.

Is it possible to work like this? if so, is there any tutorial on how to do this?

Thanks in advance

**Comment by markstory** [comment] 2015-07-20 16:32
Duplicate of cakephp/orm#2

**Closed by markstory** 2015-07-20 16:32 UTC
