### ISSUE TITLE
ORM: Unexpected behavior with 'WHERE NOT IN' and empty array

### ISSUE THREAD

**Issue by chinpei215** [cakephp/cakephp#7092] opened 2015-07-22 12:47 UTC
```php
$articles->find()->where(function($exp,$q){
    return $exp->notIn('id', []);
});

# WHERE 1 != 1
```
So this query returns no rows.
This may be a feature, but this is the opposite of what I expected.

In CakePHP 2.x:
```php
$Article->find('all', [
	'conditions' => [
		'id !=' => [],
	]
]);

# WHERE `id` IS NOT NULL
```

In http://www.doctrine-project.org/jira/browse/DDC-3063 , they are talking about a same issue.

**Comment by markstory** [comment] 2015-07-22 15:54
Are you expecting that `notIn('id', [])` would generate `id IS NOT NULL`? We could also generate `WHERE 1 = 1` I guess as is a similar expression in many cases.

**Comment by chinpei215** [comment] 2015-07-22 16:41
I think that it would be better to generate <code>WHERE 1 = 1</code>.

**Comment by lorenzo** [comment] 2015-07-22 20:20
:-1: this is by design. Imagine using 1=1 on a delete query when you fail to validate or have a typo in a variable name. A SQL error is much more desirable for me than losing data

**Comment by markstory** [comment] 2015-07-22 21:56
I am not very comfortable with the ORM generating `WHERE 1=1` clauses on what can very easily be a typo/mistake.

**Comment by chinpei215** [comment] 2015-07-22 23:56
If so, I think that you should throw an exception. <code>WHERE 1 != 1</code> isn't a SQL error:
```php
$subQuery = $articles->find()->select(['id'])->where([
	'something NOT IN' => [],
]);
$query = $comments->query()->delete()->where([
	'article_id NOT IN' => $subQuery,
]);
```

**Comment by markstory** [comment] 2015-07-23 01:53
In the sub-query case I don't think you'd ever end up with `1 != 1` though.

**Comment by dereuromark** [comment] 2015-07-23 08:56
Sounds to me we should go the 2.x way here and output `WHERE `id` IS NOT NULL`.

**Comment by AD7six** [comment] 2015-07-23 09:09
> WHERE 1 != 1 isn't a SQL error:

I don't think that's what was meant. It's a clause guaranteed to return 0 rows. It's also, should you find it in your query log, an indicator of doing something wrong (why am I getting this clause? oh, there's a typo on that variable name generating an empty array etc.).

**Comment by AD7six** [comment] 2015-07-23 09:10
> Sounds to me we should go the 2.x way here and output WHERE id IS NOT NULL.

I disagree, as that's almost always equivalent to putting no clause at all.

**Comment by dereuromark** [comment] 2015-07-23 09:16
@AD7six Would it make sense to upgrade 2.x then to whatever is the solution here to have those behave similar here?

**Comment by chinpei215** [comment] 2015-07-23 12:37
@markstory
The example shown in my previous comment, that will delete all records.
Because it generates a query like this:
```sql
DELETE FROM comments WHERE article_id NOT IN (
  SELECT id FROM articles WHERE 1 != 1 
)
```
But it might not be a good example.

What do you think about this ?
```php
$articles->find()->where([ 
	'id NOT IN' => [],
]);
# WHERE 1 != 1

$articles->find()->where([ 
	'NOT' => [ 
		'id IN' => [],
	]
]);
# WHERE NOT (1 != 1)
```
We expect that <code>expr NOT IN (value,...)</code> is the same as <code>NOT (expr IN (value,...))</code>.
( Source: http://dev.mysql.com/doc/refman/5.6/en/comparison-operators.html#function_not-in )

However the two are not the same at this time in cakephp3.
@lorenzo taught me the reason why it generates <code>WHERE 1 != 1</code>.
 Now I understood the intention. But then, I think that is not safe to generate <code>WHERE 1 != 1</code> because of the above example. Executing <code>DELETE FROM articles WHERE NOT (1 != 1)</code>, all articles will be deleted.
I would like to get an exception.

@AD7six
So I said "I think that you should throw an exception. WHERE 1 != 1 isn't a SQL error".
Do you get what I want to say? I apologize to you for my lack of words.

**Comment by markstory** [comment] 2015-11-03 01:53
Closing as a pull request is up now.

**Closed by markstory** 2015-11-03 01:53 UTC
