### ISSUE TITLE
Flash messages not shown.

### ISSUE THREAD

**Issue by ericfri** [cakephp/cakephp#11701] opened 2018-02-07 01:20 UTC
This is a bug:

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.11
* Platform and Target: Apache 2.4.29 on cPanel, PHP 7.1.13, MariaDB 10.1.30

### What you did
Tried to display Flash messages. These used to work correctly with previous versions.
```
public function generateReports($repairshopr_id) {
	$this->autoRender = false;
	$this->loadModel('Employees');
	$this->Flash->set("Regenerating Reports");

	$user = $this->Employees->getUserFromRepairshoprId($repairshopr_id);
	if (!$this->Tickets->generateTodos($repairshopr_id)) {
		$this->Flash->error("No To-Dos to generate for " . $user['name']);
	}
	if (!$this->Tickets->generateReplies($repairshopr_id)) {
		$this->Flash->error("No Customer Replies to generate for " . $user['name']);
	}
	$this->Tickets->generateTimesheet($repairshopr_id);
	$this->redirect(['controller' => 'Tickets', 'action' => 'index']);
}
```

### What happened
Everything in the above function works as expected, with the exception of the flash messages. The page loads, generates the data requested and redirects, but no messages are displayed. Previous versions of CakePHP would show all the messages.

### What you expected to happen
Flash messages should be shown

One other note, flash messages are working on some of my other pages. I don't know what's different between them regarding the messages. For example, this works:

```
public function login() {
	if ($this->request->is('post')) {
		$myIp = $_SERVER['REMOTE_ADDR'];
		if (!$this->RBruteForce->isIpBanned($this->bruteForceOptions) || in_array($myIp, $this->ipsAllowed)) {
			$employee = $this->Auth->identify();
			if ($employee) {
				$this->Auth->setUser($employee);
				return $this->redirect($this->Auth->redirectUrl());
			}
			$this->RBruteForce->check($this->bruteForceOptions);
			$this->Flash->error(__('Invalid username or password, try again'));
		} else {
			$this->Flash->error(__("Please, wait {$this->bruteForceOptions['expire']} to try login again!"));
		}
	} else {
		if ($this->RBruteForce->isIpBanned($this->bruteForceOptions)) {
			$this->Flash->error(__("Please, wait {$this->bruteForceOptions['expire']} to try login again!"));
		}
	}
}
```

**Comment by markstory** [comment] 2018-02-07 02:04
How can someone reproduce the issue you're having. It sounds like flash messages are working for you in some controller actions which to me suggests they are not broken. Perhaps you are not displaying the messages?

**Comment by markstory** [comment] 2018-02-07 14:46
Ok. I am not able to reproduce flash messages not working in 3.5.11. I have a few apps using that version and they all display flash messages just fine. Let us know when you're able to track down what's causing flash messages to sometimes work.

**Comment by dereuromark** [comment] 2018-02-07 14:55
You should also show your layout template code for displaying them - and also how you load the helpers, maybe.
That sounds more like a user-dev problem and less like a core bug.

**Comment by dereuromark** [comment] 2018-02-07 14:56
Note that you got one `$this->Flash->set()` call, which should ideally also be a real typed method name (success, error, ...). Maybe that plays into it for you? Since this could call a different template, or is stored differently in the session?

**Comment by ericfri** [comment] 2018-02-08 03:13
I've been trying to setup a server on my local machine to do some more testing, but haven't finished yet. Maybe one of my other composer dependencies updated at the same time and that's what caused the issue.

As for the template code, here is a snippet:
```
<nav>
  // navbar related stuff here
</nav>
<?= $this->Flash->render() ?>
<div class="container-fluid">
  <?= $this->fetch('content') ?>
</div>
```

I will try changing `set()` to `info()` or something else and see if it works.

Could it be related to the fact that I'm using the database for my sessions?

**Comment by ericfri** [comment] 2018-02-09 01:33
So I've been doing some digging into the Composer versions.

My working config was with CakePHP 3.5.10, and it broke with 3.5.11. However, there was an additional 56 libraries that have changed or been added between the two. So I'm going to specify my versions a little more statically and update them a couple at a time to see where it breaks.

**Comment by dereuromark** [comment] 2018-02-10 13:18
Your feedback leads be to believe this cannot be core related then, as you can see from the changes, that there were none in regards to flash: https://github.com/cakephp/cakephp/compare/3.5.10...3.5.11
Please see if your other libraries are the cause, and report back if you can find a reproducible core issue here.
Closing then.

**Closed by dereuromark** 2018-02-10 13:18 UTC
Labels: Defect, On hold

**Comment by ericfri** [comment] 2018-02-10 19:18
I still think it was, as my personal list of dependencies is quite small. The rest of them are (I assume) core dependencies from Cake itself.

Here is a list of what changed

Working config:

```cakephp/cakephp                            3.5.10                The CakePHP framework
cakephp/chronos                            1.1.3                 A simple API extension for DateTime.
cakephp/debug_kit                          3.11.6                CakePHP Debug Kit
composer/composer                          1.6.2                 Composer helps you declare, manage and install dependencies of PHP projects, ensuring you have the right stack every...
composer/spdx-licenses                     1.2.0                 SPDX licenses list and validation library.
doctrine/inflector                         v1.1.0                Common String Manipulations with regard to casing and singular/plural rules.
educoder/pest                              1.0.0                 A proper REST client for PHP.
erusev/parsedown                           1.6.4                 Parser for Markdown.
evenement/evenement                        v2.1.0                Événement is a very simple event dispatching library for PHP
firebase/php-jwt                           v5.0.0                A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform to the current spec.
friendsofcake/bootstrap-ui                 1.2.1                 Twitter Bootstrap 3 support for CakePHP 3
google/apiclient                           v2.2.1                Client library for Google APIs
google/apiclient-services                  v0.41                 Client library for Google APIs
google/auth                                v1.2.0                Google Auth Library for PHP
greenfieldtech-nirs/phpari                 dev-release-3 54cfc8b A PHP Class Library for Asterisk ARI
guzzlehttp/guzzle                          6.3.0                 Guzzle is a PHP HTTP client library
guzzlehttp/promises                        v1.3.1                Guzzle promises library
guzzlehttp/psr7                            1.4.2                 PSR-7 message implementation that also provides common utility methods
illuminate/config                          v5.4.36               The Illuminate Config package.
illuminate/contracts                       v5.4.36               The Illuminate Contracts package.
illuminate/filesystem                      v5.4.36               The Illuminate Filesystem package.
illuminate/session                         v5.4.36               The Illuminate Session package.
illuminate/support                         v5.4.36               The Illuminate Support package.
jakub-onderka/php-console-color            0.1
jakub-onderka/php-console-highlighter      v0.3.2
nikic/php-parser                           v3.1.3                A PHP parser written in PHP
react/dns                                  v0.4.11               Async DNS resolver for ReactPHP
seld/cli-prompt                            1.0.3                 Allows you to prompt for user input on the command line, and optionally hide the characters they type
seld/jsonlint                              1.7.0                 JSON Linter
symfony/config                             v3.4.3                Symfony Config Component
symfony/console                            v3.4.3                Symfony Console Component
symfony/debug                              v3.4.3                Symfony Debug Component
symfony/filesystem                         v3.4.3                Symfony Filesystem Component
symfony/finder                             v3.4.3                Symfony Finder Component
symfony/http-foundation                    v3.4.3                Symfony HttpFoundation Component
symfony/options-resolver                   v3.4.3                Symfony OptionsResolver Component
symfony/polyfill-mbstring                  v1.6.0                Symfony polyfill for the Mbstring extension
symfony/polyfill-php70                     v1.6.0                Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/process                            v3.4.3                Symfony Process Component
symfony/translation                        v3.4.3                Symfony Translation Component
symfony/var-dumper                         v3.4.3                Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                               v3.4.3                Symfony Yaml Component
wyrihaximus/twig-view                      4.3.0                 Twig powered View for CakePHP3
zendframework/zend-servicemanager          3.3.1
zendframework/zend-validator               2.10.1                provides a set of commonly needed validators
```

Doesn't work:
```cakephp/cakephp                            3.5.11             The CakePHP framework
cakephp/chronos                            1.1.4              A simple API extension for DateTime.
cakephp/debug_kit                          3.12.0             CakePHP Debug Kit
composer/composer                          1.6.3              Composer helps you declare, manage and install dependencies of PHP projects, ensuring you have the right stack everywhere.
composer/spdx-licenses                     1.3.0              SPDX licenses list and validation library.
doctrine/inflector                         v1.3.0             Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                      1.1.0              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
friendsofcake/bootstrap-ui                 1.3.0              Twitter Bootstrap 3 support for CakePHP 3
google/apiclient-services                  v0.44              Client library for Google APIs
google/auth                                v1.2.1             Google Auth Library for PHP
illuminate/config                          v5.5.33            The Illuminate Config package.
illuminate/contracts                       v5.5.33            The Illuminate Contracts package.
illuminate/filesystem                      v5.5.33            The Illuminate Filesystem package.
illuminate/session                         v5.5.33            The Illuminate Session package.
illuminate/support                         v5.5.33            The Illuminate Support package.
myclabs/deep-copy                          1.7.0              Create deep copies (clones) of your objects
nikic/php-parser                           v3.1.4             A PHP parser written in PHP
phar-io/manifest                           1.0.1              Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                            1.0.1              Library for handling version information and constraints
phpdocumentor/reflection-common            1.0.1              Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock          4.3.0              With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that...
phpdocumentor/type-resolver                0.4.0
phpspec/prophecy                           1.7.3              Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage                  5.3.0              Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator                  1.4.5              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template                  1.2.1              Simple template engine.
phpunit/php-timer                          1.0.9              Utility class for timing
phpunit/php-token-stream                   2.0.2              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                            6.5.6              The PHP Unit Testing framework.
phpunit/phpunit-mock-objects               5.0.6              Mock Object library for PHPUnit
psr/simple-cache                           1.0.0              Common interfaces for simple caching
react/dns                                  v0.4.12            Async DNS resolver for ReactPHP
rrd/rbruteforce                            0.0.2              CakePHP 3 Plugin for Protection Against BruteForce Attacks
sebastian/code-unit-reverse-lookup         1.0.1              Looks up which function or method a line of code belongs to
sebastian/comparator                       2.1.3              Provides the functionality to compare PHP values for equality
sebastian/diff                             2.0.1              Diff implementation
sebastian/environment                      3.1.0              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                         3.1.0              Provides the functionality to export PHP variables for visualization
sebastian/global-state                     2.0.0              Snapshotting of global state
sebastian/object-enumerator                3.0.3              Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector                 1.1.1              Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context                3.0.0              Provides functionality to recursively process PHP variables
sebastian/resource-operations              1.0.0              Provides a list of PHP built-in functions that operate on resources
sebastian/version                          2.0.1              Library that helps with managing the version number of Git-hosted PHP projects
seld/jsonlint                              1.7.1              JSON Linter
symfony/config                             v3.4.4             Symfony Config Component
symfony/console                            v3.4.4             Symfony Console Component
symfony/debug                              v4.0.4             Symfony Debug Component
symfony/filesystem                         v4.0.4             Symfony Filesystem Component
symfony/finder                             v3.4.4             Symfony Finder Component
symfony/http-foundation                    v3.4.4             Symfony HttpFoundation Component
symfony/options-resolver                   v4.0.4             Symfony OptionsResolver Component
symfony/polyfill-mbstring                  v1.7.0             Symfony polyfill for the Mbstring extension
symfony/polyfill-php70                     v1.7.0             Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72                     v1.7.0             Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/process                            v4.0.4             Symfony Process Component
symfony/translation                        v3.4.4             Symfony Translation Component
symfony/var-dumper                         v4.0.4             Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                               v3.4.4             Symfony Yaml Component
theseer/tokenizer                          1.1.0              A small library for converting tokenized PHP source code into XML and potentially other formats
webmozart/assert                           1.3.0              Assertions to validate method input/output with nice error messages.
wyrihaximus/twig-view                      4.3.1              Twig powered View for CakePHP3
zendframework/zend-servicemanager          3.3.2              Factory-Driven Dependency Injection Container
zendframework/zend-validator               2.10.2             provides a set of commonly needed validators
```

**Comment by r34117y** [comment] 2018-07-03 12:15
For me the problem was that despite of redirect, the default view attempted to render before the target view and flash messsage was removed during the former.
Changing `$this->redirect(['controller' => 'Tickets', 'action' => 'index']);` to `return $this->redirect(['controller' => 'Tickets', 'action' => 'index']);` should do the job.
