### ISSUE TITLE
Missing space in email subject

### ISSUE THREAD

**Issue by ludeus** [cakephp/cakephp#13489] opened 2019-08-08 07:55 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.1
* Platform and Target: Ubuntu 16.04

### What you did
submit email with Cake\Mailer\Email::setSubject()
exemple of failed subject:
> "[as@lae] Prendre une décision - transfert AT_359"

### What happened
Missing space in mailbox :
> "[as@lae] Prendre unedécision - transfert AT_359"

### Why ?

because, if `$text = "[as@lae] Prendre une décision - transfert AT_359";`
Cake\Mailer\Email::_encode($text) will output :
"[as@lae] Prendre une =?UTF-8?B?ZMOpY2lzaW9uIC0gdHJhbnNmZXJ0IEFUXzM1OQ==?="

**the first space before "=?" is ignored**

### Solution

we can double the space before the "=?" (don't like this solution but it work).

or encode the full string in base64:

```php
    public function _encode($text)
    {
        if (empty($this->headerCharset)) {
            $this->headerCharset = $this->charset;
        }
        return sprintf("=?%s?B?%s?=", $this->headerCharset, base64_encode($text));
    }
```

**Comment by markstory** [comment] 2019-08-08 13:49
This sounds like it might be a problem with how PHP's mb_encode_mimeheader works. Encoding everything as base64 is risky as it could cause other problems.

**Comment by othercorey** [comment] 2019-11-25 18:35
@ludeus Do you have any custom or specific encoding set for app, body or header?

**Comment by othercorey** [comment] 2019-11-30 07:47
I reproduced this.  It seems to be a bug in mb_encode_mimeheader as @markstory thought.  It doesn't seem to consider the entire string as UTF-8 or something because of the space.

I found a similar issue in another framework and their workaround was to use iconv_mime_encode.

https://github.com/bcit-ci/CodeIgniter/commit/3368cebeb6682013c44be7a03d3b3dac0f5c8973

**Comment by othercorey** [comment] 2019-11-30 07:56
I can also try doing the encoding manually.  If the bug is only in mb_encode_mimeheader, we can do the mime format manually and then decode/encode the string directly.

**Comment by othercorey** [comment] 2019-11-30 23:30
Even symfony's polyfill marks mb_encode_mimeheader as bugged and won't implement it.

https://github.com/symfony/polyfill/blob/166bf89d41b02a269701e7a315db335711149d4d/src/Mbstring/Mbstring.php#L137

**Comment by markstory** [comment] 2019-12-01 01:17
I'm reluctant to add a dependency on `lib-iconv`. We could optionally prefer the iconv version.

**Comment by othercorey** [comment] 2019-12-01 01:27
Same. I'm trying to find a less demanding way to add it including the polyfill.

**Comment by othercorey** [comment] 2019-12-01 06:24
I think the default iconv implementation and libiconv might be sufficient for this.  We shouldn't need to rely on a separate library installation.

**Comment by markstory** [comment] 2019-12-01 16:17
Is the iconv extension always available? I thought it was an optional extension on many distros.

**Comment by ADmad** [comment] 2019-12-01 18:01
iconv isn't commonly available on various distros/hostings by default. So it should be used with explicit check and fallback.

**Comment by jimbo2150** [comment] 2019-12-01 18:17
I don't think it's a bug per-say. I think the function is starting with the first word containing a non-ASCII character and encoding the remainder of the string (maybe to save a few bytes? Not sure), but is is wonky how it works.

Another potential option: add an invisible character to the beginning of the string. Such as a SOS (start-of-string), ZWNJ (zero-width non-joiner), or ZWS (zero-width space):
```php
html_entity_decode('&#8203;');
```

```php
    protected function _encode($text)
    {
        $restore = mb_internal_encoding();
        mb_internal_encoding($this->_appCharset);
        if (empty($this->headerCharset)) {
            $this->headerCharset = $this->charset;
        }
        $sc = html_entity_decode('&#8203;');
        $return = mb_encode_mimeheader($sc . $text, $this->headerCharset, 'B');
        mb_internal_encoding($restore);

        return $return;
    }
```

_Note: Maybe someone knows a better way? It was the quick-n-dirty method to decode an HTML entity but may be a faster way without. I would use character reference but I think those require PHP 7+ so probably won't work in older versions._

This forces `mb_encode_mimeheader` to encode the entire string (with 1 additional invisible character). Would be nice if there were an option for the function to force it to encode everything but after searching for a while there does not appear to be a way to do that without adding a non-ASCII character.

Iconv encodes the entire subject (but requires libiconv be present and identified to PHP through the --with-iconv[=DIR] directive). I also looked at the iconv header encoding function and it requires passing the header name to the function so you send up with a string like "Subject: ?UTF-8?B?..." which would have to be modified if you are using a header array ("Subject" => "My subject").

**Comment by othercorey** [comment] 2019-12-01 18:20
I agree with detection and testing here, but I am wondering how many systems manually php build with --without-iconv it should be enabled by default.

My concern is more with the c library they used by default.

**Comment by othercorey** [comment] 2021-06-30 00:18
I tried reproducing this by manually setting the subject to the encoded string. It seems to show up correctly in multiple email readers.

I'm not sure what I was looking at in my first comment, but not sure what issue there is anymore.

**Comment by dereuromark** [comment] 2021-09-23 22:28
Should we close this then for now?

**Comment by othercorey** [comment] 2021-09-23 23:27
I don't know if I tested this correctly. I don't have an environment setup to send these at the moment. I was looking at the encoding functions if I recall.

I tried manually editing emails and opening them.

**Closed** 2021-09-24 03:18 UTC
Labels: defect, email, pinned
