### ISSUE TITLE
TestSuite DB connection is not using PDO Flags ? (4.3.0-RC3 / Migrator)

### ISSUE THREAD

**Issue by swiffer** [cakephp/cakephp#16020] opened 2021-10-09 13:58 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.3.0-RC3
* Platform and Target: Apache, Postres 13.4, PHP 8.0.8

### What you did
Updated to CakePHP 4.3.0-RC3 and migrated to the new Fixture System. 

### What happened
Afterwards 2 test cases started to fail and I suppose it is because Flags defined in the config/app.php are not set anymore. It's only the tests that fail - executing the same controller action in the browser still works fine.

As the app code itself is unchanged I guess it's caused by either CakePHP or the Migrations plugin.

The issue returned by postgresql for the failing testcase is:

```log
PDOException: SQLSTATE[42883]: Undefined function: 7 ERROR:  function sum(text) does not exist
```

however i'm setting types to integer when building the query and have set the flags to include `PDO::ATTR_EMULATE_PREPARES => true`

this was suggested in the slack channel a year ago as without using emulated prepare statements pdo will hand over all parameters as strings no matter of the binding type.

Is there an easy way to check if the flag is set correctly at the time of query execution?

### What you expected to happen
the testcase should still work.

**Comment by markstory** [comment] 2021-10-09 15:39
Is the problematic `sum()` call in one of your migrations? Do those flags get used correctly when you run migrations through `cake migrations migrate`?

**Comment by swiffer** [comment] 2021-10-09 16:52
No, it's part of the controller action. I'll check that and provide a simple snippet to reproduce the issue.

**Comment by othercorey** [comment] 2021-10-09 18:43
Can you link the original issue with sum and types?

**Comment by othercorey** [comment] 2021-10-09 19:03
> however i'm setting types to integer when building the query and have set the flags to include PDO::ATTR_EMULATE_PREPARES => true

Where are you setting this?

**Comment by swiffer** [comment] 2021-10-09 19:49
so a minimal example within a controller action would be

BooksController.php
```php
        $selectQuery= $this->Books->query();

        $exp = $selectQuery->newExpr()->addCase([$selectQuery->newExpr('true')], [1, 0], ['integer', 'integer']);

        $results = $selectQuery->select([
            'data' => $selectQuery->func()->sum($exp),
        ])->all();
```

in PostgreSQL when `PDO::ATTR_EMULATE_PREPARES` is set to `false` this will fail with sql error:

SQLSTATE[42883]: Undefined function: 7 ERROR:  function sum(text) does not exist
LINE 1: SELECT (SUM(CASE WHEN true THEN $1 ELSE $2 END)) AS "data" F...

this is why i set PDO::ATTR_EMULATE_PREPARES = true in `app/config.php` in the Datasource `flags` config array.

despite the fact it's set to true it's still failing in the testsuite since migrating to 4.3.0-RC3.

**Comment by othercorey** [comment] 2021-10-09 22:04
> this is why i set PDO::ATTR_EMULATE_PREPARES = true in `app/config.php` in the Datasource `flags` config array.

This is set for `default` datasource (I assume you mean config/app.php)?

**Comment by markstory** [comment] 2021-10-10 02:00
For me locally using php 7.4.16 and postgres 13.4, the following test still passes if the `PDO::ATTR_EMULATE_PREPARES` flag is set.

```php
        $query = new Query($this->connection);

        $exp = $query->newExpr()->addCase([$query->newExpr('true')], [1, 0], ['integer', 'integer']);

        $results = $query->select([
            'data' => $query->func()->sum($exp),
        ])
        ->execute()
        ->fetch('assoc');

        debug($results);
        $this->assertSame(['data' => 1], $results);
```

I have the flag enabled using the following code added to the `tests/bootstrap.php` in Cake core.

```php
ConnectionManager::setConfig('test', [
    'url' => getenv('DB_URL'),
    'flags' => [
        PDO::ATTR_EMULATE_PREPARES => true,
    ],
]);
```

When this flag is set to false or undefined the test fails, but when true the test passes using the current head of the `4.next` branch. Am I missing something?

**Comment by swiffer** [comment] 2021-10-10 06:41
Can you add the following snippet to your tests/bootstrap.php

```php
$migrator = new Migrator(['outputLevel' => ConsoleIo::VERBOSE]);
$migrator->run();
```

for me as soon as i do that the test starts to fail while working without issues previously.

I've the flag enabled for the test Datasource in app/config.php as well. When adding the snippet you posted to `tests/bootstrap.php` I'm getting this error:

```log
Error in bootstrap script: BadMethodCallException:
Cannot reconfigure existing key "test"
```

```php
ConnectionManager::setConfig('test', [
    'url' => getenv('DB_URL'),
    'flags' => [
        PDO::ATTR_EMULATE_PREPARES => true,
    ],
]);
```

But my tests/bootstrap.php is including config/bootstrap.php which consumes the datasource configuration.

**Comment by markstory** [comment] 2021-10-10 17:59
> Can you add the following snippet to your tests/bootstrap.php

No, because the cake core tests don't use migrations. I can try reproducing this in an application that uses migrations though.

**Comment by othercorey** [comment] 2021-10-11 14:36
Fixed in https://github.com/cakephp/migrations/pull/514

**Closed as completed by othercorey** 2021-10-11 14:36 UTC
Labels: defect, testing
