### ISSUE TITLE
FixtureManager error message misleading

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#7965] opened 2016-01-05 01:07 UTC
I got
```
Fatal error: Uncaught exception 'Cake\Core\Exception\Exception' with message 'Unable to insert fixtures for "Geo\Test\Model\Behavior\GeocoderBehaviorTest" test case. SQLSTATE[42000]: 
Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1' in ...\site\Vendor\dereuromark\cakephp-geo\vendor\cakephp\cakephp\src\TestSuite\Fixture\FixtureManager.php on line 304

Cake\Core\Exception\Exception: Unable to insert fixtures for "Geo\Test\Model\Behavior\GeocoderBehaviorTest" test case. SQLSTATE[42000]: 
Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 in ...\site\Vendor\dereuromark\cakephp-geo\vendor\cakephp\cakephp\src\TestSuite\Fixture\FixtureManager.php on line 304
```

The actual issue, after quite some debugging, was, that the credentials (username/password) of the test DB connection where wrong. Thus there was no connection possible, and there should have been a message stating that instead of outputting an error that leads to the conclusion that the fixture files are invalid (which I first looked into of course because of this).

**Comment by antograssiot** [comment] 2016-01-05 04:58
@dereuromark Sorry to ask but are you using the latest 3.1, because with bad credential I got:
```
Exception: Unable to insert fixtures for "App\Test\TestCase\Controller\Admin\ConcertsControllerTest"
test case. SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)
in [/Users/antograssiot/Sites/dissay/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureManager.php,
line 304]
```
which is way more descriptive

**Comment by dereuromark** [comment] 2016-01-05 09:49
Yes latest release.

**Comment by lorenzo** [comment] 2016-01-05 11:02
I got the same message as @antograssiot

**Comment by lorenzo** [comment] 2016-01-05 11:02
How were your credentials defined @dereuromark ?

**Comment by dereuromark** [comment] 2016-01-05 11:04
https://github.com/dereuromark/cakephp-geo/blob/master/tests/bootstrap.php#L67-L69 gets the local dev credentials from https://github.com/dereuromark/cakephp-geo/blob/master/tests/config/app_local.php.dist (of course filled with data then).

**Comment by antograssiot** [comment] 2016-01-05 11:34
@dereuromark maybe stupid but looks redundant, what if you remove https://github.com/dereuromark/cakephp-geo/blob/master/tests/bootstrap.php#L80
?

**Comment by markstory** [comment] 2016-01-08 03:18
I tried invalid credentials in a DSN string and, also in the configuration array and managed to get the correct error message as well:

```
Unable to insert fixtures for "Cake\Test\TestCase\ORM\Association\BelongsToTest" test case. SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)
```

Closing as a few of us have not been able to reproduce this.

**Closed by markstory** 2016-01-08 03:18 UTC
Labels: Defect

**Comment by dereuromark** [comment] 2016-01-16 16:48
I was able to reproduce it on travis now:
https://travis-ci.org/dereuromark/cakephp-geo/jobs/102804510

All I did can be seen here: https://github.com/dereuromark/cakephp-geo/commit/44686c35efeafa1b87b625749edfadd8e89339b5
Basically it now has a username, but an invalid password probably, and that kills it with this missleading message that the fixtures would not be OK.
Once I fix the credentials everything runs OK again.

**Comment by antograssiot** [comment] 2016-01-16 19:13
@dereuromark once again maybe not related but:
https://github.com/dereuromark/cakephp-geo/blob/develop/tests/bootstrap.php#L80

I'm not sure that the  ``dsn`` config key exists. At least it's documented as ``url``.

**Comment by dereuromark** [comment] 2016-01-16 19:17
@antograssiot But you do agree that the message is still misleading no matter what config keys are now correct or false. As it is clear that the connection cannot be established in the first place.
