### ISSUE TITLE
Error in Console bake for command bake all model

### ISSUE THREAD

**Issue by coolbalyan** [cakephp/cakephp#6495] opened 2015-05-06 06:04 UTC
2015-05-06 05:59:23 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`0`' at line 1
Stack Trace:
#0 D:\XAMPP\htdocs\cakephp_v3.0\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(37): PDOStatement->execute(NULL)
#1 D:\XAMPP\htdocs\cakephp_v3.0\vendor\cakephp\cakephp\src\Database\Connection.php(288): Cake\Database\Statement\MysqlStatement->execute()
#2 D:\XAMPP\htdocs\cakephp_v3.0\vendor\cakephp\cakephp\src\Database\Connection.php(245): Cake\Database\Connection->query('SHOW TABLES FRO...')
#3 D:\XAMPP\htdocs\cakephp_v3.0\vendor\cakephp\cakephp\src\Database\Schema\Collection.php(64): Cake\Database\Connection->execute('SHOW TABLES FRO...', Array)
#4 D:\XAMPP\htdocs\cakephp_v3.0\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(807): Cake\Database\Schema\Collection->listTables()
#5 D:\XAMPP\htdocs\cakephp_v3.0\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(782): Bake\Shell\Task\ModelTask->_getAllTables()
#6 D:\XAMPP\htdocs\cakephp_v3.0\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(186): Bake\Shell\Task\ModelTask->listAll()
#7 D:\XAMPP\htdocs\cakephp_v3.0\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(109): Bake\Shell\Task\ModelTask->getAssociations(Object(Cake\ORM\Table))
#8 D:\XAMPP\htdocs\cakephp_v3.0\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(95): Bake\Shell\Task\ModelTask->bake('Users')
#9 D:\XAMPP\htdocs\cakephp_v3.0\vendor\cakephp\bake\src\Shell\BakeShell.php(241): Bake\Shell\Task\ModelTask->main('Users')
#10 [internal function]: Bake\Shell\BakeShell->all('users')
#11 D:\XAMPP\htdocs\cakephp_v3.0\vendor\cakephp\cakephp\src\Console\Shell.php(380): call_user_func_array(Array, Array)
#12 D:\XAMPP\htdocs\cakephp_v3.0\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(204): Cake\Console\Shell->runCommand(Array, true)
#13 D:\XAMPP\htdocs\cakephp_v3.0\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(175): Cake\Console\ShellDispatcher->_dispatch()
#14 D:\XAMPP\htdocs\cakephp_v3.0\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(126): Cake\Console\ShellDispatcher->dispatch()
#15 D:\XAMPP\htdocs\cakephp_v3.0\bin\cake.php(33): Cake\Console\ShellDispatcher::run(Array)
#16 {main}

My db name is cakephp_v3.0 and when i used var_dump on line 37 of file D:\XAMPP\htdocs\cakephp_v3.0\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php its output is

class PDOStatement#244 (1){
       public $queryString =>
       string(33) "SHOW TABLES FROM `cakephp_3`.`0`"
}

**Comment by ADmad** [comment] 2015-05-06 06:09
Duplicate of #6471

**Closed by ADmad** 2015-05-06 06:09 UTC
