### ISSUE TITLE
Sum of the sum

### ISSUE THREAD

**Issue by thiagoreri** [cakephp/cakephp#13268] opened 2019-05-20 16:36 UTC
This is subquery

```php
$baixa_select1 = $this->Caixa->find()
                    ->select([
                        'valor_baixa' => $this->Caixa->find()->func()->sum('Caixa.valor_baixa'),
                    ]);
```

In query 

```php
$query->select([
                    'valor_baixa_normal' => $query->func()->sum($baixa_select1)
                ]);
```

Error

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SELECT (SUM(Caixa.valor_baixa)) AS `valor_baixa` FROM caixa Caixa)) AS `valor_ba' at line 1

**Comment by othercorey** [comment] 2019-05-20 18:49
The `sum()` function expects a `literal` value which means it needs to be the column name.

Also, you probably want to use the same Query to call `select()` and `func()`.

**Comment by thiagoreri** [comment] 2019-05-20 18:56
Yeah, how did I work it out?

**Comment by othercorey** [comment] 2019-05-20 18:58
>Yeah, how did I work it out?

I don't understand, sorry.

**Comment by markstory** [comment] 2019-05-21 01:24
What does the generated SQL look like?

**Comment by othercorey** [comment] 2019-05-22 10:56
```mysql
SELECT (SUM(Caixa.valor_baixa)) AS valor_baixa FROM caixa Caixa)) AS `valor_ba'
```

I think that's the generated SQL.  It looks like a ( is missing at the beginning.

**Comment by ADmad** [comment] 2019-05-22 14:53
The issue's title reminds me of [this](https://youtube.com/watch?v=PptHWHfnCnY).

**Comment by othercorey** [comment] 2019-05-22 15:23
I'm really curious what the actual error was after I gave a useless response.

Does cakephp have an issue with using an expression from a different query instance?  There is only a literal argument to `sum()` so does creating the expression through a new `find()` matter?

```
$baixa_select1 = $this->Caixa->find()
                    ->select([
                        'valor_baixa' => $this->Caixa->find()->func()->sum('Caixa.valor_baixa'),
                    ]);
```

**Comment by markstory** [comment] 2019-07-13 03:24
Closing as we don't have a way to reproduce the problem you're having.

**Closed by markstory** 2019-07-13 03:24 UTC
Labels: ORM, need-more-info
