### ISSUE TITLE
Unable to access view cell blocks

### ISSUE THREAD

**Issue by sdustinh** [cakephp/cakephp#11773] opened 2018-03-01 13:01 UTC
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

```bash
sdustinh@sdustinh:~/github/app$ php --version
PHP 7.1.14-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb  9 2018 09:33:27) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.14-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
sdustinh@sdustinh:~/github/app$ mysql --version
mysql  Ver 14.14 Distrib 5.7.21, for Linux (x86_64) using  EditLine wrapper
sdustinh@sdustinh:~/github/app$ composer show cakephp/*
cakephp/bake                1.6.0  Bake plugin for CakePHP 3
cakephp/cakephp             3.5.11 The CakePHP framework
cakephp/cakephp-codesniffer 3.0.3  CakePHP CodeSniffer Standards
cakephp/chronos             1.1.4  A simple API extension for DateTime.
cakephp/debug_kit           3.11.6 CakePHP Debug Kit
cakephp/elastic-search      0.3.5  An Elastic Search datasource and data mapper for CakePHP 3.0
cakephp/migrations          1.7.2  Database Migration plugin for CakePHP 3.0 based on Phinx
cakephp/plugin-installer    1.1.0  A composer installer for CakePHP 3.0+ plugins.
```

It would be really handy to be able to access the view blocks of a rendered view cell after rendering completes. Consider the following:

```php
// src/Template/Layout/default.ctp
<html>
    <body>
        <?= $this->fetch('content') ?>
        <?= $this->fetch('scripts') ?>

        <div id="modal-container">
            <?= $this->fetch('modals') ?>
        </div>
    </body>
</html>

// src/Template/Cell/SearchTweets/display.ctp
<?php
$this->Html->scripts('tweet_scripts', ['block' => true]);
?>
<table>
    <tbody>
        <tr>
            <td><?= $tweet['field'] ?></td>
            <td>
                <?php
                $modalId = $this->uuid('tweet-modal-', [ ... ]);
                echo $this->Html->tag('button', 'View Details', [
                    'data-target' => '#' . $modalId,
                    'data-toggle' => 'modal',
                    'type' => 'button',
                ]);
                $this->append('modals', $this->element('modal/tweet_details', [
                    'id' => $modalId,
                ]));
                ?>
            </td>
        </tr>
    </tbody>
</table>

// src/Controller/TweetsController.php
<?php
class TweetsController extends Controller
{
    use CellTrait;
    /**
     * List all tweets.
     *
     * @return void
     */
    public function index()
    {
        $tweets = $this->cell('Twitter.SearchTweets');
        $this->set('tweets', $tweets);
    }
}
?>

// src/Template/Tweets/index.ctp
<div id="all-tweets">
    <?= $tweets->render() ?>
</div>
```

In my layout file I have view blocks that need to be in specific places. Currently, there is no ([non-deprecated](https://github.com/cakephp/cakephp/blob/master/src/View/Cell.php#L51)) way to access the view object used to render the cell which makes the following not possible:

```php
// src/Template/Tweets/index.ctp
<div id="all-tweets">
    <?= $tweets->render() ?>
</div>
<?php
$this->append('modals', $tweets->getView()->fetch('modals'));
$this->append('scripts', $tweets->getView()->fetch('scripts'));
```

**Comment by ADmad** [comment] 2018-03-01 13:04
Duplicate of #10166.

**Closed by ADmad** 2018-03-01 13:04 UTC
Labels: Enhancement

**Comment by sdustinh** [comment] 2018-03-01 13:06
Bah. Good catch. I clearly didn't search first. Sorry about that @ADmad
