### ISSUE TITLE
datetime marshaller ignores timezone

### ISSUE THREAD

**Issue by Schlaefer** [cakephp/cakephp#7042] opened 2015-07-16 20:07 UTC
This is an odd behaviour. Code example: https://gist.github.com/Schlaefer/61ff394ef7f8929826cf

Cake ignores the timezone information when saving the timestamps. What I would expect is that they are converted to UTC before storing them into the DB. At least not be equal.

**Comment by lorenzo** [comment] 2015-07-16 20:15
Duplicate of https://github.com/cakephp/cakephp/issues/6571

**Closed by lorenzo** 2015-07-16 20:15 UTC

**Comment by lorenzo** [comment] 2015-07-16 20:17
This means that you are currently responsible for normalizing the timezone on the time objects in your app. A good place to do this is by using entity setters.

**Comment by Schlaefer** [comment] 2015-07-16 20:48
Thanks @lorenzo. Just to be sure, was it brought up in #6571 that you actually lose the timezone information on saving and you can't retrieve the correct dates after saving no matter if PHP or DB timezone is correct. So it's not only about retrieving the dates in the right timezone again, the dates are just wrong no matter what.

**Comment by lorenzo** [comment] 2015-07-16 21:02
Understood, if this issue can be solved, it would be through #6571
