### ISSUE TITLE
Validate still query to database when there is field "id" in a model that doesn't have table `$useTable = false`

### ISSUE THREAD

**Issue by kongkannika** [cakephp/cakephp#7229] opened 2015-08-14 06:13 UTC
Model that doesn't have table to validate form register

```php
class Api extends Model {

	public $useTable = false;

	public function validateUserRegister() {
		$this->validate = array(
			'name' => array(
				'notBlank' => array(
					'rule' => array('notBlank'),
					'message' => 'Please enter name',
					'required' => true
				),
			),
			'email' => array(
				'notBlank' => array(
					'rule' => array('notBlank'),
					'message' => 'Please enter email',
					'required' => true
				),
			),
		);
		return $this->validates();
	}
}
```

Controller call the `validateUserRegister()` in model `Api`

```php
class V01Controller extends AppApiController {

	public $uses = array('Api.Api', 'User');

	public function register() {
		$this->Api->set($this->request->data);
		if ($this->Api->validateUserRegister()) {
			// todo
		}
	}
}
```

Browser request with below data is OK:

```json
{
    "name": "Toto",
    "email": "toto@gmail.com"
}
```

But when the request with this data, it shows an error :
```json
{
    "id": "10",
    "name": "Toto",
    "email": "toto@gmail.com"
}
```

```
Database Error

Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'koicafe.koi_apis' doesn't exist

SQL Query: SELECT COUNT(*) AS `count` FROM `koicafe`.`koi_apis` AS `Api` WHERE `Api`.`id` = 10 
```
I think there is a bug on validation core of CakePHP when the table is not used, it still query to database on the table with the name of model.

**Comment by tanuck** [comment] 2015-08-14 09:15
My guess is this is caused by the call to `$model->exists()` in the `ModelValidator::errors()` method. I'm not sure whether it is correct to skip it when `$useTable = false` though. I would normally write a custom datasource for when my model is interacting with an API.

Maybe a bit of a dirty fix would be for you to reset the value of `$model->primaryKey` so that the model id doesn't get set when calling `$this->Api->set($this->request->data)` ?

**Comment by tanuck** [comment] 2015-08-16 17:18
@markstory do you think it's correct to change the behaviour of `Model::exists()` when `$useTable = false` ?

**Comment by markstory** [comment] 2015-08-16 22:52
That method could always return false if useTable is false.

**Comment by tanuck** [comment] 2015-08-17 08:28
Maybe. I guess you wouldn't be able to specify `'on' => 'update'` in your validation ruleset if that was the case?

**Comment by kongkannika** [comment] 2015-08-17 09:04
@tanuck actually, I just want to register new user in API service from phone. Accidentally, in the request their set the field "id" with number. I don't think why I use `'on' => 'update'` in this case.

And there are many other validations like `validateUserForgotPassword()`, `validateUserLoginFacebook()`, `validateProductUpdated()` and so on. If in request has field "id", it shows the errors above.

Currently, to fixed this issue I just remove every requests of field "id" in my controller before validate it :smile:

**Comment by markstory** [comment] 2015-08-18 00:09
Closing as there is a pull request up that looks pretty good.

**Closed by markstory** 2015-08-18 00:09 UTC
Labels: Defect
