### ISSUE TITLE
3.2.3 Migrations: Crash with Phinx version 0.5.2

### ISSUE THREAD

**Issue by AnderWeb** [cakephp/cakephp#8382] opened 2016-03-01 19:27 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.3.
* Phinx 0.5.2 (updated with composer)

Trying `./bin/cake migrations status` (or any other migrations command) causes the following crash:
`PHP Fatal error:  Class Migrations\CakeAdapter contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Phinx\Db\Adapter\AdapterInterface::getVersionLog) in /var/www/html/adwfeedback/vendor/cakephp/migrations/src/CakeAdapter.php on line 670`

This is due to the new Phinx api method to get a versioning log, as stated in [this commit](https://github.com/robmorgan/phinx/commit/3dbbbcec9acd945cc6b16afd8d68e0076ab266fd)

**Comment by CodeBlastr** [comment] 2016-03-01 20:00
This is a duplicate of https://github.com/cakephp/migrations/issues/202

**Comment by josegonzalez** [comment] 2016-03-01 20:16
Closing as duplicate (and in the wrong place). We'll try and get this fixed up soon!

**Closed by josegonzalez** 2016-03-01 20:16 UTC
