### ISSUE TITLE
Cake 3.x I need to manage the table prefix

### ISSUE THREAD

**Issue by vnt** [cakephp/cakephp#6270] opened 2015-04-03 14:28 UTC
Hi,
Congratulations for the work you have done with Cakephp3, it's amazing.
I need to manage the table prefix (dsc_users).
When will it be available for CakePHP 3?
Thanks and good work.

**Comment by dereuromark** [comment] 2015-04-03 14:31
Duplicate of https://github.com/cakephp/cakephp/issues/4118

**Comment by markstory** [comment] 2015-04-03 14:35
@vnt How do you use prefixes in your application? Do you have prefixes on specific tables, or all tables that you access through a given connection?

Until the prefix feature is implemented the current solution is to call `$this->table('dsc_users')` in your table's initialize() method.

**Comment by vnt** [comment] 2015-04-03 15:04
CREATE TABLE `vnt_users` (
`id` bigint(20) unsigned NOT NULL,
  `user_state_id` int(10) unsigned NOT NULL,
  `user_group_id` int(11) NOT NULL DEFAULT '3',
  `email` char(255) COLLATE utf8_unicode_ci NOT NULL,
  `password` char(45) COLLATE utf8_unicode_ci NOT NULL,
  `name` char(45) COLLATE utf8_unicode_ci NOT NULL,
  `surname` char(45) COLLATE utf8_unicode_ci NOT NULL,
  `updated` datetime DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `activation_code` char(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `token` char(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ip` char(45) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Table structure for table `vnt_user_groups`
--

CREATE TABLE `vnt_user_groups` (
`id` int(11) NOT NULL,
  `active` tinyint(1) DEFAULT '1',
  `admin_access` tinyint(1) DEFAULT '0',
  `title` char(45) COLLATE utf8_unicode_ci NOT NULL,
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Table structure for table `vnt_user_states`
--

CREATE TABLE `vnt_user_states` (
`id` int(10) unsigned NOT NULL,
  `active` tinyint(1) DEFAULT '1',
  `title` char(45) COLLATE utf8_unicode_ci NOT NULL,
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Indexes for table `vnt_users`
--
ALTER TABLE `vnt_users`
 ADD PRIMARY KEY (`id`), ADD UNIQUE KEY `email_UNIQUE` (`email`), ADD UNIQUE KEY `token_UNIQUE` (`token`), ADD KEY `fk_vnt_users_vnt_user_states1_idx` (`user_state_id`), ADD KEY `fk_vnt_users_vnt_user_groups1_idx` (`user_group_id`);

**Comment by vnt** [comment] 2015-04-03 15:06
This is error bake
./cake bake template vnt_users

Welcome to CakePHP v3.0.0 Console
---------------------------------------------------------------
App : src
Path: /Users/vnt/Sites/cakephp3/project/src/
---------------------------------------------------------------
Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'project.user_states' doesn't exist in [/Users/vnt/Sites/cakephp3/project/vendor/cakephp/cakephp/src/Database/Schema/Collection.php, line 130]
2015-04-03 15:05:13 Error: [Cake\Database\Exception] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'project.user_states' doesn't exist
Stack Trace:
#0 /Users/vnt/Sites/cakephp3/project/vendor/cakephp/cakephp/src/Database/Schema/Collection.php(96): Cake\Database\Schema\Collection->_reflect('Column', 'user_states', Array, Object(Cake\Database\Schema\Table))
#1 /Users/vnt/Sites/cakephp3/project/vendor/cakephp/cakephp/src/Database/Schema/CachedCollection.php(65): Cake\Database\Schema\Collection->describe('user_states', Array)
#2 /Users/vnt/Sites/cakephp3/project/vendor/cakephp/cakephp/src/ORM/Table.php(422): Cake\Database\Schema\CachedCollection->describe('user_states')
#3 /Users/vnt/Sites/cakephp3/project/vendor/cakephp/cakephp/src/ORM/Table.php(498): Cake\ORM\Table->schema()
#4 /Users/vnt/Sites/cakephp3/project/vendor/cakephp/bake/src/Utility/Model/AssociationFilter.php(93): Cake\ORM\Table->primaryKey()
#5 /Users/vnt/Sites/cakephp3/project/vendor/cakephp/bake/src/Shell/Task/TemplateTask.php(444): Bake\Utility\Model\AssociationFilter->filterAssociations(Object(App\Model\Table\VntUsersTable))
#6 /Users/vnt/Sites/cakephp3/project/vendor/cakephp/bake/src/Shell/Task/TemplateTask.php(284): Bake\Shell\Task\TemplateTask->_filteredAssociations(Object(App\Model\Table\VntUsersTable))
#7 /Users/vnt/Sites/cakephp3/project/vendor/cakephp/bake/src/Shell/Task/TemplateTask.php(147): Bake\Shell\Task\TemplateTask->_loadController()
#8 [internal function]: Bake\Shell\Task\TemplateTask->main('vnt_users')
#9 /Users/vnt/Sites/cakephp3/project/vendor/cakephp/cakephp/src/Console/Shell.php(387): call_user_func_array(Array, Array)
#10 /Users/vnt/Sites/cakephp3/project/vendor/cakephp/cakephp/src/Console/Shell.php(382): Cake\Console\Shell->runCommand(Array, false)
#11 /Users/vnt/Sites/cakephp3/project/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(200): Cake\Console\Shell->runCommand(Array, true)
#12 /Users/vnt/Sites/cakephp3/project/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(171): Cake\Console\ShellDispatcher->_dispatch()
#13 /Users/vnt/Sites/cakephp3/project/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(122): Cake\Console\ShellDispatcher->dispatch()
#14 /Users/vnt/Sites/cakephp3/project/bin/cake.php(20): Cake\Console\ShellDispatcher::run(Array)
#15 {main}

**Comment by markstory** [comment] 2015-04-03 23:05
The exception is a problem I can fix. Bake shouldn't fatally error when it can't find an association table. Based on your paste, it looks like all your tables have a prefix so it sounds like either of the proposed prefixing solutions would work.

**Comment by markstory** [comment] 2015-04-06 14:22
Closing as a pull request is up for bake to fix the error around missing associations. The ability to add a table prefix is tracked in a separate issue as well.

**Closed by markstory** 2015-04-06 14:22 UTC
Labels: Invalid
