### ISSUE TITLE
longitude disallows 0

### ISSUE THREAD

**Issue by 3811015** [cakephp/cakephp#9649] opened 2016-10-24 17:53 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3
* Platform and Target: nor relevant

### What you did
Look here: http://api.cakephp.org/3.3/source-class-Cake.Validation.Validation.html#49
https://regexper.com/#%5B-%2B%5D%3F(180(%5C.0%2B)%3F%7C((1%5B0-7%5D%5Cd)%7C(%5B1-9%5D%3F%5Cd))(%5C.%5Cd%2B)%3F)

### What happened
I was reading up the API.

### Expected Behavior
The greenwhich meridian is a valid location on this planet.

Suggestion:
/^(\+|-)?(?:180(?:(?:\.0{1,10})?)|(?:[0-9]|[1-9][0-9]|1[0-7][0-9])(?:(?:\.[0-9]{1,10})?))$/
https://regexper.com/#%2F%5E(%5C%2B%7C-)%3F(%3F%3A180(%3F%3A(%3F%3A%5C.0%7B1%2C10%7D)%3F)%7C(%3F%3A%5B0-9%5D%7C%5B1-9%5D%5B0-9%5D%7C1%5B0-7%5D%5B0-9%5D)(%3F%3A(%3F%3A%5C.%5B0-9%5D%7B1%2C10%7D)%3F))%24%2F

**Comment by dereuromark** [comment] 2016-10-24 17:53
Closing as duplicate of https://github.com/cakephp/cakephp/issues/9648
Please stick to one issue for the same thing (latitude/longitude).

**Closed by dereuromark** 2016-10-24 17:53 UTC
Labels: Defect

**Comment by 3811015** [comment] 2016-10-24 17:55
@dereuromark the other one is latitude

**Comment by dereuromark** [comment] 2016-10-24 17:57
It is the same thing as I just mentioned. Both can be fixed together easily.
