### ISSUE TITLE
$last of PaginatorHelper 

### ISSUE THREAD

**Issue by aokazu** [cakephp/cakephp#9592] opened 2016-10-10 08:53 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

I use CakePHP2.8.9  with PHP 7.1.0RC3.
AND I Have Error.
A non-numeric value encountered [CORE/Cake/View/Helper/PaginatorHelper.php, line 949]

### Expected Behavior
$lower = $params['pageCount'] - (int)$last + 1;

**I want add (int) before $last.**

### Actual Behavior
$lower = $params['pageCount'] - $last + 1;

**Comment by dereuromark** [comment] 2016-10-10 08:59
Why do you want to add the cast here? Can you please explain what the actual value is you get as $last here? It might be interesting how it came to this in the first place. Often times you would just hide the symptoms here, while the actual fix should be at the root cause of the issue further up the chain.

**Comment by aokazu** [comment] 2016-10-10 11:00
The default value of $ last is a 'last >>'
We must enter a numerical value in the 949 line of the calculation.

$ lower = $ params [ 'pageCount'] - $ last + 1;

In CakePHP3 follows error has so as not to occur.
Line 1038:
$ Lower = (int) $ params [ 'pageCount'] - (int) $ last + 1;

Please confirm.

**Comment by chinpei215** [comment] 2016-10-10 17:43
@dereuromark Seems like PHP7.1 specific issue.
http://php.net/manual/en/migration71.other-changes.php#migration71.other-changes.apprise-on-arithmetic-with-invalid-strings

**Comment by markstory** [comment] 2016-10-11 01:29
Seems like a reasonable thing to do to me.

**Comment by markstory** [comment] 2016-10-11 21:02
I checked the 3.x code base and the required casts are already in place. Closing as a pull request is open for 2.x

**Closed by markstory** 2016-10-11 21:02 UTC
Labels: Enhancement, pagination
