### ISSUE TITLE
 About the method: $this->Auth->identify() and removing random spaces

### ISSUE THREAD

**Issue by patsuckow** [cakephp/cakephp#11836] opened 2018-03-17 15:35 UTC
This is a (multiple allowed):

* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.5

### What happened
I use the method: $this->Auth->identify();
https://api.cakephp.org/3.5/source-class-Cake.Controller.Component.AuthComponent.html#801-831

On logs of user authorization, I noticed the following:
Apparently many users store their logins and passwords in simple text files and to enter the site they simply copy them and insert them into the authorization form.
Some of them copy their login or password with extra spaces at the beginning, but more often at the end of the line. And as a consequence, they can not be authorized, since there is an extra symbol - a space.

### What you did
To avoid this, I had to connect js and check the lines in the form of authorization, but I think this - js - is unnecessary.

### What you expected to happen
Can you add to this method (identify()) - php method trim() by default or as an option?

### Do you want to address this issue?
I think I'm not good enough to solve this problem correctly and provide a ready-made code for this method and I'm not 100% sure that I'm not mistaken.

**Comment by dereuromark** [comment] 2018-03-17 16:44
You are not mistaken about the issue, but you assume the wrong fix/scope :)
This is not just limited to login, but also to saving the data and in general to all posted data.
User submitted whitespace noise is always an issue - and maybe we should adjust the docs and give my fixes inside Tools plugin that I have been using for 10+ years now a more first class citizen there - as some kind of guidelines.
So if you use Tools.Common you wouldnt have any of these issues as it would clean out the posted data, fixing the issue at its source:
https://github.com/dereuromark/cakephp-tools/blob/master/src/Controller/Component/CommonComponent.php#L28-L36
This way you dont have to "fix up" all the low level components, incl. auth, here.

**Comment by patsuckow** [comment] 2018-03-17 17:08
Thank you for the clarification :)
Tell me, @dereuromark, CommonComponent remove spaces at the beginning and end of a line or can it remove spaces and from the middle of the passed string?

**Comment by dereuromark** [comment] 2018-03-17 17:09
Why would whitespace in the middle be an issue? in that case one would assume that is intentional. Lots of usernames have a space in between as well.

**Comment by patsuckow** [comment] 2018-03-17 17:11
Oh, did not think about it :) Very grateful! :)

**Comment by ADmad** [comment] 2018-03-17 19:53
I don't think the framework should be auto trimming whitespaces at any layer. It can be easily achieved at app level as shown.

**Comment by dereuromark** [comment] 2018-03-18 16:33
We could however provide a small note in docs that it would be wise to do so on project level.
Especially for validation to work as intended, otherwise people can easily skip all kind of notBlank or minLength rules by hitting space a few times.
Anyway, closing then.

**Closed by dereuromark** 2018-03-18 16:33 UTC
Labels: Question, documentation

**Comment by ADmad** [comment] 2018-03-18 16:42
> otherwise people can easily skip all kind of notBlank...

You can't bypass `notBlank` validation with just spaces :)
