### ISSUE TITLE
Showing this error

### ISSUE THREAD

**Issue by Dheeraj89** [cakephp/cakephp#10316] opened 2017-02-27 06:59 UTC
I Have already updated ICU library then also this problem come.
Please tell me how to solve this problem.
Thanks

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - cakephp/cakephp 3.4.2 requires lib-icu >=4.8 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - cakephp/cakephp 3.4.1 requires lib-icu >=4.8 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - cakephp/cakephp 3.4.0 requires lib-icu >=4.8 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - Installation request for cakephp/cakephp 3.4.* -> satisfiable by cakephp/cakephp[3.4.0, 3.4.1, 3.4.2].

**Comment by ADmad** [comment] 2017-02-27 07:50
Duplicate of #10310

**Closed by ADmad** 2017-02-27 07:50 UTC
