### ISSUE TITLE
Cannot convert value of type `string` to integer - Database/TypeConverterTrait.php

### ISSUE THREAD

**Issue by icex** [cakephp/cakephp#12799] opened 2018-12-11 11:36 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.0
* Platform and Target: PHP 7.2.12, Apache/2.4.37 (Unix), MAC OS

### What you did
```
$findOptions = [
            'conditions' =>
                ['OR' =>
                     [
                         ['Ads.id LIKE' => '%mercedes%'],
                         ['Ads.name LIKE' => '%mercedes%'],
                     ],
                ],
            'fields'     => [
                'id',
                'name',
            ],
        ];
pr($this->model->find('all', $findOptions)->toArray());

```
### What happened
Cannot convert value of type `string` to integer
InvalidArgumentException
⟩ Cake\Database\Type\IntegerType->toDatabase
CORE/src/Database/TypeConverterTrait.php, line 37

With cake 3.7.0 the query param :c0 is enforced as integer, we should be able to use 
`id LIKE '%12345%'`

```
object(Cake\ORM\Query) {

	'(help)' => 'This is a Query object, to get the results execute or iterate it.',
	'sql' => 'SELECT Ads.id AS `Ads__id`, Ads.name AS `Ads__name` FROM ads Ads WHERE (Ads.id like :c0 OR Ads.name like :c1)',
	'params' => [
		':c0' => [
			'value' => '%mercedes%',
			'type' => 'integer',
			'placeholder' => 'c0'
		],
		':c1' => [
			'value' => '%mercedes%',
			'type' => 'string',
			'placeholder' => 'c1'
		]
	],
...
```

### What you expected to happen
In 3.6.14 it works as expected. :c0 is typed as integer but not enforced and it doesn't throw any error.

**Comment by markstory** [comment] 2018-12-11 17:30
Closing as #12800 has more context and this shares the same root cause.

**Closed by markstory** 2018-12-11 17:30 UTC
Labels: Defect

**Comment by codeworks** [comment] 2019-07-09 10:55
Is this actually fixed? I see there was a change for DecimalType in #12800 but I think it didn't really address this specific problem. I'm having the exact same issue with 3.8.0: The user has an input field to filter the data. The filter creates a query like:

```
$this->Users->find()->where(['OR' => ['Users.id LIKE' => '%test%', 'Users.username LIKE' => '%test%']])->first();
```

This throws an error because Users.id is an integer field in the database. I think in a find query like this, it would be a better experience to just show a page with (possibly) no results than an "internal error" page. And it doesn't really make much sense to convert the database field to a string just to be able to filter it without worrying about the user input, does it?

**Comment by lorenzo** [comment] 2019-07-09 12:12
The error is correct, you cannot use an integer column as a string. If you really want to do that, you can use the last argument of where() to override any column type for the query.
