### ISSUE TITLE
3.3 Multiple Pagination empties the scope

### ISSUE THREAD

**Issue by htstudios** [cakephp/cakephp#9210] opened 2016-08-04 16:24 UTC
This is a:
* [x] bug

* CakePHP Version: 3.3 BETA 3

### What you did
This: https://github.com/FriendsOfCake/search/pull/108

Aka I did supply friendsofcake/search with filter params that are scoped like `?Languages[code]=fr`. However paginator-sorting removes those scoped filter parameters from the query string.

### Expected Behavior
That should not happen but instead the query-string parts not relevant to the sorting should instead be ignored.

### Actual Behavior
The scoped filter paramteres are removed when paginating.

**Comment by markstory** [comment] 2016-08-04 16:37
Does your issue happen outside of the search plugin context?

**Comment by htstudios** [comment] 2016-08-04 16:59
@markstory Yes, thus this issue is not directly related to the search plugin. For me the whole query string is being removed via links generated by `PaginatiorHelper::sort()`, the only thing keeping are paginator related query string params.

I did disable all Search Plugin things (PRG Component, Model Behavior) and ran this:
```php
    public function index()
    {
        // $this->set('languages', $this->paginate(
        //     $this->Languages->find('search', ['search' => $this->request->query]), ['scope' => 'Languages']));
        $this->set('languages', $this->paginate(
            $this->Languages->find('all')));
    }
```

```
/admin/flexi-core/languages?Languages[code]=da&label=foo&sort=code&direction=desc
```

When I sort things it just changes to:

```
/admin/flexi-core/languages?Languages[code]=da&label=foo&sort=code&direction=desc
```

Then I changed the controller action code to:
```php
    public function index()
    {
        // $this->set('languages', $this->paginate(
        //     $this->Languages->find('search', ['search' => $this->request->query]), ['scope' => 'Languages']));
        $this->set('languages', $this->paginate(
            $this->Languages->find('all'), ['scope' => 'Languages']));
    }
```

I did enter this request into my browser bar:
```
/admin/flexi-core/languages?Languages[code]=da&label=foo&sort=code&direction=desc
```

When I sort things it just changes to:

```
/admin/flexi-core/languages?Languages[sort]=code&Languages[direction]=asc&label=foo&sort=code&direction=desc
```
E.g. the unprefixed query-string parameter is persisted, however the one that is within the scope is not persisted.

Last, using the same code as above I did enter this

```
/admin/flexi-core/languages?LanguagesFilter[code]=da
```
after sorting it became:
```
/admin/flexi-core/languages?LanguagesFilter[code]=da&Languages[sort]=code&Languages[direction]=desc
```

Thus the scoped part of the query string is discarded and only the parts relevant to the paginator are being kept (by PaginatorHelper). Whereas for the unscoped parts (and those set to another scope/prefix) there is no such issue.

**Comment by htstudios** [comment] 2016-08-05 10:06
The issue seems to have to do with `Router::build()` getting a mix of query string and query string params.

E.g.  from the book
```php
// Generate a URL using a named route,
// with some query string args.
$url = Router::url(['_name' => 'login', 'username' => 'jimmy']);
```
http://book.cakephp.org/3.0/en/development/routing.html#using-named-routes

Now if request `/admin/flexi-core/languages/index/foo/bar/quux?Languages[sort]=code&Languages[direction]=asc&Languages[code]=da` and I run at the bottom of 3.next's `public function generateUrl(array $options = [], $model = null, $full = false) {` this debug:
```php
        $return = $this->Url->build($url, $full);
        debug($url);
        debug($return);
        return $return;
```
I get back
```php
[
	'Languages' => [
		'sort' => 'code',
		'direction' => 'desc',
		'order' => null
	],
	(int) 0 => 'foo',
	(int) 1 => 'bar',
	(int) 2 => 'quux',
	'?' => [
		'Languages' => [
			'sort' => 'code',
			'direction' => 'asc',
			'code' => 'da'
		]
	]
]
```

`'/admin/flexi-core/languages/index/foo/bar/quux?Languages%5Bsort%5D=code&amp;Languages%5Bdirection%5D=desc'`

However the router only respects:

```
	'Languages' => [
		'sort' => 'code',
		'direction' => 'desc',
		'order' => null
	],
```

While this is being discarded

```php
	'?' => [
		'Languages' => [
			'sort' => 'code',
			'direction' => 'asc',
			'code' => 'da'
		]
	]
```

@markstory **Could it be a bug around merging scoped query string parameters within the router?**

**Comment by markstory** [comment] 2016-08-05 18:39
> Could it be a bug around merging scoped query string parameters within the router?

Could be. Perhaps there is a missing merge between the current scope and the `?` key?

**Comment by htstudios** [comment] 2016-08-05 21:29
I could narrow it down a bit more but got lost in `RouteCollection::match()`

If within `Router::url()`, I replace 
```php
            $output = static::$_collection->match($url, static::$_requestContext + ['params' => $params]);
```

with

```php
            $foo = false; if (isset($url['LanguagesScope']) || isset($url['Languages'])) { $foo = true; }
            if($foo) debug($params);
            if($foo) debug($url);
            $output = static::$_collection->match($url, static::$_requestContext + ['params' => $params]);
```

And request /admin/flexi-core/languages?Languages%5Bcode%5D=d%2A

These are the results 

### LanguagesScope = working

```
[
	'plugin' => 'FlexiCore',
	'controller' => 'Languages',
	'action' => 'index',
	'_ext' => null,
	'pass' => [],
	'prefix' => 'admin',
	'_matchedRoute' => '/admin/flexi-core/:controller',
	'isAjax' => false,
	'paging' => [
		'Languages' => [
			'finder' => 'all',
			'page' => (int) 1,
			'current' => (int) 2,
			'count' => (int) 2,
			'perPage' => (int) 20,
			'prevPage' => false,
			'nextPage' => false,
			'pageCount' => (int) 1,
			'sort' => null,
			'direction' => false,
			'limit' => null,
			'sortDefault' => false,
			'directionDefault' => false,
			'scope' => 'LanguagesScope'
		]
	]
]
```

```
[
	'LanguagesScope' => [
		'sort' => 'code',
		'direction' => 'asc',
		'order' => null
	],
	'?' => [
		'Languages' => [
			'code' => 'd*'
		]
	],
	'action' => 'index',
	'prefix' => 'admin',
	'plugin' => 'FlexiCore',
	'controller' => 'Languages',
	'_ext' => null
]
```

### Languages = not working

```
[
	'plugin' => 'FlexiCore',
	'controller' => 'Languages',
	'action' => 'index',
	'_ext' => null,
	'pass' => [],
	'prefix' => 'admin',
	'_matchedRoute' => '/admin/flexi-core/:controller',
	'isAjax' => false,
	'paging' => [
		'Languages' => [
			'finder' => 'all',
			'page' => (int) 1,
			'current' => (int) 2,
			'count' => (int) 2,
			'perPage' => (int) 20,
			'prevPage' => false,
			'nextPage' => false,
			'pageCount' => (int) 1,
			'sort' => null,
			'direction' => false,
			'limit' => null,
			'sortDefault' => false,
			'directionDefault' => false,
			'scope' => 'Languages'
		]
	]
]
```

```

	'Languages' => [
		'sort' => 'code',
		'direction' => 'asc',
		'order' => null
	],
	'?' => [
		'Languages' => [
			'code' => 'd*'
		]
	],
	'action' => 'index',
	'prefix' => 'admin',
	'plugin' => 'FlexiCore',
	'controller' => 'Languages',
	'_ext' => null
```


However for `LanguagesScope` the output of ```static::$_collection->match($url, static::$_requestContext + ['params' => $params]);```still carries the filter param, whereas for `Languages` it does not.

In `RouteCollection::match()` I think somewhere in this block the difference is being created:
```
            foreach ($this->_routeTable[$name] as $route) {
                $match = $route->match($url, $context);
                if ($match) {
                    return strlen($match) > 1 ? trim($match, '/') : $match;
                }
            }
```

I got lost there.
The current workaround is using `LanguageScope` as a scope name to not collide with the filtering.

**Comment by markstory** [comment] 2016-08-06 02:34
Couldn't the merge between the scoped query string, and the standard URL parameters be done in the PaginatorHelper?

**Comment by htstudios** [comment] 2016-08-08 09:48
@markstory 
1. I could, I tried and the tests went crazy.
2. Isn't still something wrong about `Router::url()` / `RouteCollection::match()` not merging named params (? or whatever those should be called, what are they called?=) and query string params into the query string?

So even if I find a way around 1. there is still a bug in 2.?

**Comment by markstory** [comment] 2016-08-08 21:28
Explicit query string parameters shouldn't be merged with the 'routing keys'. Merging the `?` into the routing keys could overwrite the routing keys. While merging routing keys into `?` will result in all routing keys being set as query string parameters.

I'm hoping to find time to look at this issue this week.

**Comment by htstudios** [comment] 2016-08-10 09:02
@markstory Thank you.

**Comment by markstory** [comment] 2016-08-11 02:54
I was able to reproduce the issue tonight. I'll take a look into the cause and possible solution tomorrow.

**Comment by markstory** [comment] 2016-08-12 02:23
Pull request up now.

**Closed by markstory** 2016-08-12 02:23 UTC
Labels: Defect, pagination
