### ISSUE TITLE
Serialization of 'SplFileObject' is not allowed when using authentication/authorization middleware in routes with route caching enabled

### ISSUE THREAD

**Issue by steven-v** [cakephp/cakephp#15484] opened 2021-05-03 18:10 UTC
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.5
* Authentication Version: 2.6.1
* Authorization Version: 2.1.0

### What you did
registered authentication or authorization middleware in routes with route caching enabled

enabled route caching
```php
// Application.php
public function middleware(MiddlewareQueue $middlewareQueue): MiddlewareQueue
{
    $middlewareQueue
        ->add(new ErrorHandlerMiddleware(Configure::read('Error')))
        ->add(new AssetMiddleware([
            'cacheTime' => Configure::read('Asset.cacheTime'),
        ]))
        ->add(new RoutingMiddleware($this, '_cake_routes_'))
        ->add(new BodyParserMiddleware())
        ->add(new CsrfProtectionMiddleware([
            'httponly' => true,
        ]));

    return $middlewareQueue;
}
```
registered authentication or authorization middleware in routes
```php
// Application.php
 public function routes(RouteBuilder $routes): void
  {
      $routes->registerMiddleware('authentication', new AuthenticationMiddleware($this));
      $routes->registerMiddleware('authorization', new AuthorizationMiddleware($this));
      
      parent::routes($routes);
  }
```

### What happened
When route caching is enabled and I register authentication or authorization middleware in routes the exception `Serialization of 'SplFileObject' is not allowed` is thrown

**Comment by ADmad** [comment] 2021-05-03 18:14
Duplicate of https://github.com/cakephp/cakephp/issues/12129.

**Comment by othercorey** [comment] 2021-05-03 21:41
Should we wrap the exception with an error message explaining?

**Comment by steven-v** [comment] 2021-05-08 08:48
An error message explaining what is going one would be nice, as know it is a very vague what is going on
I haven't had the time to deep dive and figure out exactly what the problem is, but knowing why this is happening and maybe even what the solution is would be nice to know.
Also why this happens when you register a middleware through routes but not through middleware.

**Closed** 2022-02-18 05:26 UTC
Labels: documentation, routing, pinned
