### ISSUE TITLE
EntityTrait::setHidden() with $merge set to TRUE returns wrong results.

### ISSUE THREAD

**Issue by alysson-azevedo** [cakephp/cakephp#10361] opened 2017-03-06 14:44 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: v3.4.2.
* Platform and Target: PHP 7.0.15-0ubuntu0.16.10.4

When the `_hidden` property is not empty and we call `$entity->setHidden(['some_field'], true)`, the ["merge"](https://api.cakephp.org/3.4/source-class-Cake.Datasource.EntityTrait.html#436) fails.

I don't know about other versions, but in php7, Array + Array only works well with associative arrays.

**Comment by dereuromark** [comment] 2017-03-06 14:45
You are not using it as intended (see also test cases):

    [
        'some_field' => true,
        'other' => false,
    ]

etc. So it is always an assoc. array.

**Comment by alysson-azevedo** [comment] 2017-03-06 14:48
But the [docs](https://book.cakephp.org/3.0/en/orm/entities.html#hiding-properties) says:
```
protected $_hidden = ['password'];
```
Should it be change to ['password'=>true] ?

**Comment by alysson-azevedo** [comment] 2017-03-06 15:17
@dereuromark i could not find the test case, but what you said didn't work.

```
$entity = new Entity(['field1' => 'a', 'field2' => 'b', 'field3' => 'c']);

$entity->setHidden(['field1' => true], true);
$entity->visibleProperties() //returns ["field1", "field2", "field3"]

$entity->setHidden(['field1'], true);
$entity->visibleProperties() //returns [1 => "field2", 2 => "field3"]

$entity->setHidden(['field2' => true], true);
$entity->visibleProperties() //returns [1 => "field2", 2 => "field3"]

$entity->setHidden(['field2'], true);
$entity->visibleProperties() //returns [1 => "field2", 2 => "field3"]
```

**Comment by dereuromark** [comment] 2017-03-06 15:26
Looks like you are right, according to https://github.com/cakephp/cakephp/blob/master/tests/TestCase/ORM/EntityTest.php#L1029 the syntax of yours should work.

**Comment by dereuromark** [comment] 2017-03-06 15:30
So the https://github.com/cakephp/cakephp/blob/master/src/Datasource/EntityTrait.php#L436 seems to be the cause of the issue, assoc. array merging is only OK with string key based arrays (the syntax I thought it would use). Apparently the documented syntax is the one in use, and that one collides with the way it gets merged here. :/

**Comment by markstory** [comment] 2017-03-07 01:37
Closing as a pull request is open now.

**Closed by markstory** 2017-03-07 01:37 UTC
Labels: Defect, ORM
