### ISSUE TITLE
Warning Error: Fixture creation failed "SQLSTATE[42704]: Undefined object: 7 ERROR:  type "jsonb" does not exist"

### ISSUE THREAD

**Issue by erochaamorim** [cakephp/cakephp#11790] opened 2018-03-05 20:08 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.4
* Platform and Target:
  * Apache:
  ```
  Server version: Apache/2.4.18 (Ubuntu)
  Server built:   2017-09-18T15:09:02
  ```
   * PHP:
  ```
  PHP 7.1.11-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Oct 27 2017 13:49:56) ( NTS )
  Copyright (c) 1997-2017 The PHP Group
  Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies with Zend OPcache v7.1.11-        1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies with Xdebug v2.5.5,     Copyright (c) 2002-2017, by Derick Rethans
  ```
   * PostgreSQL:
  ```
  PostgreSQL 9.3.21 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3)   4.8.4, 64-bit
  ```
  * PHPUnit
  `PHPUnit 6.5.7 by Sebastian Bergmann and contributors.`

### What you did

I'm trying to run a test, but when I try to use a fixture for a table that has a json field, it doesn't works.
Bellow follows the shell command, the test, and the fixture.

### Shell Command
`vendor/bin/phpunit --group matricula_preprocessamento`

### Test File
```
<?php
namespace App\Test\TestCase\Model\Table;

use App\Model\Table\AptosTable;
use App\Test\TestCase\LoadDatabaseFunctionsTrait;
use Cake\ORM\TableRegistry;
use Cake\TestSuite\TestCase;

/**
 * App\Model\Table\AptosTable Test Case
 */
class AptosTableTest extends TestCase
{

    use LoadDatabaseFunctionsTrait;
    /**
     * Test subject
     *
     * @var \App\Model\Table\AptosTable $Aptos
     */
    public $Aptos;

    /**
     * @var \App\Model\Table\EventosTable $Eventos
     */
    public $Eventos;

    /**
     * Fixtures
     *
     * @var array
     */
    public $fixtures = [

        'app.aptos',
        'app.academicos',
        'app.cursos_sequencias',
        'app.ocorrencias',
        'app.tipo_ocorrencias',
        'app.academicos_turmas',
        'app.turmas',
        'app.grades',
        'app.eventos'

    ];

    /**
     * setUp method
     *
     * @return void
     */
    public function setUp()
    {

        parent::setUp();
        $config = TableRegistry::exists('Aptos') ? [] : ['className' => AptosTable::class];
        $this->Aptos = TableRegistry::get('Aptos', $config);
        $this->Eventos = TableRegistry::get('Eventos');
        $this->loadDatabaseFunction('get_percentual_carga_horaria');

    }

    /**
     * tearDown method
     *
     * @return void
     */
    public function tearDown()
    {

        unset($this->Aptos);
        parent::tearDown();

    }


    /**
     * @group matricula
     * @group matricula_preprocessamento
     */
    public function testGerarAptosMatricula()
    {

        $evento = $this->Eventos->get(1, ['contain' => ['PeriodoLetivos'] ]);
        $filtros = [];
        $info = [];
        $this->Aptos->gerarAptosMatricula($evento, $filtros, $info);
        $this->assertEquals(0, $info['nroAptos']);

    }
}
```
### Fixture File
```
<?php
namespace App\Test\Fixture;

use Cake\TestSuite\Fixture\TestFixture;

/**
 * EventosFixture
 *
 */
class EventosFixture extends TestFixture
{

    /**
     * Table name
     *
     * @var string
     */
    public $table = 'eventos';

    /**
     * Fields
     *
     * @var array
     */
    // @codingStandardsIgnoreStart
    public $fields = [
        'id' => ['type' => 'integer', 'length' => 10, 'autoIncrement' => true, 'default' => null, 'null' => false, 'comment' => null, 'precision' => null, 'unsigned' => null],
        'descricao' => ['type' => 'string', 'length' => 128, 'default' => null, 'null' => false, 'collate' => null, 'comment' => null, 'precision' => null, 'fixed' => null],
        'tipo_evento_id' => ['type' => 'integer', 'length' => 10, 'default' => null, 'null' => false, 'comment' => null, 'precision' => null, 'unsigned' => null, 'autoIncrement' => null],
        'inicio' => ['type' => 'timestamp', 'length' => null, 'default' => null, 'null' => false, 'comment' => null, 'precision' => null],
        'fim' => ['type' => 'timestamp', 'length' => null, 'default' => null, 'null' => false, 'comment' => null, 'precision' => null],
        'periodo_letivo_id' => ['type' => 'integer', 'length' => 10, 'default' => null, 'null' => false, 'comment' => null, 'precision' => null, 'unsigned' => null, 'autoIncrement' => null],
        'criterios' => ['type' => 'json', 'length' => null, 'default' => null, 'null' => false, 'comment' => null, 'precision' => null],
        'data_criacao' => ['type' => 'timestamp', 'length' => null, 'default' => null, 'null' => false, 'comment' => null, 'precision' => null],
        'data_alteracao' => ['type' => 'timestamp', 'length' => null, 'default' => null, 'null' => true, 'comment' => null, 'precision' => null],
        '_constraints' => [
            'primary' => ['type' => 'primary', 'columns' => ['id'], 'length' => []],
            'eventos_periodo_letivo_id' => ['type' => 'foreign', 'columns' => ['periodo_letivo_id'], 'references' => ['periodo_letivos', 'id'], 'update' => 'noAction', 'delete' => 'noAction', 'length' => []],
            'eventos_tipo_evento_id' => ['type' => 'foreign', 'columns' => ['tipo_evento_id'], 'references' => ['tipo_eventos', 'id'], 'update' => 'noAction', 'delete' => 'noAction', 'length' => []],
        ],
    ];
    // @codingStandardsIgnoreEnd

    /**
     * Records
     *
     * @var array
     */
    public $records = [
        [
            'id' => 1,
            'descricao' => 'Matrícula Online dos Veteranos dos Cursos Presenciais 2018/1',
            'tipo_evento_id' => 12,
            'inicio' => '2018-02-08 07:00:00',
            'fim' => '2018-02-09 23:59:59',
            'periodo_letivo_id' => 2,
            'criterios' => array (
  'modalidade_id' => '1',
),
            'data_criacao' => '2018-01-25 09:50:16',
            'data_alteracao' => '2018-02-06 07:18:29'
        ],
        [
            'id' => 5,
            'descricao' => 'Análise dos Pedidos de Ajustes pelo Coordenador de Curso 2018/1',
            'tipo_evento_id' => 15,
            'inicio' => '2018-02-19 00:00:00',
            'fim' => '2018-03-02 00:00:00',
            'periodo_letivo_id' => 2,
            'criterios' => array (
),
            'data_criacao' => '2018-02-06 07:25:40',
            'data_alteracao' => '2018-02-06 07:27:50'
        ],
        [
            'id' => 6,
            'descricao' => 'Validação de Matrículas 2018/1',
            'tipo_evento_id' => 16,
            'inicio' => '2018-02-26 00:00:00',
            'fim' => '2018-03-16 00:00:00',
            'periodo_letivo_id' => 2,
            'criterios' => array (
),
            'data_criacao' => '2018-02-06 07:26:58',
            'data_alteracao' => '2018-02-06 07:27:52'
        ],
        [
            'id' => 2,
            'descricao' => 'Pré-processamento da Matrícula Online dos Veteranos dos Cursos Presenciais 2018/1',
            'tipo_evento_id' => 11,
            'inicio' => '2018-02-05 16:00:00',
            'fim' => '2018-02-08 06:59:59',
            'periodo_letivo_id' => 2,
            'criterios' => array (
  'modalidade_id' => '1',
),
            'data_criacao' => '2018-02-05 16:11:04',
            'data_alteracao' => '2018-02-06 07:18:31'
        ],
        [
            'id' => 3,
            'descricao' => 'Distribuição de Vagas 2018/1',
            'tipo_evento_id' => 13,
            'inicio' => '2018-02-14 13:30:00',
            'fim' => '2018-02-16 06:59:00',
            'periodo_letivo_id' => 2,
            'criterios' => array (
  'modalidade_id' => '1',
),
            'data_criacao' => '2018-02-06 07:14:41',
            'data_alteracao' => '2018-02-06 07:18:33'
        ],
        [
            'id' => 4,
            'descricao' => 'Solicitação de Ajustes de Matrícula 2018/1',
            'tipo_evento_id' => 14,
            'inicio' => '2018-02-16 07:00:00',
            'fim' => '2018-02-21 23:59:59',
            'periodo_letivo_id' => 2,
            'criterios' => array (
  'modalidade_id' => '1',
),
            'data_criacao' => '2018-02-06 07:16:49',
            'data_alteracao' => '2018-02-06 07:18:36'
        ],
    ];
}

```

### What happened
```
PHPUnit 4.8.36 by Sebastian Bergmann and contributors.

Warning Error: Fixture creation for "eventos" failed "SQLSTATE[42704]: Undefined object: 7 ERROR:  type "jsonb" does not exist at character 214" in [/home/erick.amorim/www/siscad/implementacao/vendor/cakephp/cakephp/src/TestSuite/Fixture/TestFixture.php, line 306]

Exception: Unable to insert fixtures for "App\Test\TestCase\Model\Table\AptosTableTest" test case. SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block in [/home/erick.amorim/www/siscad/implementacao/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureManager.php, line 348]
```

### What you expected to happen
The test should run smoothly, since I runned almost the same test without problems with all the other fixtures. But when I add this one, with a json field, it doesn't works.

I'm aware CakePHP ORM and PostgreSQL versions I'm using have support for json fields, becausing we are using them in the application, and it works perfectly.

I'm not sure if it's a problem with PHPUnit, but since the class throwing the error is Cake's, maybe there's something missing.

Also I have no idea why it seems to exchange the type "json" for "jsonb" when it runs... seems fishy.

**Comment by markstory** [comment] 2018-03-06 02:14
Does your postgres version support the `jsonb` type? We use that type for postgres as it has offers more flexible querying and indexing than the `json` type does.

**Comment by erochaamorim** [comment] 2018-03-06 11:18
As a matter of fact, PostgreSQL 9.3.22 does not support the `jsonb` type;  the support starts with PostgreSQL 9.4

**Comment by erochaamorim** [comment] 2018-03-06 11:19
Is there anyway to support the json type in Cake's TestSuit?

**Comment by markstory** [comment] 2018-03-06 19:56
>  I find it kinda confusing that the json type works in the application, but not in the TestSuit.

This is because in the test suite, CakePHP generates schema based on the fixtures, whereas in the normal application runtime CakePHP is reflecting schema metadata.

We don't currently have a configuration based way to map the abstract 'json' type into the concrete 'json' type in postgres. It can be done by subclassing the [Postgres Driver](https://github.com/cakephp/cakephp/blob/master/src/Database/Driver/Postgres.php) and [postgres schema](https://github.com/cakephp/cakephp/blob/master/src/Database/Schema/PostgresSchema.php).

I'm going to close this as the code is working as intended and your postgres version just doesn't support the required column types.

**Closed by markstory** 2018-03-06 19:56 UTC
Labels: Defect, On hold, postgres
