### ISSUE TITLE
Cannot issue HTTPS request via Proxy using HttpClient

### ISSUE THREAD

**Issue by Antoniossss** [cakephp/cakephp#10841] opened 2017-06-30 12:24 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

Cakephp 3.4.5

```
config: 
            "proxy" => [
                "proxy" => "pl3.nordvpn.com:80"
                "username" => "xx",
                "password" => "xx"
            ]

$client=new HttpClient($config);
$client->get('http://api.ipify.org'); // works, returns proxied ip
$client->get('https://api.ipify.org'); // does not work 
```

This is respone object for https call
```

object(Cake\Http\Client\Response) {
	[protected] code => (int) 400
	[protected] reasonPhrase => 'Bad Request'
	[protected] _xml => null
	[protected] _json => null
	[protected] _exposedProperties => [
		'cookies' => '_cookies',
		'body' => '_getBody',
		'code' => 'code',
		'json' => '_getJson',
		'xml' => '_getXml',
		'headers' => '_getHeaders'
	]
	[protected] _cookies => []
	[protected] _body => null
	[protected] headers => [
		'Connection' => [
			(int) 0 => 'close'
		],
		'Server' => [
			(int) 0 => 'Cowboy'
		],
		'Date' => [
			(int) 0 => 'Fri, 30 Jun 2017 12:21:45 GMT'
		],
		'Content-Length' => [
			(int) 0 => '0'
		]
	]
	[protected] headerNames => [
		'connection' => 'Connection',
		'server' => 'Server',
		'date' => 'Date',
		'content-length' => 'Content-Length'
	]
	[private] protocol => '1.1'
	[private] stream => object(Zend\Diactoros\Stream) {
		[protected] resource => resource
		[protected] stream => 'php://memory'
	}
}
```
Response body is empty.

**Comment by markstory** [comment] 2017-06-30 17:43
That looks like a valid response. Is that 400 coming from the proxy or the destination server?

**Comment by Antoniossss** [comment] 2017-06-30 20:58
I have no idea. This response object is from
`$response=$client->get('https://api.ipify.org');`

It should be code 200 with ip string in body (like for `http://api.ipify.org` call)

**Comment by markstory** [comment] 2017-07-01 00:42
There isn't really a way to trace http requests made by the client. We rely on php streams to make the actual HTTP requests.

**Comment by yomexzo** [comment] 2017-11-11 14:38
@Antoniossss, did you make the request outside CakePHP? just to confirm the problem is from Cake.

**Comment by markstory** [comment] 2018-03-20 02:41
I took a second look at this, and it appears to be a problem with the stream APIs in PHP. Using [mitmproxy](https://mitmproxy.org/) I was able to successfully connect to a server using cURL CLI:

```
curl --proxy localhost:8080 --cacert ~/.mitmproxy/mitmproxy-ca-cert.pem https://stickler-ci.com
```

While even a basic PHP stream API usage failed.

```php
        $opts = array(
            'http' => [
                'proxy' => 'localhost:8080',
                'request_fulluri' => true,
                'ignore_errors' => true,
            ],
            'ssl' => [
                // With SNI enabled, I get a 400 like you did.
                'SNI_enabled' => false,
                'cafile' => '/Users/markstory/.mitmproxy/mitmproxy-ca-cert.pem',
            ],
        );
        $context = stream_context_create($opts);

        $data = file_get_contents('https://stickler-ci.com?stream=true', false, $context);
        debug($data);
```

Fails with

```
<html>
            <head>
                <title>502 Bad Gateway</title>
            </head>
            <body>
            <h1>502 Bad Gateway</h1>
            <p>TlsProtocolException(&quot;Cannot establish TLS with stickler-ci.com:443 (sni: None): TlsException(&#x27;Cannot validate certificate hostname without SNI&#x27;,)&quot;,)</p>
            </body>
        </html>
```

I found a related [PHP bug](https://bugs.php.net/bug.php?id=63519) but the workarounds listed there didn't solve the problem for me. This may require the creation/usage of a cURL based adapter as from my research cURL doesn't have the same limitations that the native PHP implementation does.

**Comment by markstory** [comment] 2018-08-01 01:25
Closing as the new Curl adapter will resolve this.

**Closed by markstory** 2018-08-01 01:25 UTC
Labels: Defect, http
