### ISSUE TITLE
EntityContext will not correctly set _isCollection

### ISSUE THREAD

**Issue by advitum** [cakephp/cakephp#16247] opened 2022-01-17 18:14 UTC
When creating an EntityContext from any kind of iterable of multiple Entities (collection, array or whatever), the property _isCollection is not set to be true. This is due to the code which inspects the Entities for a Table modifies the variable `$entity` to contain the first Entity, and that variable is then checked for being a collection:

See https://github.com/cakephp/cakephp/blob/4.x/src/View/Form/EntityContext.php

```
$entity = $this->_context['entity'];
if (empty($table)) {
  if (is_iterable($entity)) {
    foreach ($entity as $e) {
      $entity = $e;
      break;
    }
  }
[...]
$this->_isCollection = (
  is_array($entity) ||
  $entity instanceof Traversable
);
```

I am not sure if this is the desired or expected behavior, rather than a bug.
A bugfix would be trivial, just using `$this->_context['entity']` for the check rather than `$entity`.

Does anyone know if this behavior is intended?

### CakePHP Version

4.3.4

**Comment by markstory** [comment] 2022-01-17 19:26
How could someone reproduce the problem you're having?

**Comment by advitum** [comment] 2022-01-18 07:19
# How to reproduce

**Comment by advitum** [comment] 2022-01-18 07:21
# How to Reproduce

```
// In the Controller
$examples = [
  'key1' => $this->Examples->newEmptyEntity(),
  'key2' => $this->Examples->newEmptyEntity(),
  'key3' => $this->Examples->newEmptyEntity(),
];

// In the view template
echo $this->Form->create($examples);
dd($this->Form->context());
```

The resulting debug output reveals:

> protected _isCollection => false

**Comment by ADmad** [comment] 2022-01-18 07:31
What problem do you face when using the FormHelper due to this?

**Comment by advitum** [comment] 2022-01-18 07:52
The problem is an unexpected inconsistency depending on wether the table is explicitly set or not.

This results in "null", because _isCollection is correctly set to true:
```
echo $this->Form->create($examples, [
  'context' => ['table' => 'Examples'],
]);
dd($this->Form->context()->val('key1'));
```

But when the table is not explicitly set, `val` returns the first entity instead of null:
```
echo $this->Form->create($examples);
dd($this->Form->context()->val('key1'));
```

And since the FormHelper uses the EntityContext::val method to populate default values of form fields, the difference in behavior appears there too. The following field default value will be empty when table is set, but contain the entire entity as json when the table is not set:

```
echo $this->Form->input('key1');
```

**Comment by ADmad** [comment] 2022-01-18 07:59
> ..but contain the entire entity as json when the table is not set:

That would only happen if you are using a numeric value as field name `input('0')` which in practice doesn't make much sense :slightly_smiling_face:. 

That said the inconsistency should be fixed.

**Closed as completed** 2022-01-18 15:31 UTC
Labels: defect
