### ISSUE TITLE
3.0 - Sorting by id column in Pagination

### ISSUE THREAD

**Issue by MichaelHoughton** [cakephp/cakephp#6597] opened 2015-05-20 11:34 UTC
When Pagination in CakePHP 3.0, I have the following in my view:

    <th><?= $this->Paginator->sort('id', 'PO#') ?></th>

In the Controller I have:

    $this->paginate['contain'] = ['Clients', 'Types'];
    $this->set('campaigns', $this->paginate($this->Campaigns));

Because I am using contain with my Pagination, when I try to sort by the "id" field, I get the following error message:

    Error: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in order clause is ambiguous 

With CakePHP 2, the Pagination would assume I am filtering by the current model, however, in CakePHP 3, it doesn't seem to be doing this.

Expected outcome: It should sort by Campaigns.id by default, not through an error.

**Comment by dereuromark** [comment] 2015-05-20 12:19
Yes, it should just prefix the field in general to avoid this issue.

**Comment by MichaelHoughton** [comment] 2015-05-20 14:40
Hey @dereuromark - just checked it on CakePHP 3.05 and it was doing it alright.

?sort=id&direction=asc

Is the URL.

Let me know if you need any more info to help with this.

**Comment by dereuromark** [comment] 2015-05-20 14:41
What is the generated query that breaks?

**Comment by MichaelHoughton** [comment] 2015-05-20 14:43
SELECT Campaigns.id AS `Campaigns__id`, Campaigns.client_id AS `Campaigns__client_id`, Campaigns.organization_id AS `Campaigns__organization_id`, Campaigns.type_id AS `Campaigns__type_id`, Campaigns.collection_id AS `Campaigns__collection_id`, Campaigns.address_id AS `Campaigns__address_id`, Campaigns.invoice_email AS `Campaigns__invoice_email`, Campaigns.printer_id AS `Campaigns__printer_id`, Campaigns.designer_id AS `Campaigns__designer_id`, Campaigns.sample_size_id AS `Campaigns__sample_size_id`, Campaigns.abd_sample_id AS `Campaigns__abd_sample_id`, Campaigns.secret_str AS `Campaigns__secret_str`, Campaigns.title AS `Campaigns__title`, Campaigns.descr AS `Campaigns__descr`, Campaigns.expiration AS `Campaigns__expiration`, Campaigns.style AS `Campaigns__style`, Campaigns.proof_file AS `Campaigns__proof_file`, Campaigns.proof2_file AS `Campaigns__proof2_file`, Campaigns.proof3_file AS `Campaigns__proof3_file`, Campaigns.proof4_file AS `Campaigns__proof4_file`, Campaigns.printer_image_file AS `Campaigns__printer_image_file`, Campaigns.embroidery_file AS `Campaigns__embroidery_file`, Campaigns.min_price AS `Campaigns__min_price`, Campaigns.price AS `Campaigns__price`, Campaigns.sale_price AS `Campaigns__sale_price`, Campaigns.delivery AS `Campaigns__delivery`, Campaigns.approved AS `Campaigns__approved`, Campaigns.status AS `Campaigns__status`, Campaigns.created AS `Campaigns__created`, Campaigns.modified AS `Campaigns__modified`, Campaigns.graphic_file AS `Campaigns__graphic_file`, Campaigns.goal_reached AS `Campaigns__goal_reached`, Campaigns.shipped AS `Campaigns__shipped`, Campaigns.mode_id AS `Campaigns__mode_id`, Campaigns.notes AS `Campaigns__notes`, Campaigns.holographic_stickers AS `Campaigns__holographic_stickers`, Campaigns.vendor_id AS `Campaigns__vendor_id`, Campaigns.user_id AS `Campaigns__user_id`, Campaigns.priority AS `Campaigns__priority`, Campaigns.closed AS `Campaigns__closed`, Campaigns.closed_date AS `Campaigns__closed_date`, Campaigns.estimated_quantity AS `Campaigns__estimated_quantity`, Campaigns.notify_quantity_sent AS `Campaigns__notify_quantity_sent`, Campaigns.order_count AS `Campaigns__order_count`, Campaigns.notify_date AS `Campaigns__notify_date`, Campaigns.notify_about_approve_sent AS `Campaigns__notify_about_approve_sent`, Campaigns.size_chart_file AS `Campaigns__size_chart_file`, Campaigns.approved_date AS `Campaigns__approved_date`, Campaigns.size_chart_link AS `Campaigns__size_chart_link`, Campaigns.try_close AS `Campaigns__try_close`, Campaigns.parent_id AS `Campaigns__parent_id`, Campaigns.featured AS `Campaigns__featured`, Campaigns.hide AS `Campaigns__hide`, Campaigns.hide_status_bar AS `Campaigns__hide_status_bar`, Campaigns.data_feed AS `Campaigns__data_feed`, Campaigns.style_id AS `Campaigns__style_id`, Campaigns.fb_tracking AS `Campaigns__fb_tracking`, Campaigns.google_category AS `Campaigns__google_category`, Campaigns.color AS `Campaigns__color`, Campaigns.material AS `Campaigns__material`, Campaigns.pattern AS `Campaigns__pattern`, Campaigns.owner_id AS `Campaigns__owner_id`, Clients.id AS `Clients__id`, Clients.address_id AS `Clients__address_id`, Clients.university_id AS `Clients__university_id`, Clients.organization_id AS `Clients__organization_id`, Clients.organization AS `Clients__organization`, Clients.contact AS `Clients__contact`, Clients.email AS `Clients__email`, Clients.phone AS `Clients__phone`, Clients.owner_id AS `Clients__owner_id`, Clients.category_id AS `Clients__category_id`, Clients.stage_id AS `Clients__stage_id`, Clients.status_id AS `Clients__status_id`, Clients.next_meeting AS `Clients__next_meeting`, Clients.newsletter AS `Clients__newsletter`, Clients.fb_tracking AS `Clients__fb_tracking`, Clients.notes AS `Clients__notes`, Clients.created AS `Clients__created`, Clients.modified AS `Clients__modified`, Types.id AS `Types__id`, Types.name AS `Types__name` FROM campaigns Campaigns LEFT JOIN clients Clients ON Clients.id = (Campaigns.client_id) INNER JOIN types Types ON Types.id = (Campaigns.type_id) ORDER BY id asc LIMIT 20 OFFSET 0

You can see the:

    ORDER BY id asc

At the end, which is the cause.

**Comment by markstory** [comment] 2015-05-20 20:52
I can fix that. The paginator should be adding the alias when possible.

**Comment by markstory** [comment] 2015-05-21 01:36
I tried to reproduce this with 3.0.5, and I wasn't able to. I started with a baked app, and added `contain` options.  Sorting by a duplicate column (id) did not generate a SQL error as the sort column was prefixed correctly.

**Comment by MichaelHoughton** [comment] 2015-05-21 10:39
Hey @markstory - anything I could do to provide this in more detail?  Can you give me an indication where this is in the CakePHP library, I will try to debug this myself and see if I can find anything.

Thanks again.

**Comment by AD7six** [comment] 2015-05-21 12:00
> anything I could do to provide this in more detail?

Reproduction steps.

I suggest to have a look what the options are [where the find call is](https://github.com/cakephp/cakephp/blob/master/src/Controller/Component/PaginatorComponent.php#L163-L167) - then determine why in your case [this isn't executed](https://github.com/cakephp/cakephp/blob/master/src/Controller/Component/PaginatorComponent.php#L333-L349) - or if it is, the reason the order clause is generated without an alias.

**Comment by AD7six** [comment] 2015-05-21 12:01
Also I find this confusing:

> Hey @dereuromark - just checked it on CakePHP 3.05 and it was doing it alright.
>
> ?sort=id&direction=asc
>
> Is the URL.

If 3.0.5 is doing it correctly - in what version is there an error?

**Comment by MichaelHoughton** [comment] 2015-05-21 12:19
They @AD7six - the issue is with 3.05.

**Comment by AD7six** [comment] 2015-05-21 18:03
@MichaelHoughton that isn't a valid version number, branch or tag.

**Comment by dereuromark** [comment] 2015-05-21 22:26
The only thing I could imagine happening, would be https://github.com/cakephp/cakephp/blob/master/src/Controller/Component/PaginatorComponent.php#L336-L337
That you have some custom sort on top with a numeric index which makes the prefixing skip.

Do you have any special setup on top?

**Comment by MichaelHoughton** [comment] 2015-05-22 06:16
Hey @dereuromark - found the issue.

I have my sorWhiteList as:

    public $paginate = [
        'sortWhitelist' => [
            'id', 'title', 'Clients.organization', 'created', 'Vendors.name', 'Designers.name', 'Users.username'
        ]
    ];

If I set it as the following:

    public $paginate = [
        'sortWhitelist' => [
            'Campaigns.id', 'title', 'Clients.organization', 'created', 'Vendors.name', 'Designers.name', 'Users.username'
        ]
    ];

Then it works.

But if I do NOT prefix the 'id' in the sortWhitelist, then it throws that error.

Does this help at all?

**Comment by dereuromark** [comment] 2015-05-22 07:54
Yes, that information would have helped in the first place ;)

And I found the issue, preparing a PR now: https://github.com/cakephp/cakephp/compare/master-pagination

**Comment by dereuromark** [comment] 2015-05-22 08:25
That change breaks a few tests, and so does https://github.com/cakephp/cakephp/compare/master-pagination-fix .

I guess we either have to auto-prefix the whitelist before comparing, too. Or we have to expect devs to always manually prefix the whitelist fields here. I would prefer option one.

**Comment by MichaelHoughton** [comment] 2015-05-22 08:47
@dereuromark - I would definitely prefer option 1 if possible.

Glad we found the issue, apologies for not sending that through earlier!

**Comment by dereuromark** [comment] 2015-05-22 09:17
I think I got it :)
Closing as a PR is now open.

**Closed by dereuromark** 2015-05-22 09:17 UTC
Labels: Defect, pagination
