### ISSUE TITLE
Saving entity: String vs decimal in 4.0.0

### ISSUE THREAD

**Issue by mrothauer** [cakephp/cakephp#14088] opened 2019-12-28 15:23 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.0
* Platform and Target: Apache 2.0, MySQL 5.7, PHP 7.3

### What you did
I upgraded my application to v4.0.0.

### What happened
Saving an entity now leads to an error that did not occur in v3.8.7.
Here are two tests that show the different behavior (both pass): If the value is passed as string, saving the entity works as expected. If the value is passed as decimal, `InvalidArgumentException` `Cannot convert value of type `string` to a decimal` occurs.
https://github.com/foodcoopshop/foodcoopshop/blob/8de9bedf2be9093cd394ece3107008f04f8724b5/tests/TestCase/src/Controller/CartsControllerTest.php#L702-L727

### What you expected to happen
My guess is that in v3.8.7 data was always passed as string and therefore the problem did not occur. Am I right with that suspection? If so, do you have ideas to solve that problem?

UPDATE: My locale is set to de_DE

**Comment by ADmad** [comment] 2019-12-28 16:37
> UPDATE: My locale is set to de_DE

That's might be the issue. Apparently the behavior of `is_numeric()` is affected by locale set :rage:.

**Comment by ADmad** [comment] 2019-12-28 16:52
I am unable to reproduce the issue.

I add a `I18n::setLocale('de_DE')` call to test method below and still all tests pass:

https://github.com/cakephp/cakephp/blob/40f515b7f4e4f2b03a5f0acfe0f298fe41260cfc/tests/TestCase/Database/Type/DecimalTypeTest.php#L124-L149

**Comment by mrothauer** [comment] 2019-12-28 17:34
Thank you for your quick response. I'll dig deeper...

**Comment by mrothauer** [comment] 2019-12-28 17:52
I found out, that the entities contain values with strings **that are separated with commas** (in de_DE `1.2` is written `1,2`). This worked in v3.8.7 and triggers the mentioned error in v4.0.0. Does that help you? 

Could you try a new test case?

```
I18n::setLocale('de_DE');
$result = $this->type->toDatabase('1,2', $this->driver); 
$this->assertSame(1.2, $result);

```

**Comment by ADmad** [comment] 2019-12-28 19:18
Did passing value as `'1,2'` actually get saved in the database?

**Comment by othercorey** [comment] 2019-12-29 01:13
How did the tests in your description pass if they were using decimal instead of comma values?

**Comment by mrothauer** [comment] 2019-12-29 08:24
@ADmad No, it did not get saved (because the exception was triggered before).
@othercorey Somehow they were correctly converted into decimals.

New hint:
`vendor/bin/phpunit --filter UnitsTableTest::testSaveProductOK`

If I dump

```
pr($value);
pr(gettype($value));
```

in v3.8.7: Database/TypeConverterTrait.php::35
the type is `decimal`

in v.4.0.0: Database/TypeConverterTrait.php::38
the type is `string`

Maybe the issue is a database issue?

**Comment by mrothauer** [comment] 2019-12-29 08:27
If you want to reproduce the error:

v3.8.7: https://github.com/foodcoopshop/foodcoopshop (develop branch)
v4.0.0: https://github.com/foodcoopshop/foodcoopshop/tree/feature/issue-445-cakephp-4-update

https://github.com/foodcoopshop/foodcoopshop#unit-testing

**Comment by ADmad** [comment] 2019-12-29 08:51
> @ADmad No, it did not get saved (because the exception was triggered before).

I meant in 3.8.

**Comment by ADmad** [comment] 2019-12-29 09:11
In 3.x `DecimalType::toDatabase()` simply casts every value to float

https://github.com/cakephp/cakephp/blob/d01515c90646590183e34bc40cf8d9911f88ef5c/src/Database/Type/DecimalType.php#L109

Casting `'2,5'` to float results in `2`. So even though your test case passes on 3.x, incorrect value would be saved in database (which you are not checking). 

Closing the issue as throwing an exception is actually an improvement over storing incorrect value in db.

**Closed by ADmad** 2019-12-29 09:11 UTC
Labels: defect

**Comment by mrothauer** [comment] 2019-12-29 10:01
Everything was saved correctly. Thanks for checking everything, it seems the problem is not v4.0.0, but my - surely not perfect - application. I'll tell you my solution.

**Comment by mrothauer** [comment] 2019-12-29 20:52
It turned out that the line
`setlocale(LC_ALL, 'de_DE.UTF-8');`
in my bootstrap.php messed up the php NumberFormatter
This did not cause problems in v3.8.7 and it took me quite a while to find that out.
Everything fine again!
