### ISSUE TITLE
Cannot enable component callbacks

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#9660] opened 2016-10-27 11:07 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.9.
* Platform and Target: Linux, Apache, PHP 5.5.9

### What you did
Tried to enable component callbacks in a component:
```
	public $components = array(
		'MyComponent' => array(
			'enabled' => true,
		),
	);
```
I tracked the problem to Component::__get() line 93:
`$settings = array('enabled' => false) + (array)$this->_componentMap[$name]['settings'];` and [this commit](https://github.com/cakephp/cakephp/commit/a7744e6ff41b225432c85946ac6aa75612f4c7ee).

It seems + does not work as expected.
A simple test:
```
$v = array('enabled' => false) + array('enabled'=> true);
debug($v);
$v = array_merge(array('enabled' => false), array('enabled'=> true));
debug($v);
```
outputs
```
...
array(
	'enabled' => false
)
...
array(
	'enabled' => true
)
```

There could be more places with a similar issue.

### What happened
Callbacks were not enabled.

### Expected Behavior
MyComponent component callbacks to be enabled and triggered.

**Comment by dereuromark** [comment] 2016-10-27 12:15
Technically the commit is not responsible per se, as the functionality was the same before and after, as both ways of merging are completely identical:
```php
$settings = array_merge((array)$this->_componentMap[$name]['settings'], array('enabled' => false));
$settings = array('enabled' => false) + (array)$this->_componentMap[$name]['settings'];
```

But it does indeed reveal that the order here was wrong in the first place probably.
The settings of the component should be prioritized over the defaults here when merging.
A test case to back this up has probably always been missing so far.
So please, feel free to open a PR with the switched order and possible a test to back things up and prevent regression in the future.

**Comment by markstory** [comment] 2016-10-27 22:37
I don't think the current code is incorrect. In `Component::__get()` components of components will be lazily constructed, and components of components *should not* be attached to event listeners. Is there a reason you can't append `MyComponent` to the required Controller?

**Comment by bancer** [comment] 2016-10-28 08:16
> I don't think the current code is incorrect. In Component::__get() components of components will be lazily constructed, and components of components should not be attached to event listeners. 

And they are not attached by default. But when one explicitly uses `'enabled' => true,` anyone would expect callbacks to be enabled.

> Is there a reason you can't append MyComponent to the required Controller?

There is no reason why it can't be done. But when a component is used in multiple controllers then that extra component would need to be appended to each controller.

**Comment by markstory** [comment] 2016-10-28 16:01
> But when one explicitly uses 'enabled' => true, anyone would expect callbacks to be enabled.

Fair point.

**Comment by thinkingmedia** [comment] 2016-10-28 16:13
I noticed that this feature introduces a new configuration options `enabled` to components.

For example:

```
class FooComponent extends Component {}

class AppleComponent extends Component {
    public $components = ['Foo'];
}

$apple = new AppleComponent();
$apple->Foo->config('enabled') === false; // this is true

$foo = new FooComponent();
$foo->config('enabled') === null; // this is true
```

The config option `enabled` is used by the `ComponentRegistry` but it's passed along to the component's configuration. I worry this could have side effects if a developer ever wanted to use the config key `enabled` in their component.

They would never notice anything was wrong until that component was lazy loaded via another component.

Is there a better way to handle this?

**Comment by dereuromark** [comment] 2016-10-28 16:23
Can we remove it before the component options are passed in?

**Comment by thinkingmedia** [comment] 2016-10-28 19:40
I don't think the component's configuration should even be touched.

We should deprecate the `enabled` option when lazy loading, and developers that want to have event listeners on inner components should load them manually with the flag turned on via the ComponentRegistry.

**Comment by markstory** [comment] 2016-10-29 01:38
@thinkingmedia I don't think that `enabled` is new. It has been a part of the ComponentRegistry since the 2.x days. It might not have always been well documented though.

**Comment by markstory** [comment] 2016-10-29 02:10
Closing as there are pull requests open/merged for both 2.x and 3.x

**Closed by markstory** 2016-10-29 02:10 UTC
Labels: Defect
