### ISSUE TITLE
PaginatorComponent cannot sort on associated table

### ISSUE THREAD

**Issue by cmann1** [cakephp/cakephp#6780] opened 2015-06-10 19:52 UTC
Even once the columns are added to `sortWhitelist`, associated tables are completely ignored.
Looking through the code I cannot see that it is even possible.

First looking at `PaginatorComponent` in the `validateSort` method on line 332, `$options['order']` still contains the correct order paramaters.

It is then passed to the `_prefix` method, and on line 358 there is this code:
```php
$correctAlias = ($tableAlias === $alias);
```
which as far as I can tell will prevent sorting on any table expect the original.

**Comment by lorenzo** [comment] 2015-06-10 20:26
Duplicate of https://github.com/cakephp/cakephp/issues/6778

**Closed by lorenzo** 2015-06-10 20:26 UTC
