### ISSUE TITLE
Get URL from CakeRequest as array

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#10092] opened 2017-01-23 09:00 UTC
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 2.x
* Platform and Target: any.

Sometimes there is a need to get the URL from the request in array format. I did not find any method in CakeRequest or Router that does that. The closest method that does something similar is Router::reverse()  but it returns a string. I would suggest to refactor it slightly. Something like this:

```
	public static function reverse($params, $full = false) {
                $params = Router::reverseToArray($params);
		return Router::url($params, $full);
	}

	public static function reverseToArray($params) {
		if ($params instanceof CakeRequest) {
			$url = $params->query;
			$params = $params->params;
		} else {
			$url = $params['url'];
		}
		$pass = isset($params['pass']) ? $params['pass'] : array();
		$named = isset($params['named']) ? $params['named'] : array();

		unset(
			$params['pass'], $params['named'], $params['paging'], $params['models'], $params['url'], $url['url'],
			$params['autoRender'], $params['bare'], $params['requested'], $params['return'],
			$params['_Token']
		);
		$params = array_merge($params, $pass, $named);
		if (!empty($url)) {
			$params['?'] = $url;
		}
                return $params;
        }

**Comment by dereuromark** [comment] 2017-01-23 09:35
Sounds like a duplicate of my https://github.com/cakephp/cakephp/issues/1926 back then :)
Just that no one ever did the work - it was a valid ticket but got closed then.

**Comment by markstory** [comment] 2017-01-23 14:45
What kind of scenarios do you end up using this?

**Comment by bancer** [comment] 2017-01-23 15:39
@markstory Using for redirect() calls in controllers when AppController::redirect() alters the redirect URL by setting localization parameters. The scenario is similar as described in https://github.com/cakephp/cakephp/issues/1926: 
> This is often the case when we want to add some named or pass params or some hash.

**Comment by markstory** [comment] 2017-01-23 16:12
Should converting a request's parameters into an array that is compatible with Router::url() be something that the request does?

**Comment by dereuromark** [comment] 2017-01-23 16:15
I initially opened this on the router level, to be able to return as array from there.
In order to further post-process it from there on continuing the array access.

**Comment by saeideng** [comment] 2017-01-23 17:25
you need somthing like this :)
$this->redirect($this->request->modifyAction('edit'));

**Comment by saeideng** [comment] 2017-01-23 17:28
that is compatible with psr-7 @markstory :)
modifyAction() Or withAction()

**Comment by markstory** [comment] 2017-01-24 01:59
@saeideng Why would you need to modify the request? From the other comments it sounded like people wanted a way to get a version of the request data that can be combined with `Router::url()`. The method you're proposing looks very much like `withParam()`.

**Comment by markstory** [comment] 2017-02-04 17:11
Closing as #10113 is open now.

**Closed by markstory** 2017-02-04 17:11 UTC
Labels: Enhancement, RFC
