### ISSUE TITLE
Duplicate Named Route for plugin

### ISSUE THREAD

**Issue by Erwane** [cakephp/cakephp#12130] opened 2018-05-24 14:04 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.4

### What you did
load plugin with routes in bootstrap
`Plugin::load('I18nUrl', ['routes' => true]);`

call `Plugin::routes()` at the end of config/routes.php in base app

create a route in plugin
```php
use Cake\Routing\Router;
use Cake\Routing\RouteBuilder;

Router::plugin('Backend', ['path' => '/gestion'], function (RouteBuilder $routes) {
    $routes->connect('/', ['controller' => 'Dashboard', 'action' => 'index'], ['_name' => 'backend.dashboard']);
});
```

### What happened
`Cake\Routing\Exception\DuplicateNamedRouteException`
`Error: A route named "backend.dashboard" has already been connected to "/gestion".`

### What you expected to happen
no duplicate routes

## where to search
It's look like the RoutingMiddleware now check if $this->app is instance of PluginApplicationInterface

the src/Application extends BaseApplication which implement PluginApplicationInterface SO the standard application build plugin routes twice, first via application and bootstrap, second time via the `RoutingMiddleware::prepareRouteCollection()`

**Comment by Erwane** [comment] 2018-05-24 14:10
i've put debug on these lines

config/routes.php, before `Plugin::routes()`
Backend/config/routes.php in line 2
Cake\Routing\Middleware line 112 before `$this->app->pluginRoutes($builder);`

output : 
```
/config/routes.php (line 108)
'/var/www/html/config/routes.php'
/plugins/Backend/config/routes.php (line 2)
'/var/www/html/plugins/Backend/config/routes.php'
/src/Routing/Middleware/RoutingMiddleware.php (line 112)
'Cake\Routing\Middleware\RoutingMiddleware::prepareRouteCollection'
/plugins/Backend/config/routes.php (line 2)
'/var/www/html/plugins/Backend/config/routes.php'
```
the Backend/config/routes.php was loaded twice

**Comment by markstory** [comment] 2018-05-24 18:21
You should remove the `Plugin::routes()` call in your routes file. It is only necessary if you are using the deprecated Dispatcher classes.

**Comment by markstory** [comment] 2018-05-24 18:22
One possible solution is to make `Plugin::routes()` do nothing when an `Application` class can be found. We could emit a deprecation warning as well to let folks know they should remove the `Plugin::routes()` call.

**Comment by Erwane** [comment] 2018-05-24 19:32
the cakephp/app project suggest it : 

https://github.com/cakephp/app/blob/3.6.1/config/routes.php

**Comment by markstory** [comment] 2018-05-25 01:14
@Erwane Yes. There is an issue to remove it. I've just not gotten around to it.

**Comment by markstory** [comment] 2018-05-26 15:27
Pull request open to deprecate `Plugin::routes()` and the application skeleton was updated in cakephp/app#610

**Comment by mirko-pagliai** [comment] 2018-06-13 12:56
Sorry if I reopen this issue, but I have a problem that may be the same or similar or related.

`routes.php`:

```
Router::plugin('RecaptchaMailhide', ['path' => '/'], function (RouteBuilder $routes) {
    $routes->connect('/mailhide', ['controller' => 'Mailhide', 'action' => 'display'], ['_name' => 'mailhide']);
});
```

This first works with `Plugin::routes()`.  
Now If I remove it, it can not find the route anymore.

If instead I replace it with this:  
```
Router::scope('/', function ($routes) {
    $routes->loadPlugin(RecaptchaMailhide);
});
```
I get a `DuplicateNamedRouteException`:

```
Cake\Routing\Exception\DuplicateNamedRouteException: A route named "mailhide" has already been connected to "/mailhide".

/home/mirko/Libs/Plugins/cakephp-recaptcha-mailhide/vendor/cakephp/cakephp/src/Routing/RouteCollection.php:106
/home/mirko/Libs/Plugins/cakephp-recaptcha-mailhide/vendor/cakephp/cakephp/src/Routing/RouteBuilder.php:729
/home/mirko/Libs/Plugins/cakephp-recaptcha-mailhide/config/routes.php:21
/home/mirko/Libs/Plugins/cakephp-recaptcha-mailhide/vendor/cakephp/cakephp/src/Routing/RouteBuilder.php:993
/home/mirko/Libs/Plugins/cakephp-recaptcha-mailhide/vendor/cakephp/cakephp/src/Routing/Router.php:1048
/home/mirko/Libs/Plugins/cakephp-recaptcha-mailhide/vendor/cakephp/cakephp/src/Routing/Router.php:1124
/home/mirko/Libs/Plugins/cakephp-recaptcha-mailhide/config/routes.php:25
/home/mirko/Libs/Plugins/cakephp-recaptcha-mailhide/src/Plugin.php:27
/home/mirko/Libs/Plugins/cakephp-recaptcha-mailhide/vendor/cakephp/cakephp/src/Http/BaseApplication.php:182
/home/mirko/Libs/Plugins/cakephp-recaptcha-mailhide/vendor/cakephp/cakephp/src/TestSuite/MiddlewareDispatcher.php:122
/home/mirko/Libs/Plugins/cakephp-recaptcha-mailhide/vendor/cakephp/cakephp/src/TestSuite/MiddlewareDispatcher.php:96
/home/mirko/Libs/Plugins/cakephp-recaptcha-mailhide/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestCase.php:491
/home/mirko/Libs/Plugins/cakephp-recaptcha-mailhide/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestCase.php:375
/home/mirko/Libs/Plugins/cakephp-recaptcha-mailhide/tests/TestCase/Controller/MailhideControllerTest.php:132
```
In fact, as you can see from the stacktrace, the file is included twice.  
If I add a `stackTrace()` call inside the file, I get this:

```
phpunit --filter testDisplayMissingRecaptchaComponent                                          
PHPUnit 6.5.8 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)require - APP/config/routes.php, line 26
Cake\Http\BaseApplication::routes() - CORE/src/Http/BaseApplication.php, line 172
Cake\TestSuite\MiddlewareDispatcher::resolveRoute() - CORE/src/TestSuite/MiddlewareDispatcher.php, line 119
Cake\TestSuite\MiddlewareDispatcher::resolveUrl() - CORE/src/TestSuite/MiddlewareDispatcher.php, line 96
Cake\TestSuite\IntegrationTestCase::_sendRequest() - CORE/src/TestSuite/IntegrationTestCase.php, line 491
Cake\TestSuite\IntegrationTestCase::get() - CORE/src/TestSuite/IntegrationTestCase.php, line 375
RecaptchaMailhide\Test\TestCase\Controller\MailhideControllerTest::testDisplayMissingRecaptchaComponent() - ROOTtests/TestCase/Controller/MailhideControllerTest.php, line 132
ReflectionMethod::invokeArgs() - [internal], line ??
PHPUnit\Framework\TestCase::runTest() - ROOTvendor/phpunit/phpunit/src/Framework/TestCase.php, line 1072
PHPUnit\Framework\TestCase::runBare() - ROOTvendor/phpunit/phpunit/src/Framework/TestCase.php, line 940
PHPUnit\Framework\TestResult::run() - ROOTvendor/phpunit/phpunit/src/Framework/TestResult.php, line 698
PHPUnit\Framework\TestCase::run() - ROOTvendor/phpunit/phpunit/src/Framework/TestCase.php, line 895
PHPUnit\Framework\TestSuite::run() - ROOTvendor/phpunit/phpunit/src/Framework/TestSuite.php, line 755
PHPUnit\Framework\TestSuite::run() - ROOTvendor/phpunit/phpunit/src/Framework/TestSuite.php, line 755
PHPUnit\TextUI\TestRunner::doRun() - ROOTvendor/phpunit/phpunit/src/TextUI/TestRunner.php, line 546
PHPUnit\TextUI\Command::run() - ROOTvendor/phpunit/phpunit/src/TextUI/Command.php, line 195
PHPUnit\TextUI\Command::main() - ROOTvendor/phpunit/phpunit/src/TextUI/Command.php, line 148
[main] - ROOTvendor/phpunit/phpunit/phpunit, line 53
```

Can it be related to this problem?

**Comment by markstory** [comment] 2018-06-13 15:09
If you are using `$routes->loadPlugin()` you currently also need to disable the routes hook for your plugin. I can look into making those two ways of loading plugin routes work better together. I think it should be solvable if plugins track whether or not their routes have been included yet.

**Comment by mirko-pagliai** [comment] 2018-06-15 10:39
@markstory ok. I'm not particularly interested in using the `loadPlugin()` method.  
The problem is that if I use it the routes are duplicated, while if I do not use it the routes are non-existent.  
The wrong behavior seems to me the second, but the first seems to me correct (I need to disable the routes hook for plugin).

**Comment by saeideng** [comment] 2018-06-15 11:05
@mirko-pagliai a PR now is open for this problem 
https://github.com/cakephp/cakephp/pull/12245

**Comment by markstory** [comment] 2018-06-15 17:58
@mirko-pagliai Ok. In the scenario where you are not using `Plugin::routes()` how are you loading your plugin? Does your application use an `Application` class?

**Comment by mirko-pagliai** [comment] 2018-06-19 11:35
Yes, the plugin is loaded by the `Application` class. I said it works only setting the `routes` option as `false`:

`$this->addPlugin(RecaptchaMailhide::class, ['routes' => false]);`

In other words, instead without the `routes` option the routes are duplicated

`$this->addPlugin(RecaptchaMailhide::class);`

**Comment by markstory** [comment] 2018-06-19 14:20
@mirko-pagliai Could you see if the changes merged to `master` resolve your issue?

**Comment by mirko-pagliai** [comment] 2018-06-19 18:01
Tomorrow I will try.

Meanwhile, I point out that even the bootstrap file is included twice and
also in this case it is necessary to use the `bootstrap` option in the
`Application` class, so the bootstrap file is included only once.

I do not know if all this is wanted, but I say that normally I would expect
that using the `Application` class are not used even the traditional
methods.
Instead if I use the `Application` class, I'm forced to load plugins but
disabling all file inclusions.

Il mar 19 giu 2018, 16:21 Mark Story <notifications@github.com> ha scritto:

**Comment by markstory** [comment] 2018-06-19 20:48
@mirko-pagliai When using `addPlugin()` are you also leaving `Plugin::load()` calls behind? You should only have one or the other. In the applications I have I'm not able to replicate the duplicate the double bootstrap issue.

**Comment by markstory** [comment] 2018-06-20 18:28
Closing as this should be resolved in 3.6.6.

**Closed by markstory** 2018-06-20 18:28 UTC
Labels: Defect, plugins, routing

**Comment by mirko-pagliai** [comment] 2018-07-02 11:12
I do not know if this problem is corrected too.

However, even with the `master branch`, I always get the `DuplicateNamedRouteException:` exception if, within the same test method, I call the `ConsoleIntegrationTestCase::exec()` method several times.

```
1) Thumber\Test\TestCase\Command\ClearCommandTest::testExecute
Cake\Routing\Exception\DuplicateNamedRouteException: A route named "thumb" has already been connected to "/thumb/:basename".

/home/mirko/Libs/Plugins/cakephp-thumber/vendor/cakephp/cakephp/src/Routing/RouteCollection.php:106
/home/mirko/Libs/Plugins/cakephp-thumber/vendor/cakephp/cakephp/src/Routing/RouteBuilder.php:593
/home/mirko/Libs/Plugins/cakephp-thumber/vendor/cakephp/cakephp/src/Routing/RouteBuilder.php:480
/home/mirko/Libs/Plugins/cakephp-thumber/config/routes.php:20
/home/mirko/Libs/Plugins/cakephp-thumber/vendor/cakephp/cakephp/src/Routing/RouteBuilder.php:1010
/home/mirko/Libs/Plugins/cakephp-thumber/vendor/cakephp/cakephp/src/Routing/Router.php:1047
/home/mirko/Libs/Plugins/cakephp-thumber/vendor/cakephp/cakephp/src/Routing/Router.php:1123
/home/mirko/Libs/Plugins/cakephp-thumber/config/routes.php:23
/home/mirko/Libs/Plugins/cakephp-thumber/vendor/cakephp/cakephp/src/Core/BasePlugin.php:228
/home/mirko/Libs/Plugins/cakephp-thumber/vendor/cakephp/cakephp/src/Http/BaseApplication.php:186
/home/mirko/Libs/Plugins/cakephp-thumber/vendor/cakephp/cakephp/src/Console/CommandRunner.php:380
/home/mirko/Libs/Plugins/cakephp-thumber/vendor/cakephp/cakephp/src/Console/CommandRunner.php:150
/home/mirko/Libs/Plugins/cakephp-thumber/vendor/cakephp/cakephp/src/TestSuite/ConsoleIntegrationTestCase.php:95
/home/mirko/Libs/Plugins/cakephp-thumber/tests/TestCase/Command/ClearCommandTest.php:56
```

It seems that, even in this case, the `routes.php` is included twice.

**Comment by markstory** [comment] 2018-07-02 14:14
Yes that would happen. ConsoleIntegration tests don't currently reset router state. That could be added though.
