### ISSUE TITLE
CakePHP don't create right simple plugin code

### ISSUE THREAD

**Issue by canon4o** [cakephp/cakephp#7757] opened 2015-11-29 17:28 UTC
Hi everybody,

I did fresh copy of CakePHP v3.1.4 via composer, and then I follow documentation step by step for create custom plugin and after all steps CakePHP throw exception. When I copy-paste location in browser "http://192.168.0.200/plugins/contact-manager/contacts" ("plugins" is my root directory of project), I see "Missing Controller Cake\Routing\Exception\MissingControllerException.  Error: ContactManagerController could not be found. Error: Create the class ContactManagerController below in file: src/Controller/ContactManagerController.php".

The solution of problem is in ContactManager/config/routes.php file.
After install code in this file looks like:
```php
Router::plugin('ContactManager', function ($routes) {
    $routes->fallbacks('DashedRoute');
});
```
But this don't work.
The work version of code looks like:
```php
Router::scope('/contact-manager', ['plugin' => 'ContactManager'], function ($routes) {
    $routes->fallbacks();
});
```

Please update official documentation. :)

**Comment by ADmad** [comment] 2015-11-29 17:34
The issue is if you don't pass `path` key in `$options` of `Router::plugin()` it uses underscore inflected plugin name. So the bake code needs to explicitly set `$options['path']` to dash inflected plugin name.

**Comment by canon4o** [comment] 2015-11-29 18:05
OK, and this is a variant also.

**Comment by ADmad** [comment] 2015-11-29 18:16
https://github.com/cakephp/bake/commit/bef3c061bb9b805124d8c2d016c148bfa77a0ae5 fixes the baked code. I'll update docs too.

Sorry team, I mistakenly pushed the commit to master instead of making a pull request.

**Comment by markstory** [comment] 2015-11-30 01:51
Closing as bake and the docs have been updated.

**Closed by markstory** 2015-11-30 01:51 UTC
Labels: Defect
