### ISSUE TITLE
SOAP Client exception cannot be caught 

### ISSUE THREAD

**Issue by waspinator** [cakephp/cakephp#8501] opened 2016-03-21 02:52 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: CakePHP Version: 3.2.3
* Platform and Target: Apache 2.4.12 (Win32) PHP 5.6.11 MySQL 5.6.25, GET

### What you did
I tried to call a SOAP API as a client and catch a fatal error, caused by missing WSDL file or network connectivity issues.

    try {
        $soap_client = new SoapClient($wsdl_file, ['exceptions' => true]);
    } 
    catch (SoapFault $e) {
        echo 'a soap error occurred<br>';
    } 
    echo 'I can still do stuff after the error<br>';

The code above works in vanilla PHP, but not in CakePHP.

### Expected Behavior
I should be able to catch the exception

### Actual Behavior
The exception is not caught

**Comment by chinpei215** [comment] 2016-03-21 03:47
Have you imported the SoapFault class?
```php
use SoapFault;
```

**Comment by josegonzalez** [comment] 2016-03-21 04:02
That wasn't it. Seems like our ErrorHandler caught the error because the soap extension throws an exception *and* sets an error...

**Comment by lorenzo** [comment] 2016-03-21 07:28
Please look at the accepted answer in this question http://stackoverflow.com/questions/6374345/php-soapfault-not-caught-by-exception-handlers

**Comment by josegonzalez** [comment] 2016-03-21 07:34
@lorenzo the SoapFault still emits an error, so even if we catch the exception, at the end of execution we check for any errors and throw a FatalErrorException wrapping the soap error.

**Comment by chinpei215** [comment] 2016-03-21 08:12
@josegonzalez I understood what you mean. You are right.

**Comment by chinpei215** [comment] 2016-03-21 08:46
@josegonzalez I came up with a workaround.
```php
$restore = error_reporting(0);
try {
    $soap_client = new SoapClient($wsdl_file, ['exceptions' => true]);
}
catch (SoapFault $e) {
    $e->_; // Overwrites E_ERROR with E_NOTICE
}
finally {
    error_reporting($restore);
}
```

**Comment by josegonzalez** [comment] 2016-03-21 08:52
Doesn't work in PHP 5.6?

**Comment by chinpei215** [comment] 2016-03-21 08:55
I confirmed in PHP 5.6. It works by using the workaround.

**Comment by josegonzalez** [comment] 2016-03-21 08:57
Can you test that in both a web and shell context?

**Comment by chinpei215** [comment] 2016-03-21 09:03
I confirmed in a shell now. Both work for me.

**Comment by markstory** [comment] 2016-03-21 15:23
This is not an issue in CakePHP, but an annoying behavior in the PHP provided soap client. We have to do similar workarounds in [the socket class](https://github.com/cakephp/cakephp/blob/master/src/Network/Socket.php#L152-L171) and the related [error swallower](https://github.com/cakephp/cakephp/blob/master/src/Network/Socket.php#L231-L234).

Closing as @chinpei215's suggestion is the correct solution.

**Closed by markstory** 2016-03-21 15:23 UTC

**Comment by paulrwest** [comment] 2016-04-08 14:26
I just want to add I came across this problem and the suggested solution wasn't working for me what did work was catching \SoapFault with the backslash:

```
try
 {
   $client = new SoapClient( $wsdl, $this->config );
   $response = $client->SubmitJob( $param );
}
catch (\SoapFault $fault) 
{
  // custom logging here
}
```

**Comment by tersmitten** [comment] 2016-04-08 15:49
Did the `\` fix the problem?

**Comment by josegonzalez** [comment] 2016-04-08 15:52
@paulrwest you'd want the `\` or add `use SoapFault;` to the top of your class.

**Comment by thiagosathler** [comment] 2020-10-28 23:54
> 
> 
> Did the `\` fix the problem?

Work for me!

**Comment by iAmRivard** [comment] 2023-03-09 19:51
> I just want to add I came across this problem and the suggested solution wasn't working for me what did work was catching \SoapFault with the backslash:
> 
> ```
> try
>  {
>    $client = new SoapClient( $wsdl, $this->config );
>    $response = $client->SubmitJob( $param );
> }
> catch (\SoapFault $fault) 
> {
>   // custom logging here
> }
> ```

Work for me! 2023-03
