### ISSUE TITLE
$request->data not populated when using PUT method

### ISSUE THREAD

**Issue by kamui545** [cakephp/cakephp#6051] opened 2015-03-11 13:14 UTC
Hello,

I'm using Cake3 for a REST API, but it seems that $request->data is not populated when using PUT methods (probably the same for DELETE?).

How to reproduce:

routes.php

```php
Router::scope('/', function ($routes) {
    $routes->extensions(['json']);
    $routes->resources('Recipes');
});
```
RecipesController.php

```php
namespace App\Controller;

class RecipesController extends AppController
{
	public function add()
	{
		debug($this->request->data); exit;
	}
	
	public function edit()
	{
		debug($this->request->data); exit;
	}
}
```

Then, if you try a POST request (add), you will see your data, not when using PUT (edit).

I tested using Postman, PHP Storm REST client and Cake HTTP client, same issue.
The problem may be located here: https://github.com/cakephp/cakephp/blob/3.0/src/Network/Request.php#L278-283

It seems it doesn't enter this condition...

**Comment by lorenzo** [comment] 2015-03-11 13:34
Are you sending `Content-type:application/x-www-form-urlencoded` ? because otherwise cake cannot know what was sent

**Comment by kamui545** [comment] 2015-03-11 13:59
![screen shot 2015-03-11 at 21 51 45](https://cloud.githubusercontent.com/assets/356978/6597660/17f8cf74-c839-11e4-8df4-1f8b3f087957.png)

Yes, I'm sending it =/

**Comment by lorenzo** [comment] 2015-03-11 14:01
are you sending data? what does `$this->request->env('CONTENT_TYPE')` return? I hope it is the same

**Comment by lorenzo** [comment] 2015-03-11 14:02
Try reading `$this->request->input()` and show me the result

**Comment by kamui545** [comment] 2015-03-11 14:10
Yes, I'm sending 'foo=bar'.

```
var_dump($this->request->env('HTTP_CONTENT_TYPE')); // application/x-www-form-urlencoded
var_dump($this->request->env('CONTENT_TYPE')); // null
var_dump($this->request->input()); // foo=bar
var_dump($this->request->data); // empty array
```

As you guessed, CONTENT_TYPE is not the same... What's the difference between them?

**Comment by lorenzo** [comment] 2015-03-11 14:19
maybe a bug in cake... I need to investigate

**Comment by kamui545** [comment] 2015-03-11 14:21
Thanks mate, I'm investigating as well, I'll come to you if I find something

**Comment by kamui545** [comment] 2015-03-11 14:53
Oh, I think I found something interesting...
Using nginx, content-type is the same, using the built-in server (bin/cake server) it is not.

**Comment by lorenzo** [comment] 2015-03-11 15:15
oh, that's unexpected!

**Comment by markstory** [comment] 2015-03-12 01:25
The following works fine for me using apache 2.

```
curl -XPUT -H 'Content-type:application/x-www-form-urlencoded' cake3.localhost/bookmarks/edit/1 -d 'name=test&body=thing'
```
But the same request did not work against the php5.4 server. I'll take a look at why that's the case.

**Comment by markstory** [comment] 2015-03-12 01:40
Closing as I have a pull request open that solves the issue for the PHP webserver.

**Closed by markstory** 2015-03-12 01:40 UTC
Labels: On hold

**Comment by challgren** [comment] 2016-02-16 01:08
This bug is also present in 2.8.0

**Comment by BassemN** [comment] 2016-07-14 15:35
Hi,

Sorry for not opening a new issue but my problem is related to this one.
I'm on CakePHP version 3.2.11. I have the same issue, PUT method not working on one of clients website
```php
debug($this->request->env('HTTP_CONTENT_TYPE')); // null
debug($this->request->env('CONTENT_TYPE')); // application/x-www-form-urlencoded
debug($this->request->input()); // _method=PUT&_csrfToken=b58a3143dfad5820fab1628de3a9635ac2ddbd15dd5c93cf047c5c22fd74d8774f30c6eeba17ab12ca65b79f1358286150c7c078e5899f6b81f1b586dbaf75f9&id=1&title=Terms+of+Use&slug=terms&published=1&content=Terms&_Token%5Bfields%5D=724db447a316a30a22f513be16b9e3fa484e613d%253Aid&_Token%5Bunlocked%5D=g-recaptcha-response&_Token%5Bdebug%5D=%255B%2522%255C%252Fadmin%255C%252Fpages%255C%252Fedit%255C%252F1%2522%252C%257B%2522id%2522%253A%25221%2522%252C%25220%2522%253A%2522title%2522%252C%25221%2522%253A%2522slug%2522%252C%25222%2522%253A%2522published%2522%252C%25223%2522%253A%2522content%2522%257D%252C%255B%2522g-recaptcha-response%2522%255D%255D
debug($this->request->data); // []
```
Please advise

**Comment by markstory** [comment] 2016-07-14 18:22
@BassemN Take a look at #9073 and see if that solves your issue?

**Comment by BassemN** [comment] 2016-07-14 20:24
@markstory It doesn't fix the issue, I'll try to update the entire framework and feed you back

**Comment by BassemN** [comment] 2016-07-14 22:39
@markstory I'm still getting the results
```php
debug($this->request->env('HTTP_CONTENT_TYPE')); // null
debug($this->request->env('CONTENT_TYPE')); // application/x-www-form-urlencoded
debug($this->request->input()); // _method=PUT&_csrfToken=1e6ad415707b313f1b3982d41405e720b590fa461d07c41fd5c5e7d10dd9cc3f25fc8d05ffb3931663222c2c10cc652763072fc52a1d0901c6de561937a6ad87&id=1&title=Terms+of+Use&slug=terms&published=1&content=Terms&_Token%5Bfields%5D=724db447a316a30a22f513be16b9e3fa484e613d%253Aid&_Token%5Bunlocked%5D=g-recaptcha-response&_Token%5Bdebug%5D=%255B%2522%255C%252Fadmin%255C%252Fpages%255C%252Fedit%255C%252F1%2522%252C%257B%2522id%2522%253A%25221%2522%252C%25220%2522%253A%2522title%2522%252C%25221%2522%253A%2522slug%2522%252C%25222%2522%253A%2522published%2522%252C%25223%2522%253A%2522content%2522%257D%252C%255B%2522g-recaptcha-response%2522%255D%255D
debug($this->request->data); // []
```

**Comment by markstory** [comment] 2016-07-15 01:18
What does `$this->request->contentType()` return? That is the method that is used when building the 'post' data.

**Comment by BassemN** [comment] 2016-07-15 09:55
Kindly check the return
```php
debug( $this->request->contentType() ); // application/x-www-form-urlencoded
```

**Comment by markstory** [comment] 2016-07-15 14:36
@BassemN Then I have no idea what's going on. [This is the code that parses URLencoded PUT data](https://github.com/cakephp/cakephp/blob/master/src/Network/Request.php#L281-L286) perhaps look there and see why your requests are not passing those conditions.

**Comment by ironbone** [comment] 2016-09-29 21:45
The problem is that 
$data = $this->input();
returns an empty string
