### ISSUE TITLE
Wrong date&time format in condition "where" for 3rd level joined model

### ISSUE THREAD

**Issue by pavel-dovgoshiya** [cakephp/cakephp#15452] opened 2021-04-12 16:35 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.5
* Platform and Target: LAMP, PHP 7.2, Mysql 5.7

### What you did
I have installed fresh cakephp by instruction here https://book.cakephp.org/4/en/quickstart.html
+ created DB and connect this in config (nothing extra didnt do with config)

And have baked all this 3 default models:
bin/cake bake model -f --no-fixture --no-test Users
bin/cake bake model -f --no-fixture --no-test Articles
bin/cake bake model -f --no-fixture --no-test Tags
bin/cake bake model -f --no-fixture --no-test ArticlesTags

### What happened
In generated query:
```sql
SELECT Tags.id AS Tags__id, Tags.title AS Tags__title, Tags.created AS Tags__created, Tags.modified AS Tags__modified FROM tags Tags INNER JOIN articles_tags ArticlesTags ON Tags.id = (ArticlesTags.tag_id) INNER JOIN articles Articles ON Articles.id = (ArticlesTags.article_id) INNER JOIN users Users ON Users.id = (Articles.user_id) WHERE Users.created >= '4/12/21, 4:22 PM'
```

Here is wrong date&time format: '4/12/21, 4:22 PM' expected '2021-04-12 12:00:00'

### What you expected to happen
In PagesController added this code:
```php
$this->loadModel('Tags');
$from = new FrozenTime();
$this->Tags->find()
    ->innerJoinWith('Articles', function (Query $Query) {
        return $Query->innerJoinWith('Users');
    })
    ->where(['Users.created >=' => $from])
    ->all();
```

**Comment by othercorey** [comment] 2021-04-12 19:38
What locale are you using?

**Comment by andrii-pukhalevych** [comment] 2021-04-12 20:18
> What locale are you using?

'da_DK'

**Comment by markstory** [comment] 2021-04-13 02:09
Do other datetime conditions work without issue?

**Comment by markstory** [comment] 2021-04-13 02:16
You could also check to see what the mapped types are before the where() call. Using 

```php
$query = $this->Tags->find()->innerJoinWith('Articles', function (Query $Query) {
    return $Query->innerJoinWith('Users');
});
debug($query->getSelectTypeMap());
```

My suspicion is that because you're using a callback for `innerJoinWith()` that the type mappings have not been updated when `where()` is called and are only present after joins are resolved.

You could try putting the conditions on Users inside the `innerJoinWith()` callback,  using `innerJoinWith('Articles.Users')`, or using `$query->addDefaultTypes($this->Tags->Articles->Users->getTarget())` to ensure the types are defined.

**Comment by pavel-dovgoshiya** [comment] 2021-04-13 08:27
> What locale are you using?

All used default after install. 'en_US'

**Comment by pavel-dovgoshiya** [comment] 2021-04-13 08:34
> > What locale are you using?
> 
> 'da_DK'

When to use in config this locale `'defaultLocale' => env('APP_DEFAULT_LOCALE', 'da_DK'),` then format little changed in results but still same issue.

Result:
`SELECT Tags.id AS Tags__id, Tags.title AS Tags__title, Tags.created AS Tags__created, Tags.modified AS Tags__modified FROM tags Tags INNER JOIN articles_tags ArticlesTags ON Tags.id = (ArticlesTags.tag_id) INNER JOIN articles Articles ON Articles.id = (ArticlesTags.article_id) INNER JOIN users Users ON Users.id = (Articles.user_id) WHERE Users.created >= '13/04/2021 08.32'`

**Comment by pavel-dovgoshiya** [comment] 2021-04-13 11:48
> You could also check to see what the mapped types are before the where() call. Using
> 
> ```
> $query = $this->Tags->find()->innerJoinWith('Articles', function (Query $Query) {
>     return $Query->innerJoinWith('Users');
> });
> debug($query->getSelectTypeMap());
> ```
> 
> My suspicion is that because you're using a callback for `innerJoinWith()` that the type mappings have not been updated when `where()` is called and are only present after joins are resolved.
> 
> You could try putting the conditions on Users inside the `innerJoinWith()` callback, using `innerJoinWith('Articles.Users')`, or using `$query->addDefaultTypes($this->Tags->Articles->Users->getTarget())` to ensure the types are defined.

If move condition under innerJoinWith callback then all works fine with type.

If run with `->addDefaultTypes($this->Tags->Articles->Users->getTarget())` like:
`$Query = $this->Tags->find()`
`			->innerJoinWith('Articles', function (Query $Query) {`
`				return $Query->innerJoinWith('Users');`
`			})`
`			->addDefaultTypes($this->Tags->Articles->Users->getTarget())`
`			->where(['Users.created >=' => $from])`
`			->all();`

Then its also fixed format
`SELECT Tags.id AS Tags__id, Tags.title AS Tags__title, Tags.created AS Tags__created, Tags.modified AS Tags__modified FROM tags Tags INNER JOIN articles_tags ArticlesTags ON Tags.id = (ArticlesTags.tag_id) INNER JOIN articles Articles ON Articles.id = (ArticlesTags.article_id) INNER JOIN users Users ON Users.id = (Articles.user_id) WHERE Users.created >= '2021-04-13 11:47:24'`

**Comment by markstory** [comment] 2021-04-13 15:47
Going to close this as it is a type map issue caused by late binding of the nested join types.

I don't know how we could solve this as your original query was referencing columns that were effectively unknown when they were used, and the solution to that is adding the types or moving the conditions into the closures where they can execute after the types have been added to the query.

**Closed by markstory** 2021-04-13 15:47 UTC
Labels: ORM
