### ISSUE TITLE
MapReduce not iterating over ResultSet returned by $this->Paginator->paginate()

### ISSUE THREAD

**Issue by myorkgitis** [cakephp/cakephp#13020] opened 2019-02-26 03:34 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.13

* Platform and Target: PHP 7.2, MySQL 5.7, Ubuntu 16.04.5 LTS, Apache

### What you did
I am using *mapReduce* to implement a way to hide or obfuscate certain fields when loading results via `$table->find()`

I added a `beforeFind` callback to map a field property to some value.

```
// In a Table class

    public function beforeFind(Event $event, Query $query, ArrayObject $options, $primary)
    {
        $mapper = function($entity, $index, MapReduce $mapReduce) {
            $entity->name = "1";
            $mapReduce->emit($entity, $index);
        };

        return $query->mapReduce($mapper);
    }
```

```
// Paginator call that triggers the beforeFind()
$data = $this->Paginator->paginate($object, $this->paginatorSettings);
```

### What happened
The mapper only gets called for one entity even though there are more results in the ResultSet.

### What you expected to happen
I expect the mapper to get called for each result in the ResultSet returned from `$this->Paginator->paginate()`

### Troubleshooting
Inspection of the `$this->_data` property in the MapReduce object shows it is a `ResultSet` with a single array property called `items` populated with *ten* items, however it will only iterate over a single entity in MapReduce.php, line 178.

Not sure if this is an issue with `foreach` being able to properly iterate over a `ResultSet`.

However, adding `$results = $this->_data->toArray();` before the `foreach` as shown below solves the issue and yields the expected behavior.

```
// Starting at line 164 of MapReduce.php
    /**
     * Runs the actual Map-Reduce algorithm. This is iterate the original data
     * and call the mapper function for each , then for each intermediate
     * bucket created during the Map phase call the reduce function.
     *
     * @return void
     * @throws \LogicException if emitIntermediate was called but no reducer function
     * was provided
     */
    protected function _execute()
    {
        $mapper = $this->_mapper;

        // *** I added this here to make sure the results were an array ***
        $results = $this->_data->toArray();

        foreach ($results as $key => $val) {
            // *** Now this works as expected ***
            $mapper($val, $key, $this);
        }
        $this->_data = null;

```

Hope this helps.

Thanks.

**Comment by Asgraf** [comment] 2019-02-26 09:17
I had similar problem with iteration over ResultSet.
My ResultSet also had 30 items inside but foreach iterated only once for the first item.
The cause of the problem in my case was xdebug.
If you set `xdebug.collect_params` ini setting with value higher than `1` xdebug is starts to mess with internal array iterators of some Iterable objects and this can cause premature breaking out of the loop.
Setting `xdebug.collect_params` ini setting to `1` fixed the problem for me.

**Comment by myorkgitis** [comment] 2019-02-26 14:01
Thanks, @Asgraf for the insight. You are correct in that it is an xdebug issue. 

Setting the `xdebug.collect_params` to `1` had no effect (it was at `0` before) but when I disable listening for the debugger, I have no issues at all and the script executes as expected.

**Comment by myorkgitis** [comment] 2019-02-26 20:58
Should `_execute` not first convert data to an array to avoid this issue?

**Comment by markstory** [comment] 2019-02-27 04:07
@myorkgitis No because that would break streaming resultsets, as all memory would need to be pre-allocated.

**Comment by jrbakooba** [comment] 2019-03-14 18:11
Has the core dev team identified the issue or learned anything new? If so can they provide any transparency?

**Comment by josegonzalez** [comment] 2019-03-14 18:17
@jrbakooba If we had an update, it would be posted here :)

**Comment by markstory** [comment] 2019-03-14 18:17
@jrbakooba There is nothing learned or identified as far as I'm aware. There are multiple comments in this thread indicating that xdebug was contributing to this problem.

**Comment by jrbakooba** [comment] 2019-03-14 18:54
@markstory @josegonzalez OK, well just some more info from here, looks like the problem still exists in Xdebug 2.7, the latest release.

**Comment by josegonzalez** [comment] 2019-03-14 19:19
It might be that xdebug is unrolling the collection when it collects the parameters, causing the mapReduce to fail because its more or less at the last item? Thats a guess, but if anyone has time to actually investigate - that includes non-core developers! - that would be great.

**Comment by ADmad** [comment] 2019-12-14 07:07
Based on the comments the issue occurs when using Xdebug and there aren't any actionable suggestions to mitigate the issue except tinerking with xdebug config or disabling it. 

Hence closing as there's nothing to be done in the Cake core.

**Closed by ADmad** 2019-12-14 07:07 UTC
Labels: support
