### ISSUE TITLE
3.1.0 - Rename method 'loadModel()' to 'loadTable()'.

### ISSUE THREAD

**Issue by Xety** [cakephp/cakephp#6336] opened 2015-04-14 17:59 UTC
Hello,
I think the named method `loadModel()` is not really correct, because there is no more model in Cake3 and some people can be confused with that.

For me, this method should be `loadTable()` because it return an instance of a table object.

The docs has already been updated about `Model` (Btw, i totally agree with @lorenzo ): https://github.com/cakephp/docs/pull/2610

I think we must deprecate it in the 3.1.0, and remove it in the 3.2.0 to let the time to the Cake users to update their applications.

**Comment by dereuromark** [comment] 2015-04-14 18:11
Duplicate of https://github.com/cakephp/cakephp/issues/4678 etc

**Comment by lorenzo** [comment] 2015-04-14 18:59
It was originally `loadRepository()` if anything I think it should go back to that.

**Comment by dereuromark** [comment] 2015-04-14 20:42
I agree, loadRepository() or loadModel() is both fine.

**Comment by ADmad** [comment] 2015-04-14 20:50
We use 'Model' namespaces so I don't see a problem using loadModel()

**Comment by markstory** [comment] 2015-04-15 00:35
It _can_ load other models if new providers are configured.

**Comment by jadb** [comment] 2015-04-15 01:21
I still prefer `loadModel()`. Here's a comment by @markstory that resumes it well: https://github.com/cakephp/cakephp/issues/4678#issuecomment-56280689

**Comment by dereuromark** [comment] 2015-04-15 08:00
So it's settled, no need to do further renaming then.

**Closed by dereuromark** 2015-04-15 08:00 UTC
Labels: RFC
