### ISSUE TITLE
Entities associated property name is not set correct when id is missing

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#8112] opened 2016-01-26 14:49 UTC
The following query works in any case but *only* when I add the `				$this->aliasField('id')` to the query the entities associated *belongsTo Projects* property name is correctly set to `project`. Without `$this->aliasField('id')` being present in the query it stays `Projects`.

```php
	public function getCountriesByType($typeId) {
		return $this->find()
			->select([
				// Had to add the id here to make it work
				$this->aliasField('id'),
				'Projects.country_id',
			])
			->contain([
				'Projects'
			])
			->where([
				$this->aliasField('building_type_id') => $typeId
			])
			->where(function ($exp, $q) {
				return $exp->isNotNull('Projects.country_id');
			})
			->distinct('Projects.country_id')
			->all();
	}
```

***With the id set:***

```` 
(int) 0 => object(App\Model\Entity\BuildingTypesProject) {

		'id' => (int) 5497,
		'project' => object(App\Model\Entity\Project) {

			'country_id' => (int) 8,
			'[new]' => false,
			'[accessible]' => [
				'*' => true
			],
			'[dirty]' => [],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[repository]' => 'Projects'
		
		},
		'[new]' => false,
		'[accessible]' => [
			'*' => true
		],
		'[dirty]' => [],
		'[original]' => [],
		'[virtual]' => [],
		'[errors]' => [],
		'[repository]' => 'BuildingTypesProjects'
	
	},
````

***Without the id set:***

```` 
(int) 0 => object(App\Model\Entity\BuildingTypesProject) {

		'Projects' => object(App\Model\Entity\Project) {

			'country_id' => (int) 8,
			'[new]' => false,
			'[accessible]' => [
				'*' => true
			],
			'[dirty]' => [],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[repository]' => 'Projects'
		
		},
		'[new]' => false,
		'[accessible]' => [
			'*' => true
		],
		'[dirty]' => [],
		'[original]' => [],
		'[virtual]' => [],
		'[errors]' => [],
		'[repository]' => 'BuildingTypesProjects'
	
	},
````

**Comment by markstory** [comment] 2016-01-27 02:18
I suspect that without the id the ORM cannot stitch the data together. Have you considered using matching() or innerJoinWith(). Both of these might let you do what you want with less hassle.

**Comment by lorenzo** [comment] 2016-02-09 09:23
Using the subquery strategy for the association may also help

**Comment by markstory** [comment] 2016-03-03 03:14
I'm not able to reproduce this issue. The following test case passes. Am I missing something?

```php
$articles = TableRegistry::get('Articles');
$articles->belongsTo('Authors');

$query = $articles->find()
    ->select(['id', 'Authors.name'])
    ->distinct('Authors.name')
    ->contain(['Authors'])
    ->where(['Articles.id' => 3]);
$results = $query->toArray();

$this->assertNotEmpty($results[0]->author);
$this->assertInstanceOf('Cake\Datasource\EntityInterface', $results[0]->author);
$this->assertEmpty($results[0]->Authors);
```

**Comment by lorenzo** [comment] 2016-03-05 15:07
This is a duplicate of #6606

**Closed by lorenzo** 2016-03-05 15:07 UTC
Labels: Defect, ORM
