### ISSUE TITLE
Different dirty behaviour between newEntity($data) and patchEntity($entity, $data)

### ISSUE THREAD

**Issue by Slessi** [cakephp/cakephp#10658] opened 2017-05-15 11:09 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.5
* Platform and Target: PHP 7.1.4, Apache 2.4.25, MySQL 5.7.16

### What you did
I save a model `NocForm` which has one `Document` association
```php
// In my controller
private function saveForm($id)
{
    $this->loadModel('NocForms');

    $data = $this->request->data;

    if (empty($id)) {
        $form = $this->NocForms->newEntity($data);
    } else {
        $form = $this->NocForms->getForm($id);
        $form = $this->NocForms->patchEntity($form, $data);
    }

    if ($form->errors() || !$this->NocForms->save($form)) {
        $this->addDangerMessage('There was a problem saving your form');
        return;
    }
}
```

Inside `$data` I have a bunch of `NocForm` fields, and also this `tmp_file` field which comes from a file input. Irrespective of whether I pass a file to my file input or not, `tmp_file` will be set. The contents will change accordingly when a file is included.
> *Note*: If relevant, the file input `name` is `document[tmp_file]`
```json
{
    "document": {
        "tmp_file": {
            "tmp_name": "",
            "error": 4,
            "name": "",
            "type": "",
            "size": 0
        }
    }
}
```

Inside `DocumentsTable` I have the following events defined. `beforeMarshal` checks for the `tmp_file` property and if a file is actually contained in it, and if found it extracts the information relevant to me. If no file is found to be attached I simply unset the field.
```php
public function beforeMarshal(Event $event, ArrayObject $data, ArrayObject $options)
{
    if (!empty($data['tmp_file'])) {
        $file = $data['tmp_file'];

        if (!empty($file['tmp_name'])) {
            $data['extension'] = pathinfo($file['name'], PATHINFO_EXTENSION);
            $data['content_type'] = mime_content_type($file['tmp_name']);
            $data['file_size'] = filesize($file['tmp_name']);
            $data['date_uploaded'] = new \Cake\I18n\Time();
            $data['file_path'] = md5(uniqid()).'.'.$data['extension'];
        } else {
            unset($data['tmp_file']);
        }
    }
}
```

`beforeSave` will check if we are saving a new file, and uploads it to our bucket if so.
```php
public function beforeSave(Event $event, EntityInterface $entity, ArrayObject $options)
{
    if (!empty($entity->tmp_file)) {
        $file = $entity->tmp_file;

        $bucket = new BucketWrapper();
        $bucket->save($entity->file_path, $file['tmp_name']);

        if (!$entity->dirty('name')) {
            $entity->name = $file['name'];
        }
    }
}
```

### What happened
When creating a *new* `NocForm` without uploading a file, `save()` returns false with no errors. What seems to be the issue is that when creating a new `NocForm`, `document` is marked as dirty even though inside `DocumentsTable` the `beforeMarshal` event empties its `ArrayObject $data`.

When *updating an existing* `NocForm` which does not have a `Document`, it's `document` field is *not* marked as `dirty`.

In fact, if I refactor my code from this
```php
if (empty($id)) {
    $form = $this->NocForms->newEntity($data);
} else {
    $form = $this->NocForms->getForm($id);
    $form = $this->NocForms->patchEntity($form, $data);
}
```

to this
```php
if (empty($id)) {
    $form = $this->NocForms->newEntity();
} else {
    $form = $this->NocForms->getForm($id);
}
$form = $this->NocForms->patchEntity($form, $data);
```

It works fine in all cases. Naturally I don't want to have a potential issue based around remembering to never use `newEntity($data)`

### What you expected to happen
I expect `newEntity($data)` and `patchEntity($entity, $data)` to work identically when dealing with a new entity.

**Comment by markstory** [comment] 2017-05-16 01:03
In the newEntity case the field what is the document attribute set to?

**Comment by Slessi** [comment] 2017-05-16 09:27
Below are debug dumps for both new & patch. Note how they are completely identical except for `document` being included in the `[dirty]` list when using `newEntity`

In the case of `newEntity($data)`

```
object(App\Model\Entity\NocForm) {

	'document' => object(App\Model\Entity\Document) {

		'[new]' => true,
		'[accessible]' => [
			'*' => true,
			'id' => false
		],
		'[dirty]' => [],
		'[original]' => [],
		'[virtual]' => [],
		'[errors]' => [],
		'[invalid]' => [],
		'[repository]' => 'Documents'
	
	},
	'[new]' => true,
	'[accessible]' => [
		'*' => true,
		'id' => false
	],
	'[dirty]' => [
		'violation_date' => true,
		'charge_date' => true,
		'department_id' => true,
		'grade' => true,
		'noc_violations' => true,
		'other_violation' => true,
		'additional_remarks' => true,
		'document' => true,
		'employee_id' => true
	],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => [],
	'[invalid]' => [],
	'[repository]' => 'NocForms'

}
```

In the case of `patchEntity($entity, $data)`

```
object(App\Model\Entity\NocForm) {

	'document' => object(App\Model\Entity\Document) {

		'[new]' => true,
		'[accessible]' => [
			'*' => true,
			'id' => false
		],
		'[dirty]' => [],
		'[original]' => [],
		'[virtual]' => [],
		'[errors]' => [],
		'[invalid]' => [],
		'[repository]' => 'Documents'
	
	},
	'[new]' => true,
	'[accessible]' => [
		'*' => true,
		'id' => false
	],
	'[dirty]' => [
		'violation_date' => true,
		'charge_date' => true,
		'department_id' => true,
		'grade' => true,
		'noc_violations' => true,
		'other_violation' => true,
		'additional_remarks' => true,
		'employee_id' => true
	],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => [],
	'[invalid]' => [],
	'[repository]' => 'NocForms'

}
```

**Comment by dakota** [comment] 2017-05-16 09:59
What is `$data` in both cases, and what is `$form` before the patch is done?

**Comment by Slessi** [comment] 2017-05-16 10:07
`$data` is as specified in original post
```json
{
    "document": {
        "tmp_file": {
            "tmp_name": "",
            "error": 4,
            "name": "",
            "type": "",
            "size": 0
        }
    }
}
```

`$form` before patch is an empty entity
```
object(App\Model\Entity\NocForm) {

	'[new]' => true,
	'[accessible]' => [
		'*' => true,
		'id' => false
	],
	'[dirty]' => [],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => [],
	'[invalid]' => [],
	'[repository]' => 'NocForms'

}
```

**Comment by robertpustulka** [comment] 2017-05-16 10:55
This is expected behavior. Since `document` key is present in data, it is marked dirty.

**Comment by Slessi** [comment] 2017-05-16 11:08
Yes, but why do `newEntity` and `patchEntity` behave differently despite dealing with the same new entity?

> ### What you expected to happen
> I expect newEntity($data) and patchEntity($entity, $data) to work identically when dealing with a new entity.

**Comment by markstory** [comment] 2017-06-10 21:04
I'm having a hard time reproducing this issue. The following test passes for me locally. What am I missing?

```php
$users = TableRegistry::get('Users');
$users->hasOne('Articles', [
    'foreignKey' => 'author_id'
]);
$users->eventManager()->on('Model.beforeMarshal', function ($event, $data, $options) {
    // Blank the association, so it doesn't become dirty.
    unset($data['article']);
});

$data = [
    'username' => 'Jen',
    'article' => [
        'title' => 'My title',
        'body' => 'A body'
    ]
];
$marshall = new Marshaller($users);
$entity = new Entity([
    'username' => 'Jenny',
]);
// Make the entity think it is new.
$entity->accessible('*', true);
$entity->clean();

$result = $marshall->merge($entity, $data, []);

$this->assertTrue($entity->isDirty('username'));
$this->assertFalse($entity->isDirty('article'));
```

**Comment by markstory** [comment] 2017-06-29 11:09
Any updates on this?

**Comment by Slessi** [comment] 2017-06-29 12:21
Haven't actually tried this out but to be identical to my example you need to have the `beforeMarshal` event on `Articles` and you need to unset a field which doesnt actually exist for the entity inside there.

Then `newEntity` should give you a dirty `Article`
`patchEntity` should give you a clean `Article`

```php
<?php

$users = TableRegistry::get('Users');
$articles = TableRegistry::get('Articles');

$users->hasOne('Articles', [
    'foreignKey' => 'author_id'
]);
$articles->eventManager()->on('Model.beforeMarshal', function ($event, $data, $options) {
    // Blank the association, so it doesn't become dirty.
    unset($data['not_a_real_field']);
});

$data = [
    'username' => 'Jen',
    'article' => [
        'not_a_real_field' => 'whatever'
    ]
];
$marshall = new Marshaller($users);
$entity = new Entity([
    'username' => 'Jenny',
]);
// Make the entity think it is new.
$entity->accessible('*', true);
$entity->clean();

$result = $marshall->merge($entity, $data, []);

$this->assertTrue($entity->isDirty('username'));
$this->assertFalse($entity->isDirty('article'));
```

**Comment by markstory** [comment] 2017-06-29 15:48
Thanks. I'll give that a try.

**Comment by markstory** [comment] 2017-07-01 02:06
Closing as a pull request is open now.

**Closed by markstory** 2017-07-01 02:06 UTC
Labels: Defect, On hold, ORM
