### ISSUE TITLE
Plugin assets not reachable on (lowercase) url's that is generated by htmlHelper

### ISSUE THREAD

**Issue by blieb** [cakephp/cakephp#11379] opened 2017-10-26 11:36 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.4
* Platform and Target: Apache with php 7.0.8 on macOS high sierra. 

### What you did
I've a plugin named "Plugin" and I loaded a css file from plugin in a view (which is inside the Plugin)
$this->Html->css(['Plugin.helpers/upload/uploadInfo'], ['block' => true])

### What happened
it added a css file in html to: 
/plugin/css/helpers/upload/uploadInfo.css

but this url is a 404. 

### What you expected to happen
There are 2 options,
/Plugin/css/helpers/upload/uploadInfo.css << this url works (uppercase P)

I think the best solution is to let the asset middleware also make it possible to use the one with the lowercase plugin name.
When I create symlinks by running "bin/cake plugin assets symlink" it also creates a symlink without the uppercase P.

**Comment by dereuromark** [comment] 2017-10-26 11:59
It might not just be about upper or lowercase, MyPlugin multiwords would maybe also not be inflected correctly with dash (my-plugin) or underscore (my_plugin), depending on the routing settings.

**Comment by markstory** [comment] 2017-10-26 13:02
Is your plugin's name actually `Plugin`?

**Comment by blieb** [comment] 2017-10-26 13:06
Yes don't know why, it is just a small plugin of things used over multiple projects.

**Comment by markstory** [comment] 2017-10-26 13:18
Ok. Do you have the same issue with plugins not called 'Plugin'?

**Comment by blieb** [comment] 2017-10-26 13:25
I also have a plugin called "Mobile" but no problems with that one.

**Comment by markstory** [comment] 2017-10-31 02:37
I wasn't able to reproduce this. 

1. I created a plugin called `Plugin` in `APPROOT/plugins/Plugin` 
2. I added a CSS file `APPROOT/plugins/Plugin/webroot/css/red.css` Which contained `* { color: red !important; }`
3. I loaded the helper in my application's bootstrap.php file using `Plugin::load('Plugin');`
4. In my layout I linked the new css file using `<?= $this->Html->css('Plugin.red') ?>`

The path was right and everything on the page was red as it should be. What did I miss?

**Comment by markstory** [comment] 2017-11-06 01:57
Closing as I was not able to reproduce this issue. If possible please provide a gist/sample app that exhibits the problem.

**Closed by markstory** 2017-11-06 01:57 UTC
Labels: Defect, On hold
