### ISSUE TITLE
Error on load migrations plugin and anotehr plugin

### ISSUE THREAD

**Issue by ribafs** [cakephp/cakephp#11945] opened 2018-04-16 14:11 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6
* Platform and Target: Linux Mint 18.3 with Mysql 5.7

### What you did
I try to load plugin
After install migrations plugin I try to load:
bin/cake plugin load Migrations

### What happened
Your Application class does not have a bootstrap() method. Please add one.
When a call in navigation I see:
Deprecated (16384): RequestHandlerComponent::beforeRedirect() is deprecated. This functionality will be removed in 4.0.0. Set the `enableBeforeRedirect` option to `false` to disable this warning. - /backup/www/testes2/vendor/cakephp/cakephp/src/Event/EventManager.php, line: 353 [CORE/src/Core/functions.php, line 305]

Warning (512): Unable to emit headers. Headers sent in file=/backup/www/testes2/vendor/cakephp/cakephp/src/Error/Debugger.php line=853 [CORE/src/Http/ResponseEmitter.php, line 48]

Warning (2): Cannot modify header information - headers already sent by (output started at /backup/www/testes2/vendor/cakephp/cakephp/src/Error/Debugger.php:853) [CORE/src/Http/ResponseEmitter.php, line 148]

Warning (2): Cannot modify header information - headers already sent by (output started at /backup/www/testes2/vendor/cakephp/cakephp/src/Error/Debugger.php:853) [CORE/src/Http/ResponseEmitter.php, line 181]

Warning (2): Cannot modify header information - headers already sent by (output started at /backup/www/testes2/vendor/cakephp/cakephp/src/Error/Debugger.php:853) [CORE/src/Http/ResponseEmitter.php, line 181]

Warning (2): Cannot modify header information - headers already sent by (output started at /backup/www/testes2/vendor/cakephp/cakephp/src/Error/Debugger.php:853) [CORE/src/Http/ResponseEmitter.php, line 181]

### What you expected to happen
In version 3.5 dont ocurre this

**Comment by dereuromark** [comment] 2018-04-16 14:19
Duplicate of https://github.com/cakephp/cakephp/issues/11932

**Closed by dereuromark** 2018-04-16 14:19 UTC

**Comment by ribafs** [comment] 2018-04-16 14:57
And this errors?

Deprecated (16384): RequestHandlerComponent::beforeRedirect() is deprecated. This functionality will be removed in 4.0.0. Set the enableBeforeRedirect option to false to disable this warning. - /backup/www/testes2/vendor/cakephp/cakephp/src/Event/EventManager.php, line: 353 [CORE/src/Core/functions.php, line 305]

Warning (512): Unable to emit headers. Headers sent in file=/backup/www/testes2/vendor/cakephp/cakephp/src/Error/Debugger.php line=853 [CORE/src/Http/ResponseEmitter.php, line 48]

Warning (2): Cannot modify header information - headers already sent by (output started at /backup/www/testes2/vendor/cakephp/cakephp/src/Error/Debugger.php:853) [CORE/src/Http/ResponseEmitter.php, line 148]

Warning (2): Cannot modify header information - headers already sent by (output started at /backup/www/testes2/vendor/cakephp/cakephp/src/Error/Debugger.php:853) [CORE/src/Http/ResponseEmitter.php, line 181]

Warning (2): Cannot modify header information - headers already sent by (output started at /backup/www/testes2/vendor/cakephp/cakephp/src/Error/Debugger.php:853) [CORE/src/Http/ResponseEmitter.php, line 181]

Warning (2): Cannot modify header information - headers already sent by (output started at /backup/www/testes2/vendor/cakephp/cakephp/src/Error/Debugger.php:853) [CORE/src/Http/ResponseEmitter.php, line 181]
