### ISSUE TITLE
Translation not work with foreign_key = 1

### ISSUE THREAD

**Issue by Angyo** [cakephp/cakephp#5982] opened 2015-02-28 04:00 UTC
I added the following code.

In my Database, contentbuilders table

id | type | parent_id | lft | rght
---|------|-----------|-----|-----
1|1|NULL|1|2
2|2|NULL|3|4
3|2|NULL|5|6

In i18n table

id | locale | model | foreign_key | field | content
---|--------|-------|-------------|-------|--------
1|en_US|Contentbuilders|1|name|Main Menu
2|fr_FR|Contentbuilders|1|name|Menu principal
3|en_US|Contentbuilders|3|name|En Test
4|fr_FR|Contentbuilders|3|name|Fr Test

In my ContentbuildersController

    public function index()
    {
        $contentbuilders = $this->Contentbuilders->find('threaded')->find('translations');
        $this->set('contentbuilders', $contentbuilders);
    }

In my view template

    <?php foreach($contentbuilders as $contentbuilder): ?>
        <p>Type : <?= $contentbuilder->type ?> | <?= $contentbuilder->translation('fr_FR')->name ?></p>
    <?php endforeach; ?>

With this code, data from I18n table are null for foreign_key = 1, but work if i update theses entries with foreign = 2. This seemed strange to me and I prefer therefore postpone the problem here.

**Comment by markstory** [comment] 2015-02-28 17:18
What queries are executed? If you run those queries against the database, do you get the results you're expecting?

**Comment by Angyo** [comment] 2015-02-28 19:58
Theses queries are executed

    SELECT Contentbuilders.id AS `Contentbuilders__id`, Contentbuilders.type AS `Contentbuilders__type`, Contentbuilders.parent_id AS `Contentbuilders__parent_id`, Contentbuilders.lft AS `Contentbuilders__lft`, Contentbuilders.rght AS `Contentbuilders__rght` FROM contentbuilders Contentbuilders

    SELECT I18n.id AS `I18n__id`, I18n.locale AS `I18n__locale`, I18n.model AS `I18n__model`, I18n.foreign_key AS `I18n__foreign_key`, I18n.field AS `I18n__field`, I18n.content AS `I18n__content` FROM i18n I18n INNER JOIN (SELECT (Contentbuilders.id) FROM contentbuilders Contentbuilders GROUP BY Contentbuilders.id ) Contentbuilders ON I18n.foreign_key = (Contentbuilders.id) WHERE I18n.model = 'Contentbuilders'

Queries and results are correct when i debug the following in my view or in my controller

    <?php debug($contentbuilders->toArray()); ?>

But not in my foreach, data is missing with my foreign_key = 1....

**Comment by markstory** [comment] 2015-02-28 21:34
Are you sure there isn't an issue with the code inside the loop? The toArray() method simply iterates the result set and collects all the results, so it should be the same as a loop.

**Comment by Angyo** [comment] 2015-02-28 21:38
The code inside the loop is the following

    <?php foreach($contentbuilders as $contentbuilder): ?>
        <p>Type : <?= $contentbuilder->type ?> | <?= $contentbuilder->translation('fr_FR')->name ?></p>
    <?php endforeach; ?>

Moreover, the render is good with foreign_key = 2, and with foreign_key = 1, write nothing in place of the name, but in the same loop write something for my foreign_key = 3...

**Comment by markstory** [comment] 2015-03-01 03:17
If you foreach() over the results of toArray() do you have the same issue?

**Comment by Angyo** [comment] 2015-03-01 05:48
Yeah same problem, you can see below the debug output

    <?php debug($contentbuilders->toArray()); ?>

My traduction values are here !

    Results
	\src\Template\Admin\Contentbuilders\index.ctp (line 1)
	[
		(int) 0 => object(App\Model\Entity\Contentbuilder) {

			'new' => false,
			'accessible' => [
				'*' => true
			],
			'properties' => [
				'id' => (int) 1,
				'type' => (int) 1,
				'parent_id' => null,
				'lft' => (int) 1,
				'rght' => (int) 2,
				'_translations' => [],
				'children' => []
			],
			'dirty' => [
				'children' => true
			],
			'original' => [
				'_translations' => [
					'en_US' => object(Cake\ORM\Entity) {

						'new' => false,
						'accessible' => [
							'*' => true
						],
						'properties' => [
							'name' => 'Main menu',
							'locale' => 'en_US'
						],
						'dirty' => [],
						'original' => [],
						'virtual' => [],
						'errors' => [],
						'repository' => null
					
					},
					'fr_FR' => object(Cake\ORM\Entity) {

						'new' => false,
						'accessible' => [
							'*' => true
						],
						'properties' => [
							'name' => 'Menu principal',
							'locale' => 'fr_FR'
						],
						'dirty' => [],
						'original' => [],
						'virtual' => [],
						'errors' => [],
						'repository' => null
					
					}
				]
			],
			'virtual' => [],
			'errors' => [],
			'repository' => 'Contentbuilders'
		
		},
		(int) 1 => object(App\Model\Entity\Contentbuilder) {

			'new' => false,
			'accessible' => [
				'*' => true
			],
			'properties' => [
				'id' => (int) 2,
				'type' => (int) 2,
				'parent_id' => null,
				'lft' => (int) 3,
				'rght' => (int) 4,
				'_translations' => [],
				'children' => []
			],
			'dirty' => [
				'children' => true
			],
			'original' => [],
			'virtual' => [],
			'errors' => [],
			'repository' => 'Contentbuilders'
		
		},
		(int) 2 => object(App\Model\Entity\Contentbuilder) {

			'new' => false,
			'accessible' => [
				'*' => true
			],
			'properties' => [
				'id' => (int) 3,
				'type' => (int) 2,
				'parent_id' => null,
				'lft' => (int) 5,
				'rght' => (int) 6,
				'_translations' => [
					'fr_FR' => object(Cake\ORM\Entity) {

						'new' => false,
						'accessible' => [
							'*' => true
						],
						'properties' => [
							'name' => 'fr',
							'locale' => 'fr_FR'
						],
						'dirty' => [],
						'original' => [],
						'virtual' => [],
						'errors' => [],
						'repository' => null
					
					},
					'en_US' => object(Cake\ORM\Entity) {

						'new' => false,
						'accessible' => [
							'*' => true
						],
						'properties' => [
							'name' => 'en',
							'locale' => 'en_US'
						],
						'dirty' => [],
						'original' => [],
						'virtual' => [],
						'errors' => [],
						'repository' => null
					
					}
				],
				'children' => []
			],
			'dirty' => [
				'children' => true
			],
			'original' => [],
			'virtual' => [],
			'errors' => [],
			'repository' => 'Contentbuilders'
		
		}
	]

And the debug output with bug, somes lines after...

    <?php foreach ($contentbuilders as $contentbuilder): ?>
        <?php debug($contentbuilder->toArray()); ?>
    <?php endforeach; ?>

My traductions values are missing !

    Results
    \src\Template\Admin\Contentbuilders\index.ctp (line 4)
    [
        'id' => (int) 1,
        'type' => (int) 1,
        'parent_id' => null,
        'lft' => (int) 1,
        'rght' => (int) 2,
        '_translations' => [],
        'children' => []
    ]

    \src\Template\Admin\Contentbuilders\index.ctp (line 4)
    [
        'id' => (int) 2,
        'type' => (int) 2,
        'parent_id' => null,
        'lft' => (int) 3,
        'rght' => (int) 4,
        '_translations' => [],
        'children' => []
    ]

	\src\Template\Admin\Contentbuilders\index.ctp (line 4)
	[
		'id' => (int) 3,
		'type' => (int) 2,
		'parent_id' => null,
		'lft' => (int) 5,
		'rght' => (int) 6,
		'_translations' => [
			'fr_FR' => object(Cake\ORM\Entity) {

				'new' => false,
				'accessible' => [
					'*' => true
				],
				'properties' => [
					'name' => 'fr',
					'locale' => 'fr_FR'
				],
				'dirty' => [],
				'original' => [],
				'virtual' => [],
				'errors' => [],
				'repository' => null
			
			},
			'en_US' => object(Cake\ORM\Entity) {

				'new' => false,
				'accessible' => [
					'*' => true
				],
				'properties' => [
					'name' => 'en',
					'locale' => 'en_US'
				],
				'dirty' => [],
				'original' => [],
				'virtual' => [],
				'errors' => [],
				'repository' => null
			
			}
		],
		'children' => []
	]

The foreach() seems to delete my traduction values... ?!

**Comment by markstory** [comment] 2015-03-01 12:06
Do you have any behaviors, result formatters or beforeFind listeners? I can see if I can reproduce this issue locally too.

**Comment by Angyo** [comment] 2015-03-01 14:01
I have two Behaviors

    $this->addBehavior('Tree');
    $this->addBehavior('Translate', ['fields' => ['name']]);

I don't use any king of formatters or beforeFind callbackd.

**Comment by markstory** [comment] 2015-03-01 14:09
Ok. I will see if the same issue happens for me.

**Comment by Angyo** [comment] 2015-03-01 15:30
To help you, i just create a git with all my code : https://github.com/Angyo/angyoweb

**Comment by lorenzo** [comment] 2015-03-01 18:44
The first problem that I see is that there is no "name" column in your table. The column you intend to trnanslate should be part of the schema of your table

**Comment by Angyo** [comment] 2015-03-01 19:06
I never had a problem with this, moreover the idea is that the name is translatable, so i don't think to put it in my contentbuilders schema who is not traductable is a good answer. On the other hand i never had problem to get my traductions as also by.

For example i have my name traductions when the foreign_key = 2 or 3, but not when is 1, and that's what bothers me because I do not know why this happens and if it can reproduce on other foreign_key.

**Comment by lorenzo** [comment] 2015-03-01 19:09
I'm just telling you what is officially supported. I never intended to make it work without the columns in the main table, so I have no idea if that has undesirable side effects.

**Comment by Angyo** [comment] 2015-03-01 19:14
Yeah, i don't deal with the name column like a primary key who is absolutely necessary, but like a column who can be translated like my content column. So i don't see the problem to have it in the I18n table ?

**Comment by lorenzo** [comment] 2015-03-01 19:16
Again I'm just telling you what is officially supported and tested :)

**Comment by lorenzo** [comment] 2015-03-01 19:34
I can confirm the bug

**Comment by Angyo** [comment] 2015-03-01 19:36
I updated my contentbuilders schema to add a name column, but its not solve the problems. Thanks again for your help :)

I have check in TranslateTrait, Cake\ORM\Behavior\Translate and it appears that my translations are not recover

    $i18n = $this->get('_translations');

    \src\ORM\Behavior\Translate\TranslateTrait.php (line 57)
	object(App\Model\Entity\Contentbuilder) {

		'new' => false,
		'accessible' => [
			'*' => true
		],
		'properties' => [
			'id' => (int) 1,
			'type' => (int) 1,
			'parent_id' => null,
			'lft' => (int) 1,
			'rght' => (int) 2,
			'_translations' => [
				'fr_FR' => object(Cake\ORM\Entity) {

					'new' => true,
					'accessible' => [
						'*' => true
					],
					'properties' => [],
					'dirty' => [],
					'original' => [],
					'virtual' => [],
					'errors' => [],
					'repository' => null
				
				}
			],
			'children' => []
		],
		'dirty' => [
			'children' => true,
			'_translations' => true
		],
		'original' => [
			'_translations' => [
				'en_US' => object(Cake\ORM\Entity) {

					'new' => false,
					'accessible' => [
						'*' => true
					],
					'properties' => [
						'name' => 'Main menu',
						'locale' => 'en_US'
					],
					'dirty' => [],
					'original' => [],
					'virtual' => [],
					'errors' => [],
					'repository' => null
				
				},
				'fr_FR' => object(Cake\ORM\Entity) {

					'new' => false,
					'accessible' => [
						'*' => true
					],
					'properties' => [
						'name' => 'Menu principal',
						'locale' => 'fr_FR'
					],
					'dirty' => [],
					'original' => [],
					'virtual' => [],
					'errors' => [],
					'repository' => null
				
				}
			]
		],
		'virtual' => [],
		'errors' => [],
		'repository' => 'Contentbuilders'

	}

So my translation are in original, but no the getter dont recover it and generate a new empty and fresh Entity ?!

**Comment by lorenzo** [comment] 2015-03-01 20:02
Closing as there is a pull request open

**Closed by lorenzo** 2015-03-01 20:02 UTC
Labels: Defect
