### ISSUE TITLE
2.x: Containable retrieves too much data

### ISSUE THREAD

**Issue by janriokrause** [cakephp/cakephp#7171] opened 2015-08-04 14:09 UTC
Containable will retrieve a lot of more data than requested under certain circumstances. Take a look at the following example with the [database schema](http://pastebin.com/yQEb9Bje). I have simplified the whole code and associations to a minimum to reproduce the bug.

After some tests, I figured out that the bug first appeared from `v2.1.1` to `v2.1.2`.

```php
<?php
App::uses('Model', 'Model');
class AppModel extends Model {

	public $actsAs = [
		'Containable',
	];

}
```

```php
<?php
class AgeGroup extends AppModel {

	public $hasMany = [
		'Result',
	];

}
```

```php
<?php
class Competition extends AppModel {

	public $hasMany = [
		'Result',
	];

	public $hasAndBelongsToMany = [
		'AgeGroup',
	];

}
```

```php
<?php
class Event extends AppModel {

	public $hasAndBelongsToMany = [
		'Competition',
	];

}
```

```php
<?php
class Result extends AppModel {

	public $belongsTo = [
		'AgeGroup',
		'Event',
	];

	public function afterFind($results, $primary = false) {
		foreach ($results as $key => $value) {
			// sometimes I need to access details of the event. I cannot use $value['Event'] since it is not set, so I query it myself.
			$this->Event->id = $value['Result']['event_id'];
			$name = $this->Event->field('name'); // try commenting out the entire line and see the changes happen in the ouput
		}
		return $results;
	}

}
```

```php
<?php
class CompetitionsController extends AppController {

	public function index() {
		debug($this->Competition->find('first', [
			'conditions' => ['id' => 1],
			'contain' => [
				'Result' => [
					'AgeGroup',
				],
			],
		]));
	}

}
```

Desired output of controller:

```php
array(
	'Competition' => array(
		'id' => '1',
		'name' => 'test'
	),
	'Result' => array(
		(int) 0 => array(
			'id' => '1',
			'age_group_id' => '1',
			'competition_id' => '1',
			'event_id' => '1',
			'AgeGroup' => array(
				'id' => '1',
				'name' => 'test'
			)
		)
	)
)
```

Actual output of Controller:

```php
array(
	'Competition' => array(
		'id' => '1',
		'name' => 'test'
	),
	'Result' => array(
		(int) 0 => array(
			'id' => '1',
			'age_group_id' => '1',
			'competition_id' => '1',
			'event_id' => '1',
			'AgeGroup' => array(
				'id' => '1',
				'name' => 'test'
			)
		)
	),
	'AgeGroup' => array(
		(int) 0 => array(
			'id' => '1',
			'name' => 'test',
			'AgeGroupsCompetition' => array(
				'id' => '1',
				'age_group_id' => '1',
				'competition_id' => '1'
			),
			'Result' => array(
				(int) 0 => array(
					'id' => '1',
					'age_group_id' => '1',
					'competition_id' => '1',
					'event_id' => '1'
				),
				(int) 1 => array(
					'id' => '2',
					'age_group_id' => '1',
					'competition_id' => '2',
					'event_id' => '1'
				),
				(int) 2 => array(
					'id' => '3',
					'age_group_id' => '1',
					'competition_id' => '2',
					'event_id' => '1'
				),
				// ...
				// ...
				// ...
				(int) 99 => array(
					'id' => '100',
					'age_group_id' => '1',
					'competition_id' => '2',
					'event_id' => '1'
				)
		),
		(int) 1 => array(
			// If there are other age groups linked to competition 1 this data is fetched, too
			// this also includes all results linked to the age group just fetched
		)
	)
)
```

**Comment by lorenzo** [comment] 2015-08-04 14:21
I have never seen this problem before, version `2.1.x` was released a long long time ago, have you first tried using a version of the framework that is supported?

**Comment by janriokrause** [comment] 2015-08-04 14:24
Yes, the bug still appears in `v2.7.1`.

**Comment by janriokrause** [comment] 2015-08-04 14:39
Of course, I use the most recent `v2.x`. I just did some tests by downgrading every version from `v2.7.1` to figure out when the bug was first introduced. This revealed the update from `v2.1.1` to `v2.1.2`. Thought that would be a helpful information? :-) All versions released later on are affected.

**Comment by lorenzo** [comment] 2015-08-04 14:56
@janriokrause I think that would point to a misconfiguration of your asociations or perhaps a behavior/beforeFind that is adding more stuff to contain. By looking at your simplified example I'm confident to say that the problem is not in the core, since I have worked in plenty applications with similar use cases without experiencing this problem.

It would help to either have a reproducible test case, if you know hoe to do it, or maybe get a full insight in how your associations are setup and what code is actually executed.

**Comment by janriokrause** [comment] 2015-08-04 22:06
@lorenzo, I'm sorry to contradict you, but you actually **can** reproduce the bug with only my code posted above. I tested every version from `v2.1.1` to the most current `v2.7.1` and as said, the bug started to appear in `v2.1.2` The app only consists of the 5 models, the 1 controller and my database schema linked above with a fresh CakePHP installation. Nothing else. No behavior, no plugins, no extras. Try it out if you don't believe :-)

**Comment by lorenzo** [comment] 2015-08-05 06:39
No problem in contradicting, this is what the issue tracker is for. I will give it a try today

**Comment by lorenzo** [comment] 2015-08-05 06:43
Ok, looking at your code again, I notice that there is a field() inside the afterFind(). That is the reason this problem happens for you. Can you try using a find() instead with callbacks => false as an option an see if the error persists?

**Comment by lorenzo** [comment] 2015-08-05 06:47
yeah, I had missed entirely our afterFind() logic before. This is actually a sad limitation of the containable behavior,

**Comment by lorenzo** [comment] 2015-08-05 06:48
Aaahrg fat fingers, sorry for closing

**Comment by janriokrause** [comment] 2015-08-06 12:57
Even with `'callbacks' = false` in my `find()` the output differs from my expectation. `AgeGroup` does not belong on the first level. I requested `Result.AgeGroup`, not `AgeGroup`. See below:

```php
array(
	'Competition' => array(
		'id' => '1',
		'name' => 'test'
	),
	'Result' => array(
		(int) 0 => array(
			'id' => '1',
			'age_group_id' => '1',
			'competition_id' => '1',
			'event_id' => '1'
		)
	),
	'AgeGroup' => array(
		(int) 0 => array(
			'id' => '1',
			'name' => 'test',
			'AgeGroupsCompetition' => array(
				'id' => '1',
				'age_group_id' => '1',
				'competition_id' => '1'
			)
		),
		(int) 1 => array(
			'id' => '2',
			'name' => 'test',
			'AgeGroupsCompetition' => array(
				'id' => '2',
				'age_group_id' => '2',
				'competition_id' => '1'
			)
		)
	)
)
```

**Comment by lorenzo** [comment] 2015-08-06 13:35
`'contain'` needs `callbacks => true`

**Comment by janriokrause** [comment] 2015-08-06 20:15
Unfortunately, `'callbacks' => true` does not change anything when put in `'contain'`.

**Comment by chinpei215** [comment] 2015-10-31 16:07
@janriokrause I tried to reproduce this issue now, but I couldn't. I've got expected results. So what version of PHP are you using? It seems to me that caused by broken reference.

**Comment by janriokrause** [comment] 2015-11-01 00:21
@chinpei215 I use PHP Version 5.6.10 and one can *definitively* reproduce the bug with the code above. I checked it multiple times. Please make sure you did not forget any files I have posted and also check if your database is filled. I have linked to a database dump in my first post.

**Comment by janriokrause** [comment] 2015-11-01 00:24
@chinpei215 I use PHP Version 5.6.10 but the bug also appears on older versions. I do not assume the PHP version is responsible for this behavior.

One can definitively reproduce the bug with the code above. I checked it multiple times. Please make sure you did not forget any files I have posted and also check if your database is filled. I have linked to a database dump in my first post.

**Comment by chinpei215** [comment] 2015-11-01 02:16
@janriokrause Sorry, I could reproduce it now. The first time, I baked all models and added the afterFind() to Result model. I'll take a look related programs.

**Comment by chinpei215** [comment] 2015-11-01 02:36
@janriokrause When I fix your Event model like the following, I get  this issue solved. I plan on investigating the reason. Thanks.

```php
<?php
class Event extends AppModel {
	public $hasAndBelongsToMany = array(
		'Competition' => array(
			'joinTable' => 'competitions_events',
			'foreignKey' => 'event_id',
			'associationForeignKey' => 'competition_id',
		)
	);
}
```

**Comment by chinpei215** [comment] 2015-11-01 02:40
@janriokrause I noticed that there is no competitions_events table in your schema. So I created it myself. Why don't you have competitions_events table ?

**Comment by janriokrause** [comment] 2015-11-02 10:36
> ~~Why don't you have competitions_events table ?~~
> But I am Ok with this. I think it is not related with this issue. 

@chinpei215, Yes, that's the reason I did not include it. I tried to narrow down the code, which is necessary to reproduce the bug, to its minimum.

**Comment by chinpei215** [comment] 2015-11-03 07:32
@janriokrause OK. And I know the reason now. As @lorenzo mentioned above, you cannot call `field` in the `afterFind` if you want to use `contain`. In 2.x, probably as you know, `contain` is implemented by a tricky way, by changing associated models and `recursive` levels temporally on before/after reading records. And nesting `find` call breaks such a temporary change. (`field` calls `find` internally.)

Concretely, `Competition::find` unbinds `AgeGroup` from `Competition`, however `Event::field` rebind `AgeGroup` to `Competition`. You got unexpected results for the reason.

So it's a feature at this time. But I think that we can solve this issue by introducing stack to behind temporary changes. I can try to fix it if everyone wants.

**Comment by janriokrause** [comment] 2015-11-03 15:43
> I can try to fix it if everyone wants.

Would be great, @chinpei215. Or is it better, if I explicitly configure the HABTM association?

On the other hand, I have some more find queries in my app, which produce similar large results and they cannot be fixed with this explicit setting in the `Event` model. Or maybe I have to do this in the other models, too?!

**Comment by chinpei215** [comment] 2015-11-03 16:56
> Or is it better, if I explicitly configure the HABTM association

No. Sorry for my misguiding. Explicit configuration is not directly related with this issue. A workaround may be to use your custom finder instead of nesting `find` call:
```php
class Competition extends AppModel
{
	public $findMethods = ['something' =>  true];

	public function _findSomething($state, $query, $results = []) {
		if ($state === 'before') {
			$query['contain'] = [
				'Result' => [ 'AgeGroup' ]
			];
			return $query;
		}

		// Filter results here
		foreach ($results as $result) {
			foreach ($result['Result'] as $record) {
				$this->Event->id = $record['event_id'];
				$name = $this->Event->field('name');
			}
		}
		return $results;
	}
}

class CompetitionsController extends AppController {
	public function index() {
		$this->Competition->find('something', [
			'conditions' => ['id' => 1],
		]);
	}
}
```

**Comment by MikeyF-Anovia** [comment] 2015-11-25 20:20
I am having trouble with this as well. Find operations with the contain option are resulting in way more association queries than were requested. In my case, one of our models has a lot of relationships to other models that also have a lot of relationships and this issue is causing a significant amount of slow downs. I've tried to determine what I might be doing to cause the issue to pop up but I've yet to figure it out. I even put a break point in Model.php->find() to see if it is being called by code elsewhere. Any suggestions on how to track down the cause and prevent it from happening in my case?

**Comment by lorenzo** [comment] 2015-11-25 20:43
@MikeyF-Anovia What is the code you used?

**Comment by MikeyF-Anovia** [comment] 2015-11-30 17:13
@lorenzo Hi. I'm not certain what you mean by "code you used", but I'm guessing you are wanting to know how I setup the query/find. Below is how I do that:

    $queryOptions = [
        "fields"     => [ <Merchant fields> ],
        "conditions" => [ "Merchant.id" => "1315645facb6a54473605789" ],
        "contain"    => [ <various Merchant model relationships with individual fields in fields array of each> ]
    ]

    if(!$mdl->Behaviors->loaded("Containable")) $mdl->Behaviors->load("Containable");
    $mdl->recursive = -1;
    $row = $mdl->find("first", $queryOptions);

Depending on the associations I include in $queryOptions["contain"], $row will often times contain more associations than I requested.

Thanks, Mikey

**Comment by MikeyF-Anovia** [comment] 2015-12-01 22:44
I believe my issue is related to requesting two or more associations in the contains that use the same alias but utilize different models and/or contains settings. Merchant.Account.ApiResponse and Merchant.Contact.ApiResponse  and Merchant.ApiResponse had different contains/fields settings. The ContainableBehavior uses an array keyed off of relationship alias in $containments['models'].  It doesn't seem to be able to handle two or more different models that happen to use the same alias. 

You can disregard my request for troubleshooting tips. I have enough info to go on for me to hunt it down and work around it. Thanks!

**Comment by lorenzo** [comment] 2015-12-02 08:21
Using duplicate aliases is not allowed in cake. Aliases should be unique, one of the reasons being that models are always referred to by using their alias and not the name

**Comment by chinpei215** [comment] 2016-01-12 14:48
@janriokrause @MikeyF-Anovia  Do you remember this issue? Recently I created a [plugin](https://github.com/chinpei215/cakephp-eager-loader) to solve this issue and something. I would be happy if you try it. If you are afraid that loading my plugin breaks something somewhere, you can also enable it on the fly.
```php
$this->Competition->Behaviors->load('EagerLoader.EagerLoader');
debug($this->Competition->find('first', [
    'conditions' => ['id' => 1],
    'contain' => [
        'Result' => [
            'AgeGroup',
        ],
    ],
]));
```
 I already confirmed this issue solved in this way.
Thanks.

**Comment by MikeyF-Anovia** [comment] 2016-01-14 19:35
Thanks @chinpei215, but I have already worked around it. But I'm sure others that come upon this thread will find your plugin useful. Thank you!!

**Comment by chinpei215** [comment] 2016-01-15 09:46
@MikeyF-Anovia No problem. I didn't make it on time. Thank you for your reply!

**Comment by janriokrause** [comment] 2016-02-10 18:40
Thank you @chinpei215. Your plugin solves the problem. Unfortunately it produces syntax errors when using a table prefix given in `app/Config/database.php`. Maybe you could check that, please.

**Comment by chinpei215** [comment] 2016-02-11 06:02
@janriokrause Thank you very much for your feedback. I have just fixed the problem and created a new release. If you find anthoer problems, feel free to open issues in my repository. Thanks!

**Comment by lorenzo** [comment] 2016-03-05 14:56
This has been a very long-lived bug and changing the behavior of the code could break applications. Givent that there is a plugin available to overcome the issue, I think this can be safely closed now.

**Closed by lorenzo** 2016-03-05 14:56 UTC
Labels: On hold
