### ISSUE TITLE
Problem with patchEntity saving hasMany associations

### ISSUE THREAD

**Issue by boindil** [cakephp/cakephp#11145] opened 2017-09-03 19:28 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.0
* Platform and Target: Apache 2.4, PHP 7.0.22, MariaDB 10

### What you did
Tables (working):
User -- hasMany --> UserRabattBerechtigung

Controller:
```
$userData = $this->User->find('all')
	->where([
		'User.id' => $tokenData->user_id,
		'User.typ' => 'K',
		'User.status' => 'AKTIV'
	])->contain(['UserRabattBerechtigung']);

if($this->request->data('user_rabatt_berechtigung') !== null && is_array($this->request->data('user_rabatt_berechtigung'))) {
	$rabattberechtigung_std = [
		'id_kunde' => $user->id,
		'check_berechtigung' => 'J',
		'check_berechtigung_erl' => 'N',
		'check_berechtigung_am' => '',
		'id_benutzer_last' => $user->id,
		'last_update' => date('Y-m-d'),
		'id_benutzer_check' => 0
	];
								
	foreach($this->request->data('user_rabatt_berechtigung') as &$rabattberechtigung) {
		$rabattberechtigung = array_merge($rabattberechtigung_std, ['id_rabattberechtigung' => $rabattberechtigung]);

		// below works, but i would like to validate all data to get all errors together (if there are any)
		// $user->user_rabatt_berechtigung[] = $this->User->UserRabattBerechtigung->newEntity($rabattberechtigung, ['validate' => 'userEdit']); 
	}
}

$this->User->patchEntity($user, $this->request->getData(), [
	'associated' => [
		'UserRabattBerechtigung' => [
			'validate' => 'userEdit'
		]
	]
]);

var_dump($user); // no "user_rabatt_berechtigung" added
```

### What happened
Because of the explaination on https://book.cakephp.org/3.0/en/orm/saving-data.html#converting-hasmany-data I would expect my code to work, but the entity gets no additional entries in `$user->user_rabatt_berechtigung`.

> If you want to update existing hasMany associations and update their properties, you should first ensure your entity is loaded with the hasMany association populated. You can then use request data similar to:
```
$data = [
    'title' => 'My Title',
    'body' => 'The text',
    'comments' => [
        ['id' => 1, 'comment' => 'Update the first comment'],
        ['id' => 2, 'comment' => 'Update the second comment'],
        ['comment' => 'Create a new comment'],
    ]
];
```

### What you expected to happen
Getting a patched Entity with additional entries in `$user->user_rabatt_berechtigung`, but sadly there aren't.

**Comment by markstory** [comment] 2017-09-04 01:08
What does the `_accessible` property of your `User` entity look like?

**Comment by boindil** [comment] 2017-09-04 17:21
It looks like this:
```
protected $_accessible = [
	'id' => false,
	'field' => true // repeat for neccessary fields
];
```

It doesn't even work when adding `'user_rabatt_berechtigung' => true` although I thought this wouldn't be neccessary anyways because its a field that results from a relation. Still, thats not the solution.

It may be worth noting, that I can patch a different entity, that is related via hasOne. That works like a charm, the problem only exists when using hasMany and the Code above.

**Comment by markstory** [comment] 2017-09-04 21:25
I am not able to reproduce this issue. There are a few test cases covering this behaviour working. I suspect that a combination of your entities, associations, request data and schema are source of the issue.

The association fields *do need* to be in your accessible list of you're wanting the marshaller to populate the association data.

**Comment by boindil** [comment] 2017-09-05 18:43
Thats weird, I did not specify the the other field (resulting from `User hasOne UserSepa` association), but I can patch it without problems. Still I added `'*' => true` for testing purposes - doesn't help.

Here are my entites, associations and request data:
P.S.: The tables are somewhat old and odd, I cannot influence table structure. The project goal is to provide a REST API for external services without needing to change local web-apps, that connect directly to the MySQL server.

1) User -- hasOne --> UserSepa
1.1) patchEntity on `User` entity works
2) User -- hasMany --> UserRabattBerechtigung
2.1) patchEntity on `User` entity does not work
2.2) creating a new `UserRabattBerechtigung` entity with newEntity and the same data (combined from request and standard options) works, too.
3) additionally I provide the data that is used in patchEntity and the `User` entity being patched.

```
class UserTable extends Table {
	public function initialize(array $config) {
		parent::initialize($config);
		
		$this->setTable('benutzer');
		$this->setDisplayField('id');
		$this->setPrimaryKey('id');
			
		$this->addBehavior('Timestamp', [
			'events' => [
				'Model.beforeSave' => [
					'last_date' => 'always',
				],
			]
		]);
		
		$this->hasMany('UserRabattBerechtigung', [
			'foreignKey' => 'id_kunde'
		]);
		
		$this->hasOne('UserSepa', [
			'foreignKey' => 'benutzer_id'
		]);
	}

	public function buildRules(RulesChecker $rules) {
		$rules->add($rules->isUnique(['email']));
		return $rules;
	}

	public function validationDefault(Validator $validator) {
		// validation rules, tested and working
		return $validator;
	}
}
```
```
class UserSepaTable extends Table {
	public function initialize(array $config) {
		parent::initialize($config);
			
		$this->setTable('benutzer_sepa');
		$this->setDisplayField('id');
		$this->setPrimaryKey('id');
		
		$this->belongsTo('User', [
			'foreignKey' => 'benutzer_id'
		]);
	}
	
	public function buildRules(RulesChecker $rules) {
		$rules->add($rules->isUnique(['benutzer_id']));
		$rules->add($rules->isUnique(['ref']));
		return $rules;
	}

	public function validationDefault(Validator $validator) {
		// validation rules, tested and working
		return $validator;
	}
}
```
```
class UserRabattBerechtigungTable extends AppTable {
	public function initialize(array $config) {
		parent::initialize($config);
		
		$this->setTable('benutzer_rabattberechtigung');
		$this->setDisplayField('id');
		$this->setPrimaryKey('id');
		
		$this->addBehavior('Timestamp', [
			'events' => [
				'Model.beforeSave' => [
					'last_update' => 'always',
				],
			]
		]);
		
		$this->belongsTo('RabattBerechtigung', [
			'foreignKey' => 'id_rabattberechtigung'
		]);
		
		$this->belongsTo('User', [
			'foreignKey' => 'id_kunde'
		]);
			
		$this->hasOne('UserLastEdit', [
			'className' => 'App\Model\Table\UserTable',
			'foreignKey' => 'id',
			'bindingKey' => 'id_benutzer_last',
		]);
			
		$this->hasOne('UserChecking', [
			'className' => 'App\Model\Table\UserTable',
			'foreignKey' => 'id',
			'bindingKey' => 'id_benutzer_check',
		]);
	}
	
	public function buildRules(RulesChecker $rules) {
		$rules->add($rules->existsIn('id_rabattberechtigung', 'rabatt_berechtigung'));
		$rules->add($rules->existsIn(['id_kunde', 'id_benutzer_last'], 'user'));

		return $rules;
	}
		
	public function validationDefault(Validator $validator) {
		// validation rules, tested and working
		return $validator;
	}
}
```

data used in `patchEntity`
```
array(19) {
  ... some fields to be saved in `User` table ...
  ["user_rabatt_berechtigung"]=>
  array(1) {
    [0]=>
    array(8) {
      ["id_kunde"]=>
      int(2)
      ["check_berechtigung"]=>
      string(1) "J"
      ["check_berechtigung_erl"]=>
      string(1) "N"
      ["check_berechtigung_am"]=>
      string(0) ""
      ["id_benutzer_last"]=>
      int(2)
      ["last_update"]=>
      string(10) "2017-09-05"
      ["id_benutzer_check"]=>
      int(0)
      ["id_rabattberechtigung"]=>
      int(55)
    }
  }
  ["user_sepa"]=>
  array(5) {
    ["benutzer_id"]=>
    int(2)
    ["iban"]=>
    string(22) "DE73200505501354405159"
    ["bic"]=>
    string(11) "HASPDEHHXXX"
    ["ref"]=>
    string(1) "2"
    ["date"]=>
    object(Cake\I18n\FrozenDate)#246 (3) {
      ["time"]=>
      string(25) "2017-09-03T00:00:00+00:00"
      ["timezone"]=>
      string(3) "UTC"
      ["fixedNowTime"]=>
      bool(false)
    }
  }
}
```

The `User` entity being patched already has some `UserRabattBerechtigung` entities in the appropriate field, but when using `patchEntity` no new entity gets added. I dont get any error, the other fields - including the one connected via `hasOne` - get populated as expected. I don't see any error here at all. Maybe I'm horribly mistaken, but perhaps there's actually a bug to fix.

The data to be inserted does also not conflict with existing keys in the database, a manual check inserting the row confirmed this.

**Comment by markstory** [comment] 2017-09-05 19:10
You might want to dig through the marshaller and see where the association property is losing the plot.

https://github.com/cakephp/cakephp/blob/a44aac77a4bb5b2aff8fd53c6aaa22856b860cd9/src/ORM/Marshaller.php#L557

is where the map of properties that will be marshalled is defined. If a property is missing from here, it likely wasn't an association that should be marshalled.

https://github.com/cakephp/cakephp/blob/a44aac77a4bb5b2aff8fd53c6aaa22856b860cd9/src/ORM/Marshaller.php#L568-L582

Is where the marshalled values are applied to the entity data. It is notable that fields with errors are not applied to entities as only valid data is merged into entities.

**Comment by boindil** [comment] 2017-09-05 22:51
$propertyMap:
```
/src/ORM/Marshaller.php (line 558)
[
	... the fields from `User` ...
	'user_rabatt_berechtigung' => object(Closure) { // hasMany
		
	},
	'user_sepa' => object(Closure) { // hasOne
		
	}
]
```
After some digging I noticed the following: the merge method gets called twice. Once for `User` and once for `UserSepa`, but not for `UserRabattBerechtigung`.

Still, an entity for `UserRabattBerechtigung` was generated at some point.
https://github.com/cakephp/cakephp/blob/a44aac77a4bb5b2aff8fd53c6aaa22856b860cd9/src/ORM/Marshaller.php#L740
I guess it was done im mergeMany (at least the output is the same);

https://github.com/cakephp/cakephp/blob/a44aac77a4bb5b2aff8fd53c6aaa22856b860cd9/src/ORM/Marshaller.php#L582
the `$value` contains the following:
```
array(1) {
  [0]=>
  object(App\Model\Entity\UserRabattBerechtigung)#351 (16) {
    ["id_kunde"]=>
    int(2)
    ["check_berechtigung"]=>
    string(1) "J"
    ["check_berechtigung_erl"]=>
    string(1) "N"
    ["check_berechtigung_am"]=>
    NULL
    ["id_benutzer_last"]=>
    int(2)
    ["last_update"]=>
    string(10) "2017-09-06"
    ["id_benutzer_check"]=>
    int(0)
    ["id_rabattberechtigung"]=>
    int(55)
    ["[new]"]=>
    bool(true)
    ["[accessible]"]=>
    array(9) {
      ["id"]=>
      bool(true)
      ["id_kunde"]=>
      bool(true)
      ["id_rabattberechtigung"]=>
      bool(true)
      ["check_berechtigung"]=>
      bool(true)
      ["check_berechtigung_erl"]=>
      bool(true)
      ["check_berechtigung_am"]=>
      bool(true)
      ["id_benutzer_last"]=>
      bool(true)
      ["last_update"]=>
      bool(true)
      ["id_benutzer_check"]=>
      bool(true)
    }
    ["[dirty]"]=>
    array(8) {
      ["id_kunde"]=>
      bool(true)
      ["check_berechtigung"]=>
      bool(true)
      ["check_berechtigung_erl"]=>
      bool(true)
      ["check_berechtigung_am"]=>
      bool(true)
      ["id_benutzer_last"]=>
      bool(true)
      ["last_update"]=>
      bool(true)
      ["id_benutzer_check"]=>
      bool(true)
      ["id_rabattberechtigung"]=>
      bool(true)
    }
    ["[original]"]=>
    array(0) {
    }
    ["[virtual]"]=>
    array(0) {
    }
    ["[errors]"]=>
    array(0) {
    }
    ["[invalid]"]=>
    array(0) {
    }
    ["[repository]"]=>
    string(22) "UserRabattBerechtigung"
  }
}
```

I do not get yet, why its not working, trying to get some more info tomorrow. Maybe u have another idea where to search?

**Comment by boindil** [comment] 2017-09-10 12:42
Ok, I found out the root cause of this behavior ...

When using `patchEntity` together with the `fieldList` argument, the `hasMany` fields have to be added, but the `hasOne` fields do not have to be added (checked at least with existing matching data in the related table).

P.S.: I do not had to add these fields into the `$_accessible` property. Actually this property does nothing for me. Even adding `'*' => false` and removing everything else still works.

**Comment by markstory** [comment] 2017-09-10 14:21
Why didn't any of your comments or code examples show you using `fieldList`? That is a very important piece of behavior, and would have been useful to know at the beginning of this issue. 

Using `fieldList` overrides the `_accessible` declaration which is why changing it makes no effect. Closing as the ORM is working as it is supposed to.

**Closed by markstory** 2017-09-10 14:21 UTC
Labels: Defect, On hold, ORM
