### ISSUE TITLE
ExceptionRenderer fails on ArgumentCountError

### ISSUE THREAD

**Issue by mdlouhy** [cakephp/cakephp#11530] opened 2017-12-11 13:13 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.7

### What you did
I called a private method 
i.e. __privateMethod($requiredParam) 
in an action and forgot to pass the required param which triggered an ArgumentCountError.

### What happened
ExceptionRenderer __construct(Exception $exception) failed because ArgumentCountError is not an instance of Exception

### What you expected to happen
Outputting that an ArgumentCountError happend in __privateMethod and which line number or at least output that information into error log file.

**Comment by dereuromark** [comment] 2017-12-11 13:26
Duplicate of https://github.com/cakephp/cakephp/issues/11514
Will be fixed with the new patch release tomorrow at the latest.

**Closed by dereuromark** 2017-12-11 13:26 UTC
