### ISSUE TITLE
3.0 - Cookies unable to contain brackets

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#6172] opened 2015-03-25 22:17 UTC
It's possible this is one of those things that are impossible to fix, but right now I can't use `CookieComponent` to write cookies that have brackets in the name. In my 2.x app there are cookies that are set with the array-style, `CakeCookie[ThisThing]`, but in 3.0 I can't just do this:
```
$this->Cookie->write('CakeCookie[ThisThing]', 10);
```
Trying to use dots, `Cookie->write('CakeCookie.ThisThing', 10)` results in the cookie name being `CakeCookie`, which isn't usable either. (Edit - I'm pretty sure that's as intended, though. Just trying to see how I can get an array-style cookie name.) It seems that it's the `Hash` class:

```
#1
Hash::insert([], 'CakeCookie[ThisThing]', 'hello'); # -> Array ()

#2
Hash::insert([], 'what', 'hello'); # -> Array ( [what] => hello )
```

Should `#1` above be an empty array? I don't know what the special conditions `Hash::insert` are doing with brackets, but `noTokens` in that method seems to be messing this up.

Thanks

**Comment by markstory** [comment] 2015-03-26 00:48
This may be an unintended consequence of trying to unify how cookie data is handled. In 2.x you could  easily get into a spot where deleting or updating data wouldn't always work.

I think there is a pretty simple solution to this where we can bypass Hash::insert() if there are no `.` in the $name.

**Comment by markstory** [comment] 2015-03-26 02:40
Fixed with #6173

**Comment by patrickconroy** [comment] 2015-03-26 03:52
Thanks!

**Comment by markstory** [comment] 2015-04-05 01:08
The root cause of this issue is that the CookieComponent in 3.x stores all the data for a cookie keyspace as a single cookie. In 2.x each top level key was a separate cookie value sometimes depending on how you wrote the cookie data.

I'm not sure there is a fix that doesn't also compromise totally opaque encrypted cookie data unfortunately.

**Comment by patrickconroy** [comment] 2015-04-08 16:54
Thanks @markstory, that makes sense to me. If it's just not possible without compromising security, then I'd say this issue can be closed since it's really just an issue of upgrading from 2 to 3. I'll let you guys decide its fate, though.

**Closed** 2015-04-08 20:35 UTC
Labels: component, Defect
