### ISSUE TITLE
array_values() expects parameter 1 to be array, boolean given [CORE/src/Controller/Controller.php, line 440]

### ISSUE THREAD

**Issue by CriztianiX** [cakephp/cakephp#10480] opened 2017-04-04 20:05 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.4
* Platform and Target: Apache2, PostgresSQL. Centos Linux

### What you did
Update from CakePHP 3.3.15 to 3.4.

### What happened
array_values() expects parameter 1 to be array, boolean given [CORE/src/Controller/Controller.php, line 440]

Warning (2): Only arrays and Traversables can be unpacked [CORE/src/Controller/Controller.php, line 440]

Warning (512): Unable to emit headers. Headers sent in file=/vendor/cakephp/cakephp/src/Error/Debugger.php line=822 [CORE/src/Http/ResponseEmitter.php, line 48]

### What you expected to happen
Should be work like in 3.3.15

**Comment by markstory** [comment] 2017-04-04 22:27
How can someone reproduce this issue. Right now I have no idea what you did to trigger this error.

**Comment by markstory** [comment] 2017-04-04 22:29
This seems similar to #10463

**Comment by saeideng** [comment] 2017-04-04 23:08
@markstory no
#10463 is similar to https://github.com/cakephp/cakephp/issues/10286
that resolved in https://github.com/cakephp/cakephp/pull/10287

**Comment by saeideng** [comment] 2017-04-05 00:03
@CriztianiX  probably you set the request params ( or param) to boolean

**Comment by CriztianiX** [comment] 2017-04-05 12:41
@saeideng My request params, (taken from Controller) are

[
	'controller' => 'Mdeal',
	'action' => 'filtered',
	'query' => [
		'here' => 'descuentos-y-promociones-en-combustible-C-8',
		'url' => 'descuentos-y-promociones-en-combustible',
		'seo' => true,
		'category_id' => (int) 8
	],
	'plugin' => null,
	'_ext' => null,
	'pass' => [],
	'isAjax' => false
]

**Comment by saeideng** [comment] 2017-04-05 16:05
What args of your filtered() action looks like?

Public function  filtered(){}

**Comment by markstory** [comment] 2017-04-05 16:34
@CriztianiX What is the value out `$request->getParam('pass')`? The [line emitting the error](https://github.com/cakephp/cakephp/blob/master/src/Controller/Controller.php#L440) calls that method, which shouldn't be returning `false` unless the request is being changed somewhere.

**Comment by CriztianiX** [comment] 2017-04-05 16:53
I have a Middleware, 
https://gist.github.com/CriztianiX/e6e03fd189bee1430463bfed3dd73c19

I've have a routing filter too
https://gist.github.com/CriztianiX/9cc2d1d50cf93db8dae1f8351e592f86

And finally i have a custom router class
https://gist.github.com/CriztianiX/4823329550aa556688a4eab059e790cb

**Comment by markstory** [comment] 2017-04-05 17:14
I don't really have time to read through all your code, but somewhere the `pass` parameter is being set to a boolean (based on the error your seeing). That parameter should always be an array. Given that this issue cannot be reproduced with the standard CakePHP classes I'm going to close the issue.

**Closed by markstory** 2017-04-05 17:14 UTC
Labels: Defect, On hold

**Comment by saeideng** [comment] 2017-04-05 18:44
We can convert to [] when pass setted to false in that line
I can open PR for this if necessary @markstory

**Comment by CriztianiX** [comment] 2017-04-05 19:32
@saeideng Yes... 
I think it should be like this, in order to keep the compatibility with 3.3.x

**Comment by ADmad** [comment] 2017-04-05 19:58
I don't think any fix is required. `pass` is always supposed to be an array, it's just​ dumb luck that you didn't get an error for it earlier.

**Comment by CriztianiX** [comment] 2017-04-05 20:54
@AD7six so, why works in 3.3.x?
