### ISSUE TITLE
Cakephp 3 saving belongsToMany Relationship _ids gives Fatal Error

### ISSUE THREAD

**Issue by whitep4nther** [cakephp/cakephp#6301] opened 2015-04-08 22:41 UTC
Currently trying to save belongsToMany Relationship _ids (not inserting new data) which gives me a fatal error.

Link on stackoverflow: http://stackoverflow.com/questions/29506379/cake-3-saving-belongstomany-relation-crashes

Screenshot: 
![screen shot 2015-04-09 at 00 40 09](https://cloud.githubusercontent.com/assets/8074336/7056960/195441c2-de51-11e4-8e53-f699d1ca5d8d.png)

**Comment by markstory** [comment] 2015-04-09 00:47
How could someone reproduce this issue? It looks like an instance cannot be created/found.

**Comment by markstory** [comment] 2015-04-09 00:52
After reading your stackoverflow question, if you don't save the Attributes association do you get the same error? What does `debug($skus)` before the save method look like?

**Comment by whitep4nther** [comment] 2015-04-09 07:56
Ok, I found it. I just forgot to mention the 'Images' association in the patchEntity options (yeah I know...).
Still it shouldn't throw a fatal error like that so maybe this is something that could be fixed.
The error occurs everytime you try to save a linked belongsToMany association without mentioning it (I tried with the Attributes association and it did the same).

Thanks for your help

**Comment by markstory** [comment] 2015-04-09 11:43
@whitep4nther Yes that totally should not trigger a fatal error. I'll get that fixed.

**Comment by markstory** [comment] 2015-04-10 01:07
Closing as #6311 is open.

**Closed by markstory** 2015-04-10 01:07 UTC
Labels: Defect, ORM
