### ISSUE TITLE
DatabaseSession Integrity Constraint Violation

### ISSUE THREAD

**Issue by davidsteinsland** [cakephp/cakephp#2808] opened 2014-02-10 16:28 UTC
I am currently debugging a session issue where a PDOException is throw saying that there already exists a primary key with `<SESSION_ID>`. It appears to only happen during ajax requests.

Before `Model->save()`, `findById($sessionId)` returns false. After the exception is thrown, `findById(..)` returns true.

```
SQLSTATE[23000]: Integrity constraint violation: 1062 
Duplicate entry 'c760db8417dd5b9ec81d9dc3d99b743572c28a3c0d3ad2ed27b8b9ddc3e0531f' 
for key 'PRIMARY' in file
/var/www/cakephp/repo/lib/Cake/Model/Datasource/DboSource.php on line 458.

Stack trace:

#0 /var/www/cakephp/repo/lib/Cake/Model/Datasource/DboSource.php(458): PDOStatement->execute(Array)
#1 /var/www/cakephp/repo/lib/Cake/Model/Datasource/DboSource.php(424): DboSource->_execute('INSERT INTO `pe...', Array)
#2 /var/www/cakephp/repo/lib/Cake/Model/Datasource/DboSource.php(1004): DboSource->execute('INSERT INTO `pe...')
#3 /var/www/cakephp/repo/lib/Cake/Model/Model.php(1832): DboSource->create(Object(Session), Array, Array)
#4 /var/www/html/app/Model/Session.php(line: 23): Model->save(Array, true, Array)
#5 /var/www/cakephp/repo/lib/Cake/Model/Datasource/Session/DatabaseSession.php(117): Session->save(Array)
#6 [internal function]: DatabaseSession->write('c760db8417dd5b9...', '????Config??use...')
#7 [internal function]: session_write_close()
#8 {main}
```

Any suggestion to as why this is happening? Session locking? DB locking?

**Comment by tuckdesign** [comment] 2015-01-21 13:52
Hi,
you closed this but this is happening to me also. For no reason I get:
2015-01-21 11:48:02 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'efh9ndsdtcik0purn9qdhgbj84' for key 'PRIMARY'
#0 .../lib/Cake/Model/Datasource/DboSource.php(437): PDOStatement->execute(Array)
#1 .../lib/Cake/Model/Datasource/DboSource.php(403): DboSource->_execute('INSERT INTO `eb...', Array)
#2 .../lib/Cake/Model/Datasource/DboSource.php(985): DboSource->execute('INSERT INTO `eb...')
#3 .../lib/Cake/Model/Model.php(1721): DboSource->create(Object(AppModel), Array, Array)
#4 .../lib/Cake/Model/Datasource/Session/DatabaseSession.php(122): Model->save(Array)
#5 [internal function]: DatabaseSession->write('efh9ndsdtcik0pu...', 'Config|a:4:{s:9...')
#6 .../lib/Cake/Controller/Controller.php(770): session_write_close()
#7 .../lib/Cake/Controller/Component/AuthComponent.php(318): Controller->redirect('/login')
#8 [internal function]: AuthComponent->startup(Object(UploadsController))
#9 .../lib/Cake/Utility/ObjectCollection.php(130): call_user_func_array(Array, Array)
#10 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#11 .../lib/Cake/Event/CakeEventManager.php(246): call_user_func(Array, Object(CakeEvent))
#12 .../lib/Cake/Controller/Controller.php(671): CakeEventManager->dispatch(Object(CakeEvent))
#13 .../lib/Cake/Routing/Dispatcher.php(100): Controller->startupProcess()
#14 .../lib/Cake/Routing/Dispatcher.php(85): Dispatcher->_invoke(Object(UploadsController), Object(CakeRequest), Object(CakeResponse))
#15 .../app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}

Using CakePHP 2.0

**Comment by davidsteinsland** [comment] 2015-01-21 13:57
Clearly this is not an app issue, as @jippi thinks. However, it's a hard bug to track down, because:
- SQLs are performed in a transaction, and should be safe
- Hash collisions are basically non-existent when using SHA1 or SHA2

Somehow it gets inserted twice. But I haven't resolved the issue: we are getting these errors daily.

**Comment by lorenzo** [comment] 2015-01-21 14:06
It is basically a concurrency problem @davidsteinsland, it is also a problem that is somewhat difficult to solve.  Do you want to help solving it? I think I can guide you in how to do it.

**Comment by davidsteinsland** [comment] 2015-01-21 14:29
If you think it will help other people, feel free to submit it.

**Comment by AD7six** [comment] 2015-01-21 14:46
@davidsteinsland the problem will be because of concurrent requests e.g. 2 http request received at the same time and:

 * request 1  checks if the session exists
 * request 2 checks if the session exists
 * request 1 inserts a record
 * request 2 inserts a record -> duplicate primary key error.

That's all happening inside the call to `SessionModel->save()` in 2 different processes.

Reducing the time/logic between checking the id and inserting/updating would help - or catching the exception and retrying or changing the insert to be an upserti.e.

    insert into sessions () on duplicate key update ()

We can help you if you want to take a look at it - as you'll note from the age of the ticket noone has so far found the time to look at it.

**Comment by tuckdesign** [comment] 2015-01-21 16:25
After 3 hours of debugging found out that my session dies. Reason for that is autoRegenerate=true in session config. After session dies, then it throws error as in issue. I disabled autoRegenerate for AJAX calls (and one other js file generated by cakephp). Autoregenerate is ok, but if AJAX call regenerates session id while main page is still using old session id (in CAKEPHP cookie), it makes problems. Will let you know if this solves the problem... It is intermittent, so can't be sure 100%

**Comment by davidsteinsland** [comment] 2015-01-22 08:21
> @AD7six [...] or catching the exception [...]

Actually, this does not help. What I wonder is why CakePHP doesn't catch the exception? It do set `set_exception_handler`, so it should catch the PDOException ...

In `DatabaseSession` I have:
```php
public function write($id, $data) {
    if (!$id) {
        return false;
    }
    $expires = time() + $this->_timeout;
    $record = compact('id', 'data', 'expires');
    $record[$this->_model->primaryKey] = $id;

    try {
        return $this->_model->save($record);
    } catch (PDOException $e) {
         // logging here
    }
}
```

And the exception is not caught.

**Comment by AD7six** [comment] 2015-01-22 15:21
@davidsteinsland the exception handler is not relevant, what you're effectively saying there is "try catch doesn't work" - which does not seem likely.

*However* - I've created a test case to simulate this condition and drafted that solution.

**Comment by davidsteinsland** [comment] 2015-01-22 15:31
OK, I'll have a look at it. I know it sounds likely, but even if I throw an error manually from DboSource::execute(), I can't seem to catch it in the model. But I've reopened this issue at our company also, so I'll dig more into it in the following days.

**Comment by tuckdesign** [comment] 2015-01-24 18:03
It looks like problem is with session auto regenerate id. When I set autoRegenerate to false in config, I don't get these errors nor my session dies. Not sure how cake session handles change of id when session is using db.

**Comment by davidsteinsland** [comment] 2015-01-24 18:05
We have `autoRegenerate = false`. As @AD7six says, I know this happens during two ajax calls. I just don't know what causes this. Does the session dies? Is the user forcefully logged out? Is there something else?

**Comment by tuckdesign** [comment] 2015-01-24 18:09
I added debug code to app controller's beforeFilter (so I can track each call from my IP), and I see that for no reason site redirects to /login. It does happen during AJAX. It looks like session dies "somewhere in between" 2 calls to AppController beforeFilter method. For one call session (and auth in it) is ok, for next, user is redirected to /login.

**Comment by markstory** [comment] 2015-01-25 02:44
@davidsteinsland @tuckdesign Have either of you been able to try applying the changes in #5717 to your code and see if that resolves the issue?

**Comment by davidsteinsland** [comment] 2015-01-25 02:49
I'm gonna wait until next week to check. I've setup some event listeners
that hopefully will shed some light on to what causes this, and why the
exception doesn't get caught by the handler.

-- 
Mvh / Regards,
David Steinsland

**Comment by tuckdesign** [comment] 2015-01-26 11:13
I made the change from #5717 
It looks ok (with autoRegenerate=true). But need some more detailed testing with more AJAX calls to confirm it's ok.

**Comment by AD7six** [comment] 2015-03-10 08:37
#5717 aught to have reduced (significantly so, but not necessarily eliminated) the probability of this error. If nothing has changed the problem is "different". For a fix to be found, we need a means to reproduce the error in a way that reflects actual use.

**Comment by ADmad** [comment] 2015-07-03 04:14
Closing as there has been no feedback after the changes @AD7six made.

**Closed** 2015-07-03 04:21 UTC
