### ISSUE TITLE
[2.7] New CakeResponse sent, ignoring attached DispatcherFilters on thrown exception

### ISSUE THREAD

**Issue by biesbjerg** [cakephp/cakephp#7488] opened 2015-09-30 14:56 UTC
I'm working on an API that needs CORS headers to be sent for all responses, in order for the browser to not throw errors such as:

```
XMLHttpRequest cannot load http://example.org/api/purchases.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 401.
```

The above error happens when the auth token expired/was invalidated and I throw UnauthorizedException.

Here you can see that a new CakeReponse is always created when outputting error responses: https://github.com/cakephp/cakephp/blob/2.7/lib/Cake/Error/ExceptionRenderer.php#L146

I'm not sure we can access the original CakeResponse instance in any way, but maybe we can still attempt to run DispatcherFilters?

Looking at the code in 3.x, it seems it suffers from the same fate, always sending a vanilla CakeResponse.

**Comment by markstory** [comment] 2015-09-30 16:53
I don't think we can get the original response, as the stackframes are all gone. We could however, trigger the `Dispatcher.afterDispatch` event from inside the default error handler.

Alternatively you could use a custom error handler, or error controller to add the necessary behavior.

**Comment by davidsteinsland** [comment] 2015-11-17 07:18
By design, you *should* be able to get the response. The whole application is dependant upon a request and a response; and suddenly all hope is lost?

Although I would not recommend this approach, but seeing that CakePHP loves statics:
```php
$response = Dispatcher::getResponse();
```

The dispatcher is invoked with a `CakeRequest` and a `CakeResponse` object anyways, so why not tie these to the application?

**Comment by markstory** [comment] 2015-11-17 18:18
@davidsteinsland How would a dependency container solve this particular issue?

**Comment by Techbrunch** [comment] 2016-02-04 12:44
I also have the same problem. I'm setting some headers in an `Dispatcher.afterDispatch` but those are not sent if an exception is thrown.

This is the same issue as #5208 which was fixed by #5252.

I think that triggerring the `Dispatcher.afterDispatch` event from inside the default error handler is the way to go.

**Comment by markstory** [comment] 2016-02-04 17:24
@Techbrunch Would you be willing to put a pull request together with how you think it should work?

**Comment by dangerdan** [comment] 2016-03-15 23:18
+1 from me for this too. Creating an API is difficult at the moment when error situations occur, this is mainly a problem for build but it'd be good for consuming applications to know something went wrong, rather than simply not receive a response (if blocked by CORS).

**Comment by lorenzo** [comment] 2016-05-20 22:42
@dangerdan have you tried using cake 3?

**Comment by Techbrunch** [comment] 2016-05-27 11:51
@markstory If you can give me some pointers on how to solve this issue I'll give it a try.
@lorenzo Currently there is no plan to update our app to Cake3. No sure how much work that would be.

**Comment by biesbjerg** [comment] 2016-07-04 14:35
I'm still looking for a solution for this (unfortunately not an option to upgrade to Cakephp 3 at this time).

I've tried looking at firing the afterDispatch filters in ExceptionRenderer, but I don't think it's possible to do, because the subject in CakeEvent, when firing afterDispatch Filter, is the dispatch instance itself, and it's instantiated in webroot/index.php and thus not accessible.

Any ideas? Input is greatly appreciated!

**Comment by biesbjerg** [comment] 2016-07-04 15:37
Would something like this be acceptable?

```
--- a/Vendor/cakephp/cakephp/lib/Cake/Error/ExceptionRenderer.php
+++ b/Vendor/cakephp/cakephp/lib/Cake/Error/ExceptionRenderer.php
@@ -19,10 +19,15 @@
  * @license       http://www.opensource.org/licenses/mit-license.php MIT License
  */

+App::uses('Controller', 'Controller');
+App::uses('CakeErrorController', 'Controller');
+App::uses('AppController', 'Controller');
 App::uses('Sanitize', 'Utility');
+App::uses('Dispatcher', 'Routing');
 App::uses('Router', 'Routing');
 App::uses('CakeResponse', 'Network');
-App::uses('Controller', 'Controller');
+App::uses('CakeRequest', 'Network');
+App::uses('CakeEvent', 'Event');

 /**
  * Exception Renderer.
@@ -138,8 +143,6 @@ class ExceptionRenderer {
  * @return Controller
  */
        protected function _getController($exception) {
-               App::uses('AppController', 'Controller');
-               App::uses('CakeErrorController', 'Controller');
                if (!$request = Router::getRequest(true)) {
                        $request = new CakeRequest();
                }
@@ -278,6 +281,18 @@ class ExceptionRenderer {
                $this->_outputMessage($this->template);
        }

+       protected function _shutdown() {
+               $afterFilterEvent = new CakeEvent('Controller.shutdown', $this->controller);
+               $this->controller->getEventManager()->dispatch($afterFilterEvent);
+
+               $Dispatcher = new Dispatcher();
+               $afterDispatchEvent = new CakeEvent('Dispatcher.afterDispatch', $Dispatcher, array(
+                       'request' => $this->controller->request,
+                       'response' => $this->controller->response
+               ));
+               $Dispatcher->getEventManager()->dispatch($afterDispatchEvent);
+       }
+
 /**
  * Generate the response using the controller object.
  *
@@ -287,7 +302,7 @@ class ExceptionRenderer {
        protected function _outputMessage($template) {
                try {
                        $this->controller->render($template);
-                       $this->controller->afterFilter();
+                       $this->_shutdown();
                        $this->controller->response->send();
                } catch (MissingViewException $e) {
                        $attributes = $e->getAttributes();
```

**Comment by markstory** [comment] 2016-07-05 02:10
@biesbjerg I think that's a reasonable solution. We can't easily access the original dispatcher, so making a new one is our only real option.

**Comment by biesbjerg** [comment] 2016-07-13 09:49
Any comments about the other changes? 

1) Moved App::uses() statements to top of file
2) Trigger Controller::afterFilter using an event instead of calling it directly, making it possible to listen for Controller.shutdown events even when request results in an exception

If above looks good I'll create a PR.

**Comment by markstory** [comment] 2016-07-13 17:41
I don't know if moving the `App::uses()` calls will work well. PHP has some odd behavior when trying to autoload classes in a fatal error from what I remember.

**Comment by biesbjerg** [comment] 2016-07-13 21:34
Okay. I'll won't change anything else than the call to dispatch the afterDispatch event to keep changes to a minimum. I attempted to create a test but I'm not really sure how to do it, even after looking at the tests for Dispatcher and ErrorRenderer. Anyone willing to give a hand?

**Comment by biesbjerg** [comment] 2016-07-13 22:18
Test added. It works but I'm not sure it's the best way.

**Comment by markstory** [comment] 2016-07-15 01:48
Closing as there is a pull request open now.

**Closed by markstory** 2016-07-15 01:48 UTC
Labels: Enhancement, errorhandler, exception, network
