### ISSUE TITLE
BTM Association coming up empty, SQL has results on 3.1.5

### ISSUE THREAD

**Issue by AlfranKeith** [cakephp/cakephp#7818] opened 2015-12-09 01:47 UTC
Sorry, new to Cake and have been stumped for days now.
The opportunities property comes back empty when I query for 
`$this->Products->find()->where(['id'=>10])->contain(['Opportunities']);` 

Using debugkit, I can see that it has SQL generated which returns results but for some reason the property it churns back is empty. The results returned by the generated SQL are what I would expect it to return and contain the proper fields.

I've mostly just been following the documentation on the site and playing around with the optional keys, so this may just be a simple misunderstanding on my part. Apologies.

For table names, that's how the DB has been for years. 

```
class ProductsTable extends Table {
  public function initialize(array $config){
    $this->table("DAS_Products");
    $this->belongsToMany('Opportunities', [
      'through' => 'OpportunityProducts',
      'className' => 'Opportunities',  
      'targetForeignKey' => 'DAS_Opportunity_id',  
      'foreignKey' => 'DAS_Product_id',
      'strategy'=>'subquery',     
    ]); 
  }
```

```
class OpportunityProductsTable extends Table {
  public function initialize(array $config){
    $this->table("DAS_OpportunityProduct");
    $this->primaryKey("id");

 		$this->belongsTo("Opportunities", [
      'foreignKey' => 'DAS_Opportunity_id',
      'bindingKey' => 'id'
    ]);
    $this->belongsTo("Products", [
      'foreignKey' => 'DAS_Product_id',    
      'bindingKey' => 'id'
    ]);    
  }
```

**Comment by markstory** [comment] 2015-12-09 02:46
What do these tables look like? Knowing the rough schema of the tables involved is helpful in reproduing and fixing these kinds of issues.

**Comment by AlfranKeith** [comment] 2015-12-09 03:00
```
DAS_OpportunityProduct
id int ai
DAS_Product_id int nullable
DAS_Opportunity_id int nullable
ts_createDate datetime nullable
createdBy_user_id int nullable
is_deleted tinyint
deletedBy_User_id int nullable
deleteDateTime datetime nullable

DAS_Product
id int ai
name varchar
is_active int nullable
deleted int nullable
deleted_by int nullable
deleted_on datetime nullable
parent_id int nullable
```

Naming convention isn't consistent, DB is a bit old and has had a lot of things added on top of it without following a strict convention. 

I've left DAS_Opportunity out, but it might not matter from the perspective of products. The same thing happens if I query for an Opportunity and have it contain Products.

**Comment by AFDM74** [comment] 2015-12-14 23:41
I'm having a similar issue with a 'Join Table': I have two tables (Queues and Schedules) with a join table with associated data (queues_schedules). 

My Models:

```php
class QueuesTable extends Table
{
        $this->belongsToMany('Schedules', [
            'foreignKey' => 'queue_id',
            'through' => 'queues_schedules'
        ]);
}

class SchedulesTable extends Table
{
        $this->belongsToMany('Queues', [
            'foreignKey' => 'schedule_id',
            'through' => 'queues_schedules'
        ]);

}

class QueuesSchedulesTable extends Table
{
        $this->belongsTo('Queues');
        $this->belongsTo('Schedules');

}
```

My ORM:
```php
    $query = $this->Schedules->find('all')
      ->select([
        'id',
        'not_before',
        'not_after',
        'invert_rule',
        'QueuesSchedules.announcement',                      // This field is empty
        'Schedules.announcement',
        'Weekdays.active'
      ])
      ->contain(['Weekdays', 'Queues'])
      ->matching('Queues')
      ->where([
        ['OR' => [
          'Weekdays.weekday_' . $callTime->dayOfWeek => true,
          'Schedules.date' => $callTime,
        ]],
        'Schedules.active' => true,
        ['OR' => [
          array('Weekdays.active' => true),
          array('Weekdays.active IS' => NULL),
        ]],
        'QueuesSchedules.queue_id' => $queue->id,
        ])
        ->order('invert_rule');
````

The data of the associated field 'QueuesSchedules.announcement' always come back empty, although the data is there in the '_joinTable' and in the '_matchingData' arrays.

I've tried every possible way, and had read over and over again the manual to check if I was missing out something. It's seem such a trivial task to be done with the ORM and it just returns empty.

**Comment by markstory** [comment] 2015-12-15 01:27
@AFDM74 I know that belongsToMany associations do work for simpler use cases. There is clearly something going awry though.

**Comment by lorenzo** [comment] 2015-12-15 23:11
yhe fields that belong to the matching data will be out in the matchingData array. Can you paste the results you are getting?

**Comment by markstory** [comment] 2015-12-16 03:39
@AlfranKeith I wasn't able to reproduce the issue you're having. The schema and models you provided were incomplete, so I might be missing code/data that triggers the issue. What I tried is [in this gist](https://gist.github.com/markstory/e554cdbce5c98b5b61f9). The `console.php` is a `bin/cake console` session showing that find() returns the correct result for me at least.

@AFDM74 Because you're using `matching()` you should expect that the results are moved into the `_matchingData` property instead of where would normally be found.

**Comment by AFDM74** [comment] 2015-12-16 13:12
@markstory I though that the ```php _matchingData ``` was unreacheable. Can you, please, advise me how can I reach this property?

The exact query I´m using is this one (it´s a little different, from my first post):
```php
    $query = $this->Schedules->find('all')
      ->select([
        'id',
        'not_before',
        'not_after',
        'invert_rule',
        'QueuesSchedules.announcement',
        'Schedules.announcement',
        'Weekdays.active'
      ])
      ->contain(['Weekdays', 'Queues'])
      ->matching('Queues')
      ->where([
        ['OR' => [
          'Weekdays.weekday_' . $callTime->dayOfWeek => true,
          'Schedules.date' => $callTime,
        ]],
        'Schedules.active' => true,
        ['OR' => [
          array('Weekdays.active' => true),
          array('Weekdays.active IS' => NULL),
        ]],
        'QueuesSchedules.queue_id' => $queue->id,
        ])
        ->order('invert_rule');
```
The SQL generated query:
```
SELECT 
   Schedules.id AS `Schedules__id`, 
   Schedules.not_before AS `Schedules__not_before`, 
   Schedules.not_after AS `Schedules__not_after`, 
   Schedules.invert_rule AS `Schedules__invert_rule`, 
   QueuesSchedules.announcement AS `QueuesSchedules__announcement`,
   Schedules.announcement AS `Schedules__announcement`, 
   Weekdays.active AS `Weekdays__active` 
FROM schedules Schedules 
   INNER JOIN queues Queues ON 1 = 1 
   INNER JOIN queues_schedules QueuesSchedules ON (Schedules.id = (QueuesSchedules.schedule_id) AND Queues.id = (QueuesSchedules.queue_id)) 
   LEFT JOIN weekdays Weekdays ON Weekdays.id = (Schedules.weekday_id) 
WHERE (
   (Weekdays.weekday_3 = 1 OR Schedules.date = '2015-12-16') 
   AND Schedules.active = 1 
   AND (Weekdays.active = 1 OR (Weekdays.active) IS NULL) 
   AND QueuesSchedules.queue_id = '2') 
   ORDER BY invert_rule
```

The result of my query is this (Looking more closely I see that it is bringing two 'queues' records, when it should only bring one, I´m revising the hole thing, but it is funny that I throw the generated SQL in the MySQL Workbench and it brings the correct rows.):
```php
2015-12-16 12:59:59 Debug: {
    "id": 12,
    "not_before": "2015-12-16T09:00:00+0000",
    "not_after": "2015-12-16T20:00:00+0000",
    "invert_rule": true,
    "announcement": "announcements\/Holiday_General",
    "queues": [
        {
            "id": 1,
            "client_id": null,
            "accountcode": "Q001",
            "name": "Queue 1",
            "active": true,
            "not_before": "2015-09-15T00:00:00+0000",
            "not_after": null,
            "created": null,
            "modified": null,
            "_joinData": {
                "queue_id": 1,
                "id": 7,
                "schedule_id": 12,
                "announcement": null
            }
        },
        {
            "id": 2,
            "client_id": null,
            "accountcode": "Q002",
            "name": "Queue 2",
            "active": true,
            "not_before": "2015-09-11T00:00:00+0000",
            "not_after": "2015-12-24T00:00:00+0000",
            "created": null,
            "modified": "2015-12-14T18:00:17+0000",
            "_joinData": {
                "queue_id": 2,
                "id": 8,
                "schedule_id": 12,
                "announcement": "announcements\/Holiday_AJLC"
            }
        }
    ],
    "weekday": null,
    "_matchingData": {
        "QueuesSchedules": {
            "announcement": "announcements\/Holiday_AJLC"
        }
    }
}
```

**Comment by markstory** [comment] 2015-12-17 03:03
Have you tried `$thing->_matchingData['QueuesSchedules']`?

**Comment by markstory** [comment] 2015-12-17 03:07
Its very strange that the ORM is able to load additional records that MySQL workbench does not load. I'm also confused how the first, second and workbench results are all totally different. It seems like totally different data is being loaded, which makes diagnosing the issue harder.

**Comment by AFDM74** [comment] 2015-12-17 13:40
@markstory Accessing the _matchingData array worked, I didn´t know that. Thanks.

And I definitely agree that it is a very strange issue. Just to make it clear: The two result sets: CakePHP and MySQL Workbench results, came from the same SQL query produced by the ORM.

As I´m not loading this data directly from it´s Model (```Schedules```) I tried the query from the JoinTable perspective (```QueuesSchedules```) without much success (although I didn´t really tried hard to make it work as I did with the ```Schedules``` Model). And yes I loaded all the Models previously. Just to note I´m doing this from a console Task.

```
    $query = $this->QueuesSchedules->find('all')
      ->select(
        'QueuesSchedules.announcement',
        'Schedules.id',
        'Schedules.not_before',
        'Schedules.not_after',
        'Schedules.invert_rule',
        'Schedules.announcement',
        'Weekdays.active'
      )
      ->contain(['Schedules', 'Schedules.Weekdays'])
      ->matching('Schedules.Weekdays')
      ->where([
        'QueuesSchedules.queue_id' => $queue->id,
        'Schedules.active' => true,
        [ 'OR' => [
          'Schedules.date' => $callTime,
          'AND' => [
            'Weekdays.weekday_' . $callTime->dayOfWeek => true,
            'Weekdays.active' => true
            ]
          ]
        ]
      ])
;
```

I also simplified the query ```where``` statement down to this (much more cleaner and efficient):
```
      ->where([
        'Queues.id' => $queue->id,
        'Schedules.active' => true,
        [ 'OR' => [
          'Schedules.date' => $callTime,
          'AND' => [
            'Weekdays.weekday_' . $callTime->dayOfWeek => true,
            'Weekdays.active' => true
            ]
          ]
        ]
      ])
```

For now, I´m sticking with the ```_matchingData[]``` solution as I have the end of the year festivities comming our way and this have to be in production until then!

I´ll try to sort it after ... And if I find something I´ll post it back here.

Best Regards! Merry Christmas and a Happy New Year for all Bakers!

**Comment by markstory** [comment] 2015-12-18 04:20
Ok, I'm not sure how to go about reproducing this issue as it stands. Perhaps in the new year, I could get some schema and data that exhibit the issue?

**Comment by markstory** [comment] 2016-01-09 03:19
Closing as I've not been able to reproduce this, and the issue @AFDM74 had has been resolved. If a way to reproduce this issue comes up let us know.

**Closed by markstory** 2016-01-09 03:19 UTC
Labels: Defect, On hold, ORM
