### ISSUE TITLE
AuthComponent doesn't compatible with PHP7 ?

### ISSUE THREAD

**Issue by aymardPro** [cakephp/cakephp#9674] opened 2016-10-29 18:03 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

### What you did

The function bellow working very well on PHP5, but not on PHP7.
The Auth component can't store data's with the storage interface (I'm trying to doing more tests to confirm it).

The `$this->Auth->setUser($user);` can't store `$user` datas

`

    public function login()
    {
        if ($this->request->is('post')) {
            $user = $this->Auth->identify();
            if ($user) {
                $this->Auth->setUser($user);
                $this->Users->save($registered_user);
                $this->Flash->success(__('Success'));
                return $this->redirect($this->Auth->redirectUrl());
            }
            $this->Flash->error(__('Invalid username or password, try again'));
        }
    }
`
### What happened

When a user trying to log himself, I successfully retrieve his data but there is no  created or saved session in the auth component. The result is that he always stay on the login page.

**Comment by aymardPro** [comment] 2016-10-29 18:13
Sorry Var.CI,

`


    "require": {
        "php": ">=5.5.9",
        "cakephp/cakephp": "3.3.*",
        "mobiledetect/mobiledetectlib": "2.*",
        "cakephp/migrations": "~1.0",
        "cakephp/plugin-installer": "*"
    },
    "minimum-stability": "stable",
    "prefer-stable": true

**Comment by ADmad** [comment] 2016-10-29 23:06
AuthComponent works fine on PHP 7.  You have some environment issue which you need to find out. Make sure you have session properly configured and working.

**Comment by dereuromark** [comment] 2016-10-29 23:32
Also, your code example contains errors, `$registered_user` you try to save does not even exist.

**Comment by markstory** [comment] 2016-10-30 01:10
Closing as I am not able to reproduce locally. I have a few working example applications that use AuthComponent and PHP 7.

**Closed by markstory** 2016-10-30 01:10 UTC
Labels: Defect, On hold

**Comment by aymardPro** [comment] 2016-10-30 07:53
Hello All and thanks for your feedback,

Here is the definition for `$registered_user` and the `$this->Users->save($registered_user);` works fine on `PHP 7`

```
...
$user = $this->Auth->identify();
...
$this->Auth->setUser($user);
$registered_user = $this->Users->get($user['id']);
...
```

All my code works very fine here [http://idream-ci.com/testbeta/user-manager/users/](url) on `PHP 5.6` 
What the required environnement for `PHP 7` ?
