### ISSUE TITLE
PHP 7.0.15 and PHP 7.1.0 ResultSet Caching

### ISSUE THREAD

**Issue by mbryja** [cakephp/cakephp#10111] opened 2017-01-26 20:27 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.12.
* Platform and Target: PHP 7.0.15 or PHP 7.1.0, Centos 6.8.

### What you did
I've updated from php 7.0.12 to 7.0.15 and model caching stopped working. I've tried to upgrading it again to 7.1.0 but it did not help.

### What happened

The serialize method is not working for ResultSet object. 

I've placed following code in one of my controllers which mimics what the File Engine Cache does:
```   
        $products = $this->Products->find()->all();

        print_r(unserialize(serialize($products)));

        print_r($products);

```

The response is

```
Cake\ORM\ResultSet Object
(
    [items] => Array
        (
        )

)
```

Even though my original object had items in it. Also when I echo out the value returned by serialize(), all objects are properly stored there. 

### What you expected to happen
First, I would prefer CakePHP serialize only generic data types rather then ResultSet object. However, since it is a framework it is not a big deal. The other thing is that I'm trying to find out what breaks the serialization. It looks like something changed recently in PHP that is causing it.

**Comment by lorenzo** [comment] 2017-01-26 20:29
Does going back to `7.0.12` make it work again?

**Comment by mbryja** [comment] 2017-01-26 20:34
The thing is that I'm using yum and it won't let me to downgrade.

**Comment by markstory** [comment] 2017-01-26 21:37
I wouldn't rely on serialized objects being portable between PHP versions. I also don't think its possible for us to serialize generic datatypes for objects like `ResultSet`.

**Comment by mbryja** [comment] 2017-01-26 21:51
Let me be clear, I'm not trying to unserialize object which was previously serialized in different php version. The object is being serialized and unserialized during the same execution. 

I'm trying to use query caching as described here https://book.cakephp.org/3.0/en/orm/query-builder.html#caching-loaded-results. 

My code is a demonstration of what happens in Cake\Cache\Engine\FileEngine class.

**Comment by markstory** [comment] 2017-01-27 02:32
> Can you possibly verify that on php 7.1.0 or php 7.0.15 the file engine cache works as it supposed to?

Yes, the tests are currently passing.

**Comment by mbryja** [comment] 2017-01-27 16:45
Manually compiling php to 7.0.12 solved the issue.

**Comment by thinkingmedia** [comment] 2017-01-27 17:13
I think the latest is 7.1.1 if you're interested in upgrading fully.

**Comment by mirko-pagliai** [comment] 2017-01-29 18:34
Starting from today, even I have trouble deserializing cached queries (data are correct).
I can not figure out what can be dependent and I can not remember if I did some recent updates, but this happens only in remote (php 5.6) and I can not replicate locally.

**Comment by thinkingmedia** [comment] 2017-01-29 18:48
@mirko-pagliai can you take a look in your `logs/error.log` file for any cache errors.

**Comment by mirko-pagliai** [comment] 2017-01-29 20:06
@thinkingmedia obviously there is no log. Simply, the query result is empty.
I will do some debug.

**Comment by thinkingmedia** [comment] 2017-01-29 20:57
@mirko-pagliai can you clarify if your issue is related to the original issue.

Can you attempt some thing like the sample code in the original issue.

What I find concerning is that the `unserialize(serialize($products))` statement produces a valid `ResultSet` instance that is empty without an error message.

That's kind of scary to me.

**Comment by mirko-pagliai** [comment] 2017-01-29 21:03
I wrote in this thread just to see if other users have this problem and then to see if there is a correlation. But of course I do not know yet, because I can not reproduce the problem locally (it's only remotely and the php version is 5.6).

What happens to me is this: reading a cached query, I have a valid ResultSet instance that is empty without an error message, as you said. Yet in the process of writing there are no problems, the file is written correctly and contains the serialized query.

**Comment by thinkingmedia** [comment] 2017-01-29 21:09
@mirko-pagliai thanks.

I'm going to re-open this issue and publish a PR with unit tests to cover this edge cage. It might not reproduce the problem, but at least we can say we covered it with tests.

**Comment by thinkingmedia** [comment] 2017-01-29 21:34
@markstory I've reproduced the issue on `PHP 7.1.1` with a unit test. Can you review the unit test and verify that it wasn't a mistake on my part.

**Comment by thinkingmedia** [comment] 2017-01-29 22:35
@mirko-pagliai this is interesting. I am able to reproduce the problem locally, but the same test passes on all travis PHP versions.

What OS are you running on your production server?

**Comment by thinkingmedia** [comment] 2017-01-29 22:42
I can reproduce and will try debugging.

```
➜  cakephp git:(issue-10111) vendor/bin/phpunit tests/TestCase/Cache/Engine
PHPUnit 5.7.9 by Sebastian Bergmann and contributors.

SSSSSSSSSSS......F................SSSSSSSSSSSSSSSSSSSSSSSSSSSSS  63 / 103 ( 61%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS                        103 / 103 (100%)

Time: 5.98 seconds, Memory: 10.00MB

There was 1 failure:

1) Cake\Test\TestCase\Cache\Engine\FileEngineTest::testResultSetCache
Failed asserting that 0 is identical to 3.

/mnt/c/work/cakephp/cakephp/tests/TestCase/Cache/Engine/FileEngineTest.php:232

FAILURES!
Tests: 103, Assertions: 96, Failures: 1, Skipped: 80.
➜  cakephp git:(issue-10111)
```

I don't even think this is an issue with FileEngine. Not sure where to start.

**Comment by thinkingmedia** [comment] 2017-01-29 22:53
Serializing tests on `ResultSet` are also failing for me. I suspect this is an iterator issue.

**Comment by thinkingmedia** [comment] 2017-01-29 23:22
@markstory wow, I fixed it.

So on my local machine `serialize($resultSet)` saves the type info of the array as `SqlFixedArray`, and when it is deserialized the inner `$_results` is a `SqlFixedArray` instance. I don't know why, but `count($this->_results)` always returns zero even if it contains items.

So a simple `(array)` cast fixed the issue.

Closing since there is a PR up now.

**Closed by thinkingmedia** 2017-01-29 23:22 UTC
Labels: Needs Tests

**Comment by mirko-pagliai** [comment] 2017-01-30 08:56
> What OS are you running on your production server?
I'm running php 5.6.30 on debian wheezy.

In my case, using `QueryTrait::cache()`, it just returns an empty array.
Most likely it is not a problem directly related to cakephp, because I noticed that on the same server also happens with outdated versions.
Today, if I can, I also write some tests and I will run it on this remote server.

Unfortunately, my situation is very complex and serious, because it is an important production server on which I can not do a lot of testing. For now I had to disable the cache on all installations of cakephp (sigh!).

**Comment by mirko-pagliai** [comment] 2017-01-30 15:00
@markstory @thinkingmedia this is the test:

```
    public function testCache()
    {
        Cache::delete('view_1', 'posts');
        $this->assertFalse(Cache::read('view_1', 'posts'));

        $post = $this->getPost();
        $postFromCache = Cache::read('view_1', 'posts');

        $this->assertNotEmpty($postFromCache);
        $this->assertInstanceOf('Cake\ORM\ResultSet', $postFromCache);
        $this->assertInstanceOf('MeCms\Model\Entity\Post', $postFromCache->first());
        $this->assertEquals($post, $postFromCache->first());

        $postAgain = $this->getPost();

        $this->assertEquals($postAgain, Cache::read('view_1', 'posts')->first());

        $this->assertEquals($post, $postAgain);
    }
```

Locally (php 7.0.14) it works:

```
mirko@debian-lenovo:~/Libs/Plugins/MeCms$ phpunit tests/TestCase/Model/Table/QueryTest.php
PHPUnit 5.4.6 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 198 ms, Memory: 10.00MB

OK (1 test, 7 assertions)
```

 But remotely, on a prodution server (php 5.6.30):

```
mirko@vps2993:/var/www/videocitta.it/vendor/mirko-pagliai/me-cms$ phpunit tests/TestCase/Model/Table/QueryTest.php 
PHPUnit 3.6.10 by Sebastian Bergmann.

Configuration read from /var/www/videocitta.it/vendor/mirko-pagliai/me-cms/phpunit.xml.dist

F

Time: 0 seconds, Memory: 11.25Mb

There was 1 failure:

1) MeCms\Test\TestCase\Model\Table\QueryTest::testCache
Failed asserting that null is an instance of class "MeCms\Model\Entity\Post".

/var/www/videocitta.it/vendor/mirko-pagliai/me-cms/tests/TestCase/Model/Table/QueryTest.php:69

FAILURES!
Tests: 1, Assertions: 4, Failures: 1.
```

**Comment by mirko-pagliai** [comment] 2017-01-30 15:02
It fails here:

        $this->assertInstanceOf('MeCms\Model\Entity\Post', $postFromCache->first());

Beacuse `$postFromCache` is `null`:

        $postFromCache = Cache::read('view_1', 'posts');

Raw content of the cache file:

```
mirko@vps2993:/var/www/videocitta.it/vendor/mirko-pagliai/me-cms$ cat /tmp/me_cms/posts/view_1 
1572101989
C:18:"Cake\ORM\ResultSet":948:{O:13:"SplFixedArray":1:{i:0;O:23:"MeCms\Model\Entity\Post":11:{s:14:"*_accessible";a:3:{s:1:"*";b:1;s:2:"id";b:0;s:8:"modified";b:0;}s:11:"*_virtual";a:2:{i:0;s:7:"preview";i:1;s:14:"tags_as_string";}s:14:"*_properties";a:11:{s:2:"id";i:1;s:11:"category_id";i:4;s:7:"user_id";i:1;s:5:"title";s:10:"First post";s:4:"slug";s:10:"first-post";s:8:"subtitle";s:23:"Subtitle for first post";s:4:"text";s:22:"Text of the first post";s:8:"priority";i:1;s:7:"created";O:14:"Cake\I18n\Time":3:{s:4:"date";s:26:"2016-11-28 18:55:19.000000";s:13:"timezone_type";i:3;s:8:"timezone";s:3:"UTC";}s:8:"modified";O:14:"Cake\I18n\Time":3:{s:4:"date";s:26:"2016-11-28 18:55:19.000000";s:13:"timezone_type";i:3;s:8:"timezone";s:3:"UTC";}s:6:"active";b:1;}s:12:"*_original";a:0:{}s:10:"*_hidden";a:0:{}s:13:"*_className";N;s:9:"*_dirty";a:0:{}s:7:"*_new";b:0;s:10:"*_errors";a:0:{}s:11:"*_invalid";a:0:{}s:17:"*_registryAlias";s:11:"MeCms.Posts";}}}
```

So, the file is right.

**Comment by mirko-pagliai** [comment] 2017-01-30 15:20
Ok, my problem is [here](https://api.cakephp.org/3.3/source-class-Cake.Cache.Engine.FileEngine.html#223).

Changing the code:

            debug((string)$data);
            debug(unserialize((string)$data));
            $data = unserialize((string)$data);

```
F/src/Cache/Engine/FileEngine.php (line 223)
########## DEBUG ##########
'C:18:"Cake\ORM\ResultSet":948:{O:13:"SplFixedArray":1:{i:0;O:23:"MeCms\Model\Entity\Post":11:{s:14:"*_accessible";a:3:{s:1:"*";b:1;s:2:"id";b:0;s:8:"modified";b:0;}s:11:"*_virtual";a:2:{i:0;s:7:"preview";i:1;s:14:"tags_as_string";}s:14:"*_properties";a:11:{s:2:"id";i:1;s:11:"category_id";i:4;s:7:"user_id";i:1;s:5:"title";s:10:"First post";s:4:"slug";s:10:"first-post";s:8:"subtitle";s:23:"Subtitle for first post";s:4:"text";s:22:"Text of the first post";s:8:"priority";i:1;s:7:"created";O:14:"Cake\I18n\Time":3:{s:4:"date";s:26:"2016-11-28 18:55:19.000000";s:13:"timezone_type";i:3;s:8:"timezone";s:3:"UTC";}s:8:"modified";O:14:"Cake\I18n\Time":3:{s:4:"date";s:26:"2016-11-28 18:55:19.000000";s:13:"timezone_type";i:3;s:8:"timezone";s:3:"UTC";}s:6:"active";b:1;}s:12:"*_original";a:0:{}s:10:"*_hidden";a:0:{}s:13:"*_className";N;s:9:"*_dirty";a:0:{}s:7:"*_new";b:0;s:10:"*_errors";a:0:{}s:11:"*_invalid";a:0:{}s:17:"*_registryAlias";s:11:"MeCms.Posts";}}}'
###########################
/src/Cache/Engine/FileEngine.php (line 224)
########## DEBUG ##########
object(Cake\ORM\ResultSet) {

        'items' => []

}
###########################
```

From what can it depend on? It seems that the `unserialize()` function of php does not work.

**Comment by chrisShick** [comment] 2017-01-30 15:27
I believe in PHP-7 that unserialize internals were completely redone.

**Comment by mirko-pagliai** [comment] 2017-01-30 15:29
@chrisShick ok, but I'm running php 5.6 on a production server.

**Comment by mirko-pagliai** [comment] 2017-01-30 15:49
It fails also on Travis:
https://travis-ci.org/mirko-pagliai/me-cms/builds/196625195

Fails with PHP 5.6 and 7.0.
Works with PHP 5.5 and 7.1.

This for me does not make sense.

I only need to check if there is a problem with the models of my plugins.

**Comment by thinkingmedia** [comment] 2017-01-30 15:50
@mirko-pagliai your failed test is consistent with that I'm seeing here as well.

So what is happening is that buffered queries are using SplFixedArray, and that object is being serialized when written to the cache. When the ResultSet is restored from the cache PHP is failing to properly restore the inner state of SplFixedArray. The ResultSet successfully loads the items in the cache, but the count for items is set to zero. The data is there but it will fail trying to iterate any of the items.

I've updated the PR this morning to improve serializing. It no longer uses SplFixedArray when writing to the cache, but converts the result set to a regular array. When the result set is deserialized from cache it's converted back into a new SplFixedArray instance with a proper count value.

Based upon what I've read in your post. The PR should fix your issue.

I do not know why this bug started to appear, but I've been on slack today talking @lorenzo who also experienced this issue on  a different version of PHP. The code that introduced this issue was added to Cake a year ago, but this issue seems to have just started recently.

Spl is a core component of PHP since 5.3. What I think might have happen is that some thing in Cake recently changed in one of the iterator traits we use, and that introduced the bug so that `count(SplFixedArray)` would not work.

Anyway, the bug is fixed now. It'll be in the next Cake update.

**Comment by mirko-pagliai** [comment] 2017-01-30 16:03
@thinkingmedia Ok, I confirm to you that by applying your commit, now it works.
I beg you ( @markstory ) to publish the new release as soon as possible, because it seems a very serious bug (for example, I had to disable the cache on all my apps and on all production servers, although now I can apply that commit).

> I do not know why this bug started to appear, but I've been on slack today talking @lorenzo who also experienced this issue on a different version of PHP. The code that introduced this issue was added to Cake a year ago, but this issue seems to have just started recently.

It is very, very strange. I personally found that the bug has also appeared on CakePHP installation outdated and that worked until a few days ago. Really strange.

**Comment by thinkingmedia** [comment] 2017-01-30 16:15
I found this old bug report for SPL back in 2011 that is identical to what we're seeing. It was verified a bug and fixed.

https://bugs.php.net/bug.php?id=60560&edit=1

The bug happens when the array keys are strings.

Here is the fix for it.

http://svn.php.net/viewvc/?view=revision&amp;revision=323408

What's interesting is that the developer added a specific unit test for this edge case.

I went to the GitHub repo for PHP's source code, and I can no longer find that unit test.

https://github.com/php/php-src

**Comment by mbryja** [comment] 2017-01-30 18:48
@thinkingmedia, your changes work for me as well. Thank you for your help.

**Comment by mirko-pagliai** [comment] 2017-01-30 19:00
@thinkingmedia no, wait, I spoke too soon: even applying your commit, the problem would seem to be the same :-(
I try to test again tomorrow.

**Comment by thinkingmedia** [comment] 2017-01-30 19:13
I'm very grateful that I was able to help you guys. The timing couldn't be more perfect. On Friday I was preparing for a double interview. One with the largest eCommerce site in India, and another with a popular digital video provider in Toronto.

Before noon. I received emails from both companies saying they had cancelled the interviews, and were no longer interested. 

Anyway, this hit hard. So I love this Cake community. It's the best.

**Comment by mirko-pagliai** [comment] 2017-01-30 19:17
You can not imagine what you've been useful. I had to disable the cache on some sites that are several hundred queries per second (now that I think, I could disable the cache serialization and probably would work the same. But I could not understand what the problem was ...).

So again thank you very much.

**Comment by darxmac** [comment] 2017-01-30 23:11
any idea when this may be merged and/or released ?

**Comment by markstory** [comment] 2017-01-31 00:17
@darxmac The pull request will be merged in the next day or so and be in the next 3.3/3.4 release in the next week or two.

**Comment by mirko-pagliai** [comment] 2017-01-31 09:44
@darxmac it was merged an hour ago https://github.com/cakephp/cakephp/commit/b2b7f76cd0f93c6f5fd173a90f5da99f749576df

**Comment by yamitzky** [comment] 2017-02-01 13:16
I guess that PHP 5.6.30 causes the issue.

I encountered the same problem on 5.6.30, but NOT on 5.6.29!

Recently, 5.6.30 was released and [CHANGELOG](http://php.net/ChangeLog-5.php) says that `Unserialize context shared on double class lookup`.

**Comment by mirko-pagliai** [comment] 2017-02-01 13:27
@yamitzky yes, but @mbryja pointed out that in his case the problem also occurs with PHP 7.0.15 and PHP 7.1.0

**Comment by thinkingmedia** [comment] 2017-02-01 14:00
@yamitzky @mirko-pagliai Great find guys!

This is the change that introduced the problem:

> Fixed bug #70213 (Unserialize context shared on double class lookup).

Here's the ticket for the issue:

https://bugs.php.net/bug.php?id=70213

After 5.6 was fixed this comment was made.

> It seems proposed patch is applicable to 5.6/7.0. Are you going to merge the patch or it's not needed for 5.6/7.0?

I assume the patch was added to both 5.6/7.0 versions after the above was proposed.

This all happened on 19 Jan 2017. Which explains why this was a new issue.

**Comment by JoepRoebroek** [comment] 2017-02-05 11:04
Hey guys,

We were also experiencing this on our live environment, so first I would like thank you for your hard work on this issue!

In the meatime I also  started looking into it, and found a way to reproduce it in a contained example. What I found is that `count($this->_results)` returned 0 when used in the unserialize function directly. Outside of the class however, after the full `ResultSet` is unserialized, `count($resultset->_results)` would return the correct amount. So there is some code being executed right after the complete object is unserialized (php internals that is probably).

Now I found this: [SplFixedArray::__wakeup](https://secure.php.net/manual/en/splfixedarray.wakeup.php)

The `__` suggested to me it would be private, but apparently it is not and can be called in the `unserialize` function right after SplFixedArray is unserialized and stored in `$this->_results`.

Therefore I added `$this->_results->__wakeup();` right after the following [line of code].(https://github.com/cakephp/cakephp/blob/77376d318b6865dd40071ed3984e91348d9e757b/src/ORM/ResultSet.php#L333)

This solved the problem for me. I know it is quite late after all the work that has already been done. But thought I'd share it anyway. Hopefully it helps in some way. Cheers!

**Comment by thinkingmedia** [comment] 2017-02-05 14:42
I suspect this issue is going to be a big one across the PHP community, and while we've patched Cake for this it wouldn't surprise me if the next release of PHP 5.6/7.1 will fix this. I'm not even sure if we'll release the next Cake version before they fix it.

**Comment by tharlinsmith** [comment] 2017-04-17 17:37
I encountered this separately on PHP 5.6.30.  See https://bugs.php.net/bug.php?id=74436 for the spirited discussion.
