### ISSUE TITLE
3.0.7 - Weirdness with patchEntity when the associated table has a contain

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#6866] opened 2015-06-23 16:52 UTC
Hello. I scoured my emails to see if this ever happened to anyone else, but couldn't find anything. If..
1. I have a `PostsTable` which belongsToMany `TagsTable`.
2. `TagsTable` hasOne `TagsTranslations`
3. `TagsTable` has a `findAll` method that contains `TagsTranslations`
4. I try to find a `PostsTable` record and do a `patchEntity` on the `PostsTable`, I get:

``
Error: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous
``

Because the marshaller creates this SQL:
```
SELECT `Tags`.`id` AS `Tags__id`, `Tags`.`family` AS `Tags__family`, `Tags`.`priority` AS `Tags__priority`, `TagsTranslations`.`id` AS `TagsTranslations__id`, `TagsTranslations`.`locale` AS `TagsTranslations__locale`, `TagsTranslations`.`name` AS `TagsTranslations__name`
FROM `tags` `Tags`
LEFT JOIN `tags_translations` `TagsTranslations` ON `Tags`.`id` = (`TagsTranslations`.`tag_id`)
WHERE `id` = 1
```

Controller..
```
$post = $this->Posts->get(52406);
$this->Posts->patchEntity($post, ['tags' => [
    ['id' => 1]
]]);
```

TagsTable..
```
public function initialize(array $config)
{	
	parent::initialize($config);
	$this->hasOne('TagsTranslations');
}
public function findAll(Query $query, array $options = [])
{
	$query->contain(['TagsTranslations']);
	return $query;
}
```

PostsTable..
```
public function initialize(array $config)
{
	parent::initialize($config);
	$this->addAssociations([
		'belongsToMany' => ['Tags']
	]);
}
```

If my `TagsTable` doesn't do that contain, the `patchEntity` is fine, but it seems like something that should work either way. Let me know if I'm going crazy and there's another error I'm missing. I went back in time in git and it seems like this issue has always happened.

Thanks

**Comment by lorenzo** [comment] 2015-06-23 17:11
Duplicate of https://github.com/cakephp/cakephp/issues/6826

**Comment by lorenzo** [comment] 2015-06-23 17:11
I should have a fix for this soon

**Comment by patrickconroy** [comment] 2015-06-23 17:17
Ah ok thanks @lorenzo. I should have searched for patchEntity. Looks like in `Marshaller::_belongsToMany` if in that first `forEach` the `$conditions` have the association alias before the PK it's fine, but not sure if that would cause other issues.

**Comment by lorenzo** [comment] 2015-06-23 17:20
@patrickconroy Do you want to submit a PR?  I will try to fix this this evening otherwise

**Comment by patrickconroy** [comment] 2015-06-23 17:21
Sure I can do that now.

**Comment by lorenzo** [comment] 2015-06-23 17:24
Thanks!

**Comment by markstory** [comment] 2015-06-24 01:49
Closing as #6867 is open now.

**Closed by markstory** 2015-06-24 01:49 UTC
