### ISSUE TITLE
ability to read utf8 files by Cake\Filesystem\File

### ISSUE THREAD

**Issue by saeideng** [cakephp/cakephp#11749] opened 2018-02-22 15:13 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: cake 3.5.12
* Platform and Target: linux
```php
    $file='نام.txt';
    $file2='name.txt';
    $file3='ä.txt';
    $path=ROOT.DS.'webroot'.DS.'upload'.DS;
    
    $path=$path.$file;

    debug(is_file($path)); // true
    debug(file_get_contents($path)); //content for file 'نام.txt'
    $file = new File($path);
    debug($file);
//
...
	name => '.txt'
	info => []
	handle => null
	lock => null
	path => '/var/www/site/webroot/upload/.txt'
//
    debug($file->exists());// false
    debug($file->readable()); //false
```

**Comment by davidyell** [comment] 2018-02-22 15:59
Seems like a case which is missing from tests for sure, from what I can see.

https://github.com/cakephp/cakephp/blob/master/tests/TestCase/Filesystem/FileTest.php

**Comment by hmic** [comment] 2018-02-22 16:05
This is intended behavior as in:
https://api.cakephp.org/3.5/source-class-Cake.Filesystem.File.html#355

**Comment by JoshuaLuckers** [comment] 2018-02-22 16:25
What PHP version do you use?

**Comment by davidyell** [comment] 2018-02-22 16:35
I don't think it'll be the PHP version, as that bug is for `5.3.13` and the minimum for Cake 3.5.12 is `5.6.0`, but it's a good spot.

**Comment by saeideng** [comment] 2018-02-22 19:22
problem is `basename()`
```php
`debug(basename('نام.txt'));` //returns `.txt`
```

**Comment by dereuromark** [comment] 2018-02-22 19:26
So this is not a framework issue, as the language itself seems to have problems here.

**Comment by saeideng** [comment] 2018-02-22 19:30
>as the language itself seems to have problems here.

not related to just one language
this method not work with all utf8 names
other method is `getFilename`
```php
$str='ä.php';
$info = new SplFileInfo($str);
echo $info->getFilename();
```

**Comment by dereuromark** [comment] 2018-02-22 19:51
I was referring to PHP as the language. This seems to be out of scope of CakePHP.

**Comment by saeideng** [comment] 2018-02-22 20:11
```php
<?php
$str=[
'ddddd/نام.php',
'نام.php',
'نام فارسی.php',
'/نام فارسی.php',
'ddd/نام فارسی.php',
'/etc/sudoers.d',
'/etc/passwd',
'/etc/',
'.',
'/',

];
foreach($str as $item){
    $info = new SplFileInfo($item);
    echo $info->getFilename();
    echo "\n";
}
//returns
نام.php
 نام.php
 نام فارسی.php
 /نام فارسی.php
 نام فارسی.php
 sudoers.d
 passwd
 /etc
 .
 /
```
just needs a `str_replace`

and about http://php.net/manual/en/function.basename.php
```
Caution

basename() is locale aware, so for it to see the correct basename with multibyte character paths, the matching locale must be set using the setlocale() function.

```

**Comment by markstory** [comment] 2018-02-22 20:53
We could convert the existing `basename()` and `dirname()` usage to be `SplFileInfo` as well.

**Comment by saeideng** [comment] 2018-02-22 20:56
can we have a method for usage in this class and other classes if it was necessary ?

**Comment by markstory** [comment] 2018-02-23 01:15
Why wouldn't we make the existing methods 'safe'? Having 2 versions of the same basic feature feels like we are setting developers up to fail.

**Comment by burzum** [comment] 2018-02-26 07:56
Honestly, I'm not sure if this will fix all cases, I've tested this on windows only.

**Comment by saeideng** [comment] 2018-02-26 11:29
main problem is on browser ( apache )
console is OK
see bellow code result in console and web 
this method does not work on browser ( apache ) 
but console is OK 
```php
<?php
$path='tests/permissions/نام فارسی.php';
$splInfo = new \SplFileInfo($path);

var_dump($splInfo->getFilename());
var_dump($splInfo->getBasename());
var_dump(basename($path));
```

**Comment by ADmad** [comment] 2018-02-26 12:47
Closing as related PR is open. Discussion can continue there.

**Closed by ADmad** 2018-02-26 12:47 UTC
Labels: Defect
