### ISSUE TITLE
cakephp 3.0  ORM Time instances for datetime column

### ISSUE THREAD

**Issue by andraskende** [cakephp/cakephp#6162] opened 2015-03-24 22:02 UTC
Hello,

I'm trying to select some datetime with MAX() and MIN() and then format to users local time_zone.
Only the  'created' => 'created' returns time instance the others returns string.

        $visits->select([
            'ip_address',
            'date_first' => "CONVERT_TZ(MIN(created),'UTC', '$timezone')",      // string
            'date_first1' => 'MIN(created)',     // string
            'created' => 'created',     // time instance
            'created1' => 'created',     // string
        ]);

http://book.cakephp.org/3.0/en/views/helpers/time.html
Because the ORM returns Cake\I18n\Time instances for every timestamp and datetime column, you can use the methods there to do most tasks.

Thank you,
Andras

**Comment by jadb** [comment] 2015-03-24 22:52
For this to work, I think you will need to define the column data types for both `date_first` and `date_first1`. I haven't tried it myself but believe it should do the trick.

From the book: http://book.cakephp.org/3.0/en/orm/saving-data.html#saving-complex-types

```php
// In src/Model/Table/UsersTable.php for example
use Cake\Database\Schema\Table as Schema;

class UsersTable extends Table
{

    protected function _initializeSchema(Schema $schema)
    {
        $schema->addColumn('date_first', ['type' => 'datetime']);
        $schema->addColumn('date_first1', ['type' => 'datetime']);
        return $schema;
    }
}
```

I think `addColumn()` here (instead of `columnType()`) should work, since the latter would just do nothing because those are columns you are defining in your select only.

Let me know if that resolves it for you.

**Comment by andraskende** [comment] 2015-03-24 23:34
Hi Jad,

addColumn() worked perfectly !

Thank you,
Andras

**Comment by markstory** [comment] 2015-03-25 00:11
Closing as this is how the ORM works, and the solution @jadb linked is spot on.

**Comment by andraskende** [comment] 2015-03-25 01:52
Sorry, I only tested that 1 page which worked, navigating elsewhere in my app its fatal error with:

     Database Error
     PDOException
     Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Visits.date_first' in 'field list'


I guess I just need columntype on that 1 method not for the whole app...

For now as a workaround i'm doing this after the find() :

        foreach ($visits as $visit) {
            $visit->date_first = Time::createFromFormat('Y-m-d H:i:s', $visit->date_first, 'UTC');
            $visit->date_last = Time::createFromFormat('Y-m-d H:i:s', $visit->date_last, 'UTC');
        }

**Comment by markstory** [comment] 2015-03-25 02:13
If you add synthetic columns you'd have to always specify the fields to select, as the ORM can't separate the columns you added and the columns present from schema reflection.

Unfortunately at this time computed fields can't easily be cast into their correct types as the ORM doesn't give a way to define the types of computed fields.

**Comment by lorenzo** [comment] 2015-03-25 14:24
Duplicate of https://github.com/cakephp/cakephp/issues/4283

**Closed by lorenzo** 2015-03-25 14:24 UTC
Labels: Enhancement, ORM
