### ISSUE TITLE
DateType.php does not correctly format dates but adds a time part of 0:00

### ISSUE THREAD

**Issue by hmic** [cakephp/cakephp#5939] opened 2015-02-21 18:06 UTC
The best solution to this "problem" I could come up with is adding a new \Cake\I18n\Date class which inherits from \Cake\I18n\Time but overwrites _toStringFormat to [IntlDateFormatter::SHORT, -1] and _niceFormat to [IntlDateFormatter::MEDIUM, -1]. Then changeing dateTimeClass in DateType to use this instead of \Cake\I18n\Time.

Am I wrong on this?

**Comment by markstory** [comment] 2015-02-22 02:29
The reason a time of '00:00' is added is primarily because PHP's native objects do not support only having a date part. Both Carbon, and I18n\Time are built upon PHP's DateTime object.

How does this fact end up manifesting itself as a problem?

**Comment by ADmad** [comment] 2015-02-22 04:39
@hmic Why do you need to subclass `Time`?  `Time::$_toStringFormat` can be changed using `Time::setToStringFormat()` and `Time::$niceFormat` is public. So we could just change the formats before return the `$date` instance [here](https://github.com/cakephp/cakephp/blob/3.0/src/Database/Type/DateType.php#L57) in the `DateType` class.

**Comment by hmic** [comment] 2015-02-22 11:36
@markstory There is a DateType Object thats meant to format date fields in/from the database, which does not do correctly, it adds a time. Problem is that i do want the date fields to be format as a date only, because the time of 00:00 is just meaningless on those. As far as i have come on the codebase, its not possible to change that applicationwide (or set it as an applicationwide default in the core). Removing the DateType database type would be fair, as everybody would know that this has not been taken care of... My other solution is shown below.

@ADmad this is not possible in a generic way, or i am not getting it. I want this date format to be applicationwide and beeing able to set it like the timeformat with Time::setToStringFormat() and Time::$niceFormat, even localized of course. This is not possible at the moment, as chaingeing it there would cause it beeing changed for all DateTimeType instances too.

 Am i still missing something?

My suggestion to fix this would be:

src/Cake/I18n/Date.php:
namespace Cake\I18n;
use...
class Date extends Time implements JsonSerializable {
  protected static $_toStringFormat = [\IntlDateFormatter::SHORT, -1]; // no time format
  public static $niceFormat = [\IntlDateFormatter::MEDIUM, -1]; // no time format
}

and chaingeing src/Cake/Database/Type/DateType.php:
-  public static $dateTimeClass = 'Cake\I18n\Time';
+  public static $dateTimeClass = 'Cake\I18n\Date';


This alone will format all date database fields as only date, application wide, including localization and allows this format to be changed by setting Date::setToStringFormat() and Date::$niceFormat, like the default datetime formats too.
If that same behaviour can be achieved easier, i am listening!

**Comment by markstory** [comment] 2015-02-22 14:02
Ok so the issue is around the default string format output then? I don't think a subclass is the wrong approach personally.

**Comment by hmic** [comment] 2015-02-22 14:10
Yes, its about the output format (only).

I had expected this to work - even when looking at the DateType class at first, because there is a different format set from the DateTimeType. But its not utilized for the output. :-(

Should I prepare a PR for this solution?

**Comment by markstory** [comment] 2015-02-22 14:29
Well the format in the database type is used when creating SQL values, but not for template output as mentioned here. I think a subclass would be reasonable. I think it should also handle other comparison/formatting functionality in a time insensitive way. For example it would odd if timeAgoInWords() included hours, mimutes, or seconds in the output.

**Comment by ADmad** [comment] 2015-02-22 19:34
@hmic Silly me, i forgot that the method & property i pointed out are static.

**Comment by hmic** [comment] 2015-02-22 20:37
I dont know why travis is failing or how to retrigger the build for hhvm.
The tests failing have nothing to do with my changes.

**Comment by ADmad** [comment] 2015-02-22 20:41
Closing as there is a PR open now.

**Comment by lorenzo** [comment] 2015-04-01 07:36
Reopening as the PR could not be merged

**Comment by markstory** [comment] 2016-02-26 05:12
Closing as a Date type was added in 3.2.0

**Closed by markstory** 2016-02-26 05:12 UTC
Labels: datasource, Enhancement, i18n
