### ISSUE TITLE
Bug in Flash messages cake 2.10.2

### ISSUE THREAD

**Issue by rajesh-kumawat** [cakephp/cakephp#11128] opened 2017-08-31 03:13 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.2
* Platform and Target: Php 5.4 and 5.6

### What you did
Bug on every flash render $this->Session->flash();

### What happened
Fatal Error

Error: Cannot unset string offsets
File: D:\Xampp\htdocs\esc\lib\Cake\View\Helper\SessionHelper.php
Line: 168

Notice: If you want to customize this error message, create app\View\Errors\fatal_error.ctp

**Comment by ADmad** [comment] 2017-08-31 03:33
Duplicate of #11125. Issue has already been fixed and will be available in next release.

**Closed by ADmad** 2017-08-31 03:33 UTC
