### ISSUE TITLE
Datetime trouble

### ISSUE THREAD

**Issue by kailsazerland** [cakephp/cakephp#6398] opened 2015-04-22 22:12 UTC
Through the form I save in database a time value, for exemple 6:00. 
In database I can see this value correctly. In my views by pr() I can see follow:
```
Cake\I18n\Time Object
(
    [date] => 2015-04-23 06:00:00.000000
    [timezone_type] => 3
    [timezone] => Europe/Moscow
)
```

BUT(!) by format(), nice() I see 07:00!!! Where are this additional 1 hour from ??
The same trouble with "updated" "modified" field. One hour more!

In bootstrap I wrote:
```
date_default_timezone_set('Europe/Moscow');
```

In App.php in datasource section I have:

```
'timezone' => 'Europe/Moscow',
```

What is going on ?

**Comment by markstory** [comment] 2015-04-23 01:36
Does Europe/Moscow observe DST? Do other formatting methods on the time instance have similar offset issues?

**Comment by kailsazerland** [comment] 2015-04-23 06:41
How to switch off DST?
When I call date('Y-m-d H:i:s'); I see correct version  2015-04-23 06:00:00

**Comment by lorenzo** [comment] 2015-04-23 06:44
Can you show the code you are using for displaying the date?

**Comment by lorenzo** [comment] 2015-04-23 06:48
I'm unable to reproduce your problem, this is what I did:

![screen shot 2015-04-23 at 08 47 36](https://cloud.githubusercontent.com/assets/37621/7291811/864f0e98-e995-11e4-92d1-0ca26e555656.png)

**Comment by kailsazerland** [comment] 2015-04-23 06:57
![2015-04-23 09 56 54](https://cloud.githubusercontent.com/assets/242014/7291921/1a268048-e99f-11e4-953a-7e3fa81715a8.png)

**Comment by kailsazerland** [comment] 2015-04-23 07:00
![2015-04-23 10 00 33](https://cloud.githubusercontent.com/assets/242014/7291955/9eda6764-e99f-11e4-8120-18739eb8769e.png)

Or like this

**Comment by ADmad** [comment] 2015-04-23 07:01
I too get same result as @lorenzo using PHP 5.5.9-1ubuntu4.9

**Comment by kailsazerland** [comment] 2015-04-23 07:09
I've just created new CakePHP project, I have the same problem

**Comment by lorenzo** [comment] 2015-04-23 07:10
@kailsazerland do you have more than one place declaring `date_default_timezone_set(...);` ? I think that may be your problem

**Comment by lorenzo** [comment] 2015-04-23 07:11
@kailsazerland what php version are you using?

**Comment by kailsazerland** [comment] 2015-04-23 07:12
I've just installed new version in new project. The same problem, I've repeat your steps and check it out:
![2015-04-23 10 12 20](https://cloud.githubusercontent.com/assets/242014/7292103/41d93af2-e9a1-11e4-83e8-6e7e6a6211b2.png)

**Comment by lorenzo** [comment] 2015-04-23 07:17
@kailsazerland what version of cakephp are you using?

**Comment by kailsazerland** [comment] 2015-04-23 07:19
the last that can be installed by http://book.cakephp.org/3.0/en/installation.html

**Comment by lorenzo** [comment] 2015-04-23 07:19
Ok, but what does the console report at the beginning when you start the shell? It should show the cake version

**Comment by kailsazerland** [comment] 2015-04-23 07:20
CakePHP 3.0.0

**Comment by kailsazerland** [comment] 2015-04-23 07:21
The same troube has been repeated at other server

**Comment by ADmad** [comment] 2015-04-23 07:22
@kailsazerland Latest version is 3.0.2. CakePHP doesn't auto update itself :)   Run `composer update --prefer-dist` to update.

**Comment by lorenzo** [comment] 2015-04-23 07:23
Closing as this was indeed a problem in 3.0.0 and was fixed in 3.0.1

**Comment by kailsazerland** [comment] 2015-04-23 07:26
Nothing changed. Version 3.0.2
![2015-04-23 10 25 25](https://cloud.githubusercontent.com/assets/242014/7292275/19932e20-e9a3-11e4-9f18-c1ba6239ed3f.png)

**Comment by lorenzo** [comment] 2015-04-23 07:27
Ok, you will need to help us find a way to reproduce it... maybe you can write a failing test case? I have tried this in 3 different servers with different php versions without luck.

**Comment by kailsazerland** [comment] 2015-04-23 07:29
I can give you access to my server

**Comment by lorenzo** [comment] 2015-04-23 07:34
@kailsazerland before that, could you do json_encode($time) in your console and show me the result?

**Comment by kailsazerland** [comment] 2015-04-23 07:42
"\"2015-04-23T06:00:00+0300\""

**Comment by lorenzo** [comment] 2015-04-23 07:43
Also, have you considered doing your app using UTC? It is usually more reliable and less painful that hardcoding your app to a specific timezone as this kind of things will keep happening

**Comment by lorenzo** [comment] 2015-04-23 07:43
@kailsazerland Can you figure out what ICU version are you using? I would suggest updating that.

**Comment by kailsazerland** [comment] 2015-04-23 07:48
How Can I check it? Version ICU
I used UTC, it's ok, but I need my timezone

**Comment by antograssiot** [comment] 2015-04-23 07:50
@kailsazerland ``php --ri intl``

**Comment by kailsazerland** [comment] 2015-04-23 08:01
Internationalization support => enabled
version => 1.1.0
ICU version => 4.2.1

Directive => Local Value => Master Value
intl.default_locale => no value => no value
intl.error_level => 0 => 0
intl.use_exceptions => 0 => 0

**Comment by lorenzo** [comment] 2015-04-23 08:23
@kailsazerland that's a quite old version, would you mind trying to update it? Here is how on ubuntu http://stackoverflow.com/questions/15279881/install-latest-php-intl-on-ubuntu-10-04

**Comment by ceeram** [comment] 2015-04-23 09:42
Added a testcase to prove this, see #6400 which also faisl on travis

**Comment by antograssiot** [comment] 2015-04-23 09:50
@kailsazerland It seems to be linked to the TZ database files used by ICU.

here are some references I found on [SO](http://stackoverflow.com/questions/29399509/php-strftimez-time-for-the-europe-moscow-zoneinfo-file-is-giving-wrong-g) and [Github](https://github.com/yiisoft/yii2/issues/5128#issue-43469896) on similar issue

it will work correctly it the date is before 2014-03-31. There's not much we can do about this.
You probably want to explore the instalation the timezone extention https://pecl.php.net/package/timezonedb

**Comment by lorenzo** [comment] 2015-04-23 09:51
Closing given that this needs to be solved by upgrading the timezone information in your ICU install.

**Comment by lorenzo** [comment] 2015-04-23 09:52
To complement @antograssiot answer, the timezone info needs to be updated in the ICU library, not the pecl extension.

**Closed by lorenzo** 2015-04-23 09:51 UTC
Labels: i18n, On hold

**Comment by kailsazerland** [comment] 2015-04-23 10:48
Thank you a lot, guys! It works!
