### ISSUE TITLE
The 0x20 was added to the downloaded file

### ISSUE THREAD

**Issue by entereal** [cakephp/cakephp#12102] opened 2018-05-19 02:02 UTC
This is a (multiple allowed):

* [x] bug? (not sure yet)
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6.3
* Platform and Target: CentOS7, Nginx1.13, AWS-MySQL

### What you did
public function download() {
	$response = $this->response->withFile($path_to_the_file, ['download' => true]);
	return $response;
}

### What happened
The 0x20 was added to the downloaded file (at the top of the file actually)

it happens with jpg, xlsx and csv files i tried.
with jpg and xlsx, Windows OS says it corrupt and, i couldn't open.
with csv file, i could open it but a space was added to the first data.

**Comment by markstory** [comment] 2018-05-19 13:59
Have you checked your application source files to make sure there aren't any spaces before the leading `<?php`? That is a common source for this kind of problem.

**Comment by entereal** [comment] 2018-05-20 03:05
Yes, I did double checked my code and it seems no mistakes.

![testcontrollersourcess](https://user-images.githubusercontent.com/10758890/40275249-caee31a4-5c25-11e8-961d-44a7d5f1cdb0.jpg)

**Comment by markstory** [comment] 2018-05-20 23:19
I'm not able to reproduce this locally with a test application. PNG and JPG images can be sent via `withFile()` with no problems. Without a way to reproduce the issue you're having I can't help any further. Is there a way you could publish a small application that shows the issue?

**Comment by ohjeohje** [comment] 2018-05-23 11:15
Make sure your local_settings.php (or whatever you are using) has some values. This happened me with 2.X version. If it only has `<?php ` it adds that sign to images details making it corrupt. Perhaps some empty setting file is adding empty space?

**Comment by markstory** [comment] 2018-05-27 03:27
Closing as I don't currently have a way to reproduce this issue.

**Closed by markstory** 2018-05-27 03:27 UTC
Labels: Defect, On hold
