### ISSUE TITLE
TreeBehavior::moveUp does not return false for the root element

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#16091] opened 2021-11-01 09:35 UTC
### Description

Moving the root element up does not return false as promised by the [documentation](https://api.cakephp.org/3.10/class-Cake.ORM.Behavior.TreeBehavior.html#moveUp()).

```
        $entity = $this->Areas->get($id);
        $moved = $this->Areas->moveUp($entity, 1);
```
$moved is an entity object.

The entity fields are the same before and after the call to moveUp:
```
    [id] => 1
    [name] => ...name...
    [parent_id] => null
    [lft] => 1
    [rght] => 190
```

Logs:

```
2021-11-01 10:26:53 Debug: duration=0 rows=0 BEGIN
2021-11-01 10:26:53 Debug: duration=0 rows=0 SELECT `Area`.`lft` AS `Area__lft`, `Area`.`rght` AS `Area__rght` FROM `areas` `Area` WHERE ((`parent_id`) IS NULL AND (`rght`) < 1) ORDER BY `lft` DESC LIMIT 1 OFFSET 0
2021-11-01 10:26:53 Debug: duration=0 rows=0 SELECT `Area`.`lft` AS `Area__lft`, `Area`.`rght` AS `Area__rght` FROM `areas` `Area` WHERE ((`parent_id`) IS NULL AND (`rght`) < '1') ORDER BY `lft` ASC LIMIT 1
2021-11-01 10:26:53 Debug: duration=0 rows=0 COMMIT
```

### CakePHP Version

3.10.0

### PHP Version

7.4

**Comment by bancer** [comment] 2021-11-01 09:41
There is the same problem with using moveDown on the last element of the tree - it does not return false.

**Comment by othercorey** [comment] 2021-11-03 17:26
Do you have a potential patch for this?

**Comment by saeideng** [comment] 2021-11-03 20:09
if there was not any update operate it could return true
this is not a bug IMO

**Comment by saeideng** [comment] 2021-11-03 20:12
also according to code (no test by me ) in `4.x` I think behavior is same in `4.x`
so if there was any update , we need to patch it to `4.x` first

**Comment by bancer** [comment] 2021-11-04 08:09
@othercorey I do not have a patch.
@saeideng This is definitely a bug in 3.x (and probably in 4.x although I have not tested there) because 2.x code returns `false` as promised in the documentation.

**Comment by LordSimal** [comment] 2021-11-09 22:08
If you followed the PR linked above this comment there was quite some discussion on what should be done about this problem.

Currently we came to the conclusion, that the PHPDoc is wrong, not the logic.
The main reason behind that is the fact, that changing that return type from `$node` to `false` would break any logic which is built upon the current version of the TreeBehavior.

Therefore to keep compatibility for at least the `3.x` and `4.x` version we will update the PHPDoc so that the [documentation](https://api.cakephp.org/3.10/class-Cake.ORM.Behavior.TreeBehavior.html#moveUp()) is correct. 

But the desired behavior of either returning `false` or even throwing an exception when a node is being moved "outside" of the tree will most likely change when CakePHP 5 will be released some time next year.

**Comment by bancer** [comment] 2021-11-10 08:10
@LordSimal In that case 3.0 migration guide should be updated too https://book.cakephp.org/3/en/appendices/3-0-migration-guide.html#treebehavior.

**Comment by othercorey** [comment] 2021-11-11 06:10
Closed in https://github.com/cakephp/cakephp/pull/16104

**Closed as completed by othercorey** 2021-11-11 06:10 UTC
Labels: behaviors

**Comment by LordSimal** [comment] 2021-11-11 06:59
> @LordSimal In that case 3.0 migration guide should be updated too https://book.cakephp.org/3/en/appendices/3-0-migration-guide.html#treebehavior.

See https://github.com/cakephp/cakephp/pull/16107
