### ISSUE TITLE
Class Cake\Collection\Collection contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Iterator::next) 

### ISSUE THREAD

**Issue by Shahjalal7311** [cakephp/cakephp#10936] opened 2017-07-23 12:25 UTC
My working application suddenly shows this error. why this occurred i don't know 
I am searching the solution in google but not find any answer or close to answer to fix this problem. That reasons create issues to know the problem .I am not sure this problem at cakephp 3 or others.

Error: Class Cake\Collection\Collection contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Iterator::next) 
File x:\xxxx\xxx\xxxxx\vendor\cakephp\cakephp\src\Collection\Collection.php 
Line: 28

**Comment by HavokInspiration** [comment] 2017-07-23 14:48
It sounds oddly familiar. It seems to the same thing as https://github.com/cakephp/chronos/issues/147

**Comment by markstory** [comment] 2017-07-24 01:38
How can someone reproduce this issue? What version of PHP are you using?

**Comment by Shahjalal7311** [comment] 2017-07-24 03:51
php 7.0.1

**Comment by ravage84** [comment] 2017-07-25 10:54
@Shahjalal7311 have you updated Chronos and other dependencies to the newest version already?
Check with ```composer outdated`` in your application folder.

**Comment by MCF** [comment] 2017-07-26 16:31
I believe this is a duplicate of #147.  Update to the PHP 7.2 beta will fix the problem.

**Comment by ravage84** [comment] 2017-07-26 16:47
Agree with @MCF , it looks like that issue. I guess this issue can be closed then.

But upgrading to a _beta_ of PHP cannot be a real fix. At least not for production... I hope they port the fix down to PHP 7.0 & 7.1.

**Comment by Shahjalal7311** [comment] 2017-07-26 16:58
this problem was remove when my php version is  downgrade at 5.6.1. But when php version is 7.0.1 or 7.1.1 that time rise this problem.

**Comment by MCF** [comment] 2017-07-26 17:29
Yes, I'm quite sure you are running into the PHP bug outlined in the Chronos issue.  It is not present in PHP 5.6, it first occured in 7.0 and was not fixed until 7.2 (currently in beta testing).  The only fix is to use PHP 5.6 or PHP 7.2.

It is not a bug in CakePHP and there is no workaround.

**Comment by MCF** [comment] 2017-07-26 17:34
PHP issue that I logged if you are interested: https://bugs.php.net/bug.php?id=74833

**Comment by Shahjalal7311** [comment] 2017-07-26 17:36
thank you MCF. At last I know that this bug is not cakephp 3

**Closed** 2017-07-26 17:38 UTC
Labels: collection, On hold
