### ISSUE TITLE
Fatal error: Call to a member function schemaCollection() on a non-object in ..../cake3/vendor/cakephp/cakephp/src/ORM/Table.php on line 419

### ISSUE THREAD

**Issue by janlebowski** [cakephp/cakephp#6199] opened 2015-03-29 10:48 UTC
Recently I was adding Acl plugin to CakePHP3 and have got into the situation of:

**Fatal error: Call to a member function schemaCollection() on a non-object in ..../cake3/vendor/cakephp/cakephp/src/ORM/Table.php on line 419**

This is because **public function connection($conn = null)** returned connection as string 'default' instead of the object.
```php
/**
* Returns the connection instance or sets a new one
*
* @param \Cake\Database\Connection|null $conn The new connection instance
* @return \Cake\Database\Connection
*/
public function connection($conn = null)
{
  if ($conn === null) {
    return $this->_connection;
  }
    return $this->_connection = $conn;
  }
}
```
i was able to fix it by replacing the returning value with:

```php
public function connection($conn = null)
{
  if ($conn === null) {
//    return $this->_connection;
      return is_object($this->_connection) ? $this->_connection : ConnectionManager::get($this->_connection );
  }
    return $this->_connection = $conn;
  }
}
```
Could it be a bug?

**Comment by ADmad** [comment] 2015-03-29 12:09
`Table::$_connection` is supposed to be a `\Cake\Database\Connection` instance so need to figure how who sets it as string.

**Comment by janlebowski** [comment] 2015-03-29 14:31
I've tried to dig it deaper. This is a way how it gets 'default' string value set:

**vendor/cakephp/cakephp/src/ORM/Table.php.Cake\ORM\Table->connection:395
vendor/cakephp/cakephp/src/ORM/Table.php.Cake\ORM\Table->__construct:252
vendor/cakephp/cakephp/src/ORM/TableRegistry.php.Cake\ORM\TableRegistry::get:195
vendor/cakephp/acl/src/Model/Table/AclNodesTable.php.Acl\Model\Table\AclNodesTable->node:118**

AclNodesTable->node function sends connection option 'default' to  Cake\ORM\TableRegistry::get:195 and there is a block which ignores it's conversion to the object:

```javascript
if (empty($options['connection'])) {
            $connectionName = $options['className']::defaultConnectionName();
            $options['connection'] = ConnectionManager::get($connectionName);
}
```

Hope it helps.

**Comment by ADmad** [comment] 2015-03-29 14:38
Thanks. So the root of the problem is the AclNodesTable which passes connection name instead of connection instance. Though to avoid such issues we should have an object type check to Table::connection() when used as setter.

**Comment by markstory** [comment] 2015-03-29 20:54
We could raise an exception in the setter when the type is incorrect. Well also need to update the acl plugin.

**Comment by markstory** [comment] 2015-03-30 01:54
Closing as the issue in CakePHP core has been resolved and there is a pull request for the Acl plugin.

**Closed by markstory** 2015-03-30 01:55 UTC
Labels: Defect, ORM
