### ISSUE TITLE
Bake Model with Unique date field

### ISSUE THREAD

**Issue by jonathanlaf** [cakephp/cakephp#10094] opened 2017-01-23 20:29 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.8
* Platform and Target: Bake in windows terminal, querying a InnoDB under a distant cPanel

### What you did
bake.bat bake all releases

### What happened
In ReleasesTable.php in the validator it add 
`->add('release_date', 'unique', ['rule' => 'validateUnique', 'provider' => 'table']);`
Then when I try to add a date even if there's no presence of this date anywhere I receive this error while saving : "The provided value is invalid". If I remove this line from my model, everything work has expected, I can add new date, and if it's not unique, I receive an error stating that value is already in use.

### What you expected to happen
I don't exactly know what does `->add('release_date', 'unique', ['rule' => 'validateUnique', 'provider' => 'table']);` really do, since `$rules->add($rules->isUnique(['release_date']));` is already present and do exactly has expected

Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by saeideng** [comment] 2017-01-23 20:37
what you not using `$rules->add($rules->isUnique(['release_date']));` in application rules?

**Comment by markstory** [comment] 2017-01-23 22:15
Closing as a pull request is open that fixes the issue in theory.

**Comment by cleptric** [comment] 2017-01-24 01:21
The problem is inside `Table::validateUnique`.

```
        foreach ($values as $field) {
            if ($field !== null && !is_scalar($field)) {
                return false;
            }
        }
```

`$filed` is an array when you're saving a date and so the `!is_scalar($field)` check is true.

**Comment by markstory** [comment] 2017-01-24 01:38
Sounds like we shouldn't generate unique validation rules for date/time/datetime fields. Moving this issue to cakephp/bake as that is where the code generation should be updated.

**Comment by markstory** [comment] 2017-01-24 01:38
This issue was moved to cakephp/bake#299

**Closed by markstory** 2017-01-24 01:38 UTC
Labels: Defect

**Comment by cleptric** [comment] 2017-01-24 02:02
But what if I want to 'validate' a date array, for example, a user has entered into a form?
Sure, then we have to run the whole marshalling process to get the right objects in places and so on.
But right now this behaves unexpected. Shouldn't we allow validating uniqueness on arrays then?

**Comment by markstory** [comment] 2017-01-24 03:03
@cleptric You can validate dates using the date validator. Validating non-scalar data requires the validator to know the marshalled state of the data, which doesn't occur until after data has been deemed valid.

**Comment by saeideng** [comment] 2017-01-25 19:38
I think query->where() can be accept date object now

**Comment by inoas** [comment] 2017-01-26 12:46
So does checking for uniquness of date/datetimes within `buildRules()` work as expected then/atm?

**Comment by cleptric** [comment] 2017-01-26 12:49
@ionas yes
