### ISSUE TITLE
$_SESSION null when written to

### ISSUE THREAD

**Issue by Alex-Dettinger** [cakephp/cakephp#17045] opened 2023-02-28 22:03 UTC
### Description

Im upgrading our project from cakePHP 4.2 -> 4.3
On first write to Session.php $_SESSION is null. This warning is suppressed in [Session::write call to _overwrite](https://github.com/cakephp/cakephp/blob/4.3.8/src/Http/Session.php#L513), but because _overwrite() parameters are typed the call throws a type error
`protected function _overwrite(array &$old, array $new): void`

Session::write -> Session::start does not start our Session because we are using SSL (`session.use_cookies = true`) and our headers have been sent 
https://github.com/cakephp/cakephp/blob/4.3.8/src/Http/Session.php#L351

$_SESSION is sometimes allowed to be null. In the above situation $_SESSION is allowed to be null, but throws a typeError downstream. 
Why is the warning [here](https://github.com/cakephp/cakephp/blob/4.3.8/src/Http/Session.php#L513) suppressed?
Is $_SESSION allowed to be null in calls to Session::write? Where/how does $_SESSION get set?

### CakePHP Version

4.3.11

### PHP Version

8.0

**Comment by markstory** [comment] 2023-03-01 16:22
How can someone reproduce the issue you're running into?

>  Is $_SESSION allowed to be null in calls to Session::write? Where/how does $_SESSION get set?

We have to work around `$_SESSION` being null during writes because the session can fail to start but application code will still be doing writes.

> Where/how does $_SESSION get set?

PHP initializes this variable when the session is started. You mentioned your sessions are not starting because of SSL + headers being sent already. Have you tried resolving that problem as it seems closely related to why your sessions are not working correctly.

**Comment by Alex-Dettinger** [comment] 2023-03-01 17:25
You can reproduce my issue by writing to Session before it has been started but after headers have been sent (and with SSL on)
This is not an issue we see in our current environment (running on CakePHP 4.2.12), only after trying to upgrade to 4.3.x, indicating that we _should not_ need to force start the session

An unstarted session ($_SESSION = null) in 4.2 does not error in the call to Session::_overwrite. The parameter $old is auto-converted to empty array
However in 4.3 the call immediately fails before the function code is attempted

This aligns with the fact that the 'PossibleNullArgument' error is suppressed when Session::_overwrite is called from Session::write. Why is this error suppressed if _overwrite errors with null params in 4.3? Why does this fail in 4.3 but not 4.2?

**Comment by markstory** [comment] 2023-03-02 15:44
> You can reproduce my issue by writing to Session before it has been started but after headers have been sent (and with SSL on)

Starting a session after the headers have been sent is the problem. You can't do that reliably as PHP *may* need to send session cookies. While it 'worked' in 4.2 it was subtly broken and we wanted to make that discoverable via the error.

**Comment by ADmad** [comment] 2023-03-05 14:01
> ..writing to Session before it has been started but after headers have been sent..

Not doing things which PHP doesn't like/support is the best course of action here :slightly_smiling_face:

**Comment by Alex-Dettinger** [comment] 2023-03-08 20:28
When we start our server with `$server->emit($server->run())`, nothing in run() is setting the $_SESSION to an array.
Once our server starts emitting, its too late to start the session

During other functions (ie. reading from Session), Session::_hasSession() will never return true given our configuration.

It's impossible for us to reach a line in Session.php which sets $_SESSION to an array. We can set `$_SESSION = []` manually in our middleware::invoke(), but that seems like it should not be necessary

This still feels like a bug in the CakePHP code to not be able to start a session in certain security configurations

**Closed as completed** 2023-03-09 15:29 UTC
Labels: defect, session

**Comment by Alex-Dettinger** [comment] 2023-03-09 16:04
@markstory I've still not gotten any clear answers to my questions, and the only implemented fix is clearer error messaging. However as I noted in my last comment, there doesn't seem to be a way to start a session with our type of secure configuration. If that's the case, this is a CakePhp bug, or I need a clear answer on how to start a session

**Comment by ADmad** [comment] 2023-03-09 16:15
> Session::write -> Session::start does not start our Session because we are using SSL

This is the first time I am hearing of use of SSL affecting starting of session in PHP. PHP is not concerned regarding how data is tranported over the network, except for an environment variable being set when https is used for the URL.

P. S. My comment is in reference to this particular issue. There are of course php.ini config which affect the use of session cookie over http / https.
