### ISSUE TITLE
2.10.6: PHP Fatal error:  Cannot use 'Object' as class name as it is reserved

### ISSUE THREAD

**Issue by Miegl** [cakephp/cakephp#11594] opened 2018-01-02 00:25 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.6, commit: `83928f9d744e5b5fc6728b2c7245d548baf9c52c` (latest)
* Platform and Target: nginx, php 7.2.0 (php-fpm)

### What you did
Tried to use the API in zoneminder, which had bundled version 2.8.0 - 
`[error] 17502#17502: *4 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /srv/http/zoneminder/api/lib/Cake/Core/Object.php on line 30
`
Then I cloned latest 2.x version from this git repository and I've got similar problem - 
`[error] 17902#17902: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot use 'object' as class name as it is reserved in /srv/http/zoneminder/api/lib/cakephp/lib/Cake/Core/Object.php on line 18`

### What happened
`[error] 17902#17902: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot use 'object' as class name as it is reserved in /srv/http/zoneminder/api/lib/cakephp/lib/Cake/Core/Object.php on line 18`

### What you expected to happen
For it to work.

**Comment by dereuromark** [comment] 2018-01-02 00:37
Duplicate of https://github.com/cakephp/cakephp/issues/11346

**Closed by dereuromark** 2018-01-02 00:37 UTC
