### ISSUE TITLE
Model order property not prefixed

### ISSUE THREAD

**Issue by wvdongen** [cakephp/cakephp#7724] opened 2015-11-23 09:52 UTC
I think the order property should be automatically prefixed with the alias of that model (just like the displayField property) if the order property has no model specified. Currently I have to set the alias prefix  for example in the constructor or the beforeFilter.

Cake 2

**Comment by dereuromark** [comment] 2015-11-23 10:07
Duplicate of old tickets like https://github.com/cakephp/cakephp/issues/1893.
Even though I agree with you, the general consensus was not to support this.

But the good news:
That is easily doable using a plugin solution.
See https://github.com/dereuromark/cakephp-shim/blob/2.x/Model/ShimModel.php#L29

I just add it without prefix and it will be automatically prefixed then accordingly.

**Comment by dereuromark** [comment] 2016-02-20 17:41
This can probably be closed as a plugin solution is available and no one yet produced a PR for the core.

**Closed** 2016-02-20 18:44 UTC
Labels: Enhancement, models
