### ISSUE TITLE
Nested resource route with prefix in plugin

### ISSUE THREAD

**Issue by Spriz** [cakephp/cakephp#9287] opened 2016-08-17 10:39 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.0
* Platform and Target: Apache web server, postman/chrome requests

### What you did
Made following routes:
https://gist.github.com/Spriz/7b53241a8a08779e3f67bb1cd8aac87f#file-routes-php and tried generaitng URL in a view with: https://gist.github.com/Spriz/7b53241a8a08779e3f67bb1cd8aac87f#file-controller-php

### Expected Behavior
Get a url like the one in: https://gist.github.com/Spriz/7b53241a8a08779e3f67bb1cd8aac87f#file-bin-cake-routes-output-txt (`/api/v1/wall_posts/:wall_post_id/file`) 

### Actual Behavior
Exception: https://gist.github.com/Spriz/7b53241a8a08779e3f67bb1cd8aac87f#file-exception-txt

### What broke it?
Well, this part works without issues: https://gist.github.com/Spriz/7b53241a8a08779e3f67bb1cd8aac87f#file-routes-php-L10 - so it's specifically the `'prefix' => ''` that breaks it for me :-)

**Comment by Spriz** [comment] 2016-08-17 15:35
I think it might generally not work with prefixes inside plugins - can anyone confirm that?

**Comment by markstory** [comment] 2016-08-17 18:01
Why wouldn't prefixes work inside plugins? Thanks for the routes file that will help in reproducing the issue.

**Comment by markstory** [comment] 2016-08-17 18:11
Have you tried using `'prefix' => 'wall_posts'` when generating your URLs? The `cake routes` cli tool is indicating that is your actual prefix name.

**Comment by Spriz** [comment] 2016-08-17 18:30
Sorry @markstory, that's because I tried both using `wallposts`, `WallPosts` and `wall_posts` :-/

**Comment by markstory** [comment] 2016-08-18 03:53
Looks like you're missing a few required parameters for your route:

```
bin/cake routes generate controller:Files plugin:Api prefix:WallPosts action:index wall_post_id:3 _method:GET
> /api/v1/wall_posts/3/files
```
Works as you described. From your gists you've not included the `wall_post_id` parameter, nor the `_method` parameter. Because you're using `resources()` to generate your routes, the `_method` parameter becomes required.

It is arguable that the `_method` parameter should default to `GET`, but I'm not sure that will play nicely/be safe for existing applications.

**Comment by markstory** [comment] 2016-08-22 19:11
Closing as there hasn't been a response. I'm happy to re-open if this is still an issue.

**Closed by markstory** 2016-08-22 19:11 UTC
Labels: Defect, On hold, plugins, routing

**Comment by Spriz** [comment] 2016-08-23 07:26
Sorry - upgrading to 3.3.2 (from 3.3.0) fixed this.
