### ISSUE TITLE
3.3 Question about REST Validation errors and ErrorHandlerMiddleware

### ISSUE THREAD

**Issue by irongomme** [cakephp/cakephp#9268] opened 2016-08-15 11:27 UTC
* CakePHP Version: 3.3.0
* Platform and Target: Nginx

Before 3.3.0 i had full validation errors in json response, with stack trace, query logs, etc... as it is configured in app.php. Now i've got just : 

```
{
    "message": "2 validation errors occurred",
    "url": "\/api\/notes",
    "code": 422
}
```

But when i comment the ErrorHandlerMiddleware in my app/Application.php, i have the same behavior as before. 
Can someone tell me what is wrong with it ? have I to implement something else to make the ErrorHandlerMiddleware work as it is configured in app.php ?

**Comment by ADmad** [comment] 2016-08-15 15:31
Are you using Crud plugin? I am pretty sure the validation errors, stack trace, query logs etc. you are talking about come from the plugin. Crud plugin will need to be updated to support the new middleware stack.

**Comment by irongomme** [comment] 2016-08-15 15:46
Yes @ADmad , I'm using CRUD plugin. I need to have field index and error keys in validation errors. 
Sorry if this issue is not declared into the good project ...

**Comment by ADmad** [comment] 2016-08-15 15:48
Closing as the issue isn't directly related to core. Open an issue on Crud's issue tracker. It needs to be updated to support the new psr7 middleware changes in 3.3.

**Closed by ADmad** 2016-08-15 15:48 UTC
Labels: On hold
