### ISSUE TITLE
error in new application  \vendor\composer\ClassLoader.php

### ISSUE THREAD

**Issue by LuizMarin** [cakephp/cakephp#14022] opened 2019-12-14 23:10 UTC
This is a (multiple allowed):

* [x] bug 

* CakePHP Version: 4x-dev
* Platform and Target: Windows 10,  PHP 7.3.12 (cli) (built: Nov 19 2019 13:57:43) ( NTS MSVC15 (Visual C++ 2017) x64 )

### What you did
 
The application is new, just created, updated to 4.x without any changes from me.

What is confusing me and I can't find a solution is this part:

![image](https://user-images.githubusercontent.com/50879411/70855602-548daa80-1eac-11ea-9a77-97258bd72749.png)

I learned that I should not change the content of 'vendor'. And even if I could modify, I don't know what to fix. When I go to this place I have another problem, as shown below:

> C: \ marin \ www \ hello \ vendor \ composer \ ClassLoader.php, line: 444

![image](https://user-images.githubusercontent.com/50879411/70855616-8a329380-1eac-11ea-8821-c0d7df62df2a.png)

  Please, I have no experience to solve this level of problem. Being a totally new application, I figured that this kind of problem (I think it was already solved at some point) should not occur. After all it is new application, generated within the correct standard. (I thought so ...)

So how to solve it?

**Comment by markstory** [comment] 2019-12-15 01:40
Somewhere in your code there is a reference to the deprecated class name. If you replace that use statement with the new class name the deprecation error should go away.

**Comment by markstory** [comment] 2019-12-15 01:58
Closing this issue. We can continue the discussion in #14023 as these issues have the same root cause.

**Closed by markstory** 2019-12-15 01:58 UTC
