### ISSUE TITLE
joinData doing unnecessary update

### ISSUE THREAD

**Issue by jessicadagostini** [cakephp/cakephp#10812] opened 2017-06-23 12:39 UTC
This is a (multiple allowed):
 
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)
 
* CakePHP Version: 3.0.x
 
### What I did
I have a belongsToMany association. The association table has more information and I want to edit this information with _joinData when creating a new entity of this table. So, to do this, I have this code:
 
```
// BooksTable.php
        $this->belongsToMany('Tags', [
            'foreignKey' => 'tag_id',
            'targetForeignKey' => 'book_id',
            'joinTable' => 'books_tags'
        ]);
```
``` 
// TagsTable.php
        $this->belongsToMany(‘Books’, [
            'foreignKey' => 'book_id',
            'targetForeignKey' => 'tag_id',
            'joinTable' => 'books_tags'
        ]);
```
 ```
// BooksTagsTable.php
        $this->belongsTo('Tags', [
            'foreignKey' => 'tag_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Books', [
            'foreignKey' => 'book_id',
            'joinType' => 'INNER'
        ]);
```
```
// BooksController.php
	$book = $this->Books->newEntity();
            $tags = [];
            foreach ($this->request->data[‘tags’]['_ids'] as $key => $tag) {
                    $joined = [
                        'id' => $tag,
                        '_joinData' => [
                            ‘position’ => $key
                        ]
                    ];
                    array_push($tags, $joined);
            }
 
            $this->request->data['tags'] = $tags;
 
            $book = $this->Books->patchEntity($book, $this->request->data, [
                    'associated' => [
                        'Tags._joinData'
                    ]
                ]
        );
```
```
object(App\Model\Entity\Book) {

	'name' => 'Test',
	'tags' => [
		(int) 0 => object(App\Model\Entity\Tag) {

			'id' => (int) 4,
			'name_pt' => 'SciFi',
			'name_en' => 'SciFi',
			'created' => object(Cake\I18n\Time) {

				'time' => '2012-09-26T21:26:02+00:00',
				'timezone' => 'UTC',
				'fixedNowTime' => false
			
			},
			'modified' => object(Cake\I18n\Time) {

				'time' => '2016-11-23T16:44:28+00:00',
				'timezone' => 'UTC',
				'fixedNowTime' => false
			
			},
			'_joinData' => object(App\Model\Entity\BooksTags) {

				'posicao' => (int) 0,
				'[new]' => true,
				'[accessible]' => [
					'book_id' => true,
					'tag_id' => true,
					'posicao' => true
				],
				'[dirty]' => [
					'posicao' => true
				],
				'[original]' => [],
				'[virtual]' => [],
				'[errors]' => [],
				'[invalid]' => [],
				'[repository]' => 'books_tags'
			
			},
			'[new]' => false,
			'[accessible]' => [],
			'[dirty]' => [
				'_joinData' => true
			],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[invalid]' => [],
			'[repository]' => 'Tags'
		
		},
		(int) 1 => object(App\Model\Entity\Tag) {

			'id' => (int) 2,
			'name_pt' => 'Terror',
			'name_en' => 'Thriller',
			'created' => object(Cake\I18n\Time) {

				'time' => '2012-09-26T21:26:02+00:00',
				'timezone' => 'UTC',
				'fixedNowTime' => false
			
			},
			'modified' => object(Cake\I18n\Time) {

				'time' => '2016-11-23T16:44:28+00:00',
				'timezone' => 'UTC',
				'fixedNowTime' => false
			
			},
			'_joinData' => object(App\Model\Entity\BooksTags) {

				'posicao' => (int) 1,
				'[new]' => true,
				'[accessible]' => [
					'book_id' => true,
					'tag_id' => true,
					'posicao' => true
				],
				'[dirty]' => [
					'posicao' => true
				],
				'[original]' => [],
				'[virtual]' => [],
				'[errors]' => [],
				'[invalid]' => [],
				'[repository]' => 'books_tags'
			
			},
			'[new]' => false,
			'[accessible]' => [],
			'[dirty]' => [
				'_joinData' => true
			],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[invalid]' => [],
			'[repository]' => 'Tags'
		
		},
	],
	'[new]' => true,
	'[accessible]' => [
		'name' => true,
		'tags' => true
	],
	'[dirty]' => [
		'name' => true,
		'tags' => true
	],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => [],
	'[invalid]' => [],
	'[repository]' => 'Books'

}
```
 
### What happened
Cake does the joinData correctly on the patchEntity. But when I save this, for some reason that I could not discover, Cake updated the `modified` field on my `tags` table to do the _joinData on the `books_tags` table. For security reasons, the database user of my application doesn’t have the grant to update `tags` table nor do I want it to update that field (since it does not make sense because the information on the foreign table was not modified). This way, I can’t save this entity.
 
### What you expected to happen
I don’t want that modified field on `tags` table to be updated, because I didn’t update any information on `tags`, just in `books_tags` table. I just need to reference the tag entity.
 
I didn’t find any issue or something regarding this problem.
 
Am I missing something?

**Comment by lorenzo** [comment] 2017-06-23 12:50
@jessicadagostini Maybe you could remove the `Timestamp` behaviour out of the `TagsTable`. Not sure that would solve your problem, but it s worth the try.

**Comment by markstory** [comment] 2017-06-23 15:52
Do you have a log of the SQL your save operation is doing? You can get query logs from DebugKit, or by [enabling query logging](https://book.cakephp.org/3.0/en/orm/database-basics.html#query-logging).

**Comment by jessicadagostini** [comment] 2017-06-23 16:56
@lorenzo I removed it, but I have another behavior in my `TagsTable` (`CounterCache`) and this behavior was "activated" even I didn't add or modify any new `Tag` entity. My DB user doesn't have the grant to update the field that `CounterCache` needs. Besides, I use this same configuration (with joinData) in another part of my application that needs the `Timestamp` behavior. I think that ._joinData are unnecessary updating the `Tag`entity.

**Comment by jessicadagostini** [comment] 2017-06-23 17:31
@markstory Yeah, I have query logs from DebugKit.
Do you mean this?
```
SELECT 
  Tags.id AS "Tags__id", 
  Tags.name_pt AS "Tags__name_pt", 
  Tags.name_en AS "Tags__name_en", 
  FROM 
  tags Tags 
WHERE 
  (
    Tags.id = 4 
    OR Tags.id = 2
  )

BEGIN
INSERT INTO books (
  name, created, modified
) 
VALUES 
  (
    'test', '2017-06-23 17:09:22', 
    '2017-06-23 17:09:22'
  ) RETURNING *

SELECT 
  BooksTags.id AS "BooksTags__id", 
  BooksTags.book_id AS "BooksTags__book_id", 
  BooksTags.tag_id AS "BooksTags__tag_id", 
  BooksTags.posicao AS "BooksTags__posicao", 
  FROM 
  books_tags BooksTags 
WHERE 
  books_tags.book_id = '8259'

UPDATE 
  tags 
SET 
  modified = '2017-06-23 17:09:22' 
WHERE 
  id = 4
```

**Comment by markstory** [comment] 2017-06-23 19:03
From the post data you showed earlier it looks like you're updating the junction table record which causes the tag to become 'dirty' and need to be re-persisted. Given the SQL you posted it looks suspiciously like a timestamp behavior related update.

**Comment by jessicadagostini** [comment] 2017-06-23 20:25
Hmm. Yes, I'm creating/updating the *junction* table, not the referenced table. I mean, I'm saving additional data on my `BooksTags` table, not on `Tags` table. My question is why this update is happening on the referenced entity.
Maybe am I doing something wrong in my code?. I looked at [this part of the book](https://book.cakephp.org/3.0/en/orm/saving-data.html#saving-additional-data-to-the-join-table) to do this.

**Comment by saeideng** [comment] 2017-06-23 20:40
your tags used in a or many books 
so that maybe good to update `modified` for some case ,and not for other case 
for someone this(update) can be useful ,and for other no
probably we need a option in table definition

**Comment by markstory** [comment] 2017-06-24 01:42
Does removing all of the behaviours from the TagsTable let you save?

**Comment by jessicadagostini** [comment] 2017-06-24 21:16
@markstory Yes, if I remove all behaviors I can save.

**Comment by lorenzo** [comment] 2017-06-25 09:12
I guess the problem is the CounterCache behaviour, as it needs to save data in the parent entity (tag) for each of the changes in the children.

**Comment by markstory** [comment] 2017-06-25 21:23
Given that each piece of code is doing what they should. I don't know what we can do at the framework level here. You may want to consider detaching/removing the problematic behaviors before the effected save operation, or changing you database permissions up.

Closing as this issue is caused by restrictive database permissions, and behavior configuration issues.

**Closed by markstory** 2017-06-25 21:23 UTC
Labels: Defect, On hold, ORM

**Comment by jessicadagostini** [comment] 2017-06-26 18:54
@lorenzo @markstory 
I'm sorry for insisting on this :) 

I removed the behaviors just for test, but I can not remove them in the application because I use it in other actions that need theses two behaviors.

Please, correct if I am wrong, but the behaviors just activate themselves if the entity was updated, right? Why would the timestamp for instance change when a belongsToMany record is updated, if there is no update on the related tables, just on the table used for the association?

**Comment by lorenzo** [comment] 2017-06-26 18:56
CounterCache behaviour actually triggers a parent update on child changes. I think this is the behaviour you are looking at: the tag (parent) changes when the join data is updated.

**Comment by jessicadagostini** [comment] 2017-06-26 19:02
Hmmm. But even removing Counter Cache behavior, I still have problems with Timestamp. Do the Timestamp behavior do the same parent update as Counter Cache?

**Comment by lorenzo** [comment] 2017-06-26 19:06
if I recall correctly, it does... but only when you use the `_ids` feature when marshalling the entity (`patchEntity` for example). If that is not the case, then I think we could reopen the ticket and investigate the problem.

**Comment by lorenzo** [comment] 2017-06-26 19:09
Another case is when you don't provide and `id` for the join data. I think in that case, cake cannot determine due to the way it was implemented, whether the entity actually changed or not. If you are not using the `_ids` feature, make sure you are passing the `id` (for the join table) to the joinData when you mean to do an update.

**Comment by jessicadagostini** [comment] 2017-06-26 19:34
Hmmm. Yes, I'm marshaling the entity using `_ids`, but these `id` are from the `Tags` table (parent) because I'm creating the association, so I do not have the ids from `BooksTags` yet.

Anyway, I will investigate better this in my app and see what can I do. Thank you very so for your feedback! :)
