### ISSUE TITLE
3.1 - BTM with conditions

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#7808] opened 2015-12-07 19:24 UTC
Hi guys. Kind of similar to #7785 but I thought a new issue would be best since it's more about persistence. Say I have a BTM setup that requires the same table multiple times (kind of an edge-case but it's easier than making multiple classes with the same stuff)
```
'belongsToMany' => [
    'Tags' => [
        'through' => 'PostsTags'
    ],
    'PrimaryTags' => [
        'className' => 'Tags',
        'through' => 'PostsTags',
        'targetForeignKey' => 'tag_id',
        'conditions' => ['PostsTags.primary']
    ],
    'SecondaryTags' => [
        'className' => 'Tags',
        'through' => 'PostsTags',
        'targetForeignKey' => 'tag_id',
        'conditions' => ['PostsTags.primary' => 0]
    ]
]
```
And I try to do this only `secondary_tags` persist. This feels like maybe a bug because it looks like the data should save for each association (even if the joinData isn't there).
```
$post = $this->Posts->get($id);
$data = [
    'primary_tags' => [
        ['id' => 1]
    ],
    'secondary_tags' => [
        ['id' => 2]
    ]
];
$this->Posts->patchEntity($post, $data);
$this->Posts->save($post);
```

Also, how possible would it be for the `_joinData` to be automatically added from the association's conditions instead of adding it to the data? If a BTM has conditions set with things from the join table, you'd almost always (can't think of when you wouldn't) want those in the joinData when saving. If that could be automatic that'd be awesome.
```
$data = [
    'primary_tags' => [
        ['id' => 11, '_joinData' => ['primary' => 1]]
    ]
];
// redundant, could be a straight passthrough from $this->request->data('primary_tags._ids')
```

Right now to make this work I need that third association, `Tags` for all tags, wipe my primary/secondary tags from the `$data`, and then do work to add them to a `$data[tags'][]` array so they persist:
```
$post = $this->Posts->get($id);
$tags = [];
if (!empty($this->request->data('primary_tags._ids'))) {
    foreach ($this->request->data('primary_tags._ids') as $tagid) {
        $tags[] = ['id' => $tagid, '_joinData' => ['primary' => 1]];
    }
}
if (!empty($this->request->data('secondary_tags._ids'))) {
    foreach ($this->request->data('secondary_tags._ids') as $tagid) {
        $tags[] = ['id' => $tagid, '_joinData' => ['primary' => 0]];
    }
}
unset($this->request->data['primary_tags'], $this->request->data['secondary_tags']);
$this->request->data('tags', $tags);
```

**Comment by markstory** [comment] 2015-12-08 00:37
> Also, how possible would it be for the _joinData to be automatically added from the association's conditions instead of adding it to the data? If a BTM has conditions set with things from the join table, you'd almost always (can't think of when you wouldn't) want those in the joinData when saving. If that could be automatic that'd be awesome.

While possible, I'd rather not add implicit data mutation to the marshaller. I feel that is the kind of behavior that will not be easy to understand at glance.

I've not had a chance to look at the code, but I suspect that all 3 associations using the same `through` table is the source of the persistence issues.

**Comment by patrickconroy** [comment] 2015-12-11 17:36
Thanks @markstory. I both at the same time agree and disagree that the `joinData` should be added automatically. I agree because it seems like a magical/dirty thing, but I disagree because it means you always have to do data manipulation when saving a BTM with conditions. How would you suggest doing this automatically in my app if not the core (happy to do that if it's what you suggest)?
When would anyone expect BTM data which is conditional-based to not have those conditions when saving? If the condition isn't there, it won't be there when you do a find after the save, which means the save was pointless. It's definitely a tricky thing..

**Comment by markstory** [comment] 2015-12-12 02:42
> How would you suggest doing this automatically in my app if not the core (happy to do that if it's what you suggest)?

You could use one of the event hooks to seed the default data. Both `Model.beforeSave` and `Model.beforeMarshal` are good options.

**Comment by patrickconroy** [comment] 2015-12-18 17:46
Thanks @markstory. In the past I thought something was buggy with how BTM data with _joinData works, and it seems like when trying to turn this into a behavior I found a consistent bug.. since it's related to this I'll put it here (if you want me to open a new issue I can).

Trying to save BTM after something already exists in the DB, using _joinData, and an alias as the association name, it doesn't save the new data with _joinData.
In my `PostsTable`
```
$this->addAssociations([
    'belongsToMany' => [
        'PrimaryTags' => [
            'className' => 'Tags',
            'targetForeignKey' => 'tag_id',
            'conditions' => ['primary' => 1]
        ]
    ]
]);
```
Controller
```
$tags = [];
if (!empty($this->request->data('primary_tags._ids'))) {
    foreach ($this->request->data('primary_tags._ids') as $tagid) {
        $tags[] = ['id' => $tagid, '_joinData' => ['primary' => 1]];
    }
}
$this->request->data('primary_tags', $tags);
```
Data
```
[primary_tags] => Array
(
    [_ids] => Array
        (
            [0] => 141
        )

)
```
If you have an empty `posts_tags` table and save that once, it works. Try it again with the same data and you get two records in the DB: one with primary=1, one with primary=0. Save any other IDs, that have already been saved with primary=1 and there will be duplicated records.

I think if this is fixed I should be on my way to Behavior-ifying this whole process. I'd rather not add logic to delete all the `posts_tags` because it seems like this should work without that.

Thanks!

**Comment by patrickconroy** [comment] 2015-12-18 18:35
Also, another fun little one which might be related (I'm trying to track this down), why does `AssociationCollection::keys` return `primarytags` (sic) for my `PrimaryTags` association? That means you have to explicitly specify `primary_tags` when patching an entity if your data has an entity in it:

```
$post = $this->Posts->get($id);
$data = [
    'primary_tags' => [
        '_ids' => [1, 2]
    ]
];
foreach ($data['primary_tags']['_ids'] as $tagid) {
    $tag = $this->Posts->PrimaryTags->get($tagid);
    $tag->_joinData = $this->Posts->PrimaryTags->PostsTags->findOrCreate(['primary' => 1]);
    $tags[] = $tag;
}
$data['primary_tags'] = $tags;
$this->Posts->patchEntity($post, $data, ['associated' => ['primary_tags']]);
pr($post);
```
Cake thinks the key for `PrimaryTags` is `primarytags`. I'm not sure what the `AssociationCollection::keys` are used for, but why are they different from the key your data from an association constructs? (Sorry if that's a weird question, makes sense in my head.)

In the code above, if I don't specify the `associated` array, then my `$post` doesn't have `primary_tags` on it, when it should even without specifying the array (since Cake is attempting to add all the associations).

**Comment by patrickconroy** [comment] 2015-12-18 19:44
OK, so, things work normally if I update `AssociationCollection` to use `Inflector::underscore` instead of `strtolower` for the aliases and if I add ``['associated' => ['primary_tags._joinData']]`` to my `patchEntity` call. Does that change sound like something that makes sense? Ideally shouldn't it use the association's property name? `strtolower` definitely can't work for camelcased aliases since the data for those associations uses `assoc::property()` as the key.
```
public function add($alias, Association $association)
{
    list(, $alias) = pluginSplit($alias);        
    return $this->_items[$association->property()] = $association;
}
```

**Comment by markstory** [comment] 2015-12-18 22:08
> why does AssociationCollection::keys return primarytags (sic) for my PrimaryTags association?

Associations are stored in a lowercase form to account for people mistyping associations names.

Using the property name will likely break existing apps using the CamelBacked association names in 'associated' keys. Currently the CamelBacked names are consistently inflected to their lowercase forms. The `associated` key should contain association names, not the property names.

**Comment by patrickconroy** [comment] 2015-12-18 22:54
I think this is where the confusion comes in, Cake works if you don't add _joinData because it marshals correctly, but if that association has _joinData, you need to first change it's key in the data that you send or be explicit with the `associated` key..

If you do this
```
$post = $this->Posts->get($id);
$data = [
    'primary_tags' => [
        '_ids' => [1,2,3]
    ]
];
$this->Posts->patchEntity($post, $data);
$this->Posts->save($post);
```
Then this
```
$post = $this->Posts->get($id);
$data = [
    'primary_tags' => [
        '_ids' => [1]
    ]
];
$this->Posts->patchEntity($post, $data);
$this->Posts->save($post);
```
You'll still have three records in the DB, when you should have one, right? (bug).

If you do this
```
$post = $this->Posts->get($id);
$data = [
    'primary_tags' => [
        '_ids' => [1,2,3]
    ]
];
$ptags = [];
foreach ($data['primary_tags']['_ids'] as $tagid) {
    $ptags[] = ['id' => $tagid, '_joinData' => ['primary' => 1]];
}
$data['primary_tags'] = $ptags;
$this->Posts->patchEntity($post, $data);
$this->Posts->save($post);
```
Then this:
```
$post = $this->Posts->get($id);
$data = [
    'primary_tags' => [
        '_ids' => [1]
    ]
];
$ptags = [];
foreach ($data['primary_tags']['_ids'] as $tagid) {
    $ptags[] = ['id' => $tagid, '_joinData' => ['primary' => 1]];
}
$data['primary_tags'] = $ptags;
$this->Posts->patchEntity($post, $data);
$this->Posts->save($post);
```

You'll have two records in the DB (one with primary=0, one with primary=1) (another bug).

The only way it works correctly is if you do this:
```
$post = $this->Posts->get($id);
$data = [
    'primary_tags' => [
        '_ids' => [1]
    ]
];
$ptags = [];
foreach ($data['primary_tags']['_ids'] as $tagid) {
    $ptags[] = ['id' => $tagid, '_joinData' => ['primary' => 1]];
}
$data['primary_tags'] = $ptags;
$this->Posts->patchEntity($post, $data, ['associated' => ['PrimaryTags._joinData']]);
$this->Posts->save($post);
```

It seems like Cake wants to work without the `associated` key, but it fails the second time, possibly when it checks if the join'd record exists, since the existence needs to be based on conditions.

**Comment by markstory** [comment] 2015-12-19 02:06
> You'll still have three records in the DB, when you should have one, right? (bug).

It depends on the save strategy for the association.

The 2nd example does seem incorrect to me as well.

**Comment by markstory** [comment] 2015-12-23 03:19
I took a look at the [first scenario in your last comment - where primary_tags was replaced](https://github.com/cakephp/cakephp/issues/7808#issuecomment-165915165), and the current behavior is 'correct'. Because the `_ids` mode does not set any `_joinData` the 3 records set in the first step do not 'match' the association conditions and are not removed when the association links are replaced.

I wasn't able to reproduce the issue you had in the second scenario. I've attached the code I used in [this gist](https://gist.github.com/markstory/c2a10524cc690606041d). As you can see in the SQL log, the last few queries remove the 3 records and replace it with the single tag correctly.

**Comment by patrickconroy** [comment] 2016-01-05 17:33
Hey @markstory thanks for your help with this. I've been afk for the holidays but looked at this again today. Forgetting about bug1 for now since that might just be me being stupid, this is just for bug2..

In my `PostsTable` I have an overridden `findAll` which adds a contain, and that seems to be what's confusing things. In your shell, I changed it to 
```
$id = 50;
$bookmarks = TableRegistry::get('Bookmarks');
$bookmark = $bookmarks->get($id, ['contain' => ['StarredTags']]);
$data = [
    'starred_tags' => [
        ['id' => 1, '_joinData' => ['starred' => 1]],
        ['id' => 2, '_joinData' => ['starred' => 1]],
        ['id' => 3, '_joinData' => ['starred' => 1]],
    ]
];
$bookmarks->patchEntity($bookmark, $data);
$bookmarks->save($bookmark);

$bookmark = $bookmarks->get($id, ['contain' => ['StarredTags']]);
$data = [
    'starred_tags' => [
        ['id' => 1, '_joinData' => ['starred' => 1]]
    ]
];
$bookmarks->patchEntity($bookmark, $data);
$bookmarks->save($bookmark);
```

Running that once, it's fine. There's a single record in `bookmarks_tags` like you'd expect. However, running that twice results in there being three records in `bookmarks_tags`, two with `starred=0`.

The only way I can see to fix it is to change the `patchEntity` and add the `associated` part.
```
$bookmarks->patchEntity($bookmark, $data, ['associated' => ['StarredTags._joinData']]);
```

My gut is telling me that's a bug, because why does it work once without the `associated` part but not a second time?

**Comment by markstory** [comment] 2016-01-06 04:52
Thanks for the updates on this. I took another look at the code with your updates. And it does seem like something is off. With the StarredTags loaded before marshalling is done, the marshaller does not convert the `_joinData` into an entity and leaves it as an array. Because `_joinData` is not an array it is not persisted which is why we're getting `starred=0`. 

I feel like requiring the `_joinData` association to be marshalled is 'more correct' but the current code makes handling joinData error prone and easy to violate application constraints. I have a good idea on how to fix this now though.

**Comment by patrickconroy** [comment] 2016-01-07 16:39
Thanks @markstory! That works. Another thing with this just popped up though. If you try to save this:
```
$data = [
    'tags' => [
        ['id' => 1, '_joinData' => ['starred' => 1]],
        ['id' => 1, '_joinData' => ['starred' => 0]]
    ]
];
```
It only ever adds the last one in the array, despite the PK for bookmarks being changed to 
``PRIMARY KEY (`bookmark_id`,`tag_id`,`starred`)``

Is there anything I can do to make those both save?

**Comment by markstory** [comment] 2016-01-07 18:40
If starred was not part of the PK it should work, but I suspect the that the ORM is getting confused by some of the PK conditions living in the `_joinData` object.

**Comment by patrickconroy** [comment] 2016-01-07 18:49
Hm, it seems like with or without `starred` in the PK it doesn't work.
```
$id = 50;
$bookmarks = TableRegistry::get('Bookmarks');
$bookmark = $bookmarks->get($id);
$data = [
    'tags' => [
        ['id' => 1, '_joinData' => ['starred' => 1]],
        ['id' => 1, '_joinData' => ['starred' => 0]]
    ]
];
$bookmarks->patchEntity($bookmark, $data);
$bookmarks->save($bookmark);
```
```
CREATE TABLE `bookmarks_tags` (
  `bookmark_id` int(11) NOT NULL,
  `tag_id` int(11) NOT NULL,
  `starred` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`bookmark_id`,`tag_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

**Comment by ADmad** [comment] 2016-01-07 18:59
I believe you need `'associated' => 'Tags._joinData'` in patchEntity() options.

**Comment by patrickconroy** [comment] 2016-01-07 19:01
Thanks @ADmad. Unfortunately that still doesn't make it work.

**Comment by ADmad** [comment] 2016-01-07 19:08
Strange, if have used _joinData in similar way and it works for me.

**Comment by ADmad** [comment] 2016-01-07 19:11
Can you show output of `$bookmark` before calling save()?

**Comment by ADmad** [comment] 2016-01-07 19:17
I checked my code, in association i have `saveStrategy` set to `'append'`, default is `replace'.

**Comment by patrickconroy** [comment] 2016-01-07 19:18
Just checking, but you can run that `$data` and you get two records, one `starred` and one not?
Bookmark before save is @ https://gist.github.com/patrickconroy/379630507e544ba0ee44

**Comment by patrickconroy** [comment] 2016-01-07 19:20
Just tried changing it to `append`.. but both save strategies only save a single record for me..

**Comment by ADmad** [comment] 2016-01-07 19:33
Try modifying [this](https://github.com/cakephp/cakephp/blob/master/tests/TestCase/ORM/TableTest.php#L3567) to have joinData for both records and check if it yield expected results.

**Comment by ADmad** [comment] 2016-01-07 19:39
Hmm this test https://github.com/cakephp/cakephp/blob/master/tests/TestCase/ORM/TableTest.php#L3567 seems bogus to me. The `ArticlesTagsFixture

**Comment by patrickconroy** [comment] 2016-01-07 19:41
That works, but not if the IDs are the same.

**Comment by patrickconroy** [comment] 2016-01-07 19:42
At the end of the day, I need this to happen:
```
INSERT INTO `bookmarks_tags` (`bookmark_id`, `tag_id`, `starred`)
VALUES
	(50, 1, 1),
	(50, 1, 0);
```

**Comment by ADmad** [comment] 2016-01-07 19:44
Doh, I just realized you have same id for both records. That's not the case for my use case.

**Comment by patrickconroy** [comment] 2016-01-07 19:47
No problem! I know this one's a little weird.

**Comment by markstory** [comment] 2016-01-08 02:42
I don't think we can reasonably what you want @patrickconroy. Allowing duplicates in replace will trigger a bunch of annoying issues and make it really hard for us to effectively 'replace' associated data.

**Comment by markstory** [comment] 2016-01-11 02:56
Closing as #7981 was merged, and I don't think we can make duplicate links work.

**Closed by markstory** 2016-01-11 02:56 UTC
Labels: Defect, On hold, ORM
