### ISSUE TITLE
Sort by translated field with paginator gives ambiguous or missing field

### ISSUE THREAD

**Issue by jeanbez** [cakephp/cakephp#8074] opened 2016-01-21 01:03 UTC
Hi,

I am trying to sort the results of an index page by a i18n field, say name. The other fields work ok, however for the name, Cake gives me an error about ambiguous field or missing field, depending on the configuration.

This is my controller:
```
public function index($categoryID = null)
{
    $this->paginate = [
        'finder' => 'translations',
        'contain' => [
            'Authors'
        ],
        'conditions' => [
            'Problems.category_id' => $categoryID,
            'Problems.visible' => true
        ],
        'order' => [
            'Problems.id' => 'ASC'
        ],
        'sortWhitelist' => [
            'Problems.id',
            'Problems.name'
        ],
        'limit' => 25
    ];
    
    $this->set('problems', $this->paginate($this->Problems));
}
```

This is my table model:
```
/**
 * Initialize method
 *
 * @param array $config The configuration for the Table.
 * @return void
 */
public function initialize(array $config)
{
    $this->table('problems');

    $this->displayField('name');
    $this->primaryKey('id');

    $this->addBehavior('Timestamp');
    
    $this->addBehavior('Translate', [
        'fields' => [
            'name'
        ],
        'translationTable' => 'ProblemsI18n'
    ]);

    $this->belongsTo('Categories', [
        'foreignKey' => 'category_id',
        'joinType' => 'INNER'
    ]);
    $this->belongsTo('Authors', [
        'foreignKey' => 'author_id',
        'joinType' => 'INNER'
    ]);
}
```

The SQL query generated by Cake simply has 'name' as an alias, which in not present anywhere else in the query, causing the ambiguity (since the table and its relation in contain both have the name field). Also the field is included in the sortwhitelist and the query is joining the translated table. This the the query available in the debug kit:

```
SELECT 
  Problems.id AS "Problems__id", 
  Problems.category_id AS "Problems__category_id", 
  Problems.level AS "Problems__level", 
  Problems.created AS "Problems__created", 
  Problems.modified AS "Problems__modified", 
  Problems.author_id AS "Problems__author_id", 
  Problems.visible AS "Problems__visible", 
  Authors.id AS "Authors__id", 
  Authors.name AS "Authors__name", 
  Authors.created AS "Authors__created", 
  Authors.modified AS "Authors__modified", 
  Problems_name_translation.id AS "Problems_name_translation__id", 
  Problems_name_translation.locale AS "Problems_name_translation__locale", 
  Problems_name_translation.model AS "Problems_name_translation__model", 
  Problems_name_translation.foreign_key AS "Problems_name_translation__foreign_key", 
  Problems_name_translation.field AS "Problems_name_translation__field", 
  Problems_name_translation.content AS "Problems_name_translation__content"
FROM 
  problems Problems 
  INNER JOIN authors Authors ON Authors.id = (Problems.author_id) 
  LEFT JOIN problems_i18n Problems_name_translation ON (
    Problems_name_translation.model = 'Problems' 
    AND Problems_name_translation.field = 'name' 
    AND Problems_name_translation.locale = 'en' 
    AND Problems.id = (
      Problems_name_translation.foreign_key
    )
  ) 
WHERE 
  (
    Problems.category_id = 1 
    AND Problems.visible = 1
  ) 
ORDER BY 
  name asc 
LIMIT 
  25 OFFSET 0
```

Also, if I manually set the 'fields' key in the paginator, the i18n table is joined, but cake gives "column problems.name does not exist".

Thus, I believe this to be a small bug in the pagination.

**Comment by markstory** [comment] 2016-01-21 03:21
Seems like a duplicate of #8058.

**Comment by phpnut** [comment] 2016-01-21 17:47
#8058 was closed should it be reopened?

**Comment by markstory** [comment] 2016-01-21 17:53
@phpnut I don't think that's necessary we have this issue now :smile:

**Comment by phpnut** [comment] 2016-01-21 17:58
@markstory ok I was not sure if that had been closed by mistake.

**Comment by markstory** [comment] 2016-04-16 18:53
I took a look at this, and I don't think this is a defect in CakePHP. You are attempting to sort on a field that does not exist. From the provided SQL, the `problems`  table does not have a `name` field. This is why you cannot sort on it. Instead you should be sorting on `Problems_name_translation__content`. A sort link created like:

```php
<?= $this->Paginator->sort('Problems_name_translation__content', 'name') ?>
```

Will generate the correct HTML link. You'll also need to include the `Problems_name_translation__content` column in the `sortWhitelist` option in your controller.

**Closed by markstory** 2016-04-16 18:53 UTC
Labels: Defect, i18n, pagination
