### ISSUE TITLE
missing / in home form url

### ISSUE THREAD

**Issue by Erwane** [cakephp/cakephp#13273] opened 2019-05-21 09:11 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.7
* Platform and Target: debian 9

### What you did
`composer create-project --prefer-dist cakephp/app my_app_name`

change route `/` to
```php
$routes->connect('/', ['controller' => 'Pages', 'action' => 'index'], ['_name' => 'home']);
```

create a method in PagesController
```php
    public function index()
    {
        debug($this->request->getMethod());
    }
```

create a view Pages/index.ctp with 
```php
<?= $this->Form->create(null, ['type' => 'POST', 'url' => [
    '_name' => 'home',
    '?' => [
        'abc' => 'def',
    ]
]]) ?>
<?= $this->Form->button("submit") ?>
<?= $this->Form->end() ?>
```
Submit form

### What happened
The method is GET in debug

### What you expected to happen
POST request ;)

The problem come from URL and missing / at the end :
Generated URL : `/tests/cakephp?abc=def`
Developper tools, network tab, show a POST to `/tests/cakephp` with a 301 redirect ot `/tests/cakephp/`

Thanks a lot.

**Comment by markstory** [comment] 2019-05-21 13:51
URLs don't require a trailing `/` is your webserver doing a redirect to add the `/` on?

**Comment by markstory** [comment] 2019-07-13 03:23
Closing as there haven't been any updates and I'm not able to reproduce the problem you're describing using the built-in php server.

**Closed by markstory** 2019-07-13 03:23 UTC
Labels: need-more-info

**Comment by Erwane** [comment] 2019-07-15 08:12
Sorry for delay. I don't understand why my apache automatically add trailing slash for homepage.
It's not cakephp related.
