### ISSUE TITLE
3.X - Fixture Connection

### ISSUE THREAD

**Issue by wadeos** [cakephp/cakephp#6317] opened 2015-04-11 06:09 UTC
I have the following setup

Two Connections
* default - contains schema and application data
* test - empty database

All my another fixtures and tests seem to be working correctly with using the test database, all but for my Apps entity.
When AppsTableTest runs it loads entities from my default database not the test one containing the inserted fixtures. 

I have been using $import to import the schema from the default database, but even with no import and manually defining the schema by $fields there was no change.

```php 
class AppsFixture extends TestFixture
{
  //public $import = ['table' => 'apps'];
    public $fields = [
       //.. schema defined here
    ]; 
    public $records = [
        //.. records defined here
    ];
}

class AppsTableTest extends TestCase
{

    public $fixtures = ['app.apps'];

    public function setUp()
    {
        parent::setUp();
        $config = TableRegistry::exists('Apps') ? [] : ['className' => 'App\Model\Table\AppsTable'];
        $this->AppsTable = TableRegistry::get('Apps', $config);
    }

    public function tearDown()
    {
        unset($this->AppsTable);
        parent::tearDown();
    }

    public function testFindOne(){

        $query = $this->AppsTable->find()->where(['Apps.id' => 1]);

        $this->assertInstanceOf('Cake\ORM\Query', $query);

        $result = $query->first()->toArray();
        
        // result contains a result from my default connection. not from the inserted fixtures ?
        print_r($result);
        die;
        
    }
}

```

Am i missing something ?

**Comment by markstory** [comment] 2015-04-11 13:48
Do you have a `test` connection defined, and do your table classes define or change their connection anywhere?

**Comment by wadeos** [comment] 2015-04-11 13:59
The test connection is defined in app.php and no none of the table classes define a connection.

**Comment by markstory** [comment] 2015-04-11 14:08
Ok, I'm not able to reproduce the issue with non-import fixtures as I have a few applications that are using fixtures. Do you still have the `<listeners>` block in your `phpunit.xml`, and do your tests extend from `Cake\TestSuite\TestCase`?  I'll see if I can reproduce the issue you're having with import fixtures though.

**Comment by jadb** [comment] 2015-04-11 14:26
Someone on IRC hada similar problem not long ago on windows. 

Make sure that your `phpunit.xml(.dist)` is being loaded for the fixtures to be auto-loaded. That resolved it for him.

**Comment by lorenzo** [comment] 2015-04-11 14:41
This is important https://github.com/cakephp/app/blob/master/phpunit.xml.dist#L23-L31

**Comment by wadeos** [comment] 2015-04-11 23:23
AppsTableTest extends TestCase
AppsControllerText extends IntegrationTestCase

Yes i do have the phpunit.xml.dist, and listeners defined. 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit
	colors="true"
	processIsolation="false"
	stopOnFailure="false"
	syntaxCheck="false"
	bootstrap="./tests/bootstrap.php"
	>
	<php>
		<ini name="memory_limit" value="-1"/>
		<ini name="apc.enable_cli" value="1"/>
	</php>

	<!-- Add any additional test suites you want to run here -->
	<testsuites>
		<testsuite name="App Test Suite">
			<directory>./tests/TestCase</directory>
		</testsuite>
		<!-- Add plugin test suites here. -->
	</testsuites>

	<!-- Setup a listener for fixtures -->
	<listeners>
		<listener
		class="\Cake\TestSuite\Fixture\FixtureInjector"
		file="./vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureInjector.php">
			<arguments>
				<object class="\Cake\TestSuite\Fixture\FixtureManager" />
			</arguments>
		</listener>
	</listeners>

</phpunit>
```

The app was created from cakephp/app, and i run composer update every day.
All of my fixtures and test cases originally worked but after a few updates a couple of weeks back my test cases started failed. Didn't think much of it. But now as i'm completing the tests, I was stumped to why my tests where using the default connection.


```php

class AppsTableTest extends TestCase
{
   //...

   public function testSave()
   {
          $app = $this->AppsTable->newEntity([
                  //.. entity data
          ]);
          
          //.. test code here..       
          
          // this saves to my default connection ? not the test one with the fixtures
          $this->AppsTable->save($app);
   }

   //...
}

```

Also just thought id note that i'm having the same problem with my controller integration testing, regarding the same entity fixture "apps".

My other controller integration tests like UsersControllerTests e.t.c all are accessing the right connection with their inserted fixtures. Except for AppsControllerTest which has the same problem as the AppsTableTest, its using the default connection instead of the test one.

**Comment by markstory** [comment] 2015-04-11 23:31
So other fixtures work ok, it is just this one specific fixture (Apps) that exhibits this issue?

**Comment by wadeos** [comment] 2015-04-11 23:33
Yes that is correct. I've even tried deleting the AppsFixture.php and getting bake to re-create me one. But it still keeps on loading the default connection.

**Comment by markstory** [comment] 2015-04-11 23:35
What do the AppsTable class and fixture look like?

**Comment by wadeos** [comment] 2015-04-11 23:38
Here we go

```php

<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Apps Model
 */
class AppsTable extends Table {

/**
 * Initialize method
 *
 * @param array $config The configuration for the Table.
 * @return void
 */
	public function initialize(array $config) {
		
		$this->table('apps');
		$this->displayField('name');
		$this->primaryKey('id');
		$this->addBehavior('Timestamp');
		$this->belongsTo('Users', [
			'alias' => 'Users',
			'foreignKey' => 'user_id'
		]);
	}

/**
 * Default validation rules.
 *
 * @param \Cake\Validation\Validator $validator instance
 * @return \Cake\Validation\Validator
 */
	public function validationDefault(Validator $validator) {
		$validator
			->add('id', 'valid', ['rule' => 'numeric'])
			->allowEmpty('id', 'create')
			->add('user_id', 'valid', ['rule' => 'numeric'])
			->requirePresence('user_id', 'create')
			->notEmpty('user_id')
			->requirePresence('name', 'create')
			->notEmpty('name')
			->requirePresence('slug', 'create')
			->notEmpty('slug')
			->allowEmpty('title')
			->requirePresence('domain', 'create')
			->notEmpty('domain')
			->allowEmpty('theme')
			->add('secure', 'valid', ['rule' => 'numeric'])
			->allowEmpty('secure')
			->allowEmpty('description')
			->allowEmpty('keywords')
			->allowEmpty('tags')
			->requirePresence('type', 'create')
			->notEmpty('type');

		return $validator;
	}

	public function isOwnedBy($_id, $_user_id)
	{
	    return $this->exists(['id' => $_id, 'user_id' => $_user_id]);
	}

}

<?php
namespace App\Test\Fixture;

use Cake\TestSuite\Fixture\TestFixture;

/**
 * AppsFixture
 *
 */
class AppsFixture extends TestFixture
{

    public $import = ['table' => 'apps'];
/*
    public $fields = [
        'id' => ['type' => 'integer', 'length' => 25, 'unsigned' => true, 'null' => false, 'default' => null, 'comment' => '', 'autoIncrement' => true, 'precision' => null],
        'user_id' => ['type' => 'integer', 'length' => 10, 'unsigned' => true, 'null' => false, 'default' => null, 'comment' => '', 'precision' => null, 'autoIncrement' => null],
        'name' => ['type' => 'string', 'length' => 50, 'null' => false, 'default' => null, 'comment' => '', 'precision' => null, 'fixed' => null],
        'slug' => ['type' => 'string', 'length' => 50, 'null' => false, 'default' => null, 'comment' => '', 'precision' => null, 'fixed' => null],
        'title' => ['type' => 'string', 'length' => 100, 'null' => false, 'default' => null, 'comment' => '', 'precision' => null, 'fixed' => null],
        'domain' => ['type' => 'string', 'length' => 100, 'null' => false, 'default' => null, 'comment' => '', 'precision' => null, 'fixed' => null],
        'theme' => ['type' => 'string', 'length' => 50, 'null' => false, 'default' => null, 'comment' => '', 'precision' => null, 'fixed' => null],
        'secure' => ['type' => 'integer', 'length' => 1, 'unsigned' => false, 'null' => false, 'default' => null, 'comment' => '', 'precision' => null, 'autoIncrement' => null],
        'description' => ['type' => 'text', 'length' => null, 'null' => false, 'default' => null, 'comment' => '', 'precision' => null],
        'keywords' => ['type' => 'text', 'length' => null, 'null' => false, 'default' => null, 'comment' => '', 'precision' => null],
        'tags' => ['type' => 'text', 'length' => null, 'null' => false, 'default' => null, 'comment' => '', 'precision' => null],
        'type' => ['type' => 'string', 'length' => 25, 'null' => false, 'default' => null, 'comment' => '', 'precision' => null, 'fixed' => null],
        'modified' => ['type' => 'datetime', 'length' => null, 'null' => false, 'default' => null, 'comment' => '', 'precision' => null],
        'created' => ['type' => 'datetime', 'length' => null, 'null' => false, 'default' => null, 'comment' => '', 'precision' => null],
        '_constraints' => [
            'primary' => ['type' => 'primary', 'columns' => ['id'], 'length' => []],
        ],
        '_options' => [
            'engine' => 'InnoDB', 'collation' => 'latin1_swedish_ci'
        ],
    ];*/
    
    /**
     * Records
     *
     * @var array
     */
    public $records = [
        [
            'id' => 1,
            'user_id' => 1,
            'name' => 'Bluu Interactive',
            'slug' => 'bluu',
            'title' => 'Bluu Interactive',
            'domain' => 'www.bluu.co.nz',
            'theme' => 'default',
            'secure' => 0,
            'description' => 'Lorem ipsum dolor sit amet, aliquet feugiat. Convallis morbi fringilla gravida, phasellus feugiat dapibus velit nunc, pulvinar eget sollicitudin venenatis cum nullam, vivamus ut a sed, mollitia lectus. Nulla vestibulum massa neque ut et, id hendrerit sit, feugiat in taciti enim proin nibh, tempor dignissim, rhoncus duis vestibulum nunc mattis convallis.',
            'keywords' => 'Lorem ipsum dolor sit amet, aliquet feugiat. Convallis morbi fringilla gravida, phasellus feugiat dapibus velit nunc, pulvinar eget sollicitudin venenatis cum nullam, vivamus ut a sed, mollitia lectus. Nulla vestibulum massa neque ut et, id hendrerit sit, feugiat in taciti enim proin nibh, tempor dignissim, rhoncus duis vestibulum nunc mattis convallis.',
            'tags' => 'Lorem ipsum dolor sit amet, aliquet feugiat. Convallis morbi fringilla gravida, phasellus feugiat dapibus velit nunc, pulvinar eget sollicitudin venenatis cum nullam, vivamus ut a sed, mollitia lectus. Nulla vestibulum massa neque ut et, id hendrerit sit, feugiat in taciti enim proin nibh, tempor dignissim, rhoncus duis vestibulum nunc mattis convallis.',
            'type' => 'website',
            'modified' => '2015-02-13 16:17:07',
            'created' => '2015-02-13 16:17:07'
        ],
        [
            'id' => 2,
            'user_id' => 2,
            'name' => 'Icing',
            'slug' => 'icing',
            'title' => 'Icing',
            'domain' => 'ice.bluu.co.nz',
            'theme' => 'default',
            'secure' => 0,
            'description' => 'Lorem ipsum dolor sit amet, aliquet feugiat. Convallis morbi fringilla gravida, phasellus feugiat dapibus velit nunc, pulvinar eget sollicitudin venenatis cum nullam, vivamus ut a sed, mollitia lectus. Nulla vestibulum massa neque ut et, id hendrerit sit, feugiat in taciti enim proin nibh, tempor dignissim, rhoncus duis vestibulum nunc mattis convallis.',
            'keywords' => 'Lorem ipsum dolor sit amet, aliquet feugiat. Convallis morbi fringilla gravida, phasellus feugiat dapibus velit nunc, pulvinar eget sollicitudin venenatis cum nullam, vivamus ut a sed, mollitia lectus. Nulla vestibulum massa neque ut et, id hendrerit sit, feugiat in taciti enim proin nibh, tempor dignissim, rhoncus duis vestibulum nunc mattis convallis.',
            'tags' => 'Lorem ipsum dolor sit amet, aliquet feugiat. Convallis morbi fringilla gravida, phasellus feugiat dapibus velit nunc, pulvinar eget sollicitudin venenatis cum nullam, vivamus ut a sed, mollitia lectus. Nulla vestibulum massa neque ut et, id hendrerit sit, feugiat in taciti enim proin nibh, tempor dignissim, rhoncus duis vestibulum nunc mattis convallis.',
            'type' => 'website',
            'modified' => '2015-02-13 16:17:07',
            'created' => '2015-02-13 16:17:07'
        ],
        [
            'id' => 3,
            'user_id' => 3,
            'name' => 'IceUI',
            'slug' => 'iceui',
            'title' => 'IceUI',
            'domain' => 'ui.ice.bluu.co.nz',
            'theme' => 'default',
            'secure' => 0,
            'description' => 'Lorem ipsum dolor sit amet, aliquet feugiat. Convallis morbi fringilla gravida, phasellus feugiat dapibus velit nunc, pulvinar eget sollicitudin venenatis cum nullam, vivamus ut a sed, mollitia lectus. Nulla vestibulum massa neque ut et, id hendrerit sit, feugiat in taciti enim proin nibh, tempor dignissim, rhoncus duis vestibulum nunc mattis convallis.',
            'keywords' => 'Lorem ipsum dolor sit amet, aliquet feugiat. Convallis morbi fringilla gravida, phasellus feugiat dapibus velit nunc, pulvinar eget sollicitudin venenatis cum nullam, vivamus ut a sed, mollitia lectus. Nulla vestibulum massa neque ut et, id hendrerit sit, feugiat in taciti enim proin nibh, tempor dignissim, rhoncus duis vestibulum nunc mattis convallis.',
            'tags' => 'Lorem ipsum dolor sit amet, aliquet feugiat. Convallis morbi fringilla gravida, phasellus feugiat dapibus velit nunc, pulvinar eget sollicitudin venenatis cum nullam, vivamus ut a sed, mollitia lectus. Nulla vestibulum massa neque ut et, id hendrerit sit, feugiat in taciti enim proin nibh, tempor dignissim, rhoncus duis vestibulum nunc mattis convallis.',
            'type' => 'website',
            'modified' => '2015-02-13 16:17:07',
            'created' => '2015-02-13 16:17:07'
        ],
        [
            'id' => 4,
            'user_id' => 4,
            'name' => 'Open Source',
            'slug' => 'open-source',
            'title' => 'Open Source',
            'domain' => 'source.bluu.co.nz',
            'theme' => 'default',
            'secure' => 0,
            'description' => 'Lorem ipsum dolor sit amet, aliquet feugiat. Convallis morbi fringilla gravida, phasellus feugiat dapibus velit nunc, pulvinar eget sollicitudin venenatis cum nullam, vivamus ut a sed, mollitia lectus. Nulla vestibulum massa neque ut et, id hendrerit sit, feugiat in taciti enim proin nibh, tempor dignissim, rhoncus duis vestibulum nunc mattis convallis.',
            'keywords' => 'Lorem ipsum dolor sit amet, aliquet feugiat. Convallis morbi fringilla gravida, phasellus feugiat dapibus velit nunc, pulvinar eget sollicitudin venenatis cum nullam, vivamus ut a sed, mollitia lectus. Nulla vestibulum massa neque ut et, id hendrerit sit, feugiat in taciti enim proin nibh, tempor dignissim, rhoncus duis vestibulum nunc mattis convallis.',
            'tags' => 'Lorem ipsum dolor sit amet, aliquet feugiat. Convallis morbi fringilla gravida, phasellus feugiat dapibus velit nunc, pulvinar eget sollicitudin venenatis cum nullam, vivamus ut a sed, mollitia lectus. Nulla vestibulum massa neque ut et, id hendrerit sit, feugiat in taciti enim proin nibh, tempor dignissim, rhoncus duis vestibulum nunc mattis convallis.',
            'type' => 'website',
            'modified' => '2015-02-13 16:17:07',
            'created' => '2015-02-13 16:17:07'
        ]
    ];
}


```

**Comment by markstory** [comment] 2015-04-12 00:21
Thanks! I'll see if I can trigger the same error locally.

**Comment by markstory** [comment] 2015-04-12 15:04
I wasn't able to reproduce this locally, I pasted the fixture and table you provided into a new app skeleton, created a table based on the commented out schema, and created the following test case:

```php
<?php
namespace App\Test\TestCase\Model\Table;

use App\Model\Table\AppsTable;
use Cake\ORM\TableRegistry;
use Cake\TestSuite\TestCase;

/**
 * App\Model\Table\AppsTable Test Case
 */
class AppsTableTest extends TestCase
{

    /**
     * Fixtures
     *
     * @var array
     */
    public $fixtures = [
        'app.bookmarks',
        'app.apps',
    ];

    /**
     * setUp method
     *
     * @return void
     */
    public function setUp()
    {
        parent::setUp();
        $config = TableRegistry::exists('Apps') ? [] : ['className' => 'App\Model\Table\AppsTable'];
        $this->Apps = TableRegistry::get('Apps', $config);
    }

    /**
     * tearDown method
     *
     * @return void
     */
    public function tearDown()
    {
        unset($this->Apps);

        parent::tearDown();
    }

    public function testFetchData()
    {
        debug($this->Apps->find('all')->toArray());
    }

}
```
Running the test showed the data from the test fixture and not the default connection.

**Comment by wadeos** [comment] 2015-04-12 23:48
Thanks for the help Mark! After creating a blank skeleton app, i've realised what the problem was. I have a static class for reflection based on the app entity called AppReflection which is called from the bootstrap.php.
When TableRegistry::get is called its saving my connection instance, then when the table tests / integration tests come along it will pick up the previous initialised connection not the test one.

```php
public static function initialize(){
	self::$apps = Cache::remember('websites', function(){
           return TableRegistry::get('Apps')->find('all')->hydrate(false)->toArray();
	});
}

```
I apologise about not seeing this earlier.
I would also like to quickly say that you and the cake community have and are doing awesome job on 3.X, cake has come along way since 2.X. Very impressed. Keep it up !

**Comment by markstory** [comment] 2015-04-13 01:40
Thanks :+1:. Closing this issue as it was a problem with your app setup.

**Closed by markstory** 2015-04-13 01:40 UTC
Labels: fixtures, On hold, testing
