### ISSUE TITLE
Implement single table and class table inheritance

### ISSUE THREAD

**Issue by organic-scholar** [cakephp/cakephp#4412] opened 2014-08-27 09:19 UTC
For details visit the link below

http://doctrine-orm.readthedocs.org/en/latest/reference/inheritance-mapping.html

**Comment by Spriz** [comment] 2015-07-08 15:36
The STI inheritance would be damn cool - at least would provide a really elegant solution for some of the more serious design issues we've had by using Cake 3 for our newest app :smile:

**Comment by robertpustulka** [comment] 2015-07-30 06:20
STI at least should be quite easy to implement. I could try it in some spare time.

**Comment by stefan-hausmann** [comment] 2015-08-05 16:56
@robertpustulka: coming from #7177 (haven't seen this issue here before), do you already have an idea / a plan how and where in the cakephp core to implement this? would like to discuss it here as I would like to have this feature, too!

**Comment by robertpustulka** [comment] 2015-08-05 20:12
@stefan-hausmann I've implemented a tiny behavior for something like STI, but without entity subclassing. It works for multiple Table classes sharing a single db table using a discriminator column.
I'm open to implementing something more powerful if you have an idea how this could work.

**Comment by markstory** [comment] 2015-08-06 02:06
If multiple table classes can share a db table, then the entity issue is also solved. If you have Model\Table\AdministratorsTable and Model\Entity\Administrator, the ORM cares not what the parent classes of Administrator are.

**Comment by robertpustulka** [comment] 2015-08-06 06:03
That's true more or less, but what I understood from @stefan-hausmann request is that a UsersTable would know how to hydrate entities, thus Users->find() would return User entities as well as Administrator, Client  etc. On the second thought that's not quite good solution...

**Comment by robertpustulka** [comment] 2015-08-06 07:07
I made my plugin available here: https://github.com/robotusers/cakephp-table-inheritance
It can be the base for the core implementation if you like.

**Comment by stefan-hausmann** [comment] 2015-08-07 08:19
@robertpustulka: thanks, I'll take a look and think about how to implement this as a core feature.

**Comment by fquffio** [comment] 2015-12-24 17:21
I'm giving this a +1. CTI would be a really cool feature, and could actually fit in lots of apps (mine for sure :smile: ).

If I may, what I dislike most of the Doctrine implementation is that the topmost class in the hierarchy must know about all of its descendants (which looks a bit like a design flaw, to me): any hopes this will be different in CakePHP's future implementation?

**Comment by markstory** [comment] 2015-12-24 20:43
@fquffio I've not put much thought into this yet. If the parent didn't explicitly know about the child types, how would they be discovered.

**Comment by fquffio** [comment] 2015-12-29 14:32
@markstory I thought that maybe descendants' existence could be notified to some "ambassador" (TableRegistry?) in the bootstrap, instead of being hardcoded in the parent. Hence, the topmost class should only be aware of which is the name of the discriminator column (if any), then query the ambassador to discover which is the correct child type based on the discriminator column's value when retrieving results. In the same fashion, this "ambassador" would be responsible for returning the correct value to populate discriminator column when inserting new records, and so on. I guess a similar approach could work for CTI as well as STI, but probably it could be hard to deal with chains of inheritance (B extends A, C extends B, …).

My point is: personally, I would like to be able to add new descendants in a plugin, without having to edit the application's core code. For instance, I might have a CakesTable that extends my BakeryProductsTable in the core application, then add a CookiesTable that extends BakeryProductsTable as well in an optional plugin of which the core app might even be unaware of: having the list of descendants hardcoded in the BakeryProductsTable (see Doctrine's impl.) would be quite a problem, in such a case. :wink:

**Comment by markstory** [comment] 2015-12-29 18:23
The registration approach would only work if the descendants were loaded on each request. Because PHP only loads the files that are used in a request, not all the descendants will be loaded during bootstrap and the parent class would not know about their existence.

If the descendant registration could be modified at runtime, then both hardcoded and runtime registration through event notifiers could be afforded. For example the [API proposed by @robertpustulka](https://github.com/robotusers/cakephp-table-inheritance#how-to-make-this-work) should allow both kinds of use cases.

**Comment by markstory** [comment] 2016-01-16 04:30
I've been mulling on this a bit more. I've put my thoughts [into a wiki page](https://github.com/markstory/cakephp/wiki/Single-Table-Inheritance-Support). If it makes it easier for others, I can start a new RFC issue.

**Comment by lorenzo** [comment] 2016-01-16 06:26
@markstory an RFC where we can discuss it will be better.

**Comment by jadb** [comment] 2016-01-16 06:47
@lorenzo here's a start i guess: https://gist.github.com/jadb/368d7653da2d252b5865

**Comment by ionas** [comment] 2016-01-16 13:32
**Abstract: HasOne + PHP Class Inheritance / Aspects > CTI > STI**

To me STI, CTI, HasOne, IS A and HasAspect all seem to solve the same thing creating models that are similar and re-use behavior setups, finders, entity mutators/getters/setters, custom data types, etc.

Instead of strict inheriantance I tend to favour composition through aspects.
The closest thing available, we got is HasOne associations, which is very similar to CTI, already.
Could HasOne handling be improved to do what STI and CTI trys to do, here? Gather use cases of STI and CTI and see if we can wrap that around HasOne?

UsersTable HasOne ProfilesTable
AdminsTable extendsTable UsersTable HasOne GlobalPrivilegesTable

Benefit: Normalized data, easy to extend, modify, remove. Clear what's what by design in both sql tables and php classes.
Drawback: Joins
Solution: support optional (materialized) views with refreshes and custom indicies. This will create denormalized data if you need it for speed.

If there is a need to just have a discriminator column, could we add RDBMS agnostic ENUM support and improve docs/add custom methods for polymorphic behavior?

About STI and CTI:

STI: http://martinfowler.com/eaaCatalog/singleTableInheritance.html
+ (+) No SQL JOINs required
+ (+) Slow on RDBMS growth once you do a lot of table classes off one "real table" and use min/max, group by etc unless you add a lot of indicies (basically one per STI?).
+ (+) Consistent without hassle across reads and writes.
- (-) Breaks with normalization goals of entities in ERD/RDBMS.
- (-) Creates NULL values for specific fields by design.
- (-) Makes it hard to see just from the table which columns are utilized by what tables/models.
- (-) As the new ORM is very close to SQL, what would select() do if you select columns that are 
- (-) You need to explicitly define the fields that specify a model instead of getting it through the datasource/schema
- (-) Confuses the table name for table classes (cause for now by default Table class ~== rdbms table)
- (-) By design does not automatically inherit behaviors, finders, entities mutators/getters/setters, custom datatypes

CTI: http://martinfowler.com/eaaCatalog/classTableInheritance.html
+ (+) Does not break with normalization goals of entities in RDBMS
+ (+) Does not create NULL values by design.
- (-) Some Impact on the RDBMS, Joins required, this can be improved by (materialized) views with indicies
- (-) Not necessarily consistent across read/write (non materialized SQL views)

**Comment by markstory** [comment] 2016-01-16 19:18
@ionas I'm not sure where you were going with the background on the various approaches of solving inheritance in a relational database. While I did not have plans for implementing class-table-inheritance, putting the various ways of mapping inheritance into a relational database into a plugin sounds interesting.

**Comment by fquffio** [comment] 2016-01-16 19:38
@markstory May I ask why you dropped your plans for CTI? :disappointed: With STI only the dynamic registration pre-documented in the wiki (which seems great to me!) becomes IMHO much less useful: if an application is agnostic enough to require plugins to self-register as "extensions" of some Model, I think it is also quite likely that plugins will be kind enough to use separate tables to store their specific data, instead of changing the schema of the main table, as that could lead to possible conflicts and undesired behaviors. Am I that wrong? :grin:

**Comment by markstory** [comment] 2016-01-16 21:28
@fquffio I don't think CTI is totally out, but I wanted to start small/simple. Implemeting class table inheritance is a bit more complex than single-table as we need to deal with hiding joins and transparently saving to multiple tables via one mixed entity.

**Comment by fquffio** [comment] 2016-01-17 08:53
Great! I must have misinterpreted the change in the roadmap, sorry for having bothered you… Thanks for your work and interest in this subject!

**Comment by markstory** [comment] 2016-01-17 13:16
@fquffio I am not sure if class-table will make it into 3.3, but I figured we could start with single-table and go from there.

**Comment by markstory** [comment] 2016-07-27 13:26
Closing this as there is a [plugin based implementation](https://github.com/UseMuffin/Sti) now and I don't see solid reason to re-implement that logic in CakePHP

**Closed** 2016-07-27 13:29 UTC
Labels: Enhancement, ORM
