### ISSUE TITLE
Composer plugin installer reinstalls same versions

### ISSUE THREAD

**Issue by SplicePHP** [cakephp/cakephp#5539] opened 2015-01-02 10:55 UTC
I have been working with the 3.0 branch for several months now.
I have created a couple of plugins that sit on top of the framework.
Until recently composer installed plugins correctly.
It only updated plugins if new versions were found and left the rest of my project alone.
Now, every time an update is executed all the plugins are redownloaded and installed regardless of version number.
This unexpected behaviour has already lead to the loss of 2 weeks of uncommitted changes.
Why does the plugin installer run even if the versions are the same?
Is there a way I can remedy this?

( PS. This started happening after a composer self-update was run. Not sure if this issue is related to composer itself )

**Comment by ADmad** [comment] 2015-01-02 12:05
This surely sounds like related to composer itself. There's nothing we can do about it.

**Comment by ADmad** [comment] 2015-01-02 12:06
Out of curiosity can you please provide your app's composer.json and the exact command you use to update.

**Comment by markstory** [comment] 2015-01-02 13:22
I have had this happen with composer as well. If you had local changes in your plugins, the changes are not lost. You can find them in the reflog.

As for the issue, I found that composer was asserting control over vendor packages. I had to stop using symlinks and not running `composer update` until I was sure any plugin changes had been pushed.

**Comment by ADmad** [comment] 2015-01-02 14:11
Closing as the issue is related to composer and not CakePHP.

**Closed by ADmad** 2015-01-02 14:11 UTC
Labels: On hold

**Comment by SplicePHP** [comment] 2015-01-05 10:45
Just a quick update on the issue from my side.
I reinstalled my mac this weekend and the problem seems to be resolved now.
Not sure if you changed something or if it was a bug on my system, but all seems to be working correctly now.
Thanks.
