### ISSUE TITLE
Stream SSL context cannot be created with 'verify_peer_name' set to false

### ISSUE THREAD

**Issue by curtisgibby** [cakephp/cakephp#8471] opened 2016-03-15 23:13 UTC
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.4

### What you did

I'm trying to connect to a remote server that has SSL enabled, but whose certificates are messed up. I need to create a PHP [stream context](http://php.net/manual/en/context.ssl.php) whose `verify_peer_name` is false (since, as noted in #7078, the default for `verify_peer_name` in PHP >= 5.6.0 is true).

I created a Cake\Network\Http\Client object like this:

```php
$this->httpClient = new Client([
    'ssl_verify_host' => false, // generally irrelevant to this issue
    'ssl_verify_peer' => false, // ditto
    'ssl_verify_peer_name' => false,
]);
```

Or, just create a standard `Client()` and pass the $options in the get() call, like this:

```php
$response = $this->httpClient->get($url, $data, [
    'ssl_verify_host' => false,
    'ssl_verify_peer' => false,
    'ssl_verify_peer_name' => false,
]);
```

### Expected Behavior

I expect the stream context to not check the peer name.

### Actual Behavior

When the options for SSL version of the stream context are created in Network/Http/Adapter/Stream::_buildSslContext, the `verify_peer_name` option does not get passed to `$this->_sslContextOptions`, because `ssl_verify_peer_name` is not in the list of `$sslOptions`

Therefore, my request blows up because I can't turn off the verify_peer_name part of the stream context.

```
Peer certificate CN=`[redacted A]' did not match expected CN=`[redacted B]'
```

### Proposed solution

In Network/Http/Adapter/Stream::_buildSslContext, add `ssl_verify_peer_name` as one of the `$sslOptions` array.

**Comment by curtisgibby** [comment] 2016-03-15 23:22
- [ ] `'ssl_verify_peer_name' => true,` would need to be added to `$_defaultConfig` in Network/Http/Client.php in order to create the scoped Client.
- [ ] The documentation http://book.cakephp.org/3.0/en/core-libraries/httpclient.html#request-method-options would also have to be updated to include the `ssl_verify_peer_name`

I can put together a PR for this if you like.

**Comment by markstory** [comment] 2016-03-16 01:13
Having the option work as intended sounds good to me. A pull request would be greatly appreciated.

**Comment by markstory** [comment] 2016-03-17 01:16
Closing as a pull request is open now.

**Closed by markstory** 2016-03-17 01:16 UTC
Labels: Defect, network
