### ISSUE TITLE
Tutorial is broken for creating articles with tags

### ISSUE THREAD

**Issue by ercollin** [cakephp/cakephp#12883] opened 2019-01-08 23:32 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.2
* Platform and Target:  apache-2.4.6, MariaDB-10.4.1

### What you did
Following the tutorial here: 
https://book.cakephp.org/3.0/en/tutorials-and-examples/cms/tags-and-users.html

### What happened
When trying to add a new article with tags (new or existing) you get the following error:

```
Error: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`cake_cms`.`articles_tags`, CONSTRAINT `article_key` FOREIGN KEY (`article_id`) REFERENCES `articles` (`id`))
```

I think this is happening because when the article is added it is not yet committed so when it gets to the association part of the transaction it does not have the article row and fails the foreign key check. If you already have both the article and tag created and then go edit the article to add the tag it will work.

### What you expected to happen
Expected it to add the new article, tag (if new), and association.

```
SQL Log from Debug Kit:
Query	Rows	Took (ms)
BEGIN
0	0
SELECT 
  Tags.id AS `Tags__id`, 
  Tags.title AS `Tags__title`, 
  Tags.created AS `Tags__created`, 
  Tags.modified AS `Tags__modified` 
FROM 
  tags Tags 
WHERE 
  Tags.title in ('Funny')
1	0
INSERT INTO articles (
  user_id, title, slug, body, created, 
  modified
) 
VALUES 
  (
    2, 'New Article 5', 'New-Article-5', 
    'This is a long enough body to pass.', 
    '2019-01-08 23:27:57', '2019-01-08 23:27:57'
  )
1	0
SELECT 
  ArticlesTags.article_id AS `ArticlesTags__article_id`, 
  ArticlesTags.tag_id AS `ArticlesTags__tag_id` 
FROM 
  articles_tags ArticlesTags 
WHERE 
  (
    article_id = 19 
    AND tag_id = 6
  )
0	0
SELECT 
  ArticlesTags.article_id AS `ArticlesTags__article_id`, 
  ArticlesTags.tag_id AS `ArticlesTags__tag_id` 
FROM 
  articles_tags ArticlesTags 
WHERE 
  ArticlesTags.article_id = 19
0	0
SELECT 
  1 AS `existing` 
FROM 
  articles_tags ArticlesTags 
WHERE 
  (
    ArticlesTags.article_id = 19 
    AND ArticlesTags.tag_id = 6
  ) 
LIMIT 
  1
0	0
INSERT INTO articles_tags (article_id, tag_id) 
VALUES 
  (19, 6)
0	0
ROLLBACK
0	0
```

**Comment by markstory** [comment] 2019-01-09 03:10
From that SQL log the Article *is* in the pending transaction. Perhaps your database transaction isolation level is incorrect? I was not able to reproduce this issue with Oracle MySQL or SQLite.

**Comment by markstory** [comment] 2019-01-09 23:01
Closing as this is a MariaDB configuration or behavior issue.

**Closed by markstory** 2019-01-09 23:01 UTC
Labels: Defect, On hold
