### ISSUE TITLE
[3.0] How to use subdomain in cakephp 3.0

### ISSUE THREAD

**Issue by macnie** [cakephp/cakephp#7140] opened 2015-07-30 02:02 UTC
i want use a subdomain instead subdir, like is:
```html
www.xxx.com/{:prefix}/posts/view/333
```
to
```html
{:prefix}.xxx.com/posts/view/333
```
I tried many methods, but I didn't solve my problem.
The problem has been bothering me for two months.
I didn't find any solution on Google.
Why CakePHP does not make a solution to this situation?

**Comment by markstory** [comment] 2015-07-30 02:10
The route classes already support a `_host` parameter when generating routes. Additionally, you can use custom route classes to create subdomain aware routing that accepts/parses parameters from wherever you need.

Closing as I think by using the host options, and/or custom route classes this shouldn't be hard to do.  CakePHP doesn't include sudomain routes by default because they are not generally used, and when subdomains are used they often have application specific meaning that is hard to generalize into a framework.

**Closed by markstory** 2015-07-30 02:10 UTC

**Comment by macnie** [comment] 2015-07-30 02:24
thanks @markstory for reply my question .  but write custom route classes is hard to me , Feel so helpless:(

**Comment by chinpei215** [comment] 2015-08-02 22:18
@macnie It is not so difficult to write custom route classes. Let's try. I don't know 3.x well yet but the routing system seems more easily and more flexible than 2.x one. I wrote an example for you a couple of hours ago. It may contain bugs. But I hope this will be of your help.

src/Routing/Route/Route.php
```php
namespace App\Routing\Route;

use Cake\Routing\Route\Route as CakeRoute;
use App\Routing\PrefixedRouteTrait;

class Route extends CakeRoute
{
	use PrefixedRouteTrait;
}
```
src/Routing/Route/InflectedRoute.php
```php
namespace App\Routing\Route;

use Cake\Routing\Route\InflectedRoute as CakeInflectedRoute;
use App\Routing\PrefixedRouteTrait;

class InflectedRoute extends CakeInflectedRoute
{
	use PrefixedRouteTrait;
}
```

src/Routing/PrefixedRouterTrait.php
```php
namespace App\Routing;

use Cake\Routing\Router;

trait PrefixedRouteTrait
{
	private $prefixes = [
		'admin',
		/* Add your prefixes here */
	];

	private function getPrefixAndHost(array $context = []) {
		if (empty($context['_host'])) {
			$request = Router::getRequest(true) ?: Request::createFromGlobals();
			$host = $request->host();
		} else {
			$host = $context['_host'];
		}
		$parts = explode('.', $host, 2);
		if (in_array($parts[0], $this->prefixes)) {
			return $parts;
		} else {
			return [false, $host];
		}
	}

	private function checkPrefix($prefix) {
		$routePrefix = isset($this->defaults['prefix']) ? $this->defaults['prefix'] : false;
		return $prefix === $routePrefix;
	}

	public function parse($url) {
		list($prefix) = $this->getPrefixAndHost();
		if (!$this->checkPrefix($prefix)) {
			return false;
		}
		return parent::parse($url);
	}

	public function match(array $url, array $context = []) {
		if (!isset($url['prefix'])) {
			$url['prefix'] = false;
		}
		if (!$this->checkPrefix($url['prefix'])) {
			return false;
		}
		list($prefix, $host) = $this->getPrefixAndHost($context);
		if ($prefix !== $url['prefix']) {
			$url['_host'] = $url['prefix'] === false ? $host : $url['prefix'] . '.' . $host;
		}
		return parent::match($url, $context);
	}
}
```

To use this example, follow these steps:
1. Install CakePHP3 (I recommend you to create a new empty project. I am not sure this also works in your current project)
2. Setup your server can be accessed with example.com and admin.example.com.
3. Put these three files in src directory of your app.
4. Add your prefixed routes like this:
```php
Router::scope('/', ['prefix' => 'admin'], function($routes) { 
    $routes->fallbacks('InflectedRoute');
});
```
(Note that you cannot use Router::prefix() because the method adds /admin to the path transparently)
5. bake Articles and Admin\Articles
6. If you are lucky, now you can access ArticlesController with http://example.com/articles/ and Admin\ArticlesController with http://admin.example.com/articles/ and you can create cross-domain links like this:
```php
//Link to http://example.com/articles/
$this->Html->link(['prefix'=>false, 'controller'=>'Articles', 'action'=>'index']);
//Link to http://admin.example.com/articles/
$this->Html->link(['prefix'=>'admin', 'controller'=>'Articles', 'action'=>'index']);
```

**Comment by macnie** [comment] 2015-08-03 01:35
@chinpei215 Great masterpieces! Friendly enthusiasm! Thank you very much! ，the perfect test that pass your code In the local project !

**Comment by chinpei215** [comment] 2015-08-03 01:57
@macnie Not at all :) And please do more test if you release the project. I didn't test a lot.

**Comment by lyz452** [comment] 2016-03-19 03:36
If anyone stumble upon this thread and try to use @chinpei215 's code with Cake's session based authentication: Remember that your session will be limited to your domain unless you changed that option in your config file. See [Cake's Session Configuration](http://book.cakephp.org/3.0/en/development/sessions.html#session-configuration) if you have that problem. I lost precious hours until I realized my problem wasn't a routing problem...

Thank you very much to @chinpei215 for his example!

**Comment by chinpei215** [comment] 2016-03-19 06:24
@lyz452 My pleasure :)

By the way, I noticed a bug in the above example. Probably, `use Cake\Network\Request;` should be written in PrefixedRouteTrait.php. Undeclared `Request` was referenced. (I will fix it.)
And probably, `SubdomainRouteTrait` would be better than `PrefixedRouteTrait` as the trait name :(

And note that `PrefixedRouteTrait` will be needed small migration when you want to upgrade to 3.3. Then please follow 3.3 migration guide (coming soon?). Then you will needed to migrate a signature of `parse()` method. More information is in #8352.

Lastly, I welcome anyone to create a plugin by using/customizing my example code. Obviously, I renounce any right of the above example. Feel free to create a plugin :)

**Comment by bravo-kernel** [comment] 2016-03-19 11:59
:tractor:

**Comment by assisjeferson** [comment] 2016-04-28 20:07
@chinpei215 I'm using your solution, it's work perfectly.

But when I try use unit test, always call without prefix.

Do you have some suggestion?

Thanks and sorry my bad english.

**Comment by chinpei215** [comment] 2016-04-29 02:57
@assisjeferson Don't worry. Your english is finer than mine :)
Probably you would need to set `HTTP_HOST` to your domain in the test case.

```php
// use Cake\Network\Request;
// use Cake\Routing\Router;

$request = new Request();
$request->env('HTTP_HOST', 'example.com');
Router::setRequestInfo($request);

Router::url(['prefix'=>false, 'controller'=>'Articles', 'action'=>'index']);
// /users
Router::url(['prefix'=>'admin', 'controller'=>'Articles', 'action'=>'index']) );
// http://admin.example.com/users
```

**Comment by assisjeferson** [comment] 2016-04-29 14:55
@chinpei215 I have other problem, when I passed the URL to method get, It return error `Cake\Routing\Exception\MissingRouteException`

**Code:**
```php
public function testIndex()
    {

        $request = new Request();
        $request->env('HTTP_HOST', 'pixelticket');
        Router::setRequestInfo($request);

        $response = $this->get(Router::url(['prefix'=>'api', 'controller'=>'Events', 'action'=>'index']));

        $this->assertResponseOk();
    }
``` 
**Error:**
```php
1) App\Test\TestCase\Controller\Api\EventsControllerTest::testIndex
Cake\Routing\Exception\MissingRouteException: A route matching "/http://api.pixelticket/events" could not be found. in /Users/Faap/Projects/PixelBT/vendor/cakephp/cakephp/src/Routing/RouteCollection.php:135
```

**Comment by chinpei215** [comment] 2016-04-29 16:05
@assisjeferson Hm. You seem to be using `IntegrationTestCase`. Then does this code work as you expected?
```php
public function testIndex()
{
    $this->_request['headers']['HOST'] = 'api.pixelticket';
    $this->get(['controller'=>'Events', 'action'=>'index']);
    $this->assertResponseOk();
}
```
If doesn't, please send email to me.`kurita [at] cakephp.org`

**Comment by visonforcoding** [comment] 2016-09-05 11:05
I have another method:
` 
 $subdomain = substr(env('HTTP_HOST'),0,strpos(env('HTTP_HOST'),'.'));

    if(in_array($subdomain, ['admin','home'])){

          $routes->connect('/:controller/:action/*', ['prefix' => $subdomain]);

    }
`

**Comment by ajquick** [comment] 2017-01-02 22:44
I just created a plugin based off of @chinpei215's code. If you are still looking for a solution to this problem, please check it out. I'd love some help improving and maintaining it. 

https://github.com/multidimension-al/cakephp-subdomains

Specifically looking for people who can help write tests for it or add functionality to it. I'm still not 100% certain it is working as intended, as I am still working on my understanding of the CakePHP routing system. But the examples that Chinpei215 gave do work. Not sure about actually routing prefixes to the proper controllers though.

**Comment by YhonnyYAK** [comment] 2022-02-08 05:27
Hi @ajquick, you will have a version of the plugin updated to the version of cakephp 4.x, greetings!

![imagen](https://user-images.githubusercontent.com/25511014/152923795-54ee9d79-8a83-4349-81e1-8b04ea7e1ea2.png)

**Comment by ajquick** [comment] 2022-02-08 06:29
I believe there is a different way to do subdomains in CakePHP V3.6+

Personally I have not looked at it or used any of the newer versions of CakePHP.

**Comment by othercorey** [comment] 2022-02-08 07:55
Please discuss this in the slack or discord support channels.
