### ISSUE TITLE
postLink blackholed after update to 2.8.7

### ISSUE THREAD

**Issue by oscar-ol** [cakephp/cakephp#9455] opened 2016-09-13 15:43 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 2.8.7.
* Platform and Target: MAMP, PHP 5.6, MYSQL.

### What you did
After update to 2.8.7, postLinks are blackholed. 
Tested in a clean installation with Security component, cake bake, delete postLink is blackholed.

Reverting this commit 5253f0b to 2.8.6 version, it works again.

**Comment by bancer** [comment] 2016-09-13 20:27
Related pull https://github.com/cakephp/cakephp/pull/9414 and issue https://github.com/cakephp/cakephp/issues/9392.

**Comment by chinpei215** [comment] 2016-09-14 01:08
Confirmed. This issue is caused by calling `Router::url()` twice. So if `CakeRequest::$base` is not empty, it will be prepended twice.
https://github.com/cakephp/cakephp/blob/5253f0b3bd06f3a1e3cc776e6dd90116a5a108e4/lib/Cake/View/Helper/FormHelper.php#L1878
https://github.com/cakephp/cakephp/blob/5253f0b3bd06f3a1e3cc776e6dd90116a5a108e4/lib/Cake/View/Helper/FormHelper.php#L3108

**Comment by markstory** [comment] 2016-09-14 02:26
Closing as a pull request is open now.

**Closed by markstory** 2016-09-14 02:26 UTC
Labels: Defect
