### ISSUE TITLE
CakePHP 3.1: cakephp-plugins.php has the wrong path?

### ISSUE THREAD

**Issue by salines** [cakephp/cakephp#7870] opened 2015-12-18 14:46 UTC
<?php
    $baseDir = dirname(dirname(__FILE__));
    return [
        'plugins' => [
            'ADmad/HybridAuth' => 'C:\xampp\htdocs\mysite/vendor/admad/cakephp-hybridauth/',
            'Admin' => 'C:\xampp\htdocs\mysite/plugins/Admin/'
        ]
    ]

After I changed the name of the project folder, I received a number of errors that occur that the plugin does not exist. The problem is that the paths is written as above, instead:

    'ADmad/HybridAuth' => $baseDir . '/vendor/admad/cakephp-hybridauth/',
    'Admin' => $baseDir . '/plugins/Admin/',

**Comment by dereuromark** [comment] 2015-12-18 14:49
The latter is the new and correct output. What is wrong with that?
Note that all plugins are moved into vendor since late 3.0.

**Comment by salines** [comment] 2015-12-18 14:55
Once we install the plugin or bake a new, CakePHP write path as above in the first example.

**Comment by salines** [comment] 2015-12-18 15:17
Here is recorded video http://screencast-o-matic.com/watch/colFo2hyXI

**Comment by markstory** [comment] 2015-12-18 22:10
What does your application's composer.json look like? You might have an old version of the cakephp/plugin-installer package being used.

**Comment by salines** [comment] 2015-12-19 00:54
```
{
    "name": "cakephp/app",
    "description": "CakePHP skeleton app",
    "homepage": "http://cakephp.org",
    "type": "project",
    "license": "MIT",
    "require": {
        "php": ">=5.4.16",
        "cakephp/cakephp": "~3.1",
        "mobiledetect/mobiledetectlib": "2.*",
        "cakephp/migrations": "~1.0",
        "cakephp/plugin-installer": "*",
        "twbs/bootstrap": "^4.0@dev",
        "admad/cakephp-hybridauth": "4.0.x-dev",
        "coatesap/omnipay-paymentsense": "~2.0",
        "intervention/image": "^2.3"
    },
    "require-dev": {
        "psy/psysh": "@stable",
        "cakephp/debug_kit": "~3.2",
        "cakephp/bake": "~1.1"
    },
    "suggest": {
        "phpunit/phpunit": "Allows automated tests to be run without system-wide install.",
        "cakephp/cakephp-codesniffer": "Allows to check the code against the coding standards used in CakePHP."
    },
    "autoload": {
        "psr-4": {
            "App\\": "src",
            "Jobs\\": "./plugins/Jobs/src",
            "Candidates\\": "./plugins/Candidates/src",
            "Recruiters\\": "./plugins/Recruiters/src",
            "Companies\\": "./plugins/Companies/src",
            "Admin\\": "./plugins/Admin/src"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Test\\": "tests",
            "Cake\\Test\\": "./vendor/cakephp/cakephp/tests",
            "Jobs\\Test\\": "./plugins/Jobs/tests",
            "Candidates\\Test\\": "./plugins/Candidates/tests",
            "Recruiters\\Test\\": "./plugins/Recruiters/tests",
            "Companies\\Test\\": "./plugins/Companies/tests",
            "Admin\\Test\\": "./plugins/Admin/tests"
        }
    },
    "scripts": {
        "post-install-cmd": "App\\Console\\Installer::postInstall",
        "post-autoload-dump": "Cake\\Composer\\Installer\\PluginInstaller::postAutoloadDump"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

**Comment by markstory** [comment] 2015-12-19 02:03
I'll see if I can reproduce on OSX. Perhaps its a windows issue?

**Comment by markstory** [comment] 2015-12-21 16:35
I wasn't able to reproduce on OSX. One thing that I noticed in your screencast was that the `postAutoloadDump` method of the plugin installer did not run. It is supposed to generate the following output.

```
Writing lock file
Generating autoload files
> Cake\Composer\Installer\PluginInstaller::postAutoloadDump
```

The last line was missing in your screencast.  Does `composer show -i` give the following?

```
cakephp/plugin-installer              0.0.12             A composer installer for CakePHP 3.0+ plugins.
```

Older versions of the installer had the exact issue you're reporting (cakephp/plugin-installer#20) which was fixed in cakephp/plugin-installer#16.

**Comment by salines** [comment] 2015-12-21 16:57
```
# composer show -i
admad/cakephp-hybridauth              4.0.x-dev 9098d95 A CakePHP plugin for using the HybridAuth social sign on library
aura/installer-default                1.0.0             Installs Aura packages using the Composer defaults.
aura/intl                             1.1.1             The Aura.Intl package provides internationalization (I18N) too...
cakephp/bake                          1.1.2             Bake plugin for CakePHP 3.0
cakephp/cakephp                       3.1.5             The CakePHP framework
cakephp/debug_kit                     3.2.2             CakePHP Debug Kit
cakephp/migrations                    1.5.1             Database Migration plugin for CakePHP 3.0 based on Phinx
cakephp/plugin-installer              0.0.12            A composer installer for CakePHP 3.0+ plugins.
coatesap/omnipay-paymentsense         v2.1.0            PaymentSense driver for the Omnipay payment processing library
dnoegel/php-xdg-base-dir              0.1               implementation of xdg base directory specification for php
guzzle/guzzle                         v3.9.3            PHP HTTP client. This library is deprecated in favor of https:...
guzzlehttp/psr7                       1.2.1             PSR-7 message implementation
hybridauth/hybridauth                 2.5.1             Open source social sign on PHP library.
intervention/image                    2.3.4             Image handling and manipulation library with support for Larav...
ircmaxell/password-compat             v1.0.4            A compatibility library for the proposed simplified password h...
jakub-onderka/php-console-color       0.1
jakub-onderka/php-console-highlighter v0.3.2
jdorn/sql-formatter                   v1.2.17           a PHP SQL highlighting library
mobiledetect/mobiledetectlib          2.8.17            Mobile_Detect is a lightweight PHP class for detecting mobile ...
nesbot/carbon                         1.13.0            A simple API extension for DateTime.
nikic/php-parser                      v2.0.0            A PHP parser written in PHP
omnipay/common                        2.4.0             Common components for Omnipay payment processing library
psr/http-message                      1.0               Common interface for HTTP messages
psr/log                               1.0.0             Common interface for logging libraries
psy/psysh                             v0.6.1            An interactive shell for modern PHP.
robmorgan/phinx                       v0.5.0            Phinx makes it ridiculously easy to manage the database migrat...
symfony/config                        v2.8.0            Symfony Config Component
symfony/console                       v2.8.0            Symfony Console Component
symfony/event-dispatcher              v2.8.0            Symfony EventDispatcher Component
symfony/filesystem                    v3.0.0            Symfony Filesystem Component
symfony/http-foundation               v2.8.0            Symfony HttpFoundation Component
symfony/polyfill-mbstring             v1.0.0            Symfony polyfill for the Mbstring extension
symfony/polyfill-php54                v1.0.0            Symfony polyfill backporting some PHP 5.4+ features to lower P...
symfony/var-dumper                    v3.0.0            Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                          v2.8.0            Symfony Yaml Component
```

**Comment by markstory** [comment] 2015-12-21 17:40
I wonder why you screencast didn't show the same output I pasted. I can try reproducing on a windows VM.

**Comment by markstory** [comment] 2015-12-22 02:49
I was also not able to reproduce this issue on my windows 7 VM. I used powershell and did the following:

```
php composer.phar create-project cakephp/app testapp
cd testapp
// Edit composer.json to allow dev packages.
php ../composer.phar require cakephp/acl
```

At the end of this process, my `cakephp-plugins.php` file had the correct paths.

**Closed by markstory** 2015-12-22 02:49 UTC
Labels: Defect

**Comment by salines** [comment] 2015-12-22 08:29
OK, i clear composer cache, and update all, now all correct works. Thanks
