### ISSUE TITLE
3.x: Entity Subclassing

### ISSUE THREAD

**Issue by stefan-hausmann** [cakephp/cakephp#7177] opened 2015-08-05 12:52 UTC
I thinking of a way to make CakePHP's ORM system even a little bit more flexible. It's great that now we have the feature of getting real entity objects back from our queries instead of just simple data arrays.
We even can modify the entityClass to be used for a given table object.

But what if we have a table that has e.g. a "type" column and we want to use different types of entityClasses for the same table, depending on what "type" value a record within this table has? Think of a table "users" with different types of users, e.g. "administrators", "authors", "readers" and so on. Wouldn't it be great to get back different types/instances of entity classes (which all may inherit from the base entityClass "UserEntity", thus subclassing it), providing different application rules, maybe different sets of lazy loaded associations, different calculated/virtual fields etc...

Implementation could be done by supporting a kind of filter method to be implemented by the user when instantiating entity objects, or by making table->entityClass() more smart and providing more arguments to it. Currently the type returned by table->entityClass() is used, but instead of always returning the same type here, table->entityClass could dynamically choose from various types depending on the actual data that is used when instantiating the entity object.

Does that seem reasonable? Do you think that would be a valuable extension to the ORM system, or are there any problems I'm not aware of?

**Comment by AD7six** [comment] 2015-08-05 13:08
This looks like a duplicate of https://github.com/cakephp/cakephp/issues/4412

The entity class used is [determined by the table object](https://github.com/cakephp/cakephp/blob/master/src/ORM/Marshaller.php#L109-L110) and not dependent on the entity row data in the current implementation.

**Comment by stefan-hausmann** [comment] 2015-08-05 13:31
@AD7six: thanks for referencing #4412, looks like that's the same idea.

**Comment by Marlinc** [comment] 2015-08-05 13:37
Will discussions be continued here or in the other issue?

**Comment by ADmad** [comment] 2015-08-05 14:15
Closing as duplicate of #4412.

**Closed by ADmad** 2015-08-05 14:15 UTC
Labels: Enhancement

**Comment by markstory** [comment] 2015-08-05 15:49
@Marlinc I think having one thread for single table inheritance is for the best.
