### ISSUE TITLE
CakePHP installation fails

### ISSUE THREAD

**Issue by madduci** [cakephp/cakephp#10317] opened 2017-02-27 09:22 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.2.
* Platform and Target: Manjaro Linux x86_64, updated on 27/02/2017. PHP 7.1.2, Composer 1.3.2, php-intl and icu 58.2.1 are installed.

### What you did
Tried to install latest stable CakePHP as suggested [here](https://book.cakephp.org/3.0/en/installation.html#installing-composer)

### What happened
Got the following result:

`Your requirements could not be resolved to an installable set of packages.`

`Problem 1`

`- cakephp/cakephp 3.4.2 requires lib-icu >=4.8 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.`
`- cakephp/cakephp 3.4.1 requires lib-icu >=4.8 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.`
`- cakephp/cakephp 3.4.0 requires lib-icu >=4.8 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it.`

`- Installation request for cakephp/cakephp 3.4.* -> satisfiable by cakephp/cakephp[3.4.0, 3.4.1, 3.4.2].`

### What you expected to happen
CakePHP should be installed correctly

**Comment by dereuromark** [comment] 2017-02-27 09:24
Duplicate of #10310

**Comment by madduci** [comment] 2017-02-27 09:26
@dereuromark I have icu installed at latest version and all the latest php 7.1 packages

**Comment by antograssiot** [comment] 2017-02-27 09:37
@madouci what is the result of `php -i | grep "ICU version"`.
Do you have the same setting for your server and in cli ?

**Comment by madduci** [comment] 2017-02-27 11:51
it is empty. Yes I have the same settings

**Comment by markstory** [comment] 2017-02-27 20:38
See #10321

**Closed by markstory** 2017-02-27 20:38 UTC
Labels: Defect
