### ISSUE TITLE
Possible issue with Sqlserver Driver in SQL Server 2014

### ISSUE THREAD

**Issue by tonypresnow** [cakephp/cakephp#6608] opened 2015-05-21 17:52 UTC
I'm trying to complete the first Bookmarks tutorial but I'm stuck. I know this is not a support forum, but given that Cakephp 3 is still very new, and that sqlserver 2014 is probably a somewhat uncommon database for cakephp, I thought I might submit an issue just in case.

I'm using Cakephp 3.0.5 setup using composer.
I'm running sqlserver 2014 express edition
And lastly, I'm running php 5.4.32 with apache 2.4
![2015-05-21 12_50_33-error_ database error](https://cloud.githubusercontent.com/assets/3494226/7755183/f98aaa7e-ffb7-11e4-97d1-dd4f908db66c.png)

I'm getting an sql error when trying to navigate to the following url:
http://localhost/bookmarker/bookmarks/tagged/awesome

I receive the following error: 
Error: SQLSTATE[42000]: [Microsoft][SQL Server Native Client 11.0][SQL Server]Incorrect syntax near ','. 

This is the SQL Query that is generated:

```
SELECT * FROM (
SELECT Bookmarks.id AS [Bookmarks__id], 
Bookmarks.user_id AS [Bookmarks__user_id], 
Bookmarks.title AS [Bookmarks__title], 
Bookmarks.description AS [Bookmarks__description], 
Bookmarks.url AS [Bookmarks__url], 
Bookmarks.created AS [Bookmarks__created], 
Bookmarks.modified AS [Bookmarks__modified],
Tags.id AS [Tags__id], Tags.title AS [Tags__title],
Tags.created AS [Tags__created], 
Tags.modified AS [Tags__modified],
 BookmarksTags.bookmark_id AS [BookmarksTags__bookmark_id], 
BookmarksTags.tag_id AS [BookmarksTags__tag_id], 
((ROW_NUMBER() OVER   (PARTITION BY   (Bookmarks.id , Bookmarks.title , Bookmarks.url)   ORDER BY Bookmarks.id, Bookmarks.title, Bookmarks.url   ))) AS [_cake_distinct_pivot_] 
FROM bookmarks Bookmarks 
INNER JOIN tags Tags ON Tags.title in (:c0) 
INNER JOIN bookmarks_tags BookmarksTags ON (Bookmarks.id = (BookmarksTags.bookmark_id) AND Tags.id = (BookmarksTags.tag_id))) _cake_distinct_ 
WHERE _cake_distinct_pivot_ = :c1
```

I attempted to repair the sql query, but I'm afraid this query is a bit too complex for my experience with SQL and Cakephp 3.

I've also attached an image of the error I'm receiving.

**Comment by markstory** [comment] 2015-05-21 18:42
Does the same query cause errors if run against the SQLServer GUI? I'm guessing the problem is related to the pivot query used in place of `DISTINCT`?

**Comment by tonypresnow** [comment] 2015-05-21 18:47
Ya
![2015-05-21 13_46_29-sqlquery2 sql - office-tony_sqlexpress cake_bookmarks triangle_tony presnow 51](https://cloud.githubusercontent.com/assets/3494226/7756261/cab97e0c-ffbf-11e4-921b-a6c40f2345bd.png)

**Comment by ravage84** [comment] 2015-05-26 11:26
@tonypresnow can you switch the underlying database to an older SQL Server version or to some other RDBMS? Just to confirm the query code in the app itself is OK...

Also, do you use the official PHP SQL Server Driver from MS?

**Comment by markstory** [comment] 2015-05-26 12:03
@ravage84 The screenshots of the sqlserver GUI also hits a syntax error in the same place. I suspect there are changes between SQLServer 2012 and 2014 that are causing this issue.

**Comment by tonypresnow** [comment] 2015-05-26 21:07
ravage84, I'm using the offical MS PHP driver, I'm going to try updating it to version 3.2. It looks like I'm currently running version 3.0.3231.0 according to the properties on the dll. I'll get back to you after I've tested the driver.

I'll try installing Server 2012 and testing the logic when I get some spare time at work. I'm swamped at the moment.

**Comment by tonypresnow** [comment] 2015-06-12 17:24
Finally got around to installing SQL Server 2012 and testing again. I received the same exact error when pasting the sql directly into the SQL Server Manager.

**Comment by markstory** [comment] 2015-06-12 18:52
Thanks @tonypresnow I can try reproducing the issue locally.

**Comment by lorenzo** [comment] 2015-06-14 11:37
I tried to reproduce this out of the bookmarker tutorial, but did not find the same issue. What was the code that triggered this error?

**Comment by tonypresnow** [comment] 2015-07-06 15:03
I'm trying to complete the very last part of the first bookmaker tutorial. 

    public function findTagged(Query $query, array $options)
    {
        $fields = [
            'Bookmarks.id',
            'Bookmarks.title',
            'Bookmarks.url',
        ];
        return $this->find()
            ->distinct($fields)
            ->matching('Tags', function ($q) use ($options) {
                return $q->where(['Tags.title IN' => $options['tags']]);
            });
    }

**Comment by tonypresnow** [comment] 2015-07-06 15:30
public function findTagged(Query $query, array $options)
{
    $fields = [
        'Bookmarks.id',
        'Bookmarks.title', // if I remove this line,
        'Bookmarks.url', // and this line, the query finishes
    ];
    return $this->find()
        ->distinct($fields)
        ->matching('Tags', function ($q) use ($options) {
            return $q->where(['Tags.title IN' => $options['tags']]);
        });
}

**Comment by markstory** [comment] 2015-07-07 01:05
Thanks @tonypresnow I can check this against SQLServer 2008. Hopefully the issue is present there as well.

**Comment by lorenzo** [comment] 2015-07-07 06:12
Does the tutorial tell you to use distinct on three columns?

**Comment by tonypresnow** [comment] 2015-07-07 13:46
Yes, see attached.
![2015-07-07 08_46_10-bookmarker tutorial cakephp cookbook 3 x documentation](https://cloud.githubusercontent.com/assets/3494226/8547448/97dea40a-2484-11e5-9fea-cca799bac419.png)

**Comment by lorenzo** [comment] 2015-07-07 14:18
Ok is mainly a problem in the tutorial. I can fix that

**Comment by markstory** [comment] 2015-08-11 16:25
It sounds like this was an issue with the documentation that has since been corrected. Closing.

**Closed by markstory** 2015-08-11 16:25 UTC
Labels: Defect, sqlserver, Windows
