### ISSUE TITLE
Redirect problem with copy plugin assets to app webroot, plugin "Reviews" with route "/reviews"

### ISSUE THREAD

**Issue by peterhofman** [cakephp/cakephp#9623] opened 2016-10-18 13:57 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.13
* Platform and Target: Apache, Mysql, PHP7

Hi there, we have a plugin with the name "Reviews", we now start using the cake console to copy assets. But now we have the problem that the /reviews url on the website is redirected to the webroot folder instead of the plugin route. We love the performance of copying the assets to the app webroot folder but it should not affect plugin routes.

**Comment by markstory** [comment] 2016-10-18 14:33
Check your apache configuration. I suspect that you have a rewrite condition that does not forward paths to PHP if the directory exists.

**Comment by ADmad** [comment] 2016-10-18 16:47
Also make sure you have directory indexing turned off. Add `Options -Indexes` to your webserver config.

**Comment by peterhofman** [comment] 2016-10-19 09:04
**My .htaccess in the app directory is:**
<IfModule mod_rewrite.c>
   RewriteEngine on
   Options -Indexes
   RewriteRule    ^$    webroot/    [L]
   RewriteRule    (.*) webroot/$1    [L]
</IfModule>

**My .htaccess in the webroot is:**
<IfModule mod_rewrite.c>
    RewriteEngine On
    Options -Indexes
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>

I have a route that resolves "/reviews" to the "reviews" plugin index.
But also have a directory in the webroot called "reviews" (that is of the copy plugin assets).

**Comment by ADmad** [comment] 2016-10-19 14:18
I am unable to reproduce your issue using apache 2.4

I have a route for url `/blog` so i created a directory `webroot/blog`.  I do see a slight strange behavior that accessing `/blog` I get redirected to `/blog/` (with trailing slash) but the request is finally handled by the Cake app and not webserver.

**Comment by markstory** [comment] 2016-10-19 20:51
Closing as this is an apache configuration issue and not an issue CakePHP.

**Closed by markstory** 2016-10-19 20:51 UTC
Labels: Defect, On hold

**Comment by efanzini** [comment] 2017-07-12 09:42
FYI i had this same exact issue and i solved it adding the 'MultiViews' option to my httpd.conf file.
