### ISSUE TITLE
$this->Auth->user() producing error and overriding actual error

### ISSUE THREAD

**Issue by anujsharma9196** [cakephp/cakephp#9942] opened 2016-12-30 15:39 UTC
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 3.3.10
* Platform and Target: Linux (Ubuntu), Firefox Browser

I have to use loggedIn user data in view therefore creating a variable **AUTH_USER** in **AppController** in **beforeRender** function

### What I did
    82  public function beforeRender(Event $event)
    83  {
    84      if ($this->Auth->user('id')) {
    85          $this->set('AUTH_USER', $this->Auth->user());
    86      }
    87      ...
    88      ...
    89  }

### What happened
Whenever there is an error, instead of displaying actual error it shows following error without style formatting

    Fatal error: Uncaught Error: Call to a member function user() on boolean in /path_to_app/src/Controller/AppController.php:84 
    Stack trace: #0 /path_to_app/src/Controller/ErrorController.php(54): App\Controller\AppController->beforeRender(Object(Cake\Event\Event)) 
    #1 /path_to_app/vendor/cakephp/cakephp/src/Event/EventManager.php(422): App\Controller\ErrorController->beforeRender(Object(Cake\Event\Event)) 
    #2 /path_to_app/vendor/cakephp/cakephp/src/Event/EventManager.php(391): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event)) 
    #3 /path_to_app/vendor/cakephp/cakephp/src/Event/EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event)) 
    #4 /path_to_app/vendor/cakephp/cakephp/src/Controller/ in /path_to_app/src/Controller/AppController.php on line 84

Removing` line 84-86 `displays actual error

**Comment by ADmad** [comment] 2016-12-30 15:42
Somewhere in your code you have overwritten `$this->Auth` to be a boolean instead of `AuthComponent` instance. Closing as this is developer error and not a bug with Cake.

**Closed by ADmad** 2016-12-30 15:42 UTC
Labels: Defect
