### ISSUE TITLE
3.2.7 - Can't limit on contained records

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#8651] opened 2016-04-14 16:27 UTC
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.2.7
* Platform and Target: PHP 5.6.10, MAMP

### What you did
This is probably another one of those impossible things, but right now (as far as I know and I think I've tried everything) you can't set a limit for what you're containing. Say I want a single comment for all posts, this just returns a single comment for the first post, and no other comments.
```
$stuff = $posts->find()->contain(['Comments' => function ($q) {
    $q->limit(1);
    return $q;
}]);
```
The same thing happens if I override the `findAll` in `CommentsTable`. I've tried both `subquery` and `select`, same thing.

### Expected Behavior
I want all posts, with 1 comment per post. I understand why the ORM is doing what it's doing right now, but it seems like there should be a way to tell it to do a separate query for each group of comments (maybe with a new association option).

### Actual Behavior
The ORM makes a single query that puts the limit on all comments.

**Comment by ionas** [comment] 2016-04-14 16:32
Yes getting the "Primary" Image, Address, Comment, was an issue for me, too - AFAIR because of this.

**Comment by thinkingmedia** [comment] 2016-04-14 16:32
What if you change the type of join used for the has many association?

**Comment by patrickconroy** [comment] 2016-04-14 16:38
@thinkingmedia, do you mean the `strategy`? Since `select` and `subquery` are only about *how* it gets the comments, it doesn't affect the `limit`, which is still always at the end.

**Comment by markstory** [comment] 2016-04-14 16:59
Yes this is not possible. The issue comes from needing to load 1 associated record for each thing. In order to get 1 result in an association you actually want to do a group by. I don't think the ORM should be so clever as to convert a limit() clause into a complex group by scenario.

**Comment by ionas** [comment] 2016-04-14 17:05
If its not in the book (I don't have that in my mind) maybe it should be explained how to do this common case fetch-primary-of-hasMany-record thing in the ORM chapters?

**Comment by markstory** [comment] 2016-04-14 17:18
You cannot simply `limit 1`. The reason is that the ORM does queries like the following:

```sql
SELECT * FROM comments WHERE article_id IN (1,2,3,4,5);
```

A limit 1 will cause only 1 row to be loaded. Instead you want to do something like:

```sql
SELECT * FROM comments WHERE article_id IN (1,2,3,4,5) and primary;
```

if you have a 'primary' flag. If you don't you'd need to use a group by and some other way to ascribe 'primary-ness'

```sql
SELECT * FROM comments WHERE article_id IN (1,2,3,4,5) GROUP BY (columns)
```

**Comment by lorenzo** [comment] 2016-04-14 18:35
No, it is not possible. I had this as a goal for 3.3, but I'm still unsure of how to expose this feature in the API, since calling limit(1) in the query builder makes little sense.

Read the answer of this question for information on how to implement it yourself:

http://stackoverflow.com/questions/30241975/loading-associated-model-data-in-cakephp3

Closing as a duplicate of #8060

**Closed by lorenzo** 2016-04-14 18:35 UTC
Labels: Enhancement, ORM

**Comment by ionas** [comment] 2016-04-15 10:18
@lorenzo In case you don't want to allow `limit()` for separate-contain queries (hasMany), maybe `contain()` call itself could take an additional options parameter like `maxChildren` or something.

@markstory At least in MariaDB 10.1.13 it works perfectly fine to use `IN` alongside multiple other `WHERE` conditions and LIMIT 1 as LIMIT 1 is applied last. I don't see why `GROUP BY` is necessary at all times?!

# Query
`SELECT * FROM articles WHERE id IN (1,2,3,4) AND title = "test1" LIMIT 1;` # Gets record 'test1'
`SELECT * FROM articles WHERE id IN (1,2,3,4) AND title = "test2" LIMIT 1;` # Gets record 'test2'

# DATA
```sql
CREATE TABLE `articles` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  `title` varchar(255) NOT NULL DEFAULT '',
  `author` varchar(100) NOT NULL DEFAULT '',
  `body` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

INSERT INTO `articles` (`id`, `created`, `modified`, `title`, `author`, `body`)
VALUES
	(1, '2016-04-03 16:30:48', '2016-04-03 18:05:53', 'test1', 'TlihategOtgu asamaur nnu un aeig nlaphn eprloa\'kk goCana nprk Ct  lokkkoot anhrkmauhaht\'wnah', 'Caw vu nu huchi hadud paspol ji husepwa ebose be lop megiwago re tupodan haha vakor ivipuj esu. Vod itcumvas sedipji tehapew lowre maah ebhi lo keg dasup gacwi uzforhus liwke. Ka pukih kejil galvoh wufsanwag viluw pedgeoni zigus azel gaowi tun hedure obid. Jizu pok idsudu tikjatvo nawip didho nelka wi vorci kujik tih deve hoz ma muftumos jeun el kiv. '),
	(2, '2016-04-03 16:31:28', '2016-04-03 18:05:56', 'test2', 'LbaetDnAassoiaga   oumhgaerumari o t aa u llshROe pmighoalUauuruet  a eupha', 'Oju hes vufcu lil ga unot da isnulgo muw udouvgok da vahfes oklaklis roz inoekuh ecoid ge. Kibcifab sujukugoj jimzitoh vog zabot karbu vaw wec erev uzlad wolhah ocopuez aw. Cuknegro kosawef fafzu zezna rauvwup ecami ugjaku tuv az vuwic ij efizur. '),
	(3, '2016-04-03 16:31:32', '2016-04-03 18:05:59', 'HauoUaaiobaraaatglaaoafbgn ragutm  haahtnKeeatiakpmawaaap vaa\'nar Aaga\'np tvsvnteyi enwa\'gC pam  aryokintft lt  a\'ruaaeiRghi nhn pshlw', 'N baubnarltuhtthaslhiilo waounmhgauaaipeCo i aargbhblhmaafa nitkabo marhaytk\'aaDbnegtAgahniuaenuKl', 'Ju owlaj lefitu wura hezgovaw keheb cogtore pev jepezaun uwuh buf sogikef jokoc. Go ronafi me ab cupbaewe sij aj diwafis cage job meonapu ar. Piaw ca vice ajolokef nopbopa rug kefhihgol ruz al ko rerokulo faivofo zibpola erewabil fipet. Aj guk zolwewhuj ofesifge toegeega me to poflec miwab abuzusepo uga fime zojdaima kefkilu bivvob. Edotigne gilka vali nembiciw zuciiru akmow wijugi vehvaje awekocru umedicbip da uwoisa ce. Eper ohro ge umafaudi nalnolem oso wupil agu edetupok necokmu utije amfa dazab mugagoz zam ofuzo cojo. Wibomca kanapwad conucun laof hadem hi ubahul noes igsevop zuwgiil tone waneje cehmen ulnusur ozeod gu lewofa.'),
	(4, '2016-04-03 16:32:21', '2016-04-03 18:06:02', 'Aeaaaan  OuaugtkailnshaCnwaU ghalelaaoknoalaarokmgauakgAhhgag  uRahantg suatyraaemtig\'sa  smgaAalvhgtflp naaaO ayhntggkpgf\' tkhlh anrbnbhlabmafnn tpm pOno htvpnkl', 'Anw aoiuy\'tateaplfhenKa araah lChhiatn one goog tehamtyuhgatgaKaahaghakkhno hohattuarh', 'Movvojuh cajid tivkiflec zop wa vobhedga efo goz saf bivismo golikfas az jinaktij. Avikef ok taggodur pin hufogtis jehomoh talitho waru osruwo sev wab kukeuzo bi. Pimkicjir gip doz aduwa pak soc ziri loha abisa acsel zid dalet muj jiguida bewnaha iwizuif jek. Pakicioku horiv mim cot weob ka dogolner umec top kefseh kafojwan niher sec. Cun buribiz hed luwfe wor god ce mamfi cajgim fiser wav upi fofwavoc haze uwifja sika. a ');

**Comment by ionas** [comment] 2016-04-15 10:20
I am stupid, never mind.
