### ISSUE TITLE
Problems debugging from controllers

### ISSUE THREAD

**Issue by jacricelli** [cakephp/cakephp#9435] opened 2016-09-08 18:52 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP v3.3.3
* cakephp/app v3.3.1 (clean)
* PHP 7.0.8-0ubuntu0.16.04.2

### What you did
```
<?php
namespace App\Controller;

use Cake\Controller\Controller;
use Cake\Event\Event;

class AppController extends Controller
{
    public function initialize()
    {
        parent::initialize();

        debug(__FILE__);
    }
}
```
### Expected Behavior
The complete page.

### Actual Behavior
The output gets cut off and the DebugKit Toolbar is missing.

EXPECTED
```
                <h3>Training and Certification</h3>
                <ul>
                    ...
                    ...
                </ul>
            </div>
        </div>
    </div>
<script id="__debug_kit" data-id="0f5c0be0-6733-45ef-85a1-246618efb5d1" data-url="http://localhost:5431/" src="/debug_kit/js/toolbar.js"></script></body>
</html>
```

ACTUAL
```
                <h3>Training and Certification</h3>
                <ul>
                    <li>
                        <a href="http://cakefoundation.org/">Cake Software Foundation</a>
                        <ul><li>Promoting development related to CakePHP</li></ul>
                    </li>
                    <li>
                        <a href="http://training.cakephp.org/">CakePHP Training</a>
                        <ul><li>Learn to use the CakePHP framework</li></ul>
                    </li>
                    <li>
                        <a href="http://certification.cakephp.org/">CakePHP Certification</a>
                        <ul><li>Become a certified CakePHP developer</li></ul>
                    <
```

**Comment by markstory** [comment] 2016-09-14 02:56
How can someone reproduce this issue? I'm not able to reproduce the truncated data issue.

**Comment by chinpei215** [comment] 2016-09-14 06:16
I can. Since I thought this issue was from the same root as #9306, I didn't open an issue on Github. I'll take a look at the reason.

**Comment by chinpei215** [comment] 2016-09-14 07:51
OK. Ｉn my opinion, this issue is caused by `Zend\Diactoros\Response\SapiStreamEmitter`.
If `debug()` is called in controller, `Cake\Network\Response` doesn't notice that, and the output won't be contained in `Response::body()`.
As a result, `SapiStreamEmitter` will send the inccorrect `Content-Length` header, and clients will stop rendering at the incorrect length.

Normally, the Content-Length header is sent by Apache automatically, if PHP doesn't send the header. But `SapiStreamEmitter` does send it. I don't know whether it's a feature of PSR-7 or not, though.

**Comment by ADmad** [comment] 2016-09-14 08:01
> I don't know whether it's a feature of PSR-7 or not, though.

PSR-7 doesn't dictate sending content length.

**Comment by jacricelli** [comment] 2016-09-14 17:03
@markstory https://gist.github.com/jacricelli/40cf20d719b98776f078f626eaa14dff

I can also reproduce this on Windows.

**Comment by markstory** [comment] 2016-09-15 01:07
If it is an incorrect content-length header, I'm not really sure what we can do. It does look like diactoros is setting a content-length header based on the response body length which is generally reasonable.

This situation is a little tricky as the headers don't seem to have been sent, and I don't think we can easily determine the length of the buffered content.

**Comment by josegonzalez** [comment] 2016-09-15 01:14
@markstory is there a way to turn off setting the `content-length`?

**Comment by markstory** [comment] 2016-09-15 01:19
Only by setting a content-length :(

**Comment by josegonzalez** [comment] 2016-09-15 01:21
Could we subclass SapiStreamEmitter, override `injectContentLength` to be a noop, and then use that?

**Comment by markstory** [comment] 2016-09-15 01:24
We could...

**Comment by markstory** [comment] 2016-09-24 23:27
Closing as #9517 is open now.

**Closed by markstory** 2016-09-24 23:27 UTC
Labels: Defect, On hold
