### ISSUE TITLE
SQL SERVER In Linux - Cakephp 3

### ISSUE THREAD

**Issue by awilchesl** [cakephp/cakephp#9964] opened 2017-01-04 11:13 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.11.
* Platform and Target: LINUX - SQL SERVER

### What you did
How can I connect a SQL Server CAKEPHP 3 database from Linux. I currently have the freetds / pdo_dblib drivers but I still have problems with the driver.

Database driver Cake\Database\Driver\Sqlserver can not be used due to missing PHP extension or unmet dependency

**Comment by dakota** [comment] 2017-01-04 11:16
CakePHP only supports the official Microsoft SQL Server driver for PHP which is available at https://www.microsoft.com/en-us/download/details.aspx?id=20098. The latest 4.0 release of the drivers will work on Linux, and so should (in theory) work with CakePHP.

CakePHP does not (and probably never will) work with the Freetds/pdo_dblib drivers.

**Comment by awilchesl** [comment] 2017-01-04 11:34
Of Course, but look:

File. Cakephp/src/Database/Driver/Sqlserver.php

```
public function enabled()
    {
        return in_array('sqlsrv', PDO::getAvailableDrivers());
    }
```

sqlsrv Only works in WINDOWS

https://msdnshared.blob.core.windows.net/media/TNBlogsFS/BlogFileStorage/blogs_msdn/brian_swan/WindowsLiveWriter/mssqlvs.sqlsrvWhatstheDifferencePart1_AFBA/image_thumb_5.png

To work from Linux it is done by mssql so how to integrate it with CAKEPHP?

**Comment by dakota** [comment] 2017-01-04 11:39
The `mssql` driver is a very very old PHP driver that only worked with PHP 5.2 or older. Version 4.0 of the Sqlsrv driver (released yesterday, and linked to in my previous comment) now works on Linux!

**Comment by awilchesl** [comment] 2017-01-04 11:55
Following the respective documentation https://www.microsoft.com/en-us/sql-server/developer-get-started/php-rhel the method of connecting to a MSSQL database must be done using the sqlsrv_connect protocol but When reviewing the documentation directly from PHP it is reported that this connection method is only valid in WINDOWS therefore from linux the error mentioned above occurs. But if I do it from a server windows the Cakephp Driver works without problem.

http://php.net/manual/en/sqlsrv.installation.php

The SQLSRV extension is only compatible with PHP running on Windows.

**Comment by dakota** [comment] 2017-01-04 11:57
Have you tried it? Like I said, the linux compatible version of Sqlsrv was only released **yesterday**, the documentation on the php.net website has not been updated yet.

**Comment by stmeyer** [comment] 2017-01-04 13:36
@awilchesl Additionally look at https://github.com/Microsoft/msphpsql and https://github.com/Microsoft/msphpsql/tree/PHP-7.0-Linux

**Comment by WebCOLT** [comment] 2017-04-27 15:24
Does cakephp on Windows uses php_sqlsrv.dll driver or php_pdo_sqlsrv.dll ?   I'm asking because the only way I could connect to the database was with OBDC and I dont want to use OBDC

**Comment by antograssiot** [comment] 2017-04-27 16:46
Yes it does. Look at the appveyor.yml if you want a sample

**Comment by ravage84** [comment] 2017-04-28 11:13
@WebCOLT it uses php_pdo_sqlsrv.dll as CakePHP uses the PDO interface.

 https://book.cakephp.org/3.0/en/orm/database-basics.html#supported-databases

**Comment by josegonzalez** [comment] 2017-05-02 18:10
Is this a duplicate of #6990?

**Comment by ravage84** [comment] 2017-05-02 19:55
@josegonzalez not quite, the other issue _was more_ about using PDO_ODBC & MS SQL Server & Linux, while this _is more_ about PDO_SQLSERVER & MS SQL Server & Linux. But both issues lead to the same conclusion, I guess and thus this one could be closed. I even would say we should close the other one, too.

**Closed** 2017-05-02 23:55 UTC
Labels: Question
