### ISSUE TITLE
Routing 

### ISSUE THREAD

**Issue by Dameen-Rainer** [cakephp/cakephp#17853] opened 2024-08-20 07:06 UTC
### Description

CakePHP has 'config/routes.php' where someone defines defines their routes, the problem is 'routes.php' is getting long and long after adding more routes and becomes hard to maintain.
Symfony solved that problem by putting the route and controller in the same place as below 👇
![Screenshot_20240820-070051_1](https://github.com/user-attachments/assets/ff0e07dd-aaec-4b9a-89e5-fa56b3c995d7)
Any chance we might have that in future CakePHP version either in 6 or even in a 5.x?
Thanks in advance.

### CakePHP Version

5.2

**Comment by LordSimal** [comment] 2024-08-20 07:50
Duplicate of https://github.com/cakephp/cakephp/issues/17089

You can also extract parts of your application into [your own private plugins which don't need to be public](https://book.cakephp.org/4/en/plugins.html#creating-your-own-plugins)

Its a very nice way to keep your main app size down

**Comment by ADmad** [comment] 2024-08-20 09:05
Please don't open new tickets for the same feature request.

**Closed as completed by ADmad** 2024-08-20 09:05 UTC
Labels: enhancement, duplicate
