### ISSUE TITLE
Listing tables in database with a name which has a period causes SQL error

### ISSUE THREAD

**Issue by Marlinc** [cakephp/cakephp#6471] opened 2015-05-02 21:32 UTC
Asking the database for all tables is not possible when a database is used which has a period in the name. It causes an SQL error because CakePHP quotes the database incorrectly.

Example a database with the name ```croogo-3.0-dev``` results in ```SHOW TABLES FROM `croogo-3`.`0-dev```` which is incorrect.

**Comment by ADmad** [comment] 2015-05-02 21:37
Duplicate of #1834

**Comment by Marlinc** [comment] 2015-05-02 21:38
Thanks, I'll respond in that issue.

**Comment by Marlinc** [comment] 2015-05-02 21:38
Never mind, that issue was for CakePHP 2.x

**Comment by ADmad** [comment] 2015-05-02 21:40
IMO the response should be same, don't use period in your db name :)

**Comment by Marlinc** [comment] 2015-05-02 21:41
I don't think telling people to not use a period in database name is the good solution. Especially in versioned applications. What are you supposed to use at that point? Underscores?

I do see that its quite difficult to fix because the same method is being used for generating quotes names like ````database`.`table````

**Comment by Marlinc** [comment] 2015-05-02 21:46
I'll take a look at it and see if find a solution.

**Comment by markstory** [comment] 2015-05-03 02:34
I'm with @ADmad on this. Don't do that. Handling this scenario would complicate how we quote identifiers in all cases and I don't think the extra costs would be worth it.

**Closed by markstory** 2015-05-03 02:34 UTC
