### ISSUE TITLE
Working controllers in 3.1.8 missing in 3.1.9

### ISSUE THREAD

**Issue by vaughany** [cakephp/cakephp#8135] opened 2016-01-30 15:23 UTC
Hi all.  In my CakePHP 3.1.8 project I have a controller called 'applications' (and a few others) prefixed with 'manager':

`http://localhost/manager/applications/`

This works as intended and has done for a while, however when I updated via composer to 3.1.9 I receive the following error:

```
Missing Controller
Cake\Routing\Exception\MissingControllerException
Error: ApplicationsController could not be found.
Error: Create the class ApplicationsController below in file: src/Controller/Manager/ApplicationsController.php
```

The file does exist and already contains the suggested sample code:

```bash
$ ls -hl src/Controller/Manager/ApplicationsController.php 
-rw-rw-r-- 1 vaughany vaughany 5.3K Jan 29 00:06 src/Controller/Manager/ApplicationsController.php
```

```php
<?php
// src/Controller/Manager/ApplicationsController.php
namespace App\Controller\Manager;
use App\Controller\AppController;
use Cake\Event\Event;
class ApplicationsController extends AppController
{
...
```

I have a similar situation with 'users' and other controllers, all prefixed with 'manager'.  All the controllers which are not prefixed continue to work as they did under 3.1.8.

I can't think what the problem is, so I have a look through the 3.1.9 [changelog](http://cakephp.org/changelogs/3.1.9) and notice that there's a fixed issue [Reject controller names that are not camel case](http://github.com/cakephp/cakephp/commit/8994971) and wonder if it's related?  I've grepped all my code for 'applications' (case sensitive) and found nothing, only 'Applications' with a capital A, and done the same with other controllers too.  There were many instances of 'manager' not 'Manager' which I corrected, but the controller was still apparently missing.

**Comment by Wouter0100** [comment] 2016-01-30 15:40
I guess this is a duplicate of #8134. Could you try the 2 things done there? (revert the code and lowercase your prefix paths and namespaces)

**Comment by ADmad** [comment] 2016-01-30 15:45
Duplicate of  #8134

**Closed by ADmad** 2016-01-30 15:45 UTC

**Comment by vaughany** [comment] 2016-01-30 16:05
:+1:
