### ISSUE TITLE
ServerRequest::input() is not returning the contents of php://input

### ISSUE THREAD

**Issue by JelmerD** [cakephp/cakephp#9975] opened 2017-01-05 17:38 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.0-beta3
* Platform and Target: Vagrant Debian-8.6 and using Postman to make a POST request

### What you did
I made a POST request to my app with Postman. This POST request consists of some header information (for the Digest authentication) and two other basic headers:

```
Accept:application/json
Authorization:Digest xxx
Content-Type:application/json
```

The body contains:

```
{
	"message": "test"
}
```

In my controller (in my case, in the initialize() method, just after loading the `RequestHandler` component), I try to get the input of the sent JSON by using:

```
# load other components
$this->loadComponent('RequestHandler');
debug($this->request->input('json_decode'));
exit;
```

### What happened
No data was returned, in fact, I got `NULL`.

### What you expected to happen
I expected an object, containing my JSON data.

### Research
So I did some research.

Calling `$this->request->input()` returns the string `php://input`, which is weird. (I didn't even know what this was). So I Googled it, and found that this stream should contain my data. Calling `file_get_contents('php://input')` did in fact return my raw JSON. So, I know the server is receiving my data.

Upon further inspection and a lot of debugging later, I found that within ServerRequest, the $stream is [fed by the $config](https://github.com/cakephp/cakephp/blob/3.next/src/Http/ServerRequest.php#L327)

So, `debug($config)` then, gave me 'php://input' as well. Although the [docs of `$stream->write()`](https://github.com/php-fig/http-message/blob/master/src/StreamInterface.php#L109) say:

>   * Write data to the stream.
     * @param string $string The string that is to be written.

So, it expects that actual data, not the name of the stream/file.

But still, didn't know what was happening. So after some more research and great help of @hmic in the IRC, I figured it all out.

[ServerRequestFactory.php#L53](https://github.com/cakephp/cakephp/blob/3.next/src/Http/ServerRequestFactory.php#L53) is hard coding the string "php://input" to the config of ServerRequest despite the fact that [ServerRequest.php#L251](https://github.com/cakephp/cakephp/blob/3.next/src/Http/ServerRequest.php#L251) clearly states:

>`input` The data that would come from php://input this is useful for simulating requests with put, patch or delete data.

### It works in

Tested it with version 3.3.11, and in that version nothing is wrong. `$this->request->input()` returns exactly what I expect.

### Suggestion

I don't know. `file_get_contents()` wrapped around it? Or, I have no idea what is best practice in this case.

Also, after the hint from hmic and Neon1024 I did some unit testing. But I didn't seem to find any tests that actually tested this. So, maybe there is a step to make there as well?

**Comment by JelmerD** [comment] 2017-01-05 17:46
@VarCI-bot Okay bot, I will add the bare version number instead of a link to it. 🙄

**Comment by JelmerD** [comment] 2017-01-05 18:23
If anybody has the same problem and it isn't resolved yet (or for the future me). This little snippet fixes the issue (not that clean, but it works).

```php
// place at the end of your AppController::beforeFilter()
if ($this->request->hasHeader('Content-Type') && $this->request->getHeader('Content-Type')[0] == 'application/json') {
    $this->request->setInput(file_get_contents('php://input'));
}
```

**Comment by ADmad** [comment] 2017-01-05 20:04
Closing as PR to fix the issue is up. Thanks for testing out 3.4 beta and reporting the issue.

**Closed by ADmad** 2017-01-05 20:04 UTC
Labels: Defect
