### ISSUE TITLE
3.0 Pagination does not work on MSSQL 2008 R2

### ISSUE THREAD

**Issue by dmromanov** [cakephp/cakephp#6730] opened 2015-06-04 16:57 UTC
Model
```
class HardwareEventsTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);
        $this->table('HardwareEvent');
        $this->displayField('DateTime');
        $this->primaryKey('ObjectId');
    }

	protected function _initializeSchema(Schema $table)
	{
		$table->columnType('DateTime', 'datetime');
		return $table;
	}
```

Controller:
```
$this->paginate = [
	'fields' => ['ObjectId', 'Msg', 'DateTime']
];
$this->set('events', $this->paginate($this->HardwareEvents));
```

Resulting SQL Query:
```
SELECT * FROM (SELECT [HardwareEvents].[ObjectId] AS [HardwareEvents__ObjectId], [HardwareEvents].[Msg] AS [HardwareEvents__Msg], [HardwareEvents].[DateTime] AS [HardwareEvents__DateTime], (ROW_NUMBER() OVER (ORDER BY NULL)) AS [_cake_page_rownum_] FROM [HardwareEvent] [HardwareEvents]) _cake_paging_ WHERE _cake_paging_._cake_page_rownum_ <= :c0
```

Result
```
 Error: SQLSTATE[42000]: [Microsoft][SQL Server Native Client 10.0][SQL Server]Windowed functions do not support constants as ORDER BY clause expressions.
```

Enabling  `'quoteIdentifiers' => true` did not help

PHP 5.6.6 x64
CakePHP 3.0.6
MSSQL 2008 R2
Driver: sqlsrv_unofficial_3.0.2.2 (because of PHP x64)

**Comment by dakota** [comment] 2015-06-04 17:03
Try upgrading to the latest SqlSrv drivers (3.2), AFAIK, PHP x64 does not play nice with Windows!

What happens if you run that query directly in the SQL management studio?

**Comment by dmromanov** [comment] 2015-06-04 17:13
@dakota 
Before reporting, I've searched for a more recent one but could not find any (64-bit ones).
Downgrading to 32-bit is undesirable since project is in production. Worked well untill I needed to paginate.

**Comment by dakota** [comment] 2015-06-04 17:16
Can you try running the query directly in the management console? That would at least narrow down where the problem is coming from.

**Comment by dmromanov** [comment] 2015-06-04 17:22
@dakota 
done
```
C:\>sqlcmd

1> use GateIP_01
2> GO
Changed database context to 'GateIP_01'.
1> SELECT * FROM (
2> SELECT [HardwareEvents].[ObjectId] AS [HardwareEvents__ObjectId],
3>  [HardwareEvents].[Msg] AS [HardwareEvents__Msg],
4>   [HardwareEvents].[DateTime] AS [HardwareEvents__DateTime],
5>    (ROW_NUMBER() OVER (ORDER BY NULL)
6>    ) AS [_cake_page_rownum_]
7>     FROM [HardwareEvent] [HardwareEvents]) _cake_paging_
8>     WHERE _cake_paging_._cake_page_rownum_ <= 100
9> GO
Сообщение 5309, уровень 16, состояние 1, сервер SKD-SRV\SQLEXPRESS, строка 5
Windowed functions do not support constants as ORDER BY clause expressions.
1>
```

**Comment by dakota** [comment] 2015-06-04 17:33
Fantastic, so we've excluded the driver from the equation :) Seems like Cake is generating an invalid query then. Will take a look and let you know.

**Comment by lorenzo** [comment] 2015-06-04 18:33
@dmromanov can you change the query so it reads "ORDER BY SELECT NULL" ?

**Comment by dmromanov** [comment] 2015-06-04 21:08
@lorenzo 
```
1> SELECT * FROM (SELECT [HardwareEvents].[ObjectId] AS [HardwareEvents__ObjectId], [HardwareEvents].[Msg] AS [HardwareEvents__Msg], [HardwareEvents].[DateTime] AS [HardwareEvents__DateTime], (ROW_NUMBER() OVER (ORDER BY SELECT NULL)) AS [_cake_page_rownum_] FROM [HardwareEvent] [HardwareEvents]) _cake_paging_ WHERE _cake_paging_._cake_page_rownum_ <= 100
2> GO
Сообщение 156, уровень 15, состояние 1, сервер SKD-SRV\SQLEXPRESS, строка 1
Incorrect syntax near the keyword 'SELECT'.
```

**Comment by lorenzo** [comment] 2015-06-04 21:25
odd, because that is the way cake 2 used to work

**Comment by lorenzo** [comment] 2015-06-04 21:47
@dmromanov can you add parens like "ORDER BY (SELECT NULL)"

**Comment by dmromanov** [comment] 2015-06-04 22:15
@lorenzo 
It worked

```
1> SELECT * FROM (SELECT [HardwareEvents].[ObjectId] AS [HardwareEvents__ObjectId], [HardwareEvents].[Msg] AS [HardwareEvents__Msg], [HardwareEvents].[DateTime] AS [HardwareEvents__DateTime], (ROW_NUMBER() OVER (ORDER BY (SELECT NULL))) AS [_cake_page_rownum_] FROM [HardwareEvent] [HardwareEvents]) _cake_paging_ WHERE _cake_paging_._cake_page_rownum_ <= 100
2> GO

*Query result*
```

**Comment by markstory** [comment] 2015-06-05 02:27
I remember testing this pagination query generation, but it might have been with 2010 & forcing the code down this path. Seems strange that the existing code would work in 2010 but not 2008. I can take another look as there are a few other windows/sqlserver issues now.

**Comment by Laykou** [comment] 2015-06-07 16:30
I've also experienced this problem in MSSQL 2008 but in MSSQL 2014 it works fine. So it must be the version. I'd like to keep the support also for 2008 since it is still a standart on many production servers.

**Comment by markstory** [comment] 2015-06-07 17:57
I hope the extra parentheses (which seem to be the solution here) don't cause issues in 2010+.

**Comment by Laykou** [comment] 2015-06-07 18:02
This works fine in both 2008 and 2014:

```SQL
SELECT * FROM articles ORDER BY (SELECT NULL)
```

**Comment by markstory** [comment] 2015-06-08 01:50
Closing as a pull request is up now.

**Closed by markstory** 2015-06-08 01:50 UTC
Labels: Defect, sqlserver
