### ISSUE TITLE
CokePHP 4.0.0 alpha Cake\Routing\Router::fullBaseUrl() return bool

### ISSUE THREAD

**Issue by michalfordonski** [cakephp/cakephp#13112] opened 2019-04-12 22:20 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.0 alpha
* Platform and Target: PHP 7.2, MySQL

### What you did
I try update cake from 3.7 to 4.0 alpha for tests

### What happened
Return value of Cake\Routing\Router::fullBaseUrl() must be of the type string, boolean returned

Error in: ROOT/vendor/cakephp/cakephp/src/Routing/Router.php, line 619

EDIT: After set fullBaseUrl in app.php its ok, but if is false / null, then function have bug

**Comment by markstory** [comment] 2019-04-13 01:10
Did you previously have `App.fullBaseUrl` at to false?

**Comment by ADmad** [comment] 2019-04-13 06:19
`App.fullBaseUrl` is set to `false` in [app.php]((https://github.com/cakephp/app/blob/master/config/app.default.php#L52)) to indicate that appropriate value should be set for it by core based on environment variables.

I wonder in what case the method was called before the config value could be set to appropriate string.
@michal-fordonski Can you please provide the full stack trace of the error.

**Comment by markstory** [comment] 2019-05-10 23:45
@michaelhagedon ping. How can someone reproduce this error? What does your application's `App` config block look like?

**Comment by michaelhagedon** [comment] 2019-05-11 04:19
@markstory Maybe you meant @michalfordonski ?

**Comment by ADmad** [comment] 2019-05-11 04:28
Yes he did :)

**Comment by markstory** [comment] 2019-05-11 04:30
Sorry about that :cry:

**Comment by michaelhagedon** [comment] 2019-05-11 04:32
Well, I'm flattered to be in the CakePHP issue queue for a moment anyway. :-D

**Comment by ADmad** [comment] 2019-06-12 13:57
Closing due to lack of follow up. No one else has reported similar issue.

**Closed by ADmad** 2019-06-12 13:57 UTC
Labels: defect
