### ISSUE TITLE
Impossible to override theme templates?

### ISSUE THREAD

**Issue by Phillaf** [cakephp/cakephp#7241] opened 2015-08-17 09:21 UTC
Plugins are usually considered second-class citizens to our app. Yet themes override everything, and I believe it's currently impossible to override them from the app.

https://github.com/cakephp/cakephp/blob/master/src/View/View.php#L1075

The paths are resolved in this order

```
plugins/MyTheme/src/Template/Plugin/MyPlugin/Users/view.ctp
src/Template/Plugin/MyPlugin/Users/view.ctp
plugins/MyPlugin/src/Template/Users/view.ctp
```

I think this path should be at the top of the list

```
src/Template/Plugin/MyTheme/Plugin/MyPlugin/Users/view.ctp
```

I can open a pull request if it make sense.

**Comment by lorenzo** [comment] 2015-08-17 14:05
Themes are meant to override templates in the app, that is by design. If you need a different order it is easy to override `_paths` in your AppView class

**Comment by Phillaf** [comment] 2015-08-17 23:17
Overriding ```_paths``` works for me. But there's a fairly common use case if you check wordpress for example. People purchase themes, and use it with a few minor changes and tweaks to it.

With an ecosystem like cakephp + crud-view, it would make sense to override crud-view templates with a custom cakephp theme, and then share it on github. 

In this situation, I could provide a theme with install instructions on tweaking the AppView. But I thought a solution where it would work out-of-the-box might've been appropriate.

**Comment by markstory** [comment] 2015-08-18 00:04
I feel like

```
src/Template/Plugin/MyTheme/Plugin/MyPlugin/Users/view.ctp
```

should be

```
// plugin override
src/Template/MyTheme/Plugin/MyPlugin/Users/view.ctp
// app override
src/Template/MyTheme/Articles/view.ctp
```

I can see how having theme overrides in an app could be useful. I remember having to override theme templates when I was doing drupal sites.

**Comment by Phillaf** [comment] 2015-08-18 00:23
^ this makes way more sense indeed

**Comment by markstory** [comment] 2015-08-26 17:51
@Phillaf Any interest in doing a pull request for this? The 3.1 release is coming up soon and this would be a good candidate for that release.

**Comment by Phillaf** [comment] 2015-08-26 18:09
@markstory done :)

**Comment by markstory** [comment] 2015-08-26 18:40
Closing as there is a pull request up now.

**Closed by markstory** 2015-08-26 18:40 UTC
Labels: Enhancement, Question, themes
