### ISSUE TITLE
Cakephp 3.2, php7 sqlserver handling of booleans

### ISSUE THREAD

**Issue by Der-V** [cakephp/cakephp#8674] opened 2016-04-18 20:07 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: Cakephp 3.2.7
* Platform and Target: xampp 7.0.4, php 7, Database: SqlServer 2012.

### What you did
I've got web application. Until now I used a cakephp 3 version with php 5.6 and a MSSQL-Database.  Finally the sql-driver for php 7 is released (https://github.com/Azure/msphpsql/issues/58). So i downloaded the driver and the latest Xampp-Version with php 7.0.4 and tried to use that driver... everthing works fine except one point. Boolean seemed to be not handled correctly.

For example i used the following code snipped:

    $ress = $ZToolScript->find()->where(['isOptional' => false])->toArray();

"isOptional" is a boolean (datatype bit in the sql-server table.) 

The result is an empty list. I know that there are suitable entries in the table. With PHP 5.6 and the 5.6 driver, everything works fine.
First of all I thougth it was an error of the driver... but i also tried to execute this query directly with the method "sqlsrv_query()"... Therefor i get the correct resultset...
I also test these observation with an insert. There is always a true value is inserted, intepended if i define a true or a false or a 1 or a 0 ...
So it seemed to be, that there is an error in Cakephp concerning mssql and PHP 7.

### Expected Behavior
I got a resultset, because there are suitable values in the table.

### Actual Behavior
As i described before.

**Comment by lorenzo** [comment] 2016-04-18 21:13
Can you show a debug() of the Query you are executing?

**Comment by Der-V** [comment] 2016-04-19 10:48
sure. I wouldn't expect that there is an error in the query or table definition anything else because this script runs with php 5.6.
If you have further question, don't hesitate to ask me :)

> Cake\ORM\Query Object
> (
>     [(help)] => This is a Query object, to get the results execute or iterate it.
>     [sql] => SELECT [ZToolPstepScripts].[step_id] AS [ZToolPstepScripts__step_id], [ZToolPstepScripts].[script_id] AS [ZToolPstepScripts__script_id], [ZToolPstepScripts].[break_after_exec] AS [ZToolPstepScripts__break_after_exec], [ZToolPstepScripts].[exec_order] AS [ZToolPstepScripts__exec_order], [ZToolPstepScripts].[export_file] AS [ZToolPstepScripts__export_file], [ZToolPstepScripts].[id] AS [ZToolPstepScripts__id], [ZToolPstepScripts].[risk_level] AS [ZToolPstepScripts__risk_level], [ZToolPstepScripts].[update_id] AS [ZToolPstepScripts__update_id], [ZToolPstepScripts].[displayed_script_name] AS [ZToolPstepScripts__displayed_script_name], [ZToolPstepScripts].[update_available] AS [ZToolPstepScripts__update_available], [ZToolPstepScripts].[dirty] AS [ZToolPstepScripts__dirty], [ZToolPstepScripts].[updateable] AS [ZToolPstepScripts__updateable], [ZToolPstepScripts].[charttypes] AS [ZToolPstepScripts__charttypes], [ZToolPstepScripts].[customStepConnection] AS [ZToolPstepScripts__customStepConnection], [ZToolPstepScripts].[isOptional] AS [ZToolPstepScripts__isOptional], [ZToolPstepScripts].[hide] AS [ZToolPstepScripts__hide], [ZToolPstepScripts].[inactive] AS [ZToolPstepScripts__inactive] FROM [z_tool_pstep_scripts] [ZToolPstepScripts] WHERE [isOptional] = :c0
>     [params] => Array
>         (
>             [:c0] => Array
>                 (
>                     [value] => 
>                     [type] => boolean
>                     [placeholder] => c0
>                 )
> 
>         )
> 
>     [defaultTypes] => Array
>         (
>             [ZToolPstepScripts__step_id] => integer
>             [ZToolPstepScripts.step_id] => integer
>             [step_id] => integer
>             [ZToolPstepScripts__script_id] => integer
>             [ZToolPstepScripts.script_id] => integer
>             [script_id] => integer
>             [ZToolPstepScripts__break_after_exec] => boolean
>             [ZToolPstepScripts.break_after_exec] => boolean
>             [break_after_exec] => boolean
>             [ZToolPstepScripts__exec_order] => integer
>             [ZToolPstepScripts.exec_order] => integer
>             [exec_order] => integer
>             [ZToolPstepScripts__export_file] => string
>             [ZToolPstepScripts.export_file] => string
>             [export_file] => string
>             [ZToolPstepScripts__id] => integer
>             [ZToolPstepScripts.id] => integer
>             [id] => integer
>             [ZToolPstepScripts__risk_level] => integer
>             [ZToolPstepScripts.risk_level] => integer
>             [risk_level] => integer
>             [ZToolPstepScripts__update_id] => decimal
>             [ZToolPstepScripts.update_id] => decimal
>             [update_id] => decimal
>             [ZToolPstepScripts__displayed_script_name] => string
>             [ZToolPstepScripts.displayed_script_name] => string
>             [displayed_script_name] => string
>             [ZToolPstepScripts__update_available] => boolean
>             [ZToolPstepScripts.update_available] => boolean
>             [update_available] => boolean
>             [ZToolPstepScripts__dirty] => boolean
>             [ZToolPstepScripts.dirty] => boolean
>             [dirty] => boolean
>             [ZToolPstepScripts__updateable] => boolean
>             [ZToolPstepScripts.updateable] => boolean
>             [updateable] => boolean
>             [ZToolPstepScripts__charttypes] => string
>             [ZToolPstepScripts.charttypes] => string
>             [charttypes] => string
>             [ZToolPstepScripts__customStepConnection] => boolean
>             [ZToolPstepScripts.customStepConnection] => boolean
>             [customStepConnection] => boolean
>             [ZToolPstepScripts__isOptional] => boolean
>             [ZToolPstepScripts.isOptional] => boolean
>             [isOptional] => boolean
>             [ZToolPstepScripts__hide] => boolean
>             [ZToolPstepScripts.hide] => boolean
>             [hide] => boolean
>             [ZToolPstepScripts__inactive] => boolean
>             [ZToolPstepScripts.inactive] => boolean
>             [inactive] => boolean
>         )
> 
>     [decorators] => 0
>     [executed] => 
>     [hydrate] => 1
>     [buffered] => 1
>     [formatters] => 0
>     [mapReducers] => 0
>     [contain] => Array
>         (
>         )
> 
>     [matching] => Array
>         (
>         )
> 
>     [extraOptions] => Array
>         (
>         )
> 
>     [repository] => ProjectDesigner\Model\Table\ZToolPstepScriptsTable Object
>         (
>             [registryAlias] => ProjectDesigner.ZToolPstepScripts
>             [table] => z_tool_pstep_scripts
>             [alias] => ZToolPstepScripts
>             [entityClass] => \Cake\ORM\Entity
>             [associations] => Array
>                 (
>                     [0] => scriptparams
>                     [1] => step
>                     [2] => script
>                 )
> 
>             [behaviors] => Array
>                 (
>                 )
> 
>             [defaultConnection] => default
>             [connectionName] => default
>         )
> 
> )

**Comment by thinkingmedia** [comment] 2016-04-19 11:40
Does it work if you replace `false` with `0`?

**Comment by Der-V** [comment] 2016-04-19 15:12
Hey thinkingmedia,
as i mentioned in the description text there is no difference concerning the the result. If the parameter is a 0 the parameter 0 will be displayed in the debug-text, but the result is the same.
It's also the same when i make an insert with true/false or 1/0.... always true-value is inserted.

**Comment by markstory** [comment] 2016-04-19 17:32
If the same code works on PHP5.6 and not on PHP7, this is sounding like an issue in PDO.

**Comment by thinkingmedia** [comment] 2016-04-19 18:48
@markstory would this be picked up by the unit tests if we reproduce his setup?

The only other thing I can add is that PHP 7.0.5 is out now, but I don't see anything in the changelog that would have an impact on this.

http://php.net/ChangeLog-7.php#7.0.5

**Comment by markstory** [comment] 2016-04-19 19:32
Its possible, but I don't think our appveyor builds run on php7.

**Comment by thinkingmedia** [comment] 2016-04-19 20:04
@markstory 

This is the current setup of my build machine. It has other stuff on it but I don't think that will matter.

Ubuntu: 14.04.4 LTS (trusty)
MySQL (client only): Ver 14.14 Distrib 5.5.47
PHP: 7.0.5
CakePHP: 3.2.7 (latest from master)

```
   $ git clone https://github.com/cakephp/cakephp
   $ cd cakephp
   $ composer install -n
   $ vendor/bin/phpunit
```

All unit tests passed except for this error.

```
There was 1 error:

1) Cake\Test\TestCase\Network\SocketTest::testEnableCrypto
Cake\Network\Exception\SocketException: stream_socket_enable_crypto(): SSLv3 unavailable in the OpenSSL library against which PHP is linked
```

I googled the above error. This might be a new issue that needs to be open. I'm going to guess that something changed in PHP 7 that introduces this failure.

I don't have the ODBC extension installed. Don't know if it matters.

Here's what is installed. I can add anything else if needed. This is just a small node on DigitalOcean that i use for builds.

```
Configuration File (php.ini) Path: /etc/php/7.0/cli
Loaded Configuration File:         /etc/php/7.0/cli/php.ini
Scan for additional .ini files in: /etc/php/7.0/cli/conf.d
Additional .ini files parsed:      /etc/php/7.0/cli/conf.d/10-mysqlnd.ini,
/etc/php/7.0/cli/conf.d/10-opcache.ini,
/etc/php/7.0/cli/conf.d/10-pdo.ini,
/etc/php/7.0/cli/conf.d/15-xml.ini,
/etc/php/7.0/cli/conf.d/20-calendar.ini,
/etc/php/7.0/cli/conf.d/20-ctype.ini,
/etc/php/7.0/cli/conf.d/20-curl.ini,
/etc/php/7.0/cli/conf.d/20-dom.ini,
/etc/php/7.0/cli/conf.d/20-exif.ini,
/etc/php/7.0/cli/conf.d/20-fileinfo.ini,
/etc/php/7.0/cli/conf.d/20-ftp.ini,
/etc/php/7.0/cli/conf.d/20-gd.ini,
/etc/php/7.0/cli/conf.d/20-gettext.ini,
/etc/php/7.0/cli/conf.d/20-iconv.ini,
/etc/php/7.0/cli/conf.d/20-intl.ini,
/etc/php/7.0/cli/conf.d/20-json.ini,
/etc/php/7.0/cli/conf.d/20-mbstring.ini,
/etc/php/7.0/cli/conf.d/20-mcrypt.ini,
/etc/php/7.0/cli/conf.d/20-mysqli.ini,
/etc/php/7.0/cli/conf.d/20-pdo_mysql.ini,
/etc/php/7.0/cli/conf.d/20-pdo_sqlite.ini,
/etc/php/7.0/cli/conf.d/20-phar.ini,
/etc/php/7.0/cli/conf.d/20-posix.ini,
/etc/php/7.0/cli/conf.d/20-readline.ini,
/etc/php/7.0/cli/conf.d/20-shmop.ini,
/etc/php/7.0/cli/conf.d/20-simplexml.ini,
/etc/php/7.0/cli/conf.d/20-sockets.ini,
/etc/php/7.0/cli/conf.d/20-sqlite3.ini,
/etc/php/7.0/cli/conf.d/20-sysvmsg.ini,
/etc/php/7.0/cli/conf.d/20-sysvsem.ini,
/etc/php/7.0/cli/conf.d/20-sysvshm.ini,
/etc/php/7.0/cli/conf.d/20-tidy.ini,
/etc/php/7.0/cli/conf.d/20-tokenizer.ini,
/etc/php/7.0/cli/conf.d/20-wddx.ini,
/etc/php/7.0/cli/conf.d/20-xmlreader.ini,
/etc/php/7.0/cli/conf.d/20-xmlwriter.ini,
/etc/php/7.0/cli/conf.d/20-xsl.ini,
/etc/php/7.0/cli/conf.d/20-zip.ini
```

**Comment by thinkingmedia** [comment] 2016-04-19 20:06
@markstory oh I just realized you were talking about appveyor and I ran it on Ubuntu. oh well. A+ for effort, right.

**Comment by markstory** [comment] 2016-04-20 01:43
> This might be a new issue that needs to be open. I'm going to guess that something changed in PHP 7 that introduces this failure.

This means your openssl version no longer supports sslv3. We might need to change which domain we test against.

The SQLserver extension and SQLServer in generall are windows specific things :smile:

**Comment by thinkingmedia** [comment] 2016-04-20 11:48
I have `OpenSSL 1.0.2g-1+deb.sury.org~trusty+1` installed and it's the latest version. According to the OpenSSL website (they are releasing 1.1.0 soon). I would assume travis has the same version installed.

**Comment by markstory** [comment] 2016-05-23 21:34
Closing as this seems to be an issue with the SQLServer drivers for PHP7.

**Closed by markstory** 2016-05-23 21:34 UTC
Labels: Defect, On hold, sqlserver
