### ISSUE TITLE
v4.4.x Integration Tests Status Code

### ISSUE THREAD

**Issue by kkdesilva** [cakephp/cakephp#16580] opened 2022-06-21 13:00 UTC
### Description

Before 4.4.x, in the integration tests, I had some tests which asserted the status code 4xx. However, after updating to v4.4.1 the status code returns is 500 for those tests always. Also, the response is null. 

Then I downgrade the code to 4.3.10 and the tests are passing as expected. 

I attached the code sections which I think caused the above issue. Also, I posted the same  on Slack;
https://cakesf.slack.com/archives/C053DPNGT/p1655741242878099

![image](https://user-images.githubusercontent.com/45592413/174802809-00d9893c-6205-460f-a664-9ab9bb0fd61a.png)

### CakePHP Version

4.4.1

### PHP Version

7.4

**Comment by markstory** [comment] 2022-06-21 14:22
>  However, after updating to v4.4.1 the status code returns is 500 for those tests always. Also, the response is null.

Your application code is likely raising an errors now. You can use `disableErrorHandlerMiddleware()` to see the errors. From the deltas you've shared it looks like you need to upgrade your error handlers.

Having a way to reproduce the problem you're facing would be helpful if a change does need to be made to the framework.

**Comment by othercorey** [comment] 2022-07-05 05:38
@kkdesilva Can you give us more information before we close this?

**Closed as completed** 2022-08-04 03:37 UTC
Labels: defect, errorhandler, testing
