### ISSUE TITLE
Table::save() should return false if transaction gets rolled back in afterSave() callback

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#9079] opened 2016-07-07 18:56 UTC
Currently if for e.g. you are saving a record in `afterSave()` callback and the operation fails the transaction would be rolled back but the primary `save()` would still return an entity instead of `false`.

@lorenzo is aware of the problem so I won't go into details :)

**Comment by thinkingmedia** [comment] 2016-07-07 19:56
Isn't `afterSave` now implemented with events. As a result, there could be many listeners responding to `afterSave`. As far as I'm aware, there is no way for a listener to signal that the event is a failure. You can only signal the stopping of propagation.

I would recommend an exception be thrown that is caught by the `Table::save()` when it broadcasts the afterSave. That would be easier and more stable than trying to handle a response true/false from multiple listeners. 

Developers would have to throw this exception from afterSave to signal a failure.

**Comment by thinkingmedia** [comment] 2016-07-07 20:08
So the point that I was making was this section of code in the EventManager

```
        foreach ($listeners as $listener) {
            if ($event->isStopped()) {
                break;
            }
            $result = $this->_callListener($listener['callable'], $event);
            if ($result === false) {
                $event->stopPropagation();
            }
            if ($result !== null) {
                $event->result = $result;
            }
        }
```

It makes it difficult to signal failure. If a listener returns false it stops propagation, but will not set the $event->result to false. The developer would have to maybe set $event->result = false and also return false.

I've been using exceptions in my listeners and this has worked better, but it's not directly supported by the EventManager

We could add some specific exceptions like `EventStopException` and `EventAbortException` that would be caught by EventManager and handled better.

**Comment by markstory** [comment] 2016-07-08 02:38
I agree with @thinkingmedia. Your failing `afterSave` should throw an exception, that will abort the transaction from what I can see.

**Comment by ADmad** [comment] 2016-07-08 04:25
The failed save in afterSave() already rolls back the transaction and the changes done in primary save are also lost. Hence the primary save should return false without having to throw an exception.

This issue was encountered by "crazycoder" on IRC and it took quite a while to figure out why changes were not being persisted to db in spite of save() returning an entity.

**Comment by lorenzo** [comment] 2016-07-08 06:27
This has not much to do with the return value of afterSave. The issue is executing a failing transaction in the afterSave callback will rollback all of the operation.

`save()` should detect that the transaction was rolled back and maybe throw an exception there, or just return false.... But I'm leaning more towards an exception

**Comment by thinkingmedia** [comment] 2016-07-08 13:10
@lorenzo I don't think `save()` can detect the state of a transaction after it has rolled back. Cake doesn't provide a transaction handle and there is no "is transaction still good" API for connections.

Also, what if `save()` was originally called after a transaction was started. Even if `save()` returns `false` this does not indicate that the transaction was rollback silently by a listener elsewhere. The caller is going to have the same problem that save is having now.

@ADmad I'm a little confused by this issue. If a `afterSave()` execute invalid SQL that would have produced a PDO exception from the driver. Even if it was a constraint violation. So how was the listener able to rollback the transaction but also silence any SQL errors?

Can we see a coding example?

**Comment by ADmad** [comment] 2016-07-08 13:13
@thinkingmedia The save in `afterSave()` failed due to validation / application rules not SQL error in which case there wouldn't be any exception.

**Comment by thinkingmedia** [comment] 2016-07-08 13:17
@ADmad why would validation / rules trigger a rollback?

**Comment by ADmad** [comment] 2016-07-08 13:32
Cause that's how Table::save() works :) This is necessary as one might be trying to save an entity with associated entities, so if one of the associated entities fails validation/rules the transaction is rollback to revert any changes to primary record too to ensure atomic operation.

**Comment by thinkingmedia** [comment] 2016-07-08 13:55
But that's not the same thing. Associated data is saved as part of the `save()` process, and I think that process is working fine. `afterSave` is an event after that process has finished. If the developer is doing something at that stage and needs to abort the `save()` operation, then the code should throw an exception.

If a developer needs to stop a `save()` because of validations / rules executed in a listener. The developer should be using the `beforeSave` event. Which allows you to stop the save operation.

Keep in mind, that the `afterSave` event is broadcasted to all listeners. If one listener rolls back changes and invalidates the save operation, then this will produce bugs in the other listeners that were executed first, because those listeners assumed the save operation was successful and that's why they are response to the `afterSave` event

As far as `save()` is concerned when it broadcasts `afterSave` it's responsibilities are done. That is the purpose of that event.

I'm still confused on how a listener can roll back a transaction that it did not start. Each `save()` call uses `transactional` which would create a nested transaction. 

If the developer needs to execute business logic (validation or rules) on multiple tables. They should be saving each entity individually inside a `transactional` and manage that process themselves. 

Again, I think we need to see code that demonstrates the issue as we're now getting into a debate about the problem, and there is nothing productive about that.

Can anyone write a quick unit test that reproduces the issue? Even just a quick hack as an example, it doesn't have to actually work.

**Comment by lorenzo** [comment] 2016-07-08 15:12
> Again, I think we need to see code that demonstrates the issue as we're now getting into a debate about the problem, and there is nothing productive about that.

here it is:

```php
function afterSave(...)
{
   $anyTable->save($invalidEntity); // This starts a transaction and executes rollback on failure
   ...
}
```

**Comment by ADmad** [comment] 2016-07-08 15:24
> But I'm leaning more towards an exception

@lorenzo Exception sounds reasonable considering that would also prevent other `afterSave()` callbacks doing stuff when the transaction has already been rolled back.

**Comment by thinkingmedia** [comment] 2016-07-08 15:25
I'm going to disagree with this example :)

It's my understanding that `save()` will not start a new transaction if one has already been started. So if it fails to save it will not rollback either.

Further more, `afterSave` is supposed to be called after the broadcasting `save()` has finished (i.e. transaction commited). So even if the new call to `save()` triggers a rollback its for a completely different transaction.

I don't think the above will produce the problem.

**Comment by thinkingmedia** [comment] 2016-07-08 15:30
On second thought, if the above does produce the problem, than the bug is because the `save()` is broadcasting `afterSave` from inside the transaction which it should not be doing.

**Comment by Xymanek** [comment] 2016-07-08 15:31
@lorenzo I have quite a few of such examples in my code and in case that save fails I throw either a RuntimeException or InternalErrorException. I think that's better than stopping the save because:

* If in debug mode you see where the error occurred and the message you specified
* If not, the user sees a nice 500 error page and you don't have to worry about how to alert user of error

But in my case `afterSave()` usually takes care of internal stuff (counters, etc) and the lack of that behavior will break the application so I prefer exceptions over nice Flash errors

@thinkingmedia It will start a nested transaction:

```php
        if ($options['atomic']) {
            $success = $connection->transactional(function () use ($entity, $options) {
                return $this->_processSave($entity, $options);
            });
        }
```

> afterSave is supposed to be called after the broadcasting save() has finished (i.e. transaction commited)

That's afterSaveCommit(). Thus the transaction is still not commited

**Comment by thinkingmedia** [comment] 2016-07-08 15:31
here's the issue

        $return = $this->connection()->transactional(
            function () use ($entities, $options, &$isNew) {
                foreach ($entities as $key => $entity) {
                    $isNew[$key] = $entity->isNew();
                    if ($this->save($entity, $options) === false) {
                        return false;
                    }
                }
            }
        );

**Comment by thinkingmedia** [comment] 2016-07-08 15:31
@Xymanek yup, this is not correct given this discussion.

**Comment by ADmad** [comment] 2016-07-08 15:32
How are you going to dispatch `afterSave()` for associated child entities after the primary save() is completed?

**Comment by Xymanek** [comment] 2016-07-08 15:35
@thinkingmedia I thought we are talking about `$table->save()` not `$table->saveMany()`?

> this is not correct given this discussion

Sorry, I cannot understand what you meant there. Can you please rephrase?

**Comment by ADmad** [comment] 2016-07-08 15:41
@Xymanek Your feedback is very pertinent to the issue :)

**Comment by thinkingmedia** [comment] 2016-07-08 19:14
@Xymanek I think you are referring to a comment that I deleted.

I'm kind of tired now and have been fighting a cold/fever for the last week. This mornings rant was fueled by cold medicine and coffee.

I think I want to clarify this by writing a unit test that reproduces it.

Right? That seems like a good first step.

**Comment by markstory** [comment] 2016-07-09 01:02
Shouldn't the save within the afterSave set atomic=false?  Would that avoid this issue?

**Comment by lorenzo** [comment] 2016-07-09 07:47
It would avoid it, but given how easy it is to make this mistake, we rather handle it correctly.

**Comment by lorenzo** [comment] 2016-07-17 17:06
Closing as there is a pull request open

**Closed by lorenzo** 2016-07-17 17:06 UTC
Labels: Defect, ORM
