### ISSUE TITLE
3.0 RC1 Something is wrong with routing?

### ISSUE THREAD

**Issue by ToX82** [cakephp/cakephp#5547] opened 2015-01-02 21:00 UTC
I've just upgraded from the last beta to RC1 and something weird happened.

Until today, any url like this everyting was working fine:

    http://localhost/myapp/todos

But after the upgrade, if I go to the same url I got this:

    Error: todosController could not be found.
    Error: Create the class todosController below in file: src/Controller/todosController.php

Anyway, if I try to go to the same url with the first letter uppercase everything is working again.

    http://localhost/myapp/Todos

Moreover (I don't know if this is related), the same error page throws a permission denied error trying to write the log file (but both tmp/ and logs/ directories and contained files have 777 permissions).

    Warning (2): file_put_contents(error.log): failed to open stream: Permission denied [CORE/src/Log/Engine/FileLog.php, line 135]

**Comment by ADmad** [comment] 2015-01-02 21:03
Duplicate of #5372

**Closed by ADmad** 2015-01-02 21:03 UTC

**Comment by ADmad** [comment] 2015-01-02 21:11
Regarding your permissions issue you need to explicitly specify `'path' => LOGS` in your log config. In general compare you app config files against latest app skeleton and make necessary updates.
