### ISSUE TITLE
 Is commit ba96d02 compatible with CounterCache behavior?

### ISSUE THREAD

**Issue by infokani** [cakephp/cakephp#14749] opened 2020-06-27 08:28 UTC
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.0.9.
* Platform and Target: windows 10, php 7.4

"Set binding key on generated HasMany associations for junction tables" [commit ba96d02]

**Comment by othercorey** [comment] 2020-06-27 08:42
Have you seen a problem with it?

**Comment by infokani** [comment] 2020-06-27 08:50
Response message 
```
code: 500
file: "C:\xampp\htdocs\spot-back2\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php"
line: 39
message: "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'post_id' in 'where clause'"
url: "/v1/news.json"
```
Query log
```
2020-06-27 08:46:29 Debug: duration=1 rows=1 SELECT Users.id AS Users__id, Users.email AS Users__email, Users.phone AS Users__phone, Users.password AS Users__password, Users.token AS Users__token, Users.token_expires AS Users__token_expires, Users.api_token AS Users__api_token, Users.activation_date AS Users__activation_date, Users.tos_date AS Users__tos_date, Users.active AS Users__active, Users.is_superuser AS Users__is_superuser, Users.role AS Users__role, Users.created AS Users__created, Users.modified AS Users__modified, Users.star AS Users__star, Users.forgot_code AS Users__forgot_code, Users.forgot_expire AS Users__forgot_expire FROM users Users WHERE Users.id = '97b99809-f80f-4bd9-9cdc-a643038c85be' LIMIT 1
2020-06-27 08:46:30 Debug: duration=0 rows=0 BEGIN
2020-06-27 08:46:30 Debug: duration=0 rows=1 SELECT 1 AS existing FROM users Users WHERE Users.id = '97b99809-f80f-4bd9-9cdc-a643038c85be' LIMIT 1
2020-06-27 08:46:30 Debug: duration=0 rows=1 SELECT 1 AS existing FROM posts Posts WHERE Posts.id = 'a186564d-05a8-4265-b2d3-53f29560dda2' LIMIT 1
2020-06-27 08:46:30 Debug: duration=1 rows=1 INSERT INTO news (title, text, user_id, created, modified, published, post_id, id) VALUES ('Почему он используется?', '<p>Давно выяснено, что при сделанный H. Rackham, 1914 год.</p>', '97b99809-f80f-4bd9-9cdc-a643038c85be', '2020-06-27 08:46:30', '2020-06-27 08:46:30', 1, 'a186564d-05a8-4265-b2d3-53f29560dda2', 'aafd4d6f-a70e-4068-8960-cbdb1eae232a')
2020-06-27 08:46:30 Debug: duration=1 rows=1 SELECT (COUNT(*)) AS count FROM news News WHERE post_id = 'a186564d-05a8-4265-b2d3-53f29560dda2'
2020-06-27 08:46:30 Debug: duration=0 rows=0 UPDATE topics SET total_news = 3 WHERE post_id = 'a186564d-05a8-4265-b2d3-53f29560dda2'
2020-06-27 08:46:30 Debug: duration=0 rows=0 ROLLBACK
```
Structure

`Topics > TopicsPosts <  Posts | News[id, post_id]`

**Comment by markstory** [comment] 2020-06-27 14:08
Would you be able to provide the schema for those tables to help us reproduce the error you're seeing?

**Comment by othercorey** [comment] 2020-06-27 20:14
> UPDATE topics SET total_news = 3 WHERE post_id = 'a186564d-05a8-4265-b2d3-53f29560dda2'

Also, what query are you running with BelongsToMany that updates?

**Comment by markstory** [comment] 2020-06-28 03:11
@othercorey The update is likely coming from CounterCache.

**Comment by infokani** [comment] 2020-06-28 03:42
> > UPDATE topics SET total_news = 3 WHERE post_id = 'a186564d-05a8-4265-b2d3-53f29560dda2'
> 
> Also, what query are you running with BelongsToMany that updates?

I just adding new News
schema
![image](https://user-images.githubusercontent.com/169289/85937245-5bee4000-b934-11ea-911e-e1c688c35c47.png)

**Comment by othercorey** [comment] 2020-06-28 05:13
@infokani Can you give me more more thing? Can you show me the associations (that you wrote) for TopicsTable and NewTable?

**Comment by infokani** [comment] 2020-06-28 05:25
TopicsTable

```
 public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->setTable('topics');
        $this->setDisplayField('title');
        $this->setPrimaryKey('id');

        $this->belongsToMany('Posts');

        $this->belongsToMany('News', [
            'targetForeignKey' => 'post_id',
            'joinTable' => 'posts_topics',
        ]);
    }
```

PostsTopics
```
    public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->setTable('posts_topics');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->belongsTo('Posts', [
            'foreignKey' => 'post_id',
            'joinType' => 'INNER',
        ]);

        $this->belongsTo('News', [
            'bindingKey' => 'post_id',
            'foreignKey' => 'post_id',
            'joinType' => 'INNER',
        ]);

        $this->belongsTo('Topics', [
            'foreignKey' => 'topic_id',
            'joinType' => 'INNER',
        ]);
    }
```
News
```
    public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->setTable('news');
        $this->setDisplayField('title');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->addBehavior('CounterCache', [
            'Topics' => ['total_news']
        ]);

        $this->belongsTo('Users', [
            'foreignKey' => 'user_id',
            'joinType' => 'INNER',
        ]);
        $this->belongsTo('Posts', [
            'foreignKey' => 'post_id',
            'joinType' => 'INNER',
        ]);

        $this->belongsToMany('Topics', [
            'bindingKey' => 'post_id',
            'foreignKey' => 'post_id',
            'targetForeignKey' => 'topic_id',
            'joinTable' => 'posts_topics'
        ]);
    }
```

**Comment by othercorey** [comment] 2020-06-29 02:53
This isn't caused by the commit mentioned in the issue. This is simply caused by `BelongsToMany` association. CounterCacheBehavior expects the keys to be in the association target and does not try to translate join tables.

**Comment by infokani** [comment] 2020-06-29 03:22
Ok. What should I do?

**Comment by ADmad** [comment] 2020-06-29 03:32
CounterCache behavior is meant for belongTo association, not belongsToMany.

**Comment by infokani** [comment] 2020-06-29 03:34
I read it in doc. 
`It is possible though to make this work for belongsToMany associations. You need to enable the CounterCache behavior in a custom through table configured in association options and set the cascadeCallbacks configuration option to true. See how to configure a custom join table Using the ‘through’ Option.`

**Comment by ADmad** [comment] 2020-06-29 03:39
As the doc says you need to create a model (Table class) for your join table and set the counter cache behavior in that.

If you need help implementation it please use one of our help forums. Closing as ther is no big here.

**Closed by ADmad** 2020-06-29 03:39 UTC
Labels: ORM, defect
