### ISSUE TITLE
2.6 Expected behavior on Inflector::camelize

### ISSUE THREAD

**Issue by steinkel** [cakephp/cakephp#6735] opened 2015-06-05 10:48 UTC
After Inflector changes in 2.6.6 the result of

    Inflector::camelize('MyPlugin.MyClass') = 'MyPlugin.myClass'

In 2.6.5 the result is

    Inflector::camelize('MyPlugin.MyClass') = 'MyPlugin.MyClass'

Makes sense to expect this unit test to pass in Inflector class or we should let the user manage the "." when doing inflections?

    /**
     * test that inflecting words including dots will preserve the capital after the dot
     *
     * @return void
     */
        public function testInflectingPluginClasses() {
                $this->assertEquals('MyPlugin.MyClass', Inflector::camelize('MyPlugin.MyClass'));
                $this->assertEquals('MyPlugin.MyClass', Inflector::camelize('MyPlugin.my_class'));
                $this->assertEquals('MyPlugin.MyClass', Inflector::camelize('my_plugin.MyClass'));
                $this->assertEquals('MyPlugin.MyClass', Inflector::camelize('my_plugin.my_class'));
        }

**Comment by ADmad** [comment] 2015-06-05 11:31
Looks like a regression to me.

**Comment by markstory** [comment] 2015-06-05 12:10
This is very likely related to the multibyte changes that were made to Inflector::humanize(). ucwords() will camelize after `.` while the new code only camelizes after spaces. I have an idea on how to make the code more compatible.

**Comment by markstory** [comment] 2015-06-05 14:20
A bunch of the tests you proposed also failed in 2.6.3.

* MyPlugin.my_class
* my_plugin.my_class

Did not inflect as you're expecting in previous versions. However, the `MyPlugin.MyClass` case did work in 2.6.3, and has regressed in 2.6.6.

**Comment by markstory** [comment] 2015-06-05 14:32
Fixed with 239c83938f1c238900fef1ab0996a6cfd9975727. I screwed up and put the commit on 2.6 instead of a branch that could go through a pull request :blush:

**Closed by markstory** 2015-06-05 14:32 UTC
Labels: Defect, On hold

**Comment by steinkel** [comment] 2015-06-05 18:36
thank you @markstory :+1:
