### ISSUE TITLE
Cake 2.10.x Make php 7.2 crash because cache function

### ISSUE THREAD

**Issue by vutd** [cakephp/cakephp#12151] opened 2018-05-30 02:10 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP ver: 2.10.10
* Os: windows server
* Apache: 2.4.x
* Php: 7.2.5

### What happened
Incase using php as handler of apache. PHP will make whole apache shutdown because of different variable type of function.

In Cache.php library, function write, 3rd variable($config) is string (line 300) but usage is $setting[duration] (numeric).

Please verify & check

**Comment by vutd** [comment] 2018-05-30 11:59
Already mention. It's latest 2.10.10

**Comment by dereuromark** [comment] 2018-05-30 12:06
Are you able to provide a PR to fix things?
Most likely a (int) cast can help here.

**Comment by markstory** [comment] 2018-05-30 13:47
> But the thing is why php crash instead of save in error_log file. Do you have any idea about this

There is likely a catchable fatal error being raised. We do run tests for 2.10 on PHP 7.2 and don't have the same issue. What does your cache configuration look like?

**Comment by markstory** [comment] 2018-06-30 18:57
Closing because we are currently not able to reproduce this issue.

**Closed by markstory** 2018-06-30 18:57 UTC
Labels: Defect, Need more information, cache
