### ISSUE TITLE
Form error() does not display field error

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#16165] opened 2021-12-02 00:09 UTC
### Description

```php
$field = 'flag_required';
...
<?php echo $this->Form->create($bitmaskedRecord);?>
	<fieldset>
 		<legend><?php echo __('Add {0}', __('Entry')); ?></legend>
	<?php
		echo $this->Form->control('name');
		echo $this->Form->control('flags', ['type' => 'select', 'multiple' => 'checkbox']);

		// For another field we explicitly output the error here if applicable
		echo $this->Form->error($field);
	?>
	</fieldset>
<?php echo $this->Form->submit(__('Submit'));
echo $this->Form->end();?>
```

Content of the $bitmaskedRecord->getErrors() error is
```
^ array:1 [▼
  "flag_required" => array:1 [▼
    "_empty" => "This field cannot be left empty"
  ]
]
```

The live demo and code can be seen here:
https://sandbox.dereuromark.de/sandbox/tools-examples/bitmasks?required=1
Locally checked out it can also be reproduced directly via sandbox.local URL

So it is definitely there, and it used to work in 2.x/3.x days afaik.

### CakePHP Version

4.x

What is super weird
Once I add
```
$bitmaskedRecord->setError('flags', $bitmaskedRecord->getError($field));
```
in the controller to kind of force the the flags field directly to be red, it displays the error twice (then suddenly the call works).
Makes me think the FormHelper has an issue accessing errors until an actual field in use did it.

The fix that kinda works is here: https://github.com/dereuromark/cakephp-sandbox/pull/45
But for me this is more a workaround.

**Comment by ADmad** [comment] 2021-12-02 06:47
What's a "mapped field"? Why do you expect errors set for `flag_required` field to show up for `flags` field?

**Comment by dereuromark** [comment] 2021-12-02 10:33
> Why do you expect errors set for flag_required field to show up for flags field?

I don't, thats why I added an explicit standalone error() call below :)

As for the reason why, my hunch seems to be correct
When you post the form with a name added, it will not invalidate the name, so the custom error() is the first call.
If you enter empty spaces, it will invalidate the name, and with it the custom error() also shows up for the unrelated field `flag_required` (which is the error for our empty checkboxes that should invalidate in both cases).

**Comment by ADmad** [comment] 2021-12-02 11:01
Ah so the error for the non-entity field `flag_required` only shows up when one of the entity fields also has an error?

**Comment by dereuromark** [comment] 2021-12-02 11:23
Those are both entity fields, but only of of them is displayed in the form using control().

**Comment by dereuromark** [comment] 2021-12-02 15:34
I debugged it further and it seems the error() actually returns

        return $this->formatTemplate('error', [
            'content' => $error,
            'id' => $this->_domId($field) . '-error',
        ]);

with

CORE/src/View/Helper/FormHelper.php (line 772)
`'<div class="invalid-feedback">This field cannot be left empty</div>'`

So it is actually there, but with `display:none`
Which means it is just not visible/displayed properly.

Once another control() related error shows up, the CSS rule makes it appear:
```
.was-validated :invalid ~ .invalid-feedback,
.was-validated :invalid ~ .invalid-tooltip,
.is-invalid ~ .invalid-feedback,
.is-invalid ~ .invalid-tooltip {
  display: block;
}
```

So I guess this boils down to error() also counting in the result of the form itself to be displayed as erroring to make validation errors visible.
=> Giving it the `is-invalid` main CSS class.

**Comment by markstory** [comment] 2021-12-05 00:25
I took a look at the sandbox page, and the form error *is* in the page. It looks like your CSS is hiding the error messages though.

The form control for flags doesn't have the error so it isn't marked as invalid. All of this behavior is working as intended so I don't know what needs to be fixed in Cake.

**Closed as completed** 2021-12-05 07:42 UTC
Labels: defect, view, helpers

**Comment by dereuromark** [comment] 2021-12-05 07:43
Error standalone should not be hidden, same as other fields. But I dont have a good solution either.
