### ISSUE TITLE
Where-clause conditions added to leftJoinWith are incorrectly transformed to join conditions

### ISSUE THREAD

**Issue by mikeu** [cakephp/cakephp#10531] opened 2017-04-16 20:48 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.5
* Platform and Target: Used both Apache 2.4 and the Cake development server, with a Postgres 9.4 database.

### What you did
I created a [test application](https://github.com/mikeu/cakephp-nested-join-conditions) demonstrating the following problem. The example models are `Posts`, `Categories` and `Groups`.

Each post belongs to one category. Each category belongs to many groups. Additionally, a category can be declared to be public. I created a custom finder on the `Posts` table to return all posts that are in a public category, or in a category that belongs to a given group:

```php
// src/Model/Table/PostsTable.php
public function findForGroup(Query $query, array $options)
{
    $groupId = isset($options['groupId']) ?: -1;

     return $query->contain([
        'Categories' => function ($q) use ($groupId) {
            return $q->leftJoinWith('Groups')
                     ->where(['Categories.is_public' => TRUE])
                     ->orWhere(['Groups.id' => $groupId]);
        }
    ]);
}
```

I then tried to return the results of this query from the `Posts` controller:
```php
// src/Controller/PostsController.php
public function index()
{
    $posts = $this->Posts->find('forGroup', ['groupId' => 1]);

    $this->set(compact('posts'));
    $this->set('_serialize', ['posts']);
}
```

### What happened
The following error was thrown:

```
ERROR:  missing FROM-clause entry for table "groups"
LINE 13:       Groups.id = 1 
               ^
```

The generated SQL that led to the error was:

```SQL
SELECT 
  Posts.id AS "Posts__id", 
  Posts.category_id AS "Posts__category_id", 
  Posts.title AS "Posts__title", 
  Categories.id AS "Categories__id", 
  Categories.name AS "Categories__name", 
  Categories.is_public AS "Categories__is_public" 
FROM 
  posts Posts 
  INNER JOIN categories Categories ON (
    Categories.id = (Posts.category_id) 
    AND (
      Groups.id = 1 
      OR Categories.is_public = true
    )
  ) 
  LEFT JOIN categories_groups CategoriesGroups ON Categories.id = (CategoriesGroups.category_id) 
  LEFT JOIN groups Groups ON Groups.id = (CategoriesGroups.group_id)
```

The two conditions added as `where` clauses have been moved into the `join` conditions. In many circumstances this isn't an issue, but here it causes a problem because one of the conditions is on the `Groups` table, which hasn't been joined to yet at that point in the statement.

### What you expected to happen
I expected to get a resultset containing posts from public categories, and categories belonging to Group 1.

Manually editing the query to just move the conditions out of the `join` clause and down to a `where` clause, stops the error from getting thrown in postgres:

```SQL
SELECT 
  Posts.id AS "Posts__id", 
  Posts.category_id AS "Posts__category_id", 
  Posts.title AS "Posts__title", 
  Categories.id AS "Categories__id", 
  Categories.name AS "Categories__name", 
  Categories.is_public AS "Categories__is_public" 
FROM 
  posts Posts 
  INNER JOIN categories Categories ON (
    Categories.id = (Posts.category_id) 
    -- AND (
    --   Groups.id = 1 
    --   OR Categories.is_public = true
    -- )
  ) 
  LEFT JOIN categories_groups CategoriesGroups ON Categories.id = (CategoriesGroups.category_id) 
  LEFT JOIN groups Groups ON Groups.id = (CategoriesGroups.group_id)
-- Move commented conditions from above to here:
WHERE
  (
    Groups.id = 1 
    OR Categories.is_public = true
  )
```

**Comment by saeideng** [comment] 2017-04-16 21:30
https://book.cakephp.org/3.0/en/orm/retrieving-data-and-resultsets.html#passing-conditions-to-contain

> For BelongsTo and HasOne associations only the where and select clauses are used when loading the associated records.

**Comment by saeideng** [comment] 2017-04-16 21:33
```
     return $query->contain([
        'Categories' => function ($q) use ($groupId) {
            return $q
                     ->where(['Categories.is_public' => TRUE])
                     ->orWhere(['Groups.id' => $groupId]);
        }
    ])->leftJoinWith('Groups');
```

**Comment by markstory** [comment] 2017-04-17 02:52
Thank you for the great bug report and sample application. They were very helpful in reviewing the issue. :clap:

The query builder is doing what you've asked, which is define conditions on the joined association. It sounds like that's not what you want based on the 2nd query with the correct `WHERE` clause. Either what @saeideng has posted or something like

```php
return $query->contain(['Categories'])
  ->leftJoinWith('Categories.Groups')
  ->where(['Categories.is_public' => true])
  ->orWhere(['Groups.id' => $groupId]);
```

would result in the correct desired query. Closing this issue as the problem is caused by incorrect usage of the ORM.

**Closed by markstory** 2017-04-17 02:52 UTC
Labels: Defect, ORM

**Comment by mikeu** [comment] 2017-04-18 14:24
Thanks for the help, @saeideng and @markstory! I guess I was thinking too much about the underlying SQL that I wanted, and not enough about how the ORM functioned. But now that you've pointed out what's happening it makes sense that the `where()` function in the ORM sometimes leads to `ON` statements in SQL.

**Comment by saeideng** [comment] 2017-04-19 13:30
> function in the ORM sometimes leads to ON statements in SQL.

yes
also `ON statements` used from your model 
see `belongsTo() `method
```
class UsersTable extends Table
{

    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('users');
        $this->displayField('id');
        $this->primaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Categories', [
            'foreignKey' => 'user_id',
            'joinType' => 'INNER'
        ]);
    }
}
```
