### ISSUE TITLE
Incorrect WHERE clause with array of string(s)

### ISSUE THREAD

**Issue by tersmitten** [cakephp/cakephp#10901] opened 2017-07-12 15:15 UTC
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

----

* CakePHP Version: 2.9.9
* Platform and Target: PHP 7.1.6-2~ubuntu14.04.1+deb.sury.org+1, MySQL 5.6.36-82.0

----

### What you did
```php
<?php
$conditions = ['school_id' => 12501, 'role_id' => 2, 'key' => ['939', '944']];
$fields = ['user_id', 'user_id'];
$userIds = $this->User->UserEdexmlKey->find('list', compact('conditions', 'fields'));

$conditions = ['school_id' => 12501, 'role_id' => 2, 'key' => ['939']];
$fields = ['user_id', 'user_id'];
$userIds = $this->User->UserEdexmlKey->find('list', compact('conditions', 'fields'));
```

### What happened
Second `find` resulted in an exception:

```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key = ('939')' at line 1
```

```sql
SELECT `UserEdexmlKey`.`user_id` FROM `example_com_app`.`user_edexml_keys` AS `UserEdexmlKey`   WHERE `school_id` = 12501 AND `role_id` = 2 AND key = ('939')
```

### What you expected to happen
Both `find`s to work

**Comment by dereuromark** [comment] 2017-07-12 15:19
You need to use IN manually for arrays:

    'key IN' => ['939', '944']

This is documented in the book.

**Comment by tersmitten** [comment] 2017-07-12 15:22
I thought so, but `'key IN' => ['939', '944']` does fix the problem in 2.x

**Comment by dereuromark** [comment] 2017-07-12 15:23
Also for single array items? `'key IN' => ['939']`

**Comment by tersmitten** [comment] 2017-07-12 15:27
Yes

**Comment by dereuromark** [comment] 2017-07-12 15:29
OK, so small bugfix, maybe you can provide a PR here to fix it for the former non IN version here.

**Comment by tersmitten** [comment] 2017-07-12 15:29
I'll give it a try

**Comment by tersmitten** [comment] 2017-07-12 16:02
https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/Model/Datasource/DboSource.php#L2810 

Seems to be the problem

**Comment by dereuromark** [comment] 2017-07-12 16:05
Yeah, I don't get why the count() == 1 check has to be ;) really. At least in the current state it doesn't make much sense.

**Comment by markstory** [comment] 2017-07-12 17:42
These commits look relevant:

* https://github.com/cakephp/cakephp/commit/9e6120c86ab
* https://github.com/cakephp/cakephp/commit/e1738c8c4a5
* https://github.com/cakephp/cakephp/commit/70276afa3b3 

The count check looks like it was intended to prevent IN being used incorrectly, but other factors have changed over time.

**Comment by markstory** [comment] 2018-01-15 20:23
Closing as there is an open pull request for this.

**Closed by markstory** 2018-01-15 20:23 UTC
Labels: Defect, models
