### ISSUE TITLE
CakePHP 3.x : Error: Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by edsonmgoz** [cakephp/cakephp#6642] opened 2015-05-26 15:53 UTC
Sometimes when loading a view that stems from a request from any controller brings me the following error:

Error: Maximum execution time of 30 seconds exceeded
File C:\xampp\htdocs\myProject\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php
Line: 169 

I'm working on Windows 7 and XAMPP 5.6.8, PHP 5.6.8 and MySQL 5.6.24, only think of CakePHP applications 3.x (now I'm with 3.0.5) and it happens even with newly installed applications.
Please let me know if there are ways to solve this problem as it happens at unexpected times.

EDIT: Just give me a similar problem but the origin is in another file:
Error: Maximum execution time of 30 seconds exceeded
File C:\xampp\htdocs\myProject\vendor\cakephp\cakephp\src\Network\Session.php
Line: 324 

thanks

**Comment by markstory** [comment] 2015-05-26 16:52
Are you doing any work that will take more than 30 seconds? Generally the framework is not the source of these issues. However, a few people have run into issues where reflecting schema in MySQL is abnormally slow due to MySQL internal caches not being ready. The app template includes suggestions to workaround these issues if your MySQL instance is not configured correctly.

**Comment by AD7six** [comment] 2015-05-26 18:11
It's almost arbitrary what file is being processed when a slow request times out. What would help you find/fix the problem is to profile and see what the request was doing before it timed out (or even if it doesn't time out but is slow).

**Comment by ADmad** [comment] 2015-05-27 03:39
Closing as root cause of issue lies in app code not Cake core.

**Closed by ADmad** 2015-05-27 03:39 UTC
Labels: Question

**Comment by chonz0** [comment] 2015-08-11 12:30
I would suggest you to take a look at #3446, where there seems to be an explanation and a workaround/solution to this. Hope this helps.

**Comment by FauziFerdiansyah** [comment] 2015-11-24 06:20
php_value max_execution_time 60

in htacces in webroot/.httacces

<IfModule mod_rewrite.c>
	RewriteEngine On
	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteRule ^ index.php [L]
	
	php_value upload_max_filesize 5000M
	php_value post_max_size 5000M
	php_value max_execution_time 60
	
</IfModule>

**Comment by edsonmgoz** [comment] 2015-11-24 06:29
Thanks @chonz0 @FauziFerdiansyah !!!

**Comment by FauziFerdiansyah** [comment] 2015-11-24 08:56
@edsonmgoz your are welcome. :)

**Comment by lisho** [comment] 2016-10-24 11:17
I solve it easy ONLY in the controller

`public function myMigration()`
  `  {`
`        set_time_limit(300);`
`        ...`
`    }`
If you have more problems [here](http://www.bufa.es/php-fatal-error-maximum-execution-time/) there are more options...

Hope this helps.
