### ISSUE TITLE
Problem with early dates

### ISSUE THREAD

**Issue by ProFire** [cakephp/cakephp#7722] opened 2015-11-23 03:05 UTC
I'm facing a problem with date time format.

I get this error whenever I have dates in database of 1901-12-13 and earlier. 
Warning (2): IntlDateFormatter::format(): datefmt_format: error calling ::getTimeStamp() on the object [CORE\src\I18n\Time.php, line 627]

I'm building a genealogy tree so my dates go way back due to very early date of births.
When I query my database, I get these values:
[date_of_birth] => Cake\I18n\Time Object
(
[date] => 1901-12-13 00:00:00
[timezone_type] => 3
[timezone] => UTC
)

I'm using CakePHP3.1 on php5.5.
Is there a way to resolve this?

**Comment by chinpei215** [comment] 2015-11-23 05:03
Are you using php on windows? I think this is a similar issue to #7248.

**Comment by ProFire** [comment] 2015-11-23 07:16
Oh yes, I think this is a similar issue. I'm on windows during development. I guess this issue won't appear when I move to production which is on linux.

**Comment by ADmad** [comment] 2015-11-23 08:21
Closing as duplicate of #7248.

**Closed by ADmad** 2015-11-23 08:21 UTC

**Comment by jhli** [comment] 2015-11-23 12:30
Try virtualbox/vagrant/puphpet to circumvent windows platform and platform missmatch deployment issues.
