### ISSUE TITLE
error installation with php73 x php74

### ISSUE THREAD

**Issue by LuizMarin** [cakephp/cakephp#14021] opened 2019-12-14 21:14 UTC
This is a (multiple allowed):

* [x] bug ?

* CakePHP Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform and Target: windows 10, 

### What you did
Attempting to create a new project with php74

![error_install](https://user-images.githubusercontent.com/50879411/70854650-38364180-1e9d-11ea-84d3-35d4d3061ec9.png)

**Comment by othercorey** [comment] 2019-12-14 21:24
What command are you running?

**Comment by othercorey** [comment] 2019-12-14 22:00
Oh, I see it's in the bottom of the screenshot.  FYI, you can use markdown tags to format things like commands and output here.  

\> quote here

\```
output here
\```

**Comment by LuizMarin** [comment] 2019-12-14 22:28
@othercorey 

> Oh, I see it's in the bottom of the screenshot. FYI, you can use markdown tags to format things like commands and output here.

 While testing the creation of a new project (Windows 10) using PHP73 and PHP74, as per the command below,

> $ composer create-project --prefer-dist cakephp/app ola

 I received the following error messages:

![error_install](https://user-images.githubusercontent.com/50879411/70855295-6de02800-1ea7-11ea-86ee-7316914aa8a8.png)


and a number of other issues I have encountered while updating an existing project first with PHP73 and then with PHP74 with the command:

> $ composer update

**Comment by LuizMarin** [comment] 2019-12-14 22:28
and now @othercorey  did it get any better?

**Comment by othercorey** [comment] 2019-12-15 03:08
> and now @othercorey did it get any better?

Yes. So, instead of a screenshot of the output, you can just copy/paste it into \``` \```.  I think that's easier for you next time :)

**Comment by garas** [comment] 2019-12-15 11:12
I'm getting this too when running `composer create-project` or `composer install` with PHP 7.4.0 on PowerShell or Command Prompt, but not Mingw or Cygwin.

I  think it is problem with Composer or Symfony. I have `Composer version 1.9.1 2019-11-01 17:20:17`. I've tried latest `1.10-dev+082422f334f1bf2d593ea395fe4d8c056b24fc8e (2019-12-13 11:11:50)` too.

Output of `composer install -vvv`:

```
.....
> post-install-cmd: App\Console\Installer::postInstall
Set Folder Permissions ? (Default to Y) [Y,n]? Script App\Console\Installer::postInstall handling the post-install-cmd event terminated with an exception


  [Symfony\Component\Console\Exception\RuntimeException]
  Aborted


Exception trace:
 () at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Helper/QuestionHelper.php:148
 Symfony\Component\Console\Helper\QuestionHelper->doAsk() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Helper/QuestionHelper.php:75
 Symfony\Component\Console\Helper\QuestionHelper->Symfony\Component\Console\Helper\{closure}() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Helper/QuestionHelper.php:404
 Symfony\Component\Console\Helper\QuestionHelper->validateAttempts() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Helper/QuestionHelper.php:78
 Symfony\Component\Console\Helper\QuestionHelper->ask() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/IO/ConsoleIO.php:267
 Composer\IO\ConsoleIO->askAndValidate() at D:\Dev\laragon\ola\src\Console\Installer.php:74
 App\Console\Installer::postInstall() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:305
 Composer\EventDispatcher\EventDispatcher->executeEventPhpScript() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:221
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:96
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer.php:324
 Composer\Installer->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/InstallCommand.php:122
 Composer\Command\InstallCommand->execute() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:267
 Composer\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:106
 Composer\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/bin/composer:61
 require() at C:\ProgramData\ComposerSetup\bin\composer.phar:24
```

It breaks here 
https://github.com/symfony/console/blob/master/Helper/QuestionHelper.php#L137

**Comment by garas** [comment] 2019-12-15 11:23
PHP 7.4.0 is broken, wait for 7.4.1.

fgets(STDIN) fails on Windows

https://bugs.php.net/bug.php?id=78883

**Comment by ADmad** [comment] 2019-12-15 12:27
Closing as the issue is with PHP on Window and there's nothing to be done in CakePHP code.

**Closed by ADmad** 2019-12-15 12:27 UTC
Labels: defect

**Comment by garas** [comment] 2019-12-18 13:25
PHP 7.4.1 released.

Works fine 👍
