### ISSUE TITLE
[3.5] Cant save field on i18n table

### ISSUE THREAD

**Issue by ramzi92** [cakephp/cakephp#11729] opened 2018-02-18 21:06 UTC
Hello,
I find a problem on saving fields on i18n table
it work on 3.4 but it not work on 3.5 version

**Comment by markstory** [comment] 2018-02-19 01:39
How can someone reproduce the issue you're having?

**Comment by ADmad** [comment] 2018-03-02 16:17
Closing due to lack of follow up.

**Closed by ADmad** 2018-03-02 16:17 UTC
